### ISSUE TITLE
Unable to deserialize location pathspecs - unused kwarg data_stream

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#415] opened 2015-11-27 14:01 UTC
To replicate:
1. Run log2timeline on test_data dir
2. Run psort on resulting storage file

```
[ERROR] Unused keyword arguments.
> /home/onager/code/dfvfs/dfvfs/path/path_spec.py(25)__init__()
-> raise ValueError(u'Unused keyword arguments.')
(Pdb) u
> /home/onager/code/dfvfs/dfvfs/path/location_path_spec.py(26)__init__()
-> super(LocationPathSpec, self).__init__(parent=parent, **kwargs)
(Pdb) a
self = <dfvfs.path.os_path_spec.OSPathSpec object at 0x7f749524e510>
location = /home/onager/code/plaso/test_data/syslog
parent = None
kwargs = {u'data_stream': u''}
```

Both plaso and dfvfs at head.

The problem appears to be either that location_path_spec doesn't support a data_stream attribute, but we serialize one into the storage file anyway.

**Comment by Onager** [comment] 2015-11-27 14:02
This is either a dfvfs bug (location_path_spec should do something a data_stream kwargs) or a plaso one (plaso shouldn't write a data_stream attribute for location pathspecs).

**Comment by joachimmetz** [comment] 2015-11-27 16:32
Duplicate of: https://github.com/log2timeline/plaso/issues/371

**Closed by joachimmetz** 2015-11-27 16:32 UTC
Labels: bug
