### ISSUE TITLE
SkyDrive parser decode error

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#504] opened 2016-01-03 10:31 UTC
```
ERROR:root:[skydrive_log] unable to parse file: TSK:/Users/%USER%/AppData/Local/Microsoft/SkyDrive/logs/SkyDrive.exe.reg.2013-08-12-010852.985.log with error: Unable to read lines from file with error: 'ascii' codec can't decode byte 0xdc in position 110: ordinal not in range(128)
```

Offending log entry where non-ASCII chars are escaped as <##>:

```
08-31-13,03:45:49.128,32d,32ec,0,WNS,wnptransimpl.cpp(541),d2edf8,00D2F1B0,NRM,SendCommand,TrID=0x7;cmd=ACK^A<DC>C3p<E4>C3p<E0>C3pDEL;pszFullNameSpace=WNS\NOTIF;cbPayloadSize=0x1c;payload=Msg-Id: 568f2f9b598e38af
```

Current behavior is that only the specific log line is skipped.
- [ ] Read log file as binary data - re-evaluate the [text reader approach](https://github.com/log2timeline/plaso/blob/master/plaso/parsers/text_parser.py#L1028)

**Comment by thePidge** [comment] 2016-08-01 20:07
Just a note that this bug also appears to impact OneDrive build 2015 - 17.3.6390.0509 (on Win10)

2016-08-01 11:18:33,943 [DEBUG] (Worker_00 ) PID:122582 <worker> skydrive_log unable to parse file: OS:/tmp/TraceArchive.6390.0509-4.etl with error: Not a text file, with error: 'ascii' codec can't decode byte 0xe8 in position 48: ordinal not in range(128)

**Comment by joachimmetz** [comment] 2017-12-28 20:32
bumping release

**Comment by Onager** [comment] 2018-09-19 09:06
Skydrive parser now reads files as UTF-8 by default, since https://github.com/log2timeline/plaso/commit/b88ce46af445f83d6e50bcbb2493b5886bcb77af. 

I suspect that this isn't an issue any more, closing out. Please reopen this is reproducible.

**Closed by Onager** 2018-09-19 09:06 UTC
Labels: bug, parsers
