### ISSUE TITLE
Tagging issues with plaso 1.4

### ISSUE THREAD

**Issue by jbeley** [log2timeline/plaso#572] opened 2016-02-02 12:50 UTC
I'm trying to utilize the tagging feature of plaso specifically targeting events from the winevt parser.
I'm currently running plaso (1.4.0-dev-20160123-1ppa1~trusty) on Ubuntu Trusty. I was unable to replicate the below using plaso 1.3.0-dev-20150721-1ppa1~trusty.

After timelining my evt/evtx files:
`log2timeline.py --parsers winevt evt.pb /path/to/evt/file`
or for evtx files 
`log2timeline.py --parsers winevtx evt.pb /path/to/evtx/files`

No errors were produced by running the either of the  log2timeline commands above.
I then test the resultant evt.pb file by running:
`pinfo.py evt.pb`

Output from pinfo.py:
```
Storage file:           evt.pb
Serialization format:   json
Source processed:       N/A
Time of processing:     2016-02-02T12:22:07+00:00

Collection information:
        parser_selection = winevtx
        recursive = False
        preferred_encoding = UTF-8
        os_detected = N/A
        configured_zone = UTC
        output_file = evt.pb
        preprocess = False
        version = 1.4.0
        cmd_line = /usr/bin/log2timeline.py --parsers winevtx evt.pb /path/to/evtx/files/Security.evtx
        debug = False
        runtime = single process mode
        parsers = winevtx
        method = OS collection
        protobuf_size = 0

Parser counter information:
        Counter: total = 38328
        Counter: winevtx = 38328

Store information:
        Number of available stores: 1
        Store information details omitted (to see use: --verbose)

Preprocessing information omitted (to see use: --verbose).

No reports stored.
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

I then run:
`psort.py evt.pb `
To validate the presence of events of interest within the file. FinallStorage file:           evt.pb
Serialization format:   json
Source processed:       N/A
Time of processing:     2016-02-02T12:22:07+00:00

Collection information:
        parser_selection = winevtx
        recursive = False
        preferred_encoding = UTF-8
        os_detected = N/A
        configured_zone = UTC
        output_file = evt.pb
        preprocess = False
        version = 1.4.0
        cmd_line = /usr/bin/log2timeline.py --parsers winevtx evt.pb /path/to/evtx/files/Security.evtx
        debug = False
        runtime = single process mode
        parsers = winevtx
        method = OS collection
        protobuf_size = 0

Parser counter information:
        Counter: total = 38328
        Counter: winevtx = 38328

Store information:
        Number of available stores: 1
        Store information details omitted (to see use: --verbose)

Preprocessing information omitted (to see use: --verbose).

No reports stored.
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+y, I run:
`psort.py -d  --logfile psort.log  --analysis tagging  -o null   --tagging-file /usr/share/plaso/tag_windows.txt evt.pb `
Which produces output such as:
Report generated from: tagging
Generated on: 2016-02-02T12:25:51+00:00

Report text:
Tagging plugin produced 27 tags.

Processing completed.

*********************************** Counter ************************************
  Stored Events : 38328
Events Included : 38328
  Total Reports : 1
Report: tagging : 1
--------------------------------------------------------------------------------

The above produces no errors.

I then run:
psort.py  evt.pb

The above command runs for a moment (small sampling of evt/evtx files in this case) and produces a few lines of output:

```
2010-11-21T03:58:32.153973+00:00,Content Modification Time,EVT,WinEVTX,[109 / 0x006d] Record Number: 27 Event Level: 4 Source Name: Microsoft-Windows-Kernel-Power Computer Name: 37L4247F27-25 Message string: The kernel power manager has initiated a shutdown transition. Strings: ['5'  '0'  '0'],winevtx,OS:/mnt/Windows/System32/winevt/Logs/System.evtx,-,1,26
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 698, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 693, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 642, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 267, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 525, in ProcessStorage
    time_slice=time_slice)
  File "/usr/lib/python2.7/dist-packages/plaso/output/event_buffer.py", line 49, in __exit__
    self.End()
  File "/usr/lib/python2.7/dist-packages/plaso/output/event_buffer.py", line 72, in End
    self.Flush()
  File "/usr/lib/python2.7/dist-packages/plaso/output/event_buffer.py", line 85, in Flush
    self._output_module.WriteEvent(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 86, in WriteEvent
    self.WriteEventBody(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/dynamic.py", line 355, in WriteEventBody
    output_value = callback_function(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/dynamic.py", line 250, in _FormatTag
    return u' '.join(tag.tags)
AttributeError: 'str' object has no attribute 'tags'
```

The same python traceback error occurs when:
`psort.py -o l2tcsv -w evt.csv evt.pb
`
I've tried different evt and evtx files from different machines to no avail.

**Comment by joachimmetz** [comment] 2016-02-02 19:06
Thanks for the report. We'll have a look to see if we can reproduce the issue first.

**Comment by dfirfpi** [comment] 2016-02-10 16:48
I'm facing the very same issue, using version 1.4.0 (Windows OS).

Don't want to lead down a bad road, but when I execute psort on the tagget pstorage file the {tag} field is populated with all the data inside the "plaso_tagging" file coming from the pstorage file.

HEX: 2F 00 00 00 2A 0B 0A 09 64 66 61 78 5F 62 61 61 68 32 20 62 64 61 35 62 30 32 63 38 36 39 38 34 63 33 31 62 35 61 36 36 61 31 36 39 63 32 62 31 38 35 39
ASCII: /...*...dfax_baah2 bda5b02c86984c31b5a66a169c2b1859 

{tag}: ...*...dfax_baah2 bda5b02c86984c31b5a66a169c2b1859 

Could it be related to an error during reading/writing/serialization of the pb file?

Find attached a small sample with a single event: single.pb (before tagging), single_tagged.pb (after tagging).

Please let me know if you need further info, thank you.

[tagging.zip](https://github.com/log2timeline/plaso/files/125128/tagging.zip)

**Comment by elceef** [comment] 2016-02-12 08:49
Same issue here using plaso 1.4.0

```
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 698, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 693, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 642, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 267, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 525, in ProcessStorage
    time_slice=time_slice)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 402, in ProcessEventsFromStorage
    if my_filter.Match(event_match):
  File "/usr/lib/python2.7/dist-packages/plaso/filters/event_filter.py", line 42, in Match
    self._decision = self._matcher.Matches(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/lib/objectfilter.py", line 246, in Matches
    if values and self.Operate(values):
  File "/usr/lib/python2.7/dist-packages/plaso/lib/objectfilter.py", line 233, in Operate
    for val in values:
  File "/usr/lib/python2.7/dist-packages/plaso/lib/objectfilter.py", line 527, in Expand
    attr_value = self._GetValue(obj, attr_name)
  File "/usr/lib/python2.7/dist-packages/plaso/lib/pfilter.py", line 126, in _GetValue
    return ret.tags
AttributeError: 'str' object has no attribute 'tags'
```

**Comment by querist** [comment] 2016-02-12 17:42
Same error here with Windows version from installer. I will test tonight or tomorrow morning with OS X version.

**Comment by Onager** [comment] 2016-02-12 18:10
Just to check - everyone is using Plaso 1.4 to both extract, tag and output (psort), correct?

**Comment by querist** [comment] 2016-02-12 18:12
Yes. Downloaded and installed two days ago.

**Comment by elceef** [comment] 2016-02-12 23:45
I also get error `AttributeError: 'str' object has no attribute 'tags'` using Plaso 1.4 for a container created with Plaso 1.3

**Comment by joachimmetz** [comment] 2016-02-14 19:55
Issue reproduces fix pending: https://codereview.appspot.com/282600043

**Comment by querist** [comment] 2016-02-15 14:21
Does this mean that the code is in the github master branch?

----------------------------
妇女能顶半边天
-- 毛泽东

**Comment by Onager** [comment] 2016-02-15 14:49
Nope, not yet - we'll update this issue when it's merged.

**Comment by joachimmetz** [comment] 2016-02-15 19:45
Merged, try again with HEAD and reopen if not working.

**Closed by joachimmetz** 2016-02-15 19:45 UTC
Labels: analysis, bug

**Comment by querist** [comment] 2016-02-15 21:07
I just did a pull and I am still receiving the same error.

questor:supertimeline querist$ psort.sh -w test.csv -z EST5EDT ./my-plaso.dmp 
WARNING: unable to determine location of data files.
[WARNING] Unable to automatically determine data location.
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 698, in <module>
    if not Main():
  File "/usr/local/bin/psort.py", line 693, in Main
    tool.ProcessStorage()
  File "/usr/local/bin/psort.py", line 642, in ProcessStorage
    self._ProcessStorage()
  File "/usr/local/bin/psort.py", line 267, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/Library/Python/2.7/site-packages/plaso/frontend/psort.py", line 525, in ProcessStorage
    time_slice=time_slice)
  File "/Library/Python/2.7/site-packages/plaso/output/event_buffer.py", line 49, in __exit__
    self.End()
  File "/Library/Python/2.7/site-packages/plaso/output/event_buffer.py", line 72, in End
    self.Flush()
  File "/Library/Python/2.7/site-packages/plaso/output/event_buffer.py", line 85, in Flush
    self._output_module.WriteEvent(event_object)
  File "/Library/Python/2.7/site-packages/plaso/output/interface.py", line 86, in WriteEvent
    self.WriteEventBody(event_object)
  File "/Library/Python/2.7/site-packages/plaso/output/dynamic.py", line 355, in WriteEventBody
    output_value = callback_function(event_object)
  File "/Library/Python/2.7/site-packages/plaso/output/dynamic.py", line 250, in _FormatTag
    return u' '.join(tag.tags)
AttributeError: 'str' object has no attribute 'tags'
questor:supertimeline querist$

**Comment by joachimmetz** [comment] 2016-02-15 21:11
What does `psort.sh -V` return?

**Comment by querist** [comment] 2016-02-15 21:16
plaso - psort version 1.4.0

**Comment by joachimmetz** [comment] 2016-02-15 21:19
So you're still testing with the old code the version should be: `plaso - psort version 1.4.1_20160215`

Try running the following from the checked out source:
```
PYTHONPATH=.;/Library/Python/2.7/site-packages/ python tools/psort.py -V 
```

**Comment by querist** [comment] 2016-02-15 21:24
questor:plaso querist$ PYTHONPATH=.:/Library/Python/2.7/site-packages/
questor:plaso querist$ python tools/psort.py -V
Traceback (most recent call last):
  File "tools/psort.py", line 24, in <module>
    from plaso.cli.helpers import manager as helpers_manager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaso-1.4.1.post20160215-py2.7.egg/plaso/cli/helpers/__init__.py", line 4, in <module>
    from plaso.cli.helpers import dynamic_output
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaso-1.4.1.post20160215-py2.7.egg/plaso/cli/helpers/dynamic_output.py", line 7, in <module>
    from plaso.output import dynamic
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaso-1.4.1.post20160215-py2.7.egg/plaso/output/__init__.py", line 12, in <module>
    from plaso.output import pstorage
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaso-1.4.1.post20160215-py2.7.egg/plaso/output/pstorage.py", line 9, in <module>
    from plaso.storage import zip_file
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaso-1.4.1.post20160215-py2.7.egg/plaso/storage/zip_file.py", line 92, in <module>
    from google.protobuf import message
ImportError: No module named google.protobuf

**Comment by joachimmetz** [comment] 2016-02-15 21:28
PYTHONPATH and python should be on the same command line otherwise you need to export PYTHONPATH. But you also appear to use a non Apple provided python release. Make sure you use the Apple provided one if you're using the pkgs provided by plaso (also see: https://github.com/log2timeline/plaso/wiki/Dependencies-Mac-OS-X)

**Comment by querist** [comment] 2016-02-15 21:34
I do not remember ever changing my python to a non-standard one. How can I check?

**Comment by joachimmetz** [comment] 2016-02-15 21:39
so `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages` is not the default path for `site-packages` but you can try `which python` and `whereis python` to which python versions are available.

**Comment by joachimmetz** [comment] 2016-02-15 21:43
As per [convention]9https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) `/usr/bin/python` is the Apple provided one

**Comment by querist** [comment] 2016-02-15 21:46
Let me see if I can unlink that other one and remove it from the path...

**Comment by querist** [comment] 2016-02-15 21:48
questor:~ querist$ PYTHONPATH=.:/Library/Python/2.7/site-packages/ /usr/bin/python Downloads/forensics/plaso/tools/psort.py -V
plaso - psort version 1.4.0
questor:~ querist$

**Comment by joachimmetz** [comment] 2016-02-15 21:49
Not sure what you mean with `unlink` but here an explanation of the [term](https://en.wikipedia.org/wiki/Unlink_(Unix)) 

In your case make sure to set `PYTHONPATH` correctly:
```
PYTHONPATH=Downloads/forensics/plaso:/Library/Python/2.7/site-packages/ /usr/bin/python Downloads/forensics/plaso/tools/psort.py -V
```

**Comment by querist** [comment] 2016-02-15 21:50
questor:~ querist$ PYTHONPATH=Downloads/forensics/plaso:/Library/Python/2.7/site-packages/ /usr/bin/python Downloads/forensics/plaso/tools/psort.py -V
Traceback (most recent call last):
  File "Downloads/forensics/plaso/tools/psort.py", line 27, in <module>
    from plaso.frontend import psort
  File "/Users/querist/Downloads/forensics/plaso/plaso/frontend/psort.py", line 22, in <module>
    from plaso.multi_processing import multi_process
  File "/Users/querist/Downloads/forensics/plaso/plaso/multi_processing/multi_process.py", line 18, in <module>
    from plaso.engine import engine
  File "/Users/querist/Downloads/forensics/plaso/plaso/engine/engine.py", line 14, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/Users/querist/Downloads/forensics/plaso/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/Users/querist/Downloads/forensics/plaso/plaso/preprocessors/macosx.py", line 10, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/Users/querist/Downloads/forensics/plaso/plaso/parsers/__init__.py", line 16, in <module>
    from plaso.parsers import hachoir
  File "/Users/querist/Downloads/forensics/plaso/plaso/parsers/hachoir.py", line 7, in <module>
    import hachoir_core.config
ImportError: No module named hachoir_core.config

**Comment by joachimmetz** [comment] 2016-02-15 21:55
You'll need to install the 

I opt the following (since we keep going back and forth and I'm explaining very basic system steps to you here and it is getting late here):

* read up on the different plaso versions: https://github.com/log2timeline/plaso/wiki/Releases-and-roadmap and the developer version: https://github.com/log2timeline/plaso/wiki/Developers-Guide
* read up on Mac OS X (or BSD Unix) essentials

**Comment by joachimmetz** [comment] 2016-02-15 22:00
End-to-end test confirm fix is working: https://travis-ci.org/log2timeline/plaso/builds/109449483

**Comment by querist** [comment] 2016-02-15 22:02
OK. I found the problem - I installed Python with Macports. I'm trying to uninstall it now. Thanks.

**Comment by querist** [comment] 2016-02-15 22:10
Python version conflict corrected, but now a new issue... i'm trying to track down the dependencies.

sh-3.2# ./run_tests.py 
Checking availability and versions of plaso dependencies.
[OK]		artifacts version: 20160114
[OK]		bencode
[OK]		binplist version: 0.1.5
[OK]		construct version: 2.5.2
[OK]		dateutil version: 1.5
[OK]		dfvfs version: 20160108
[FAILURE]	dfwinreg version: 20151105 is too old, 20160116 or later required.
[OK]		dpkt version: 1.8.6.2
[OK]		google.protobuf
[FAILURE]	missing: hachoir_core.
[FAILURE]	missing: hachoir_parser.
[FAILURE]	missing: hachoir_metadata.
[OK]		IPython version: 1.2.1
[OK]		pefile version: 1.2.10-139
[OK]		psutil version: 1.2.1
[FAILURE]	pyparsing version: 2.0.1 is too old, 2.0.3 or later required.
[OK]		pytz
[OK]		requests version: 2.9.1
[OK]		six version: 1.4.1
[OK]		xlsxwriter version: 0.8.4
[OK]		yaml version: 3.11
[OK]		zmq version: 15.2.0
[OK]		sqlite3 version: 3.8.5
[OK]		SleuthKit version: 4.2.0
[OK]		pytsk3 version: 20150406
[OK]		libbde (pybde) version: 20160110
[OK]		libesedb (pyesedb) version: 20151213
[OK]		libevt (pyevt) version: 20160107
[OK]		libevtx (pyevtx) version: 20160107
[OK]		libewf (pyewf) version: 20140608
[OK]		libfsntfs (pyfsntfs) version: 20160108
[OK]		libfwsi (pyfwsi) version: 20160110
[OK]		liblnk (pylnk) version: 20160107
[OK]		libmsiecf (pymsiecf) version: 20160107
[OK]		libolecf (pyolecf) version: 20160107
[OK]		libqcow (pyqcow) version: 20160123
[OK]		libregf (pyregf) version: 20160107
[OK]		libscca (pyscca) version: 20160108
[OK]		libsigscan (pysigscan) version: 20160108
[OK]		libsmdev (pysmdev) version: 20160109
[OK]		libsmraw (pysmraw) version: 20160108
[OK]		libvhdi (pyvhdi) version: 20160108
[OK]		libvmdk (pyvmdk) version: 20160119
[OK]		libvshadow (pyvshadow) version: 20160110

**Comment by joachimmetz** [comment] 2016-02-16 07:03
Check the links I pointed to you out earlier.

**Comment by querist** [comment] 2016-02-16 13:05
I know my way around UNIX as I've been using it since the 1980s. :-) What
tripped me up was the fact that installing Python with macports installed a
second copy rather than overwriting the existing one.

That and the requirement for hachoir.

I fixed it on my Mac. Now I need to wait to tomorrow when I will be back in
the office to update it on the Windows box.

Thanks.

2016年2月16日星期二，Joachim Metz <notifications@github.com> 写道：

> Check the links I pointed to you out earlier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/log2timeline/plaso/issues/572#issuecomment-184552424>.
>


-- 
----------------------------
妇女能顶半边天
-- 毛泽东

**Comment by querist** [comment] 2016-02-17 15:38
OK - strange problem. I used the Windows installer to install log2timeline originally on my Windows machine. When I run check_dependencies.py after cloning the git head it reports that I'm missing nearly all of the dependencies.

Will the fix be put into a Windows installer, or is there some other way to make it find the dependencies correctly that the old Windows installer installed?

**Comment by joachimmetz** [comment] 2016-02-17 17:30
>  I used the Windows installer to install log2timeline originally on my Windows machine

It is unclear to me what you mean? If you are running into issues because of differences between the packaged and development version. It is all outlined in the links I mentioned to you earlier.

**Comment by querist** [comment] 2016-02-17 18:43
I followed the instructions, installed the dependencies, and it still does
not find the dependencies.

2016年2月17日星期三，Joachim Metz <notifications@github.com> 写道：

> I used the Windows installer to install log2timeline originally on my
> Windows machine
>
> It is unclear to me what you mean? If you are running into issues because
> of differences between the packaged and development version. It is all
> outlined in the links I mentioned to you earlier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/log2timeline/plaso/issues/572#issuecomment-185314685>.
>


-- 
----------------------------
妇女能顶半边天
-- 毛泽东
