### ISSUE TITLE
Question - What are the possible "additional fields"

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#1595] opened 2017-12-28 23:12 UTC
The following is found in the psort.py usage.  What are the possible additional fields?  I have searched the docs and even tried to review code to find this answer.  I have not had any luck so I am raising the question here.

A related question - Is there documentation of the database structure for the storage file? 

Thanks for your help with this question(s).

-Mark

--additional_fields ADDITIONAL_FIELDS
                        Defines extra fields to be included in the output, in
                        addition to the default fields, which are datetime,
                        timestamp_desc, source, source_long, message, parser,
                        display_name, tag.

**Comment by joachimmetz** [comment] 2017-12-29 05:21
> What are the possible additional fields?

This might answer your question: https://github.com/log2timeline/plaso/issues/1562

> A related question - Is there documentation of the database structure for the storage file?
The docstring of the class: https://github.com/log2timeline/plaso/blob/master/plaso/storage/zip_file.py

However we are deprecating the ZIP storage in favor of SQLite storage.

**Comment by joachimmetz** [comment] 2018-01-06 17:48
Duplicate of https://github.com/log2timeline/plaso/issues/1636

**Closed by joachimmetz** 2018-01-06 17:48 UTC
Labels: question
