### ISSUE TITLE
SIGSEGV in libcdata_btree_replace_value()

### ISSUE THREAD

**Issue by apapadop** [log2timeline/plaso#81] opened 2015-01-11 00:19 UTC
I'm hand-copying this from apport as I'm not sure how to copy/paste from Ubuntu's crash reporter.

I was running
log2timeline.py --vss_stores 1..7 --log foo.log foo.dump image.dd &> foo.err
to hopefully debug #71 when this happened:

log2timeline.py crashed with SIGSEGV in libcdata_btree_replace_value()
Arch: amd64
Distro: Ubuntu 14.04
Interpreter: /usr/bin/python2.7
SegvReason: reading unknown VMA
Uname: Linux 3.13.0-43-generic x86_64

This has also been submitted via apport.

**Comment by joachimmetz** [comment] 2015-01-11 08:09
Could you try to run log2timeline in gdb and send me a backtrace. See section "Run The Tool as a single process with gdb" of https://sites.google.com/a/kiddaland.net/plaso/developer/troubleshooting

**Comment by joachimmetz** [comment] 2015-01-15 07:29
> This has also been submitted via apport.

This ends up with Ubuntu and this info is not directly accessible.

**Comment by joachimmetz** [comment] 2015-01-22 07:28
@apapadop some signs of life please

**Comment by apapadop** [comment] 2015-01-22 09:10
Joachim, sorry for the lack of response. Complicating factors:
- each run takes 12+ hours
- each run seems to fail in a different way - which is particularly frustrating... e.g. the latest run got stuck in an endless cycle of:

2015-01-12 16:09:44,011 [INFO] (MainProcess) PID:11631 <foreman> Worker_4 [11648] - Events Extracted: 560647 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/fedtmsg[1].js) - Running: True <sleeping>
2015-01-12 16:09:54,014 [INFO] (MainProcess) PID:11631 <foreman> Worker_0 [11640] - Events Extracted: 675839 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/flag-DE[1].png) - Running: True <sleeping>
2015-01-12 16:09:54,017 [INFO] (MainProcess) PID:11631 <foreman> Worker_1 [11641] - Events Extracted: 710476 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/featured_product_0[1].jpg) - Running: True <sleeping>
2015-01-12 16:09:54,018 [WARNING] (MainProcess) PID:11631 <foreman> Unable to connect to RPC socket to: Worker_2 at http://localhost:11643
2015-01-12 16:09:54,018 [ERROR] (MainProcess) PID:11631 <foreman> Process Worker_2 [11643] is not functioning when it should be. Terminating it and removing from list.
2015-01-12 16:09:54,019 [WARNING] (MainProcess) PID:11631 <foreman> Process Worker_2 [11643] is still alive.
2015-01-12 16:09:54,022 [INFO] (MainProcess) PID:11631 <foreman> Worker_3 [11645] - Events Extracted: 589770 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/featured_product_3[1].jpg) - Running: True <sleeping>
2015-01-12 16:09:54,024 [INFO] (MainProcess) PID:11631 <foreman> Worker_4 [11648] - Events Extracted: 560647 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/fedtmsg[1].js) - Running: True <sleeping>
2015-01-12 16:10:04,028 [INFO] (MainProcess) PID:11631 <foreman> Worker_0 [11640] - Events Extracted: 675839 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/flag-DE[1].png) - Running: True <sleeping>
2015-01-12 16:10:04,030 [INFO] (MainProcess) PID:11631 <foreman> Worker_1 [11641] - Events Extracted: 710476 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/featured_product_0[1].jpg) - Running: True <sleeping>
2015-01-12 16:10:04,031 [WARNING] (MainProcess) PID:11631 <foreman> Unable to connect to RPC socket to: Worker_2 at http://localhost:11643
2015-01-12 16:10:04,031 [ERROR] (MainProcess) PID:11631 <foreman> Process Worker_2 [11643] is not functioning when it should be. Terminating it and removing from list.
2015-01-12 16:10:04,032 [WARNING] (MainProcess) PID:11631 <foreman> Process Worker_2 [11643] is still alive.
2015-01-12 16:10:04,035 [INFO] (MainProcess) PID:11631 <foreman> Worker_3 [11645] - Events Extracted: 589770 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/featured_product_3[1].jpg) - Running: True <sleeping>
2015-01-12 16:10:04,036 [INFO] (MainProcess) PID:11631 <foreman> Worker_4 [11648] - Events Extracted: 560647 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/fedtmsg[1].js) - Running: True <sleeping>
2015-01-12 16:10:14,038 [INFO] (MainProcess) PID:11631 <foreman> Worker_0 [11640] - Events Extracted: 675839 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/flag-DE[1].png) - Running: True <sleeping>
2015-01-12 16:10:14,041 [INFO] (MainProcess) PID:11631 <foreman> Worker_1 [11641] - Events Extracted: 710476 - File (/Users/abslfi/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/SQR38RTM/featured_product_0[1].jpg) - Running: True <sleeping>
2015-01-12 16:10:14,042 [WARNING] (MainProcess) PID:11631 <foreman> Unable to connect to RPC socket to: Worker_2 at http://localhost:11643
2015-01-12 16:10:14,042 [ERROR] (MainProcess) PID:11631 <foreman> Process Worker_2 [11643] is not functioning when it should be. Terminating it and removing from list.
2015-01-12 16:10:14,043 [WARNING] (MainProcess) PID:11631 <foreman> Process Worker_2 [11643] is still alive.

After hours of outputting the same messages I just had to CTRL-C out. Does this qualify as a new bug? Or is it an instance of #71 ?

I will now follow the debugging instructions and hopefully have results for you by tonight.

**Comment by joachimmetz** [comment] 2015-01-22 09:51
Thx, for the update. I wanted to make sure we can try to find the root cause here and try to fix it.

> each run takes 12+ hours

Useful feedback; something for me to consider if we can come up with a way of some automated lightweight testing first to rule out problems.

> each run seems to fail in a different way - which is particularly frustrating...

Sounds like a subtle bug; maybe in thread locking somewhere.

> After hours of outputting the same messages I just had to CTRL-C out.

Sounds very similar to issue 71; no need to file a new issue. In those cases you can add the info to same issue but you've already done so by mentioning the issue ;)

**Comment by apapadop** [comment] 2015-01-22 09:59
Currently #94 is blocking this issue for me.

Please note in terms of 12+ hours runtime that log2timeline-perl takes approx 1 hour on the same hardware for the same image. There are 7 VSS snapshots on the image I'm examining but still... something not quite right here.

**Comment by joachimmetz** [comment] 2015-01-23 07:34
> Please note in terms of 12+ hours runtime that log2timeline-perl takes approx 1 hour on the same hardware for the same image

Comparing the perl version with the python version is comparing apples and oranges.
Also if you process all the VSS you are processing 1 + 7 number of systems.

There are certain performance issues with the storage but work is in progress to get fixed. However the performance also highly depends on what parsers you enable/disable.

There is currently some issues with the dev version that need to be fixed before a useful test run can be done. However to make the test representative it would be useful if you could test with the version that caused the issue in the first place.

**Comment by joachimmetz** [comment] 2015-04-14 05:20
No update from OP in a while. Cannot fix issue without the necessary debug information. Closing issue for now.

**Comment by joachimmetz** [comment] 2015-04-14 05:21
Marking wontfix for lack of cantfix label.

**Closed by joachimmetz** 2015-04-14 05:20 UTC
Labels: bug
