### ISSUE TITLE
TimeSketch output disabled

### ISSUE THREAD

**Issue by orlikoski** [log2timeline/plaso#2398] opened 2019-03-19 15:03 UTC
**Description of problem:**

The TimeSketch output to psorty.py is disabled after installing the latest versions of Plaso and Timesketch. This has happened on freshly installed systems as well as systems that have used `apt-get update && apt-get dist-upgrade -y` to update the OS and APT installed software (which included Plaso).

**Command line and arguments:**
```
skadi@skadi:~$ psort.py -o list

******************************** Output Modules ********************************
          Name : Description
--------------------------------------------------------------------------------
           tln : TLN 5 field | delimited output.
       elastic : Saves the events into an Elasticsearch database.
          xlsx : Excel Spreadsheet (XLSX) output
       dynamic : Dynamic selection of fields for a separated value output
                 format.
          json : Saves the events into a JSON format.
          null : Output module that does not output anything.
           kml : Saves events with geography data into a KML format.
         rawpy : "raw" (or native) Python output.
4n6time_sqlite : Saves the data in a SQLite database, used by the tool 4n6time.
        l2tcsv : CSV format used by legacy log2timeline, with 17 fixed fields.
     json_line : Saves the events into a JSON line format.
      elastic5 : Saves the events into an Elasticsearch5 database.
        l2ttln : Extended TLN 7 field | delimited output.
--------------------------------------------------------------------------------

*************************** Disabled Output Modules ****************************
         Name : Description
--------------------------------------------------------------------------------
4n6time_mysql : MySQL database output for the 4n6time tool.
   timesketch : Create a Timesketch timeline.
--------------------------------------------------------------------------------
```

Please provide the source data you used when you experienced the problem.
For publicly available data please provide an URL or path of the source data.

**Plaso version:**
```
skadi@skadi:~$ psort.py --version
plaso - psort version 20190131
```
**Operating system Plaso is running on:**

Tested on Ubuntu 16.04

**Installation method:**
The following script was run to install both Plaso and TimeSketch

```
#!/bin/bash
set -e

# Update
sudo apt-get update && sudo apt-get dist-upgrade -y

# Install deps
sudo apt-get install -y\
  openssh-server \
  git \
  apt-transport-https \
  ca-certificates \
  curl \
  software-properties-common \
  python-pip \
  glances \
  unzip \
  vim \
  htop \
  apache2-utils
sudo pip install --upgrade pip

# Add Plaso repository
sudo add-apt-repository ppa:gift/stable -y

# Install Plaso
sudo apt-get update
sudo apt-get install -y \
  python-plaso \
  plaso-tools \
  python-psycopg2

# Install TimeSketch on the Host  from GitHub Master with Pip (required for psort.py to output in timesketch format)
sudo git clone https://github.com/google/timesketch.git /opt/timesketch
sudo chown -R skadi:skadi /opt/timesketch
cd /opt/timesketch && yarn install && yarn run build
sed -i -e '/pyyaml/d' /opt/timesketch/requirements.txt
pip install /opt/timesketch/
```

**Comment by joachimmetz** [comment] 2019-03-19 16:01
Per https://github.com/log2timeline/plaso/blob/master/plaso/output/timesketch_out.py the timesketch module is conditional based on:
```
try:
  from flask import current_app
  import timesketch
  from timesketch.models import db_session as timesketch_db_session
  from timesketch.models import sketch as timesketch_sketch
  from timesketch.models import user as timesketch_user
except ImportError:
timesketch = None
```

**Comment by joachimmetz** [comment] 2019-03-19 16:02
@berggren do you recall if anything has changed recently that would break these imports.

@orlikoski could you check which of these imports fails on your configuration

**Comment by orlikoski** [comment] 2019-03-19 16:28
In my quick test (all details below) I didn't see anything fail to import
```
skadi@skadi:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask import current_app
>>> import timesketch
>>> from timesketch.models import db_session as timesketch_db_session
>>> from timesketch.models import sketch as timesketch_sketch
>>> from timesketch.models import user as timesketch_user
>>> exit(1)
skadi@skadi:~$ psort.py -o list

******************************** Output Modules ********************************
          Name : Description
--------------------------------------------------------------------------------
          xlsx : Excel Spreadsheet (XLSX) output
           kml : Saves events with geography data into a KML format.
         rawpy : "raw" (or native) Python output.
       elastic : Saves the events into an Elasticsearch database.
4n6time_sqlite : Saves the data in a SQLite database, used by the tool 4n6time.
      elastic5 : Saves the events into an Elasticsearch5 database.
        l2tcsv : CSV format used by legacy log2timeline, with 17 fixed fields.
          null : Output module that does not output anything.
       dynamic : Dynamic selection of fields for a separated value output
                 format.
           tln : TLN 5 field | delimited output.
          json : Saves the events into a JSON format.
     json_line : Saves the events into a JSON line format.
        l2ttln : Extended TLN 7 field | delimited output.
--------------------------------------------------------------------------------

*************************** Disabled Output Modules ****************************
         Name : Description
--------------------------------------------------------------------------------
4n6time_mysql : MySQL database output for the 4n6time tool.
   timesketch : Create a Timesketch timeline.
--------------------------------------------------------------------------------
```

**Comment by joachimmetz** [comment] 2019-03-19 16:28
so on Xenial the plaso-tools depend on python3-plaso by default. Which version of python do you run pip?

**Comment by orlikoski** [comment] 2019-03-19 16:32
Interesting

For version 20190131
```
skadi@skadi:~$ head /usr/bin/psort.py
#!/usr/bin/python3.5
```

For version 20181219
```
skadi@skadi:~$ head /usr/bin/psort.py
#! /usr/bin/python
```

**Comment by orlikoski** [comment] 2019-03-19 16:51
So the solution is to force Xenial to use pip3 to install/update TimeSketch in for versions of Plaso 20181219 and newer?  On Bionic that won't be required because pip3 is used by default?

I just did that and the timesketch output module is enabled.

**Comment by joachimmetz** [comment] 2019-03-19 17:46
> I just did that and the timesketch output module is enabled but want to make it's documented and confirmed to be correct

The more structural way to solve this is to use 1 package manager, this is why we're adding timesketch to GIFT PPA. This also allows for a dev track and catching integration issues before releases.

**Comment by joachimmetz** [comment] 2019-03-19 20:27
Marking as duplicate of https://github.com/log2timeline/plaso/issues/2344

**Closed** 2019-03-19 20:28 UTC
Labels: duplicate
