### ISSUE TITLE
image_export doesn't substitute variables from filter file

### ISSUE THREAD

**Issue by ant1** [log2timeline/plaso#1731] opened 2018-02-24 16:46 UTC
I am using plaso version 20180127.

When I use image_export on a windows image with filter file filter_windows.txt ,  it seems {systemroot} substitution doesn't happen.

$ image_export.py -w /tmp/export/ -f /usr/local/share/plaso/filter_windows.txt /path/to/win7-32-c-drive.E01
...
Extracting file entries from: TSK:/
2018-02-24 14:56:57,234 [WARNING] (MainProcess) PID:73842 <filter_file> The path filter must be defined as an abolute path: {systemroot}/System32/config/(SAM|SOFTWARE|SECURITY|SYSTEM)
2018-02-24 14:56:57,234 [WARNING] (MainProcess) PID:73842 <filter_file> The path filter must be defined as an abolute path: {systemroot}/System32/winevt/Logs/.+[.]evtx
2018-02-24 14:56:57,234 [WARNING] (MainProcess) PID:73842 <filter_file> The path filter must be defined as an abolute path: {systemroot}/System32/config/.+[.]evt
...

**Comment by Onager** [comment] 2018-03-01 18:44
Possibly related to #396

**Comment by ant1** [comment] 2018-03-01 19:13
Patch below fixes the issue for me.  However I don't know if it's correct.

```
diff --git a/plaso/cli/image_export_tool.py b/plaso/cli/image_export_tool.py
index 9e2ee58..79d4268 100644
--- a/plaso/cli/image_export_tool.py
+++ b/plaso/cli/image_export_tool.py
@@ -305,8 +305,8 @@ class ImageExportTool(storage_media_tool.StorageMediaTool):
       file_system, mount_point = self._GetSourceFileSystem(
           source_path_spec, resolver_context=self._resolver_context)
 
-      if self._knowledge_base is None:
-        self._Preprocess(file_system, mount_point)
+      #if self._knowledge_base is None:
+      self._Preprocess(file_system, mount_point)
 
       display_name = path_helper.PathHelper.GetDisplayNameForPathSpec(
           source_path_spec)
```

**Comment by Onager** [comment] 2018-11-07 23:04
From the fix, this seems to be the same root cause as #396  - that the knowledge base only supports one system configuration, and it's from the first partition examined. Marking this a duplicate of that issue, to consolidate work.

**Closed by Onager** 2018-11-07 23:04 UTC
Labels: needs closer look, tools
