### ISSUE TITLE
TypeError deserializing pathspec

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#4655] opened 2023-05-16 10:03 UTC
From #4640 

Traceback:
```
pinfo.py /Users/onager/disk.plaso 

************************** Plaso Storage Information ***************************
            Filename : disk.plaso
      Format version : 20230107
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
bbdd6bd9-aae1-4a8b-b0c2-81a907c5df79 : 2023-04-28T11:50:16.857555+00:00
--------------------------------------------------------------------------------
2023-05-12 13:15:10,312 [WARNING] (MainProcess) PID:78955 <tools> Unable to set memory limit to 4294967296 current limit is 9223372036854775807.
Traceback (most recent call last):
  File "/Users/onager/code/plaso/tools/pinfo.py", line 85, in <module>
    if not Main():
  File "/Users/onager/code/plaso/tools/pinfo.py", line 62, in Main
    tool.PrintStorageInformation()
  File "/Users/onager/code/plaso/plaso/cli/pinfo_tool.py", line 1682, in PrintStorageInformation
    self._PrintStorageInformation(storage_reader)
  File "/Users/onager/code/plaso/plaso/cli/pinfo_tool.py", line 1135, in _PrintStorageInformation
    self._PrintSourcesOverview(storage_reader)
  File "/Users/onager/code/plaso/plaso/cli/pinfo_tool.py", line 1203, in _PrintSourcesOverview
    for source_index, source in enumerate(generator):
  File "/Users/onager/.virtualenvs/plaso/lib/python3.9/site-packages/acstore/sqlite_store.py", line 499, in _GetAttributeContainersWithFilter
    container = self._CreatetAttributeContainerFromRow(
  File "/Users/onager/code/plaso/plaso/storage/sqlite/sqlite_file.py", line 89, in _CreatetAttributeContainerFromRow
    return super(SQLiteStorageFile, self)._CreatetAttributeContainerFromRow(
  File "/Users/onager/.virtualenvs/plaso/lib/python3.9/site-packages/acstore/sqlite_store.py", line 383, in _CreatetAttributeContainerFromRow
    attribute_value = self._schema_helper.DeserializeValue(
  File "/Users/onager/.virtualenvs/plaso/lib/python3.9/site-packages/acstore/sqlite_store.py", line 125, in DeserializeValue
    value = serializer.DeserializeValue(value)
  File "/Users/onager/code/plaso/plaso/storage/serializers.py", line 65, in DeserializeValue
    json_dict['parent'] = self.DeserializeValue(json_dict['parent'])
  File "/Users/onager/code/plaso/plaso/storage/serializers.py", line 58, in DeserializeValue
    json_dict = json.loads(value)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

DeserializeValue is being called with:
`{"__type__": "PathSpec", "parent": {"__type__": "PathSpec", "location": "/media/disk/usr/lib/kbd/consolefonts/alt-8x16.gz", "type_indicator": "OS"}, "type_indicator": "GZIP"}`

Which looks to be missing some string escaping, compared with my manual testing:

```python
parent_path_spec = dfvfs_path_spec_factory.Factory.NewPathSpec(
    dfvfs_definitions.TYPE_INDICATOR_OS,
    location='/media/disk/usr/lib/kbd/consolefonts/alt-8x16.gz')
path_spec = dfvfs_path_spec_factory.Factory.NewPathSpec(
    dfvfs_definitions.TYPE_INDICATOR_GZIP, parent=parent_path_spec)
serializer = serializers.JSONPathSpecAttributeSerializer()
print(serializer.SerializeValue(path_spec))
{"__type__": "PathSpec", "parent": "{\"__type__\": \"PathSpec\", \"location\": \"/media/disk/usr/lib/kbd/consolefonts/alt-8x16.gz\", \"type_indicator\": \"OS\"}", "type_indicator": "GZIP"}
```

So I assume that the escaping is being removed somewhere in the storage writing process

**Comment by joachimmetz** [comment] 2023-06-10 04:17
Was not able to reproduce this with HEAD, so let's test the next pre-release on this source data.

**Comment by joachimmetz** [comment] 2023-07-15 03:59
no updates from @Onager closing, reopen if issue still persist

**Closed by joachimmetz** 2023-07-15 03:59 UTC
Labels: blocked
