### ISSUE TITLE
 File "/usr/lib64/python2.7/collections.py", line 106, in values     return [self[key] for key in self] KeyError: '7779c7e5f1214e44a6a500dee1d9539d'

### ISSUE THREAD

**Issue by jasonblanks** [log2timeline/plaso#1010] opened 2016-09-27 16:32 UTC
**Plaso version:**

For example 1.5.0 Release

**Operating system Plaso is running on:**

CentOS running through virtualenv

**Installation method:**

https://github.com/log2timeline/plaso/wiki/running-plaso-in-virtualenv

**Description of problem:**

```
plaso - log2timeline version 1.5.0

Source path     : /data/images/2016-0945-00/2016-0945-00-HDD01.E01
Source type     : storage media image

Identifier      PID     Status          Sources         Events          File
Main            15282   running         124812 (0)      148935 (0)
Worker_00       15292   collecting      1903 (0)        3419 (0)        TSK:/Windows/System32/WindowsPowerShell/v1.0
Worker_01       15296   collecting      4843 (0)        10232 (0)       TSK:/Windows/System32/{
Worker_02       15300   collecting      6450 (0)        5009 (0)        TSK:/Windows/System32/SMI/Manifests
Worker_03       15304   collecting      2934 (0)        50431 (0)       TSK:/Windows/System32/wdi/{c4a3}
Worker_04       15308   collecting      2917 (0)        3460 (0)        TSK:/Windows/System32/{3D
Worker_05       15312   running         3820 (7)        9815 (4)        TSK:/Windows/System32/{3DA
Worker_06       15316   collecting      21192 (0)       3489 (0)      TSK:/Windows/System32/wdi/{8643c
Worker_07       15320   collecting      3495 (0)        7159 (0)        TSK:/Windows/System32/winevt/Logs
Worker_08       15324   collecting      21358 (0)       3350 (0)        TSK:/Windows/System32/wdi/perftrack
Worker_09       15328   collecting      2212 (0)        12994 (0)       TSK:/Windows/System32/winrm/0409
Worker_10       15332   collecting      2206 (0)        16475 (0)       TSK:/Windows/System32/winevt/TraceFormat
Worker_11       15336   collecting      20089 (0)       3615 (0)        TSK:/Windows/System32/WinBioPlugIns/en-US
Worker_12       15340   collecting      4551 (0)        3547 (0)        TSK:/Windows/System32/wdi/{6
Worker_13       15344   collecting      15735 (0)       12450 (0)       TSK:/Windows/System32/{3DA228B
Worker_14       15348   collecting      11200 (0)       3510 (0)        TSK:/Windows/System32/SMI/Store

Traceback (most recent call last):
  File "/data/plaso/plasoenv/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.5.0', 'log2timeline.py')
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 767, in <module>
    if not Main():
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 753, in Main
    tool.ProcessSources()
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 664, in ProcessSources
    timezone=self._timezone, yara_rules_string=self._yara_rules_string)
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/frontend/extraction_frontend.py", line 483, in ProcessSources
    yara_rules_string=yara_rules_string)
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/multi_processing/task_engine.py", line 791, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/multi_processing/task_engine.py", line 288, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/multi_processing/task_engine.py", line 397, in _ScheduleTasks
    while event_source or self._task_manager.HasActiveTasks():
  File "/data/plaso/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/multi_processing/task_manager.py", line 192, in HasActiveTasks
    for task in iter(self._tasks_processing.values()):
  File "/usr/lib64/python2.7/collections.py", line 106, in values
    return [self[key] for key in self]
KeyError: '7779c7e5f1214e44a6a500dee1d9539d'
```

Not much to go on, didn't see much in the debug log, any pointers?

**Comment by jasonblanks** [comment] 2016-09-29 14:42
Closing this, I have re-kicked off the job on the same image this time it has been running for 3 days without error, not expecting to see this again.  Must have been a fluke, I don't think this issue report will be productive so I am closing.

**Comment by Onager** [comment] 2016-09-29 17:14
Hey Jason,
This actually looks like a very live issue, and probably isn't related to the specific image you're processing. @joachimmetz and I have been unavailable for a few days, so apologies for the delay getting back to you.

**Comment by Onager** [comment] 2016-10-03 10:39
It looks like the _tasks_processing dict is being modified while we're iterating over it in the task manager. Some possible sources of the bug:

- UpdateTaskAsPendingMerge
- HasActiveTasks
- RescheduleTaskByIdentifer
- UpdateTaskByIdentifier

**Comment by Onager** [comment] 2016-10-03 11:49
RescheduleTaskByIdentifier seems like a likely candidate, as it's called by a different thread.

**Comment by Onager** [comment] 2016-10-04 15:48
Additionally, I've noticed errors like this: 
```
16-10-04 15:29:06,809 [ERROR] (MainProcess) PID:2696 <task_engine> Worker Worker_00 is processing unknown task: 5b06d6ab742d4145a0ab6ae86d1e3fba.
2016-10-04 15:29:50,282 [ERROR] (MainProcess) PID:2696 <task_engine> Worker Worker_02 is processing unknown task: 9ff453995e234d47890d6ae8385ea0c8.
2016-10-04 15:29:53,608 [ERROR] (MainProcess) PID:2696 <task_engine> Worker Worker_00 is processing unknown task: 942fe66cf6f045f6adc77744084a393f.
2016-10-04 15:31:49,338 [ERROR] (MainProcess) PID:2696 <task_engine> Worker Worker_03 is processing unknown task: ee501283326c454e88f4a0352f69d735.
2016-10-04 15:32:02,417 [ERROR] (MainProcess) PID:2696 <task_engine> Worker Worker_06 is processing unknown task: 0da01781cea84488aee0a6808fc6ff02.
2016-10-04 15:36:32,614 [ERROR] (MainProcess) PID:2696 <task_engine> Worker Worker_02 is processing unknown task: c81e216283b6482592bb88585e51c7db.
```
Which look like they could be caused by concurrency issues between the main and update threads.

**Comment by jipegit** [comment] 2016-10-13 08:09
I also encountered what I guess is the same issue with version 1.5:

Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 791, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 288, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 397, in _ScheduleTasks
  File "plaso\multi_processing\task_manager.py", line 192, in HasActiveTasks
  File "collections.py", line 123, in values
KeyError: '24ce7d22e0e8489aa1c6f62279f035e0'
Failed to execute script log2timeline

**Comment by Onager** [comment] 2017-01-18 07:20
Per #1132 we still need to add some more locking.

**Comment by joachimmetz** [comment] 2017-08-14 07:00
@Onager to confirm this issue has been addressed or is there still work to be done?

**Comment by Onager** [comment] 2017-08-14 08:18
This is fixed now.

**Closed by Onager** 2017-08-14 08:18 UTC
Labels: bug, core
