### ISSUE TITLE
PSORT time slice and date v1.4 issues

### ISSUE THREAD

**Issue by 3Fingers** [log2timeline/plaso#721] opened 2016-06-01 12:31 UTC
**Plaso version:**

1.4.0 Release

**Operating system Plaso is running on:**

Windows 7 Enterprise x64

**Installation method:**

Windows binary downloaded from GitHub

**Description of problem:**
PSORT Time slice and filter by date not giving same results as v1.3. 1.3 the slice is as expected, with a default of 5 minutes before and 5 minutes after the subject date.  In 1.4, it appears that PSORT is outputting the entire database.  Tried filtering by specific dates "date > '2016-04-01 12:00:00' and date < '2016-04-01 12:10:00'" and this did not provide any results.  Rolled back to version 1.3 and everything worked as expected using the same commands.

**Comment by joachimmetz** [comment] 2016-06-17 06:06
Thx for the report. We'll look into this as soon as time permits and try to get this addressed before the 1.5 release.

**Comment by joachimmetz** [comment] 2016-07-07 18:32
Likely a duplicate of: https://github.com/log2timeline/plaso/issues/598

**Closed** 2016-07-07 18:32 UTC
Labels: duplicate
