### ISSUE TITLE
How can I parse an extracted USN journal?

### ISSUE THREAD

**Issue by DfirJos** [log2timeline/plaso#4240] opened 2022-09-15 14:23 UTC
When using Plaso to post-process a standalone USN journal file (30 MB - zero's removed) it does not post-process. Is there a way to add this functionality? Including a USN and MFT-merge based on MFT-ID so the result shows the filepaths.

**Comment by joachimmetz** [comment] 2022-09-15 14:26
a stand-alone UsnJrnl:$J is not supported

**Comment by joachimmetz** [comment] 2022-09-15 14:28
Duplicate of https://github.com/log2timeline/plaso/issues/1034

**Comment by joachimmetz** [comment] 2022-09-19 04:04
Also related https://github.com/log2timeline/plaso/issues/3604, closing issue.

**Closed by joachimmetz** 2022-09-19 04:04 UTC
Labels: duplicate, question
