### ISSUE TITLE
Log2timeline dependency problem

### ISSUE THREAD

**Issue by ricci3** [log2timeline/plaso#1998] opened 2018-07-02 12:37 UTC
Hello All,

Just recently downloaded version of the log2timeline/plaso docker version. But when execute the log2timeline.py, the log2timeline.py shows the failure error of missing pyewf in my MacOS docker

While for the sift workstation .ova version, when I executed log2timeline.py, the dependency check shows that the elastic search module is missing.

So can someone please advise:
1) what should I do to resolve the missing pyewf problem?
2) while for ova version, how to rectify the missing elastic search module issue?

Thx

Ricci

**Comment by Onager** [comment] 2018-07-02 13:44
How are you running the docker version? Are you building it yourself, or pulling from docker hub?

We don't maintain sift workstation, it looks like their issue tracker is here: https://github.com/sans-dfir/sift/issues

**Comment by Onager** [comment] 2018-07-02 13:44
In fact, it looks like the sift folks already have a fix documented: https://github.com/sans-dfir/sift/issues/283

**Comment by Rolinh** [comment] 2018-07-02 13:51
FWIW, I also encounter the pyewf dependency missing when running version `20180630`, from a freshly built docker image (Ubuntu 16:04, gift PPA installation), running `log2timeline`:

```
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lzma.
[FAILURE]       missing: pyewf.
```

**Comment by DeKe42** [comment] 2018-07-02 14:08
I'm experiencing the same thing in a fresh docker image.

I'm pretty sure the current `libewf-python` package in `ppa:gift` is incomplete. If I download it manually (or check with `dpkg-query -L`), it only contains documentation but no actual python module.

I'm referring to this file: https://launchpad.net/~gift/+archive/ubuntu/stable/+files/libewf-python_20140803-1ppa1~xenial_amd64.deb

**Comment by Onager** [comment] 2018-07-02 14:20
Yep, this looks like a problem with that package. We'll roll a new one.

**Comment by joachimmetz** [comment] 2018-07-02 14:47
having a look later today

**Comment by joachimmetz** [comment] 2018-07-02 14:51
so libewf_20140803-1ppa1~xenial_amd64.deb contains a shared object
libewf2_20140803-1ppa1~xenial_amd64.deb is a stub preventing Ubuntu to install and override libewf.so when not installed as libewf2.

**Comment by joachimmetz** [comment] 2018-07-02 14:55
> In fact, it looks like the sift folks already have a fix documented: sans-dfir/sift#283

Running `log2timeline.py --no-dependencies-check -V` is not a fix but a work-around

**Comment by joachimmetz** [comment] 2018-07-03 05:19
New libewf release building on launchpad

**Comment by joachimmetz** [comment] 2018-07-03 05:38
@ricci3 @DeKe42 @Rolinh could you try again and confirm that new libewf release works / does not work for you

**Comment by Rolinh** [comment] 2018-07-03 06:00
@joachimmetz I can confirm that it now works for me. Thanks for addressing this issue so quickly!

**Comment by ricci3** [comment] 2018-07-03 06:10
silly me. Please advise if this solution is already able to work for the docker version? If not, is that I should try using full installation?

**Comment by joachimmetz** [comment] 2018-07-03 06:32
> Please advise if this solution is already able to work for the docker version? 

How are you building your docker container? If you use the GIFT PPA then it should provide you with the new version.

**Comment by Onager** [comment] 2018-07-03 06:53
@ricci3 I've just updated the image on docker hub, you should be go now.

**Comment by ricci3** [comment] 2018-07-03 07:22
I didn't build mine. I just use docker pull log2timeline/plaso. may be I should try to pull again.

**Comment by Onager** [comment] 2018-07-03 09:00
Looks like this resolved, closing out.

**Closed by Onager** 2018-07-03 09:00 UTC
Labels: deployment, development
