### ISSUE TITLE
Error running log2timeline.py - Mac OS X El Capitan

### ISSUE THREAD

**Issue by Lou511** [log2timeline/plaso#476] opened 2015-12-28 13:39 UTC
I am encountering the following error when running log2timeline.py (Command: $ log2timeline.py test.plaso ~/Desktop/"Test Data"/15HT-0041/NTUSER.DAT)

```
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 22, in <module>
    from plaso.cli import extraction_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 7, in <module>
    from plaso.engine import engine
  File "/Library/Python/2.7/site-packages/plaso/engine/engine.py", line 11, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/macosx.py", line 10, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/Library/Python/2.7/site-packages/plaso/parsers/__init__.py", line 39, in <module>
    from plaso.parsers import skydrivelog
  File "/Library/Python/2.7/site-packages/plaso/parsers/skydrivelog.py", line 78, in <module>
    class SkyDriveLogParser(text_parser.PyparsingMultiLineTextParser):
  File "/Library/Python/2.7/site-packages/plaso/parsers/skydrivelog.py", line 129, in SkyDriveLogParser
    pyparsing.ZeroOrMore(pyparsing.lineEnd()))
TypeError: __call__() takes exactly 2 arguments (1 given)
```
I have seen this error elsewhere in a previous issue.  The recommendation was check the version of pyparsing - I have 2.0.6. I checked my python version - I have 2.7.  Log2timeline is using the following python path - /Library/Python/2.7... (not the python.framework path).  I changed the path as per troubleshooting instructions found here.

 I am running on El Capitan.  I'm wondering if this has anything to do with the error above.  I hope to receive some guidance as to how I can resolve this issue (I must be doing something wrong).

Thank you.

**Comment by Onager** [comment] 2015-12-28 14:33
Hi Lou,
If you're using the latest RC build of Plaso, try using the log2timeline.sh wrapper script, it should correct the python path to include the correct version of pyparsing. This looks to me like an issue with the pyparsing version. How are you setting PYTHONPATH? 

If you try the exact command line from #202, ```PYTHONPATH=/Library/Python/2.7/site-packages:$PYTHONPATH log2timeline.py --help``` what happens?

**Comment by Lou511** [comment] 2015-12-28 14:49
Interesting - logt2timeline runs (gives me the list of switches and other descriptors), when I try the exact command line from #202.  I should have tried that in the first place.  However, I'm curious about the meaning of "$PYTHONPATH" after ..../site-packages:

Before I posted this issue, I did create an alias for log2timeline, using "PYTHONPATH=/Library/Python/2.7/site-packages" (without ":$PYTHONPATH")

**Comment by joachimmetz** [comment] 2015-12-29 08:20
> However, I'm curious about the meaning of "$PYTHONPATH" after ..../site-packages:

"$PYTHONPATH" means the current contents of the shell variable PYTHONPATH (similar to %PYTHONPATH% on Windows) e.g.
```
echo $PYTHONPATH
PYTHONPATH=/Library/Python/2.7/site-packages:$PYTHONPATH && echo $PYTHONPATH
```

For more detailed information see: https://www.gnu.org/software/bash/manual/bashref.html

**Comment by joachimmetz** [comment] 2015-12-29 08:22
More detailed information about the root cause of your issue can be found here:
https://github.com/log2timeline/plaso/wiki/Dependencies-Mac-OS-X#pyparsing

Closing issue since the work-around seems to work for you.

**Closed by joachimmetz** 2015-12-29 08:22 UTC
Labels: question
