### ISSUE TITLE
dfvfs.lib.errors.CacheFullError: Maximum number of cached values reached

### ISSUE THREAD

**Issue by garanews** [log2timeline/plaso#2159] opened 2018-09-26 14:51 UTC
**Description of problem:**

Failed to execute script log2timeline

I see this issue in some old post and I was considering fixed, but I am receiving it with Plaso Version: 20180818 running on Windows...

**Command line and arguments:**

```
"C:\Users\Analyst\Tools\plaso-20180818-amd64/log2timeline.exe" "--partition" "all" "--vss_stores" "all" "--status_view" "linear" "--process_archives" "--parsers" "amcache,appcompatcache,bash,bash_history,bagmru,bencode_transmission,bencode_utorrent,binary_cookies,ccleaner,chrome_cache,chrome_cookies,chrome_extension_activity,chrome_history,chrome_preferences,cron,explorer_mountpoints2,explorer_programscache,filestat,firefox_cache,firefox_cache2,firefox_cookies,firefox_downloads,firefox_history,google_drive,hachoir,java_idx,lnk,mcafee_protection,mft,microsoft_office_mru,microsoft_outlook_mru,mrulist_shell_item_list,mrulist_string,mrulistex_shell_item_list,mrulistex_string,mrulistex_string_and_shell_item,mrulistex_string_and_shell_item_list,msie_zone,msiecf,mstsc_rdp,mstsc_rdp_mru,network_drives,olecf,openxml,opera_global,opera_typed_history,pe,pls_recall,prefetch,recycle_bin,recycle_bin_info2,rplog,safari_history,sccm,sophos_av,sqlite,syslog,ssh,symantec_scanlog,userassist,usnjrnl,windows_boot_execute,windows_boot_verify,windows_run,windows_sam_users,windows_services,windows_shutdown,windows_task_cache,windows_timezone,windows_typed_urls,windows_usb_devices,windows_usbstor_devices,windows_version,winevt,winevtx,winfirewall,winjob,winlogon,winrar_mru,winreg,winreg_default,xchatlog,xchatscrollback" "--hashers" "none" "--workers" "37" "J:/Cases/Plaso_Db_disk2.E01.plaso" "D:/disk2.E01" "--no_dependencies_check"
```

**Plaso version:**

20180818

**Operating system Plaso is running on:**

Windows 7 SP1

**Installation method:**

installed from https://github.com/log2timeline/plaso/releases/download/20180818/plaso-20180818-amd64.zip

**Comment by joachimmetz** [comment] 2018-09-27 07:00
thx for the additional info, I was actually looking for the name of the last filename image.E01. image.E02, image.E## (or something)?

**Comment by garanews** [comment] 2018-09-27 07:00
image.E01

**Comment by joachimmetz** [comment] 2018-09-27 07:02
Thx in that case I'll need to take a closer look at recent parser changes to see if there was regression.

**Comment by garanews** [comment] 2018-10-02 08:14
There is something that I can do to help you in order to find the issue?

**Comment by joachimmetz** [comment] 2018-10-03 09:59
Let me get back to you later this week.

**Comment by Onager** [comment] 2018-10-03 15:09
@garanews could you run with a debug log turned on? Instructions on how to do it there: https://github.com/log2timeline/plaso/wiki/Troubleshooting#producing-debug-logs

If you can't share the file due to sensitivity please have a look through the log for any references to parsers not closing files properly.

**Comment by garanews** [comment] 2018-10-04 10:00
In log file just one row with same error, but in console this:
![image](https://user-images.githubusercontent.com/16938405/46466877-ba70a380-c7cc-11e8-8745-2022f9993b0a.png)

Trying without -vss_stores all seems working.
FYI, I have just 29 vss.
(tried with 10 vss and get error, tried with 1 vss no error, maybe can help you)

**Comment by garanews** [comment] 2018-10-23 09:33
Hi, did you have some time to check this issue?

**Comment by MADx00** [comment] 2019-10-21 07:03
Hello,

Is there any update on this issue? or any workarounds?

**Comment by joachimmetz** [comment] 2020-02-24 08:10
@MADx00 @garanews are you still running into this issue with recent versions of dfVFS and plaso?

**Comment by joachimmetz** [comment] 2020-05-23 07:22
No response closing issue

**Closed by joachimmetz** 2020-05-23 07:22 UTC
Labels: needs closer look
