### ISSUE TITLE
Plaso hangs indefinitely on Google Earth files

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#107] opened 2015-02-11 16:56 UTC
I am using current version from git `log2timeline - plaso back-end 1.2.1_20150206` and experience a hangup over 10 minutes with Google Earth files where all worker processes appear stuck:

```
foobar@pc ~/> log2timeline.py ~/l2t.dump /var/run/media/foobar/Windows/
[...]
2015-02-11 17:45:04,742 [INFO] (MainProcess) PID:25014 <foreman> Worker_4 [25088] - Events Extracted: 21097 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476) - Running: True <sleeping>
2015-02-11 17:45:14,745 [INFO] (MainProcess) PID:25014 <foreman> Worker_0 [25079] - Events Extracted: 21111 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000473) - Running: True <sleeping>
2015-02-11 17:45:14,748 [INFO] (MainProcess) PID:25014 <foreman> Worker_1 [25081] - Events Extracted: 13369 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000474) - Running: True <sleeping>
2015-02-11 17:45:14,751 [INFO] (MainProcess) PID:25014 <foreman> Worker_2 [25083] - Events Extracted: 22223 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000472) - Running: True <sleeping>
2015-02-11 17:45:14,754 [INFO] (MainProcess) PID:25014 <foreman> Worker_3 [25086] - Events Extracted: 13119 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000475) - Running: True <sleeping>
2015-02-11 17:45:14,756 [INFO] (MainProcess) PID:25014 <foreman> Worker_4 [25088] - Events Extracted: 21097 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476) - Running: True <sleeping>
2015-02-11 17:45:24,759 [INFO] (MainProcess) PID:25014 <foreman> Worker_0 [25079] - Events Extracted: 21111 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000473) - Running: True <sleeping>
2015-02-11 17:45:24,762 [INFO] (MainProcess) PID:25014 <foreman> Worker_1 [25081] - Events Extracted: 13369 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000474) - Running: True <sleeping>
2015-02-11 17:45:24,765 [INFO] (MainProcess) PID:25014 <foreman> Worker_2 [25083] - Events Extracted: 22223 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000472) - Running: True <sleeping>
2015-02-11 17:45:24,768 [INFO] (MainProcess) PID:25014 <foreman> Worker_3 [25086] - Events Extracted: 13119 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000475) - Running: True <sleeping>
2015-02-11 17:45:24,771 [INFO] (MainProcess) PID:25014 <foreman> Worker_4 [25088] - Events Extracted: 21097 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476) - Running: True <sleeping>
2015-02-11 17:45:34,774 [INFO] (MainProcess) PID:25014 <foreman> Worker_0 [25079] - Events Extracted: 21111 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000473) - Running: True <sleeping>
2015-02-11 17:45:34,777 [INFO] (MainProcess) PID:25014 <foreman> Worker_1 [25081] - Events Extracted: 13369 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000474) - Running: True <sleeping>
2015-02-11 17:45:34,780 [INFO] (MainProcess) PID:25014 <foreman> Worker_2 [25083] - Events Extracted: 22223 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000472) - Running: True <sleeping>
2015-02-11 17:45:34,783 [INFO] (MainProcess) PID:25014 <foreman> Worker_3 [25086] - Events Extracted: 13119 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000475) - Running: True <sleeping>
2015-02-11 17:45:34,785 [INFO] (MainProcess) PID:25014 <foreman> Worker_4 [25088] - Events Extracted: 21097 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476) - Running: True <sleeping>
2015-02-11 17:45:44,788 [INFO] (MainProcess) PID:25014 <foreman> Worker_0 [25079] - Events Extracted: 21111 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000473) - Running: True <sleeping>
2015-02-11 17:45:44,791 [INFO] (MainProcess) PID:25014 <foreman> Worker_1 [25081] - Events Extracted: 13369 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000474) - Running: True <sleeping>
2015-02-11 17:45:44,793 [INFO] (MainProcess) PID:25014 <foreman> Worker_2 [25083] - Events Extracted: 22223 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000472) - Running: True <sleeping>
2015-02-11 17:45:44,796 [INFO] (MainProcess) PID:25014 <foreman> Worker_3 [25086] - Events Extracted: 13119 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000475) - Running: True <sleeping>
2015-02-11 17:45:44,798 [INFO] (MainProcess) PID:25014 <foreman> Worker_4 [25088] - Events Extracted: 21097 - File (/var/run/media/foobar/Windows/Users/XXXXXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476) - Running: True <sleeping>
^C2015-02-11 17:45:51,331 [WARNING] (MainProcess) PID:25014 <frontend> Stopping collector.
^C2015-02-11 17:46:24,774 [WARNING] (MainProcess) PID:25014 <log2timeline> Aborted by user.
^C^C^C^C^C^C^C^C^C^C^C^C^C^Cfish: Job 1, 'log2timeline.py ~/l2t.dump /var/run/media/foobar/Windows/ ' durch Signal SIGTERM (Höfliche Beendigungsanforderung) beendet
foobar@pc ~/ [143]>
```

The files in question could be supplied.

```
> file /var/run/media/foobar/Windows/Users/XXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476
/var/run/media/foobar/Windows/Users/XXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)
> ls -lh /var/run/media/foobar/Windows/Users/XXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476
-rw------- 1 foobar foobar 39K  7. Okt 12:45 /var/run/media/foobar/Windows/Users/XXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000476
```

These are the plaso depedencies I have installed:

```
> python2.7 utils/check_dependencies.py 
Checking availability and versions of plaso dependencies.
[OK]		bencode
[OK]		binplist version: 0.1.4
[OK]		construct version: 2.5.2
[OK]		dateutil.parser
[OK]		dfvfs version: 20150129
[OK]		dpkt version: 1.8
[OK]		google.protobuf
[OK]		hachoir_core version: 1.3.3
[OK]		hachoir_parser version: 1.3.4
[OK]		hachoir_metadata version: 1.3.3
[OK]		IPython version: 2.4.0
[OK]		yaml version: 3.11
[OK]		psutil version: 2.2.0
[OK]		pyparsing version: 2.0.3
[OK]		pytz
[OK]		six version: 1.9.0
[OK]		sqlite3 version: 3.8.8.2
[OK]		SleuthKit version: 4.1.3
[OK]		pytsk3 version: 20150114
[INFO]		libbde (pybde) version: 20150204 installed, version: 20150124 available.
[INFO]		libesedb (pyesedb) version: 20150105 installed, version: 20141110 available.
[OK]		libevt (pyevt) version: 20150105
[OK]		libevtx (pyevtx) version: 20150105
[INFO]		libewf (pyewf) version: 20140608 installed, version: 20150126 available.
[OK]		libfwsi (pyfwsi) version: 20150124
[OK]		liblnk (pylnk) version: 20150105
[OK]		libmsiecf (pymsiecf) version: 20150106
[OK]		libolecf (pyolecf) version: 20150106
[OK]		libqcow (pyqcow) version: 20150105
[OK]		libregf (pyregf) version: 20150105
[INFO]		libsigscan (pysigscan) version: 20150204 installed, version: 20150125 available.
[OK]		libsmdev (pysmdev) version: 20150105
[OK]		libsmraw (pysmraw) version: 20150105
[OK]		libvhdi (pyvhdi) version: 20150110
[OK]		libvmdk (pyvmdk) version: 20150105
[OK]		libvshadow (pyvshadow) version: 20150106
```

Do you have any idea what causes this?

**Comment by joachimmetz** [comment] 2015-02-11 21:50
This is likely due to the new and experimental compressed file support. This is still WIP.

**Comment by kiddinn** [comment] 2015-02-11 22:14
is this consistent? As in if you kill the tool and re-run it, does it keep hanging on these same files?

And what if you run the tool just against the directory that contains these files, eg:

    $ log2timeline.py ~/l2t.dump /var/run/media/foobar/Windows/Users/XXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/

Does the tool hang then as well?

And can you also run this against the disk image itself, instead of against the mount point. Does that result in the same issue?

**Comment by bf** [comment] 2015-02-11 22:21
Thanks for your feedback. It kept hanging up all the time, and from my observation the workers always were in <sleeping> or <disk-sleep> state when they locked up.

I re-ran log2timeline.py on the specific directory and it worked.. But it seems I have found another bug with psort.py?

These messages prompted me to try out the latest plaso version in an Ubuntu VM to rule out some weird arch linux issues. But with ubuntu 14.04, I get the same locking up of log2timeline.py worker threads after a while (<disk-sleep> state). Could the fact that I am using a hardware write blocker to access the disk be an issue here? I will try the same on an image tomorrow.

Here are some log files:


```
> log2timeline.py bugfix.dump /var/run/media/XXXXXXXX/Windows/Users/XXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/

Source path       : /var/run/media/XXXXXXXX/Windows/Users/XXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata
Is storage media image or device  : False

2015-02-11 23:15:26,543 [INFO] (MainProcess) PID:7497 <frontend> Starting extraction in multi process mode.
2015-02-11 23:15:26,591 [INFO] (MainProcess) PID:7497 <multi_process> Starting extraction worker processes.
2015-02-11 23:15:26,596 [INFO] (Worker_0  ) PID:7505 <worker> Worker 0 (PID: 7505) started monitoring process queue.
2015-02-11 23:15:26,599 [INFO] (Worker_1  ) PID:7506 <worker> Worker 1 (PID: 7506) started monitoring process queue.
2015-02-11 23:15:26,601 [INFO] (Worker_2  ) PID:7509 <worker> Worker 2 (PID: 7509) started monitoring process queue.
2015-02-11 23:15:26,603 [INFO] (Worker_3  ) PID:7511 <worker> Worker 3 (PID: 7511) started monitoring process queue.
2015-02-11 23:15:26,605 [INFO] (Worker_4  ) PID:7513 <worker> Worker 4 (PID: 7513) started monitoring process queue.
2015-02-11 23:15:27,899 [ERROR] (Worker_1  ) PID:7506 <syslog> Unable to determine year of syslog file.
Defautling to: 2015
2015-02-11 23:15:27,969 [ERROR] (Worker_4  ) PID:7513 <syslog> Unable to determine year of syslog file.
Defautling to: 2015
2015-02-11 23:15:27,970 [ERROR] (Worker_2  ) PID:7509 <syslog> Unable to determine year of syslog file.
Defautling to: 2015
2015-02-11 23:15:28,006 [ERROR] (Worker_3  ) PID:7511 <syslog> Unable to determine year of syslog file.
Defautling to: 2015
2015-02-11 23:15:28,635 [ERROR] (Worker_0  ) PID:7505 <syslog> Unable to determine year of syslog file.
Defautling to: 2015
2015-02-11 23:15:28,737 [INFO] (MainProcess) PID:7497 <foreman> Foreman received a signal indicating that processing is completed.
2015-02-11 23:15:29,323 [INFO] (MainProcess) PID:7497 <foreman> Worker_0 [7505] - Events Extracted: 361 - File (/var/run/media/XXXXXXXX/Windows/Users/XXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000377) - Running: True <sleeping>
2015-02-11 23:15:29,324 [INFO] (MainProcess) PID:7497 <foreman> Worker_1 [7506] - Events Extracted: 596 - File () - Running: True <sleeping>
2015-02-11 23:15:29,326 [INFO] (MainProcess) PID:7497 <foreman> Worker_2 [7509] - Events Extracted: 394 - File () - Running: True <running>
2015-02-11 23:15:29,328 [INFO] (MainProcess) PID:7497 <foreman> Worker_3 [7511] - Events Extracted: 423 - File () - Running: True <sleeping>
2015-02-11 23:15:29,330 [INFO] (MainProcess) PID:7497 <foreman> Worker_4 [7513] - Events Extracted: 318 - File () - Running: True <running>
2015-02-11 23:15:29,330 [INFO] (MainProcess) PID:7497 <multi_process> Collection stopped.
2015-02-11 23:15:29,330 [INFO] (MainProcess) PID:7497 <foreman> Foreman received a signal indicating that processing is completed.
2015-02-11 23:15:29,740 [INFO] (MainProcess) PID:7497 <foreman> Worker_0 [7505] - Events Extracted: 556 - File (/var/run/media/XXXXXXXX/Windows/Users/XXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/f_000432) - Running: True <running>
2015-02-11 23:15:30,066 [INFO] (Worker_0  ) PID:7505 <worker> Worker 0 (PID: 7505) stopped monitoring process queue.
2015-02-11 23:15:30,257 [INFO] (MainProcess) PID:7497 <foreman> Worker_1 [7506] - Events Extracted: 838 - File (/var/run/media/XXXXXXXX/Windows/Users/XXXXXXXX/AppData/LocalLow/Google/GoogleEarth/webdata/index) - Running: True <running>
2015-02-11 23:15:30,407 [INFO] (Worker_2  ) PID:7509 <worker> Worker 2 (PID: 7509) stopped monitoring process queue.
2015-02-11 23:15:30,407 [INFO] (Worker_4  ) PID:7513 <worker> Worker 4 (PID: 7513) stopped monitoring process queue.
2015-02-11 23:15:30,454 [INFO] (Worker_3  ) PID:7511 <worker> Worker 3 (PID: 7511) stopped monitoring process queue.
2015-02-11 23:15:34,220 [INFO] (Worker_1  ) PID:7506 <worker> Worker 1 (PID: 7506) stopped monitoring process queue.
2015-02-11 23:15:34,278 [INFO] (MainProcess) PID:7497 <foreman> Worker_2 [7509] has been removed from foreman monitoring.
2015-02-11 23:15:34,278 [INFO] (MainProcess) PID:7497 <foreman> Worker_3 [7511] has been removed from foreman monitoring.
2015-02-11 23:15:34,278 [INFO] (MainProcess) PID:7497 <foreman> Worker_4 [7513] has been removed from foreman monitoring.
2015-02-11 23:15:34,278 [INFO] (MainProcess) PID:7497 <foreman> Worker_0 [7505] has been removed from foreman monitoring.
2015-02-11 23:15:34,278 [INFO] (MainProcess) PID:7497 <foreman> Worker_1 [7506] has been removed from foreman monitoring.
2015-02-11 23:15:34,278 [INFO] (MainProcess) PID:7497 <multi_process> Extraction workers stopped.
2015-02-11 23:15:34,370 [INFO] (StorageProcess) PID:7503 <storage> [Storage] Closing the storage, number of events processed: 8023
2015-02-11 23:15:34,373 [INFO] (MainProcess) PID:7497 <multi_process> Storage writer stopped.
2015-02-11 23:15:34,373 [INFO] (MainProcess) PID:7497 <log2timeline> Processing completed.

> psort.py -w bugfix.csv -o L2tcsv bugfix.dump 
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150206', 'psort.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 528, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1401, in run_script
  File "/usr/lib/python2.7/site-packages/plaso-1.2.1_20150206-py2.7.egg/EGG-INFO/scripts/psort.py", line 767, in <module>
    
  File "/usr/lib/python2.7/site-packages/plaso-1.2.1_20150206-py2.7.egg/EGG-INFO/scripts/psort.py", line 741, in Main
    
  File "/usr/lib/python2.7/site-packages/plaso-1.2.1_20150206-py2.7.egg/EGG-INFO/scripts/psort.py", line 363, in ParseStorage
    
AttributeError: 'PsortFrontend' object has no attribute '_ProcessOutput'

[1]> psort.py -v
log2timeline - psort version 1.2.1_20150206


```

**Comment by kiddinn** [comment] 2015-05-01 22:04
Hi, sorry could you update the code and test this again to see if this has not been fixed in the latest version?

**Comment by joachimmetz** [comment] 2015-06-06 09:13
Likely root cause found, potential deadlock with path spec queuing by workers. Being addressed in https://codereview.appspot.com/243100043/.

**Closed by joachimmetz** 2015-06-06 09:13 UTC
Labels: bug
