### ISSUE TITLE
psteal takes a lot of time to complete

### ISSUE THREAD

**Issue by SamMaesschalck** [log2timeline/plaso#1874] opened 2018-05-08 11:18 UTC
**Description of problem:**

When running psteal on an image it can take more than 2 days for it to complete.

**Command line and arguments:**

psteal.exe --source F:\Images\WindowsImage.E01 -o xlsx -w output.xlsx

**Source data:**

Windows image created with FTK Imager.

**Plaso version:**

20180127

**Operating system Plaso is running on:**

Windows 10 Pro (x64)

**Installation method:**

https://github.com/log2timeline/plaso/releases/download/20180127/plaso-20180127-amd64.zip

**Debug output/tracebacks:**

No errors, just running normally.

**Comment by SamMaesschalck** [comment] 2018-05-08 11:30
It is a 60GB disk with a standard Windows installation with Office 2016, the total size of the image is 20.5GB and does not include any shadow copies. The images and all are being examined. I don't have an indication about the number of files, but won't be much more than just the standard Windows files.

![afbeelding](https://user-images.githubusercontent.com/17174408/39754812-b2676ad0-52c3-11e8-9444-c4b08fc71931.png)

**Comment by fejl504** [comment] 2019-04-22 15:33
Error reading image file (tsk_fs_read: Offset missing in partial image: 45049352192)) (ntfs_dinode_lookup: Error reading MFT Entry at 45049352192  - proc_attrlist)

**Comment by joachimmetz** [comment] 2019-04-23 07:19
Closing issue in favor of https://github.com/log2timeline/plaso/issues/2467. Without detailed information about the original configuration unable to reproduce or troubleshoot.

**Closed by joachimmetz** 2019-04-23 07:19 UTC
Labels: question
