### ISSUE TITLE
zipfile - IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1362] opened 2017-08-20 07:39 UTC
**Plaso version:**
20170818

Ubuntu 16.04.2

**Installation method:**

Install GIFT and git clone development Plaso

**Description of problem:**

Processing E01 or mounted volumes (directory), error and stopped halfway through.

**Debug output/tracebacks:**

```
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20170818', 'log2timeline.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 70, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 56, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/plaso/cli/log2timeline_tool.py", line 600, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/plaso/multi_processing/task_engine.py", line 790, in ProcessSources
    storage_writer.WriteSessionCompletion(aborted=self._abort)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/plaso/storage/interface.py", line 1404, in WriteSessionCompletion
    self._storage_file.WriteSessionCompletion(session_completion)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/plaso/storage/zip_file.py", line 2743, in WriteSessionCompletion
    self.Flush()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/plaso/storage/zip_file.py", line 2326, in Flush
    self._WriteSerializedAttributeContainerList(u'event_source')
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/plaso/storage/zip_file.py", line 1860, in _WriteSerializedAttributeContainerList
    offset_table.Write()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170818-py2.7.egg/plaso/storage/zip_file.py", line 549, in Write
    self._zip_file.writestr(self._stream_name, table_data)
  File "/usr/lib/python2.7/zipfile.py", line 1249, in writestr
    self.fp.write(bytes)
IOError: [Errno 5] Input/output error
```

**Source data:**

Tried both E01 original and after mounted E01 as directory. Same errors.

**Comment by joachimmetz** [comment] 2017-08-20 08:50
https://github.com/log2timeline/plaso/blob/master/plaso/storage/zip_file.py#L549

**Comment by joachimmetz** [comment] 2017-08-20 08:59
Based on the error and description it looks like the error lies outside of plaso. Python zipfile fails with an IO error in `self.fp.write(bytes)`.

Make sure you have sufficient available space on the storage device.

**Comment by madsumm** [comment] 2017-08-20 12:34
It has enough size. This I assume is writing to plaso container by L2T?

**Comment by joachimmetz** [comment] 2017-08-20 12:44
> This I assume is writing to plaso container by L2T?

I'm not sure what you are asking me

**Comment by Onager** [comment] 2017-08-20 12:50
This error is being raised while log2timeline is trying to write to a storage file. It's a very low-level error, so it looks like there's something wrong with the storage medium that Plaso's trying to write to. Is it some sort of network storage? External device?

**Comment by madsumm** [comment] 2017-08-20 15:22
Its USB. I am checking on the source image. The question prior was related to when its reading the image that causes the error or when writing results into the drive that is causing the issue.

I am suspecting image issue.

**Comment by Onager** [comment] 2017-08-20 16:46
It's very unlikely to be an image issue - log2timeline is seeing this problem when writing its output to the drive, not when reading or processing the image.

**Comment by Onager** [comment] 2017-09-07 13:43
@madsumm Any updates on this? Did changing the drive you were writing output to help?

**Comment by madsumm** [comment] 2017-09-07 14:35
No it did not. 
Strangly, I took out OpenXML and SCCM log parsers, it seemed to work….(!!)

Don’t ask me, but without these 2 parsers, it got through the whole log2timeline thing well.

Rgds
Mathew

**Comment by joachimmetz** [comment] 2017-11-27 06:50
Closing issue, seeing ZIP-based storage is on the deprecation list https://github.com/log2timeline/plaso/projects/1

**Closed by joachimmetz** 2017-11-27 06:50 UTC
Labels: dependency, question

**Comment by joachimmetz** [comment] 2017-11-27 06:53
Also seems to be a duplicate of https://github.com/log2timeline/plaso/issues/1495

**Comment by joachimmetz** [comment] 2017-11-27 06:56
> Don’t ask me, but without these 2 parsers, it got through the whole log2timeline thing well.

This might be related to the IO volume to the destination
