### ISSUE TITLE
psort.py with event filter raises ValueError: Unsupported date time string value: None

### ISSUE THREAD

**Issue by eagerbeaver-ce** [log2timeline/plaso#4676] opened 2023-06-02 14:26 UTC
**Describe the problem:**

I installed cast v0.14 on an Ubuntu 22.04.2.  I then tried to generate a supertimeline from a package collected using Cylr.  https://github.com/orlikoski/CyLR.

psort.py stops with the following error:

```
plaso - psort version 20230311

Storage file		: Host_Cylr.plaso
Processing time		: 00:00:03

Events:         Filtered        In time slice   Duplicates      MACB grouped    Total
                0               0               0               0               5512457

Identifier              PID     Status          Memory          Events          Tags            Reports
Main                    6604    exporting       79.5 MiB        0 (0)           0 (0)           0 (0)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/filters/value_types.py", line 37, in __init__
    self.CopyFromDateTimeString(value)
  File "/usr/lib/python3/dist-packages/dfdatetime/posix_time.py", line 289, in CopyFromDateTimeString
    date_time_values = self._CopyDateTimeFromString(time_string)
  File "/usr/lib/python3/dist-packages/dfdatetime/interface.py", line 357, in _CopyDateTimeFromString
    raise ValueError('Invalid time string.')
ValueError: Invalid time string.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 487, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 257, in _ExportEvents
    filter_match = event_filter.Match(
  File "/usr/lib/python3/dist-packages/plaso/filters/event_filter.py", line 48, in Match
    return self._event_filter.Matches(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 90, in Matches
    match = sub_filter.Matches(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 300, in Matches
    value = self._GetValue(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 261, in _GetValue
    attribute_value = value_types.DateTimeValueType(attribute_value)
  File "/usr/lib/python3/dist-packages/plaso/filters/value_types.py", line 39, in __init__
    raise ValueError('Unsupported date time string value: {0!s}'.format(
ValueError: Unsupported date time string value: None

```

This error happened on plaso-20230311.  Error doesn't happen plaso-20220724.

I checked the plaso file generated on plaso-20230311.  It seems it generated some events with null timestamps:

```
$ sqlite3 Host_Cylr.plaso
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> select * from event where timestamp is null;
579391|event_data.462049|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Creation Time
579392|event_data.462049|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Last Connection Time
579393|event_data.462050|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Creation Time
579394|event_data.462050|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Last Connection Time
579395|event_data.462051|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Creation Time
579396|event_data.462051|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Last Connection Time
579397|event_data.462052|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Creation Time
579398|event_data.462052|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Last Connection Time
579399|event_data.462053|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Creation Time
579400|event_data.462053|{"__class_name__": "Systemtime", "__type__": "DateTimeValues"}||Last Connection Time
sqlite> 

```

If I check on a plaso file generated from plaso-20220724, there are no empty timestamps.

**To Reproduce:**

The version of Plaso you used:  20230311.
The operating system you are running Plaso on Ubuntu 22.04.02

Steps to reproduce the behavior including command line and arguments and output:

1. Run Cylr.exe on a Windows 10 endpoint to get relevant artifacts.
2. Copy them to Linux and extract the ZIP file.  
3. Run the following command:  
   ` log2timeline.py --parsers "win7_slow" --process_memory_limit 12582912000 --storage_file Host_Cylr.plaso DE-BNC-GRUPDBP && psort.py -o L2tcsv Host_Cylr.plaso "date > '2023-01-01 00:00:00' AND date < '2023-01-31 23:59:59'" -w supertimeline_DE-BNC-GRUPDBP_Cylr_2023-01-01_2023-01-31.csv`
4. The error above will appear.

If I use the same steps on plaso-20220724, the supertimeline is generated. 

**Expected behavior:**

Able to create a supertimeline from psort from artifacts collected.

**Comment by joachimmetz** [comment] 2023-06-02 17:11
This could be related to https://github.com/log2timeline/dfdatetime/commit/caddd88e5025dd203cca071810d5d3a710c2087f could you try updating dfdatetime run log2timeline and psort again, see if that solves the issue.

Otherwise there were some related changes in https://github.com/log2timeline/plaso/pull/4667/files, you can give that a try if you want.

**Comment by joachimmetz** [comment] 2023-06-03 07:04
This looks like a duplicate of https://github.com/log2timeline/plaso/issues/4646

**Comment by joachimmetz** [comment] 2023-06-03 07:05
Closing issue since it has been addressed

**Closed by joachimmetz** 2023-06-03 07:05 UTC
Labels: duplicate
