### ISSUE TITLE
psort to CSV output missing microseconds.

### ISSUE THREAD

**Issue by MariasStory** [log2timeline/plaso#1929] opened 2018-06-07 09:51 UTC
**Description of problem:**

I don't see microseconds in MFT data while doing psort of plaso file to csv.

**Command line and arguments:**

psort.py -w output.csv input.plaso

**Source data:**

From MFT export:
/thumbcache_sr.db","2013-04-30 **17:31:06.640667**","2013-04-30 17:31:06.640667" ...

In csv file:
04/30/2013,**17:31:06**,UTC,MACB,FILE,NTFS Content Modification Time,Content Modification Time; Creation Time; Last Access Time; Metadata Modification Time,- /thumbcache_sr.db

**Plaso version:**

20180528

**Operating system Plaso is running on:**

linux

**Installation method:**

* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch

**Comment by MariasStory** [comment] 2018-06-09 19:51
Hi @Onager,
If I am right, the time format is defined in the file l2t_csv.py in line 163:

```
    time_string = '{0:02d}:{1:02d}:{2:02d}'.format(
        date_use.hour, date_use.minute, date_use.second)
```
There should be nanoseconds somewhere.

I guess this will work:

```
    time_string = '{0:02d}:{1:02d}:{2:02d}.{3:06d}'.format(
        date_use.hour, date_use.minute, date_use.second, date_use.micro_seconds)
```
Please check it.

**Comment by MariasStory** [comment] 2018-08-07 15:32
Hi, I did some tests and the simple modification of the format string did not work for me.
Someone else have an idea?

**Comment by joachimmetz** [comment] 2020-06-10 10:59
Duplicate of https://github.com/log2timeline/plaso/issues/2132

**Closed by joachimmetz** 2020-06-10 10:59 UTC
Labels: output, question
