### ISSUE TITLE
pinfo: linux timezone not displayed correctly

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#929] opened 2016-08-14 12:32 UTC
- [x] ~~Change preprocess plugin to detect time zone~~
  - ~~/etc/localtime~~
  - ~~symbolic link or timezone data file (http://man7.org/linux/man-pages/man5/tzfile.5.html)~~
  - ~~parse tzfiles, https://www.ietf.org/timezones/data/tzfile.h, dateutil.tz.tzfile~~
  - ~~https://codereview.appspot.com/323390043/~~
- [x] ~~Add test for determining timezone from tzfile~~
  - ~~https://codereview.appspot.com/327050043/~~
- [x] ~~Fix time zone being overwritten by preferred time zone~~
  - ~~https://codereview.appspot.com/325250043/~~
- [x] fix issue with empty file
  * https://codereview.appspot.com/328320043

**Description of problem:**

Originally reported in #924.
Timezone is detected as UTC, but should be Europe/Paris

**Debug output/tracebacks:**

```
***************************** System configuration *****************************
                Hostname : victoria
        Operating system : N/A
Operating system product : N/A
Operating system version : N/A
               Code page : cp1252
         Keyboard layout : N/A
               Time zone : UTC
```

**Source data:**
victoria-v8.sda1.img from a Honeynet forensics challenge here: https://www.honeynet.org/challenges/2011_7_compromised_server

**Comment by Onager** [comment] 2016-08-14 13:02
From the error log attached to #924 
```
2016-08-14 16:32:12,810 [INFO] (MainProcess) PID:4482 <interface> [PreProcess] Set attribute: time_zone_str to Europe/Paris
2016-08-14 16:32:12,810 [DEBUG] (MainProcess) PID:4482 <extraction_frontend> Preprocessing done.
2016-08-14 16:32:12,811 [INFO] (MainProcess) PID:4482 <extraction_frontend> Setting timezone to: Europe/Paris
```
So it looks like the preprocessor is working.

**Comment by Onager** [comment] 2016-08-14 13:21
This looks to be due to #241 being WIP. I believe https://codereview.appspot.com/305120043/ will fix this.

**Comment by Onager** [comment] 2016-08-14 13:54
Assigning to @joachimmetz as he already code that I believe will fix this.

**Comment by joachimmetz** [comment] 2016-08-14 16:18
'/etc/issue' or equiv is not parsed at the moment, this is working as intended.

**Comment by joachimmetz** [comment] 2016-08-14 16:19
I'll add an item to #241 to add support for this. The lack of this functionality is not a show stopper for the 1.5 release. Closing issue.

**Comment by joachimmetz** [comment] 2016-08-14 16:22
Comment on wrong issue,

**Comment by joachimmetz** [comment] 2016-08-14 16:56
The issue here is that the time zone information is currently not stored on a per-session basis in the knowledge base. https://codereview.appspot.com/305120043/ does not address this, but is a step towards it.

**Comment by joachimmetz** [comment] 2017-08-16 19:12
```
***************************** System configuration *****************************
                Hostname : victoria
        Operating system : N/A
Operating system product : N/A
Operating system version : N/A
               Code page : cp1252
         Keyboard layout : N/A
               Time zone : CET
--------------------------------------------------------------------------------
```

**Closed** 2017-08-23 10:18 UTC
Labels: bug, preprocessing
