### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by odibrowne** [log2timeline/plaso#474] opened 2015-12-27 20:10 UTC
Just after installing plaso - log2timeline version 1.3.1_20151218. Ran the dependencies check which passed the test however log2timeline.py fails to process with error code segmentation fault (core dumped)

**Comment by joachimmetz** [comment] 2015-12-28 05:42
Thanks for the report but can you provide more details so we can try to determine what the root cause of the segfault is.

Also see:
* https://github.com/log2timeline/plaso/wiki/Troubleshooting
* https://github.com/log2timeline/plaso/wiki/Troubleshooting#analyzing-crashes-with-single-process-and-debug-mode
* https://github.com/log2timeline/plaso/wiki/Troubleshooting#analyzing-crashes-with-gdb

**Comment by odibrowne** [comment] 2015-12-29 23:37
Apologies my error. It would appear that one of the dependencies did not compile correctly causing the error. Rebuilt a new os and added bleeding edge dependencies and latest version of plaso and all worked out fine.

Have only started using plaso in the last few weeks but really impressed by its results. Great work by the plaso development team

Regards
Alan Browne 

-----Original Message-----

**Comment by joachimmetz** [comment] 2015-12-30 06:14
Alan, thanks for the update. I'll close this out as "wontfix".

**Closed by joachimmetz** 2015-12-30 06:14 UTC
Labels: bug, dependency, wontfix
