### ISSUE TITLE
Exception while parsing registry file

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#2734] opened 2019-08-08 11:30 UTC
**Description of problem:**

Parsing a registry file results in an exception. This causes the worker that is processing this file to be killed. The worker is probably killed because the XMLRPC no longer responds after the exception. In similar cases, I have seen malloc and heap corruption errors.

```
free/malloc

free(): invalid next size (fast)
```

**Command line and arguments:**

`log2timeline.py -d -f filter-reg.yaml --partitions 2 --workers 1 --no_vss --parsers winreg --logfile log.txt dump.plaso image.E01`

**Source data:**

Input E01 file that needs parsing was successfully limited to a single SYSTEM registry file. 

**Plaso version:**

plaso - log2timeline version 20190708

**Operating system Plaso is running on:**

Fedora release 30 (Thirty)

**Installation method:**

RPM plaso-20190708-1.fc30.x86_64 from LiFTeR ( https://forensics.cert.org/ )

**Debug output/tracebacks:**

(Selection from) Logfile output:

```
<task_manager> Task af29d7a89baa4c92a872d2a24dd7778b was queued, now processing.
<plaso_xmlrpc> Unable to make RPC call with error: [Errno 111] Connection refused
<engine> Process Worker_00 (PID: 11116) is not functioning correctly. Status code: killed.
<engine> Terminating process: (PID: 11116).
<engine> Stopped monitoring process: Worker_00 (PID: 11116)
<engine> Attempt: 1 to start replacement worker process for Worker_00
```

(Selection from) Worker logfile output:

```
<worker_process> Started processing task: af29d7a89baa4c92a872d2a24dd7778b.
<worker> [ProcessFileEntry] processing file entry: TSK:/Windows/System32/config/RegBack/SYSTEM
<worker> [ProcessFileEntryDataStream] processing data stream: "" of file entry: TSK:/Windows/System32/config/RegBack/SYSTEM
<worker> [AnalyzeDataStream] analyzing file: TSK:/Windows/System32/config/RegBack/SYSTEM
<hashing_analyzer> Processing results for hasher sha256
<worker> [AnalyzeFileObject] attribute sha256_hash:<redacted> calculated for file: TSK:/Windows/System32/config/RegBack/SYSTEM.
<worker> [AnalyzeDataStream] completed analyzing file: TSK:/Windows/System32/config/RegBack/SYSTEM
<worker> [ExtractMetadataFromFileEntry] processing file entry: TSK:/Windows/System32/config/RegBack/SYSTEM
<extractors> [ParseFileEntryWithParsers] parsing file: TSK:/Windows/System32/config/RegBack/SYSTEM with parser: winreg
<usbstor> Expected 4 &-separated values in: Disk&Ven_Kingston&Prod_DT_Rubber_3.0
```
I am unsure whether it is the `usbstor` parser that fails, as I am unable to exclude this parser because of #2732

**Comment by joachimmetz** [comment] 2019-08-08 11:40
we don't maintain https://forensics.cert.org/ the issue is caused by a pre-release of libregf that has a bug and we never promoted beyond dev also see https://github.com/log2timeline/plaso/issues/2727

**Comment by kinky-it** [comment] 2019-08-08 12:23
Replaced libregf 20190714-1 with 20190303-1. 

Exception no longer occurs, thanks!

(Now `winreg_default` only produces 2 events though :/ )

**Comment by joachimmetz** [comment] 2019-08-08 12:26
> (Now winreg_default only produces 2 events though :/ )

Any indication why? e.g. in debug logs?

**Comment by kinky-it** [comment] 2019-08-08 12:48
Noticed dfwinreg errors in debug log. Downgrading dfwinreg from 20190714-1 to 20190517-1 did the trick. 

Thanks a lot!

**Comment by joachimmetz** [comment] 2019-08-08 13:18
Same there dfWinReg 20190714 is a pre-release for testing https://github.com/log2timeline/dfwinreg/releases/edit/20190714 it requires pyregf 20190714 or later. Plaso stable is on 20190517 https://copr.fedorainfracloud.org/coprs/g/gift/stable/package/dfwinreg/

**Comment by kinky-it** [comment] 2019-08-08 14:34
Yup. Will switch repo. Tnx

**Comment by joachimmetz** [comment] 2019-12-23 18:50
Question answered, closing issue.

**Closed by joachimmetz** 2019-12-23 18:50 UTC
Labels: dependency, duplicate
