### ISSUE TITLE
Questions about strange date and time values

### ISSUE THREAD

**Issue by siddiqains** [log2timeline/plaso#1171] opened 2017-02-25 19:39 UTC
Hi
I have converted .Plaso file to a csv using psort.py. The process ended successfully but the dates in the csv files are all 01/01/1600. and time is 00.00.00 .
Please help.
thanks

**Comment by Onager** [comment] 2017-02-25 20:31
@siddiqains - this isn't enough information for us to look at your problem. Please provide the information in the issue template: 

**Plaso version:**

For example 1.4.0 Release

**Operating system Plaso is running on:**

Not the operating system of the image/files you're trying to analyze.

**Installation method:**

For example installed from [GiFT][https://launchpad.net/~gift], built using [l2devtools][https://github.com/log2timeline/l2tdevtools], or some other method.

**Description of problem:**

Please describe the problem in as much detail as possible, including relevant command line arguments, flags etc.
What does the tool not do that it should? What would you like it to do?

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.

**Source data:**

Please describe the source that is causing the issue.

**Comment by siddiqains** [comment] 2017-02-25 21:12
Plaso version:

1.5.2

Operating system Plaso is running on:
win7 64bit
Not the operating system of the image/files you're trying to analyze.
I am not sure all I know is this is a .Plaso file generated using log2timeline 

Installation method:
https://github.com/log2timeline/plaso

got the dependencies from 
https://github.com/log2timeline/l2tbinaries


Description of problem:

I have converted .Plaso file to a csv using psort.py. The process ended successfully but the dates in the csv files are all 01/01/1600. and time is 00.00.00 .

What we want to do is to ideally load it in to ELK using psort, raised that as seperate issue. Alternatively, I have been trying to convert this into CSV or Sqlite3. In both instances the dates are not coming out as expected. 

 

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

Debug output/tracebacks:

Please run the tool with "-d" to generate debug output, and include anything relevant.

Source data:

.plaso file

Also getting this error before the plaso to csv converion ends.

017-02-25 19:58:26,578 [ERROR] (MainProcess) PID:29772 <timelib> Unable to copy
 311385727406771590 to a datetime object with error: date value out of range
2017-02-25 19:58:26,588 [ERROR] (MainProcess) PID:29772 <timelib> Unable to copy
 311385727406771590 to a datetime object with error: date value out of range
2017-02-25 19:58:26,598 [ERROR] (MainProcess) PID:29772 <timelib> Unable to copy
 1019771884640511107 to a datetime object with error: date value out of range
2017-02-25 19:58:26,609 [ERROR] (MainProcess) PID:29772 <timelib> Unable to copy
 1019771884640511107 to a datetime object with error: date value out of range
2017-02-25 19:58:26,621 [ERROR] (MainProcess) PID:29772 <timelib> Unable to copy
 1150678718737376745 to a datetime object with error: date value out of range
2017-02-25 19:58:26,631 [ERROR] (MainProcess) PID:29772 <timelib> Unable to copy
 1150678718737376745 to a datetime object with error: date value out of range


thanks for the help

**Comment by madsumm** [comment] 2017-03-08 03:57
There seems to be problem with psort.py after testing that is related to this (and maybe my previous tests as well).

Using "kitchen sink" method of log2timeline collection of data to PLASO, and using "kitchen sink" method of PSORT extraction to l2tcsv format from the plaso created, ends in strange output.

Closer look, last date it contains is 2016-02-13 at around 13:00 hrs. After than, no more events. (This is not true as the image tested is created in 2017)

I see a lot of 1607 year and 2107 year.

I decided to do date slice. did a filter of "date > '2016-03-01' and date < '2017-02-01'"
It  worked and extracted all information with no errors.

One such error I see doing full kitchen sink PSORT is stated above where datetime object error is detected to be out of range.

Not sure what is the issue.

**Comment by joachimmetz** [comment] 2017-03-12 07:23
> ends in strange output.

@madsumm can you be more descriptive, based on your description we can only make wild guesses

what is the input data of log2timeline?
any processing errors when log2timeline processes the input? does pinfo FILE.plaso show any processing errors?
what date/times does the text output of psort provide you?

**Comment by joachimmetz** [comment] 2017-03-25 15:37
> The process ended successfully but the dates in the csv files are all 01/01/1600. and time is 00.00.00

@siddiqains This looks like a timestamp set to 0

**Comment by joachimmetz** [comment] 2017-03-25 15:39
@madsumm did this issue surface in combination with the syslog parser?

**Comment by madsumm** [comment] 2017-03-27 04:40
@joachimmetz i need to try using SYSLOG parser only.
But the strange dates in the final report doesn't add up.
Furthermore, it stopped exactly on all my runs, 13th Feb 2016 around 13:00 hrs.
I need to run a separate time SPLIT to allow the parsers to run through the rest of the times.

I did it for multiple images. Same results.
I am using Kitchen Sink and did not specify parsers. The last I did was using WIN7 presets.
Rgds

**Comment by joachimmetz** [comment] 2017-03-27 07:31
Ack, we'll try to reproduce the issue based on your description as far possible.

**Comment by madsumm** [comment] 2017-03-28 03:56
@joachimmetz  just realized its WIN7, so no syslog.
Today I tried new version _0325.

Plaso file creation has the following errors : 

```
********************************** Error: 18 ***********************************
           Message : unsupported modified time: 2012-03-05T20:40:00.0000000Z
                     with error: Invalid time string..
      Parser chain : openxml
Path specification : type: OS, location:
                     /media/<redact>
                   : type: RAW
                   : type: TSK, inode: 34380, location:
                     /Users/<redact>
--------------------------------------------------------------------------------

********************************** Error: 19 ***********************************
           Message : unsupported modified time: 2012-03-05T20:40:00.0000000Z
                     with error: Invalid time string..
      Parser chain : openxml
Path specification : type: OS, location:
                     /media/<redact>
                   : type: RAW
                   : type: TSK, inode: 75592, location:
                     /Users/<redact>
--------------------------------------------------------------------------------

********************************** Error: 20 ***********************************
           Message : unsupported modified time: 2012-03-05T20:48:00.0000000Z
                     with error: Invalid time string..
      Parser chain : openxml
Path specification : type: OS, location:
                     /media/<redact>
                   : type: RAW
                   : type: TSK, inode: 7790, location:
                     /Users/<redact>
--------------------------------------------------------------------------------
```

After running psort.py on the same file above to create l2tcsv I had this error :
```
2017-03-27 20:28:54,442 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 910692730085477580 to a datetime object with error: date value out of range
2017-03-27 20:28:54,442 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 910692730085477580 to a datetime object with error: date value out of range
2017-03-27 20:28:54,443 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 910692730085477580 to a datetime object with error: date value out of range
2017-03-27 20:28:54,443 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 910692730085477580 to a datetime object with error: date value out of range
2017-03-27 20:28:54,445 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 910692730085477580 to a datetime object with error: date value out of range
2017-03-27 20:28:54,447 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 910692730085477580 to a datetime object with error: date value out of range
2017-03-27 20:28:54,448 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 910692730085477580 to a datetime object with error: date value out of range
2017-03-27 20:28:54,449 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 1333522686778274202 to a datetime object with error: date value out of range
2017-03-27 20:28:54,450 [ERROR] (MainProcess) PID:53643 <timelib> Unable to copy 1333522686778274202 to a datetime object with error: date value out of range
2017-03-27 20:28:54,450 [ERROR] (MainProcess...
```

Beginning of the csv file after psort:
```
01/01/1601,00:00:00,UTC,....,WEBHIST,MSIE WebCache container record,Expiration Time,<redacted>
01/01/1601,00:00:00,UTC,....,WEBHIST,MSIE WebCache container record,Expiration Time,<redacted
/start/sso/directory.jnlp Access count: 20 Sync count: 0 Filename: directory.jnlp <redacted>
01/01/1601,00:00:00,UTC,....,WEBHIST,MSIE WebCache container record,Expiration Time,<redacted>
```
At the TAIL of the CSV after psort:
```
01/01/1970,00:00:00,UTC,...B,OLECF,OLECF Item,Creation Time,-<redacted>
01/01/1970,00:00:00,UTC,...B,OLECF,OLECF Item,Creation Time<redacted>
01/01/1970,00:00:00,UTC,...B,OLECF,OLECF Item,Creation Time,<redacted>
```

The last date recorded in 2016 in CSV after psort is:
```
02/13/2016,13:18:25,UTC,M...,EVT,WinEVTX,Content Modification Time,<redacted    <TimeCreated SystemTime="2016-02-13T13:18:25.028248800Z"/>-    <redacted>
```

However if I slice the time after 02/13/2016 to 2017 and extract from the same Plaso, it extracted.
Somehow, psort got stuck somewhere or corruption. The dates above are strange to say the least.
So now I need to run PSORT twice. Once for all, another to find the last time and run the next with slice.

**Comment by joachimmetz** [comment] 2017-03-28 06:59
FYI we are working on better preserving original date and time values https://github.com/log2timeline/plaso/issues/910

```
********************************** Error: 18 ***********************************
           Message : unsupported modified time: 2012-03-05T20:40:00.0000000Z
                     with error: Invalid time string..
      Parser chain : openxml
Path specification : type: OS, location:
                     /media/<redact>
                   : type: RAW
                   : type: TSK, inode: 34380, location:
                     /Users/<redact>
--------------------------------------------------------------------------------
```

These are warnings about limitation in the parsers, I can have a look to improve the openxml for this particular case.

```
01/01/1601,00:00:00,UTC,....,WEBHIST,MSIE WebCache container record,Expiration Time,<redacted>
```
01/01/1601,00:00:00,UTC is FILETIME timestamp of 0. https://github.com/log2timeline/plaso/issues/910 should give us the functionality to describe this as "semantic time" of "Not set"

**Comment by joachimmetz** [comment] 2017-12-01 06:46
@Onager I've added this issue to the December milestone with the intent, see if there is something left to fix or close out.

**Comment by Onager** [comment] 2017-12-29 09:57
This looks like a combination of #872  https://github.com/log2timeline/dfdatetime/issues/58 and some semantic timestamp references being confusing. 

Closing out

**Closed by Onager** 2017-12-29 09:57 UTC
Labels: question
