### ISSUE TITLE
Can't run psort against plaso output

### ISSUE THREAD

**Issue by yani1shu** [log2timeline/plaso#456] opened 2015-12-21 18:08 UTC
I ran log2timeline against a forensic image and got a 320 MB Plaso file. I'm now trying to run psort against the Plaso output but get the following message:

C:\Users\examiner\Desktop\plaso-1.3.0-win-amd64-vs2010\plaso>psort.exe e:\timeline.plaso
[INFO] Data files will be loaded from None by default.
[WARNING] Unable to automatically determine data location.
Traceback (most recent call last):
  File "<string>", line 646, in <module>
  File "<string>", line 641, in Main
  File "<string>", line 593, in ProcessStorage
  File "<string>", line 176, in _ProcessStorage
RuntimeError: Unable to open storage file: e:\timeline.plaso with error: Unable to read ZIP file with error: File is not a zip file.

Is there anything I can do to make the Plaso output usable or do I need to rerun log2timeline. This is on a Windows 10 box. I used Plaso 1.3.

**Comment by joachimmetz** [comment] 2015-12-21 18:34
Can you provide a hexdump of the first bytes of the `e:\timeline.plaso` file?

**Comment by yani1shu** [comment] 2015-12-21 18:40
Here you go: 50 4B 03 04 14 00 00 00 08 00 CB 50 92 47 45 25 07

**Comment by joachimmetz** [comment] 2015-12-21 18:44
```
Unable to read ZIP file with error: File is not a zip file.
```
My assumption is then it did not get closed correctly.
You could check with other ZIP tools e.g. zipinfo

Re-running is the easiest approach, but I would be interested if anything happened when running log2timeline that could explain why the ZIP file might be corrupt?

**Comment by yani1shu** [comment] 2015-12-22 14:35
I tried reprocessing and am getting the same error. It looks like
log2timeline might be getting hung up and not completing successfully and
thus not closing the file properly.

Worker_14 (PID: 20024) - events extracted: 191152 - file:
GZIP:/Users/user/App
Data/Local/Google/Chrome/User Data/Default/Cache/f_031cca - running: True
<runni
ng>
2015-12-22 07:43:24,367 [ERROR] (MainProcess) PID:19240 <logging> Workers
idle f
or too long
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Processing a
borted with engine error: Workers idle for too long.
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_11 (PID: 18760).
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_02 (PID: 19056).
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_10 (PID: 18020).
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Collector (PID: 19784).
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_01 (PID: 16584).
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_08 (PID: 13000).
2015-12-22 07:43:24,367 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_09 (PID: 20364).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_06 (PID: 16560).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_04 (PID: 15884).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_07 (PID: 12040).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: StorageWriter (PID: 20272).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_03 (PID: 19464).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_12 (PID: 19796).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_13 (PID: 18896).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_14 (PID: 20024).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_05 (PID: 19592).
2015-12-22 07:43:24,382 [WARNING] (MainProcess) PID:19240 <logging>
Terminating
process: Worker_00 (PID: 2556).
Processing completed with errors.


C:\Users\Administrator\Desktop\plaso-1.3.0-win-amd64-vs2010\plaso>psort.exe
d:\timeline.plaso -w timeline.csv
[INFO] Data files will be loaded from None by default.
[WARNING] Unable to automatically determine data location.
Traceback (most recent call last):
  File "<string>", line 646, in <module>
  File "<string>", line 641, in Main
  File "<string>", line 593, in ProcessStorage
  File "<string>", line 176, in _ProcessStorage
RuntimeError: Unable to open storage file: d:\timeline.plaso with error: Una
ble to read ZIP file with error: File is not a zip file.


Is there anything I can do? It took around 17 hours to process which seems
excessive.

**Comment by joachimmetz** [comment] 2015-12-22 15:00
The following happens:

* the "Workers idle for too long" exception kicks in that means the worker processes appear to be idle
* that causes the tool to abort
* it seems to be unable to abort cleanly and corrupting the zip file in the process

I would be interested in what is processed just before the "idle exception" kicks in

For context we are working on [phased processing](https://github.com/log2timeline/plaso/issues/338) which would reduce the impact of these failures, but this requires changing a lot of early plaso code in the process.

> Is there anything I can do? It took around 17 hours to process which seems excessive.

Yes you can turn off and on different parsers. Typically the best approach is to only process what you need and then add more if needed. Also see:

* https://github.com/log2timeline/plaso/wiki/Troubleshooting
* https://github.com/log2timeline/plaso/wiki/Troubleshooting-Windows

**Comment by yani1shu** [comment] 2015-12-22 15:12
Thanks. It seems to spend an incredible amount of time processing
GZIP:/Users/user/AppData/Local/Google/Chrome/User Data/Default/Cache/
sources. I will try playing with selecting only certain parsers.

**Comment by joachimmetz** [comment] 2015-12-29 08:25
> Thanks. It seems to spend an incredible amount of time processing
> GZIP:/Users/user/AppData/Local/Google/Chrome/User Data/Default/Cache/
> sources.

I opt to try again with version: https://github.com/log2timeline/plaso/commit/bfe70efc7530321f7be6d6c9ade5348e6b84037e or wait for the next release (candidate).

**Comment by joachimmetz** [comment] 2015-12-31 19:37
Do you know if log2timeline ended with a warning about the termination of the storage worker process?

If so your issue could be caused by the behavior observed in https://github.com/log2timeline/plaso/issues/491

**Comment by joachimmetz** [comment] 2016-01-11 20:50
Closing this issue, since this is to be expected when the storage file is corrupted. Related issues have been fixed in the current git version (HEAD) and will be integrated in version 1.4

**Closed by joachimmetz** 2016-01-11 20:50 UTC
Labels: question

**Comment by fbruzzaniti** [comment] 2016-02-26 03:22
I was able to successfully fix my plaso file when I encountered this error by doing the following:
zip -FF broken.plaso --out fixed.plaso

**Comment by joachimmetz** [comment] 2016-02-26 04:42
@fbruzzaniti even that you are able to read the zip file now, it is likely that you are missing results.

**Comment by yani1shu** [comment] 2016-02-26 17:19
I'm running into this issue again where I run Log2timeline against my
forensic image but the proecssing completes with errors and I'm unable to
process the plaso output file:

[ERROR] Unable to open storage file: d:\Item001a.plaso with error: Unable
to open ZIP file with error: File is not a zip file

I've rerun log2timeline several times with the exact same results. Here are
the final results Log2timeline shows before it "completes":

2016-02-26 11:05:18,976 [ERROR] (MainProcess) PID:9868 <multi_process>
Workers idle for too long
2016-02-26 11:05:18,976 [WARNING] (MainProcess) PID:9868 <multi_process>
Processing aborted with engine error: Workers idle for too long.
2016-02-26 11:05:18,976 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_08 (PID: 9328).
2016-02-26 11:05:18,976 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_00 (PID: 15940).
2016-02-26 11:05:18,990 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_03 (PID: 16060).
2016-02-26 11:05:18,990 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_09 (PID: 13996).
2016-02-26 11:05:18,990 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_07 (PID: 12772).
2016-02-26 11:05:18,990 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_02 (PID: 13340).
2016-02-26 11:05:18,990 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_05 (PID: 10332).
2016-02-26 11:05:18,990 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: StorageWriter (PID: 15764).
2016-02-26 11:05:19,006 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_04 (PID: 9560).
2016-02-26 11:05:19,006 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_01 (PID: 4292).
2016-02-26 11:05:19,006 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Collector (PID: 12668).
2016-02-26 11:05:19,006 [WARNING] (MainProcess) PID:9868 <multi_process>
Terminating process: Worker_06 (PID: 8788).
Processing completed with errors.

**Comment by yani1shu** [comment] 2016-02-26 17:20
Meant to include the version info:

S:\Plaso\plaso-1.4.0-win-amd64-vs2010\plaso>log2timeline.exe -V
plaso - log2timeline version 1.4.0

**Comment by TailoredAccessTeam** [comment] 2018-06-12 14:42
I have exactly the same issue, how can i easily find out which module  creates the broken file without try and error of all the possible log2timeline parsers?
