### ISSUE TITLE
Psort OSX Parsing Error: "TypeError: unsupported type for timedelta microseconds component: unicode"

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#1041] opened 2016-10-10 19:57 UTC
**Plaso version:**

1.5.0

**Operating system Plaso is running on:**

Fedora 24

**Installation method:**

Installed via CERT Forensic Repo

**Description of problem:**

L2t of source dmg file completed successfully with errors (though that seems oxymoronic in a way). Pinfo shows 1066 errors, mostly related to "Unable to parse/decode...". 
Psort parsing of .dump file fails. 

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.

`psort.py -d -w disk_l2t.csv -o l2tcsv disk_l2t.dump`

> 2016-10-10 13:06:52,018 [ERROR](MainProcess) PID:7819 <interface> Event: aa6b4606ea554f54b3598462aa786882 data type: mac:keychain:application display name: TSK:/Library/Keychains/System.keychain parser chain: mac_keychain with error: Unicode decode error: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
> 2016-10-10 13:06:52,019 [ERROR](MainProcess) PID:7819 <interface> Event: aa6b4606ea554f54b3598462aa786882 data type: mac:keychain:application display name: TSK:/Library/Keychains/System.keychain parser chain: mac_keychain with error: Unicode decode error: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
> 2016-10-10 13:06:52,019 [ERROR](MainProcess) PID:7819 <interface> Event: bde0253876904c4fb1c8e068a6af3b75 data type: mac:keychain:application display name: TSK:/Library/Keychains/System.keychain parser chain: mac_keychain with error: Unicode decode error: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
> 2016-10-10 13:06:52,019 [ERROR](MainProcess) PID:7819 <interface> Event: bde0253876904c4fb1c8e068a6af3b75 data type: mac:keychain:application display name: TSK:/Library/Keychains/System.keychain parser chain: mac_keychain with error: Unicode decode error: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
> 2016-10-10 13:13:39,315 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 253402300859000000 to a datetime object with error: date value out of range
> 2016-10-10 13:13:39,316 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 253402300887000000 to a datetime object with error: date value out of range
> 2016-10-10 13:13:39,317 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 253402301040236854 to a datetime object with error: date value out of range
> 2016-10-10 13:13:39,319 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 673298681652000000 to a datetime object with error: date value out of range
> 2016-10-10 13:13:39,319 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 1434060948162000000 to a datetime object with error: date value out of range
> 2016-10-10 13:13:39,320 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 1465061373145000000 to a datetime object with error: date value out of range
> 2016-10-10 13:13:39,321 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 1466206274669000000 to a datetime object with error: date value out of range
> 2016-10-10 13:13:39,322 [ERROR](MainProcess) PID:7819 <timelib> Unable to copy 1466786552038000000 to a datetime object with error: date value out of range
> Traceback (most recent call last):
>   File "/bin/psort.py", line 868, in <module>
>     if not Main():
>   File "/bin/psort.py", line 854, in Main
>     tool.ProcessStorage()
>   File "/bin/psort.py", line 798, in ProcessStorage
>     time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
>   File "/usr/lib/python2.7/site-packages/plaso/frontend/psort.py", line 283, in ExportEvents
>     use_time_slicer=use_time_slicer)
>   File "/usr/lib/python2.7/site-packages/plaso/multi_processing/psort.py", line 614, in ExportEvents
>     time_slice=time_slice, use_time_slicer=use_time_slicer)
>   File "/usr/lib/python2.7/site-packages/plaso/output/event_buffer.py", line 102, in __exit__
>     self.End()
>   File "/usr/lib/python2.7/site-packages/plaso/output/event_buffer.py", line 131, in End
>     self.Flush()
>   File "/usr/lib/python2.7/site-packages/plaso/output/event_buffer.py", line 154, in Flush
>     self._output_module.WriteEvent(event)
>   File "/usr/lib/python2.7/site-packages/plaso/output/interface.py", line 87, in WriteEvent
>     self.WriteEventBody(event)
>   File "/usr/lib/python2.7/site-packages/plaso/output/l2t_csv.py", line 90, in WriteEventBody
>     event.timestamp, self._output_mediator.timezone)
>   File "/usr/lib/python2.7/site-packages/plaso/lib/timelib.py", line 290, in CopyToDatetime
>     datetime_object += datetime.timedelta(microseconds=timestamp)
> TypeError: unsupported type for timedelta microseconds component: unicode>

**Comment by joachimmetz** [comment] 2017-12-29 06:44
Not sure why this issue was never followed up on, but might be obsolete by now.

Note to self run latest log2timeline on 1.5.0 dmg

**Comment by joachimmetz** [comment] 2018-01-22 08:06
HEAD error out on the file
```
2018-01-22 09:05:14,227 [WARNING] (MainProcess) PID:21188 <log2timeline> No supported file system found in source.
```
seeing it is a compressed dmg this is working as intended.

**Comment by joachimmetz** [comment] 2018-01-22 08:10
Closing this issue as cannot reproduce with current version. Unless more information about the issue surfaces unable to reproduce.

**Closed by joachimmetz** 2018-01-22 08:10 UTC
Labels: bug
