### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by Rolinh** [log2timeline/plaso#1970] opened 2018-06-22 06:26 UTC
**Description of problem:**

`log2timeline` crashes while analyzing a Firefox's `cookies.sqlite` file with Python exception `OverflowError: Python int too large to convert to SQLite INTEGER`.

**Command line and arguments:**

```
log2timeline --status_view linear /path/file.plaso cookies.sqlite
```

**Source data:**

This data is sensitive, I can't provide it unfortunately.

**Plaso version:**

20180524

**Operating system Plaso is running on:**

Plaso is running inside a Docker container based on an Ubuntu 16.04 image.

**Installation method:**

Relevant part of the Dockerfile:

```
RUN add-apt-repository -y "deb http://ppa.launchpad.net/gift/stable/ubuntu xenial main"
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade
RUN apt-get -y install python-plaso plaso-tools
```

**Debug output/tracebacks:**

```
$ log2timeline -d --status_view linear  /path/file.plaso /path/cookies.sqlite
2018-06-22 06:13:55,562 [WARNING] (MainProcess) PID:7 <tool_options> Appending to an already existing storage file.
2018-06-22 06:13:55,749 [DEBUG] (MainProcess) PID:7 <log2timeline_tool> Starting extraction in single process mode.
2018-06-22 06:13:55,768 [DEBUG] (MainProcess) PID:7 <extractors> Active parsers: amcache, android_app_usage, asl_log, bash, bencode, binary_cookies, bsm_log, chrome_cache, chrome_preferences, cups_ipp, custom_destinations, dockerjson, dpkg, esedb, filestat, firefox_cache, firefox_cache2, fsevents, gdrive_synclog, hachoir, java_idx, lnk, mac_appfirewall_log, mac_keychain, mac_securityd, mactime, macwifi, mcafee_protection, mft, msiecf, olecf, openxml, opera_global, opera_typed_history, pe, plist, pls_recall, popularity_contest, prefetch, recycle_bin, recycle_bin_info2, rplog, sccm, selinux, skydrive_log, skydrive_log_old, sophos_av, sqlite, symantec_scanlog, syslog, systemd_journal, trendmicro_vd, usnjrnl, utmp, utmpx, winevt, winevtx, winfirewall, winiis, winjob, winreg, xchatlog, xchatscrollback, zsh_extended_history
2018-06-22 06:13:55,768 [DEBUG] (MainProcess) PID:7 <hashing_analyzer> Got hasher names: sha256
2018-06-22 06:13:55,768 [DEBUG] (MainProcess) PID:7 <single_process> Processing started.
2018-06-22 06:13:55,772 [DEBUG] (MainProcess) PID:7 <worker> [ProcessFileEntry] processing file entry: OS:/path/cookies.sqlite
2018-06-22 06:13:55,772 [DEBUG] (MainProcess) PID:7 <worker> [ProcessFileEntryDataStream] processing data stream: "" of file entry: OS:/path/cookies.sqlite
2018-06-22 06:13:55,772 [DEBUG] (MainProcess) PID:7 <worker> [AnalyzeDataStream] analyzing file: OS:/path/cookies.sqlite
2018-06-22 06:13:55,778 [DEBUG] (MainProcess) PID:7 <hashing_analyzer> Processing results for hasher sha256
2018-06-22 06:13:55,778 [DEBUG] (MainProcess) PID:7 <worker> [AnalyzeFileObject] attribute sha256_hash:379ac9073895c45ce81540d6e264666ef40918b52627bac169325b9d6b591f31 calculated for file: OS:/path/cookies.sqlite
2018-06-22 06:13:55,778 [DEBUG] (MainProcess) PID:7 <worker> [AnalyzeDataStream] completed analyzing file: OS:/path/cookies.sqlite
2018-06-22 06:13:55,778 [DEBUG] (MainProcess) PID:7 <worker> [ExtractMetadataFromFileEntry] processing file entry: OS:/path/cookies.sqlite
2018-06-22 06:13:55,781 [DEBUG] (MainProcess) PID:7 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/path/cookies.sqlite with parser: sqlite
2018-06-22 06:13:57,935 [DEBUG] (MainProcess) PID:7 <worker> [ProcessFileEntry] done processing file entry: OS:/path/cookies.sqlite
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lzma.
[OK]


Source path     : /path/cookies.sqlite
Source type     : single file
Processing time : 00:00:00

Processing started.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 433, in ExtractEventsFromSources
    status_update_callback=status_update_callback)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/single_process.py", line 283, in ProcessSources
    storage_writer.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 1308, in Close
    self._storage_file.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 665, in Close
    self._WriteSerializedAttributeContainerList(self._CONTAINER_TYPE_EVENT)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 445, in _WriteSerializedAttributeContainerList
    self._cursor.executemany(query, values_tuple_list)
OverflowError: Python int too large to convert to SQLite INTEGER
```

**Comment by joachimmetz** [comment] 2018-06-25 12:19
Note to self, maybe change timestamp to `BIGINT`, `UNSIGNED BIG INT`

Also see:
* https://www.sqlite.org/datatype3.html
* https://doc.ispirer.com/sqlways/Output/SQLWays-1-196.html

**Comment by Rolinh** [comment] 2018-07-03 06:21
@joachimmetz Thanks for quickly addressing this issue.

With the recent release of `20180630`, I was eager to test this fix. However, it fails still:

```
$ log2timeline -d --status_view linear  /path/file.plaso /path/cookies.sqlite
2018-07-03 06:05:47,922 [DEBUG] (MainProcess) PID:9 <log2timeline_tool> Starting extraction in single process mode.
2018-07-03 06:05:48,140 [DEBUG] (MainProcess) PID:9 <extractors> Active parsers: amcache, android_app_usage, asl_log, bash, bencode, binary_cookies, bsm_log, chrome_cache, chrome_preferences, cups_ipp, custom_destinations, dockerjson, dpkg, esedb, filestat, firefox_cache, firefox_cache2, fsevents, gdrive_synclog, hachoir, java_idx, lnk, mac_appfirewall_log, mac_keychain, mac_securityd, mactime, macwifi, mcafee_protection, mft, msiecf, olecf, openxml, opera_global, opera_typed_history, pe, plist, pls_recall, popularity_contest, prefetch, recycle_bin, recycle_bin_info2, rplog, sccm, selinux, skydrive_log, skydrive_log_old, sophos_av, sqlite, symantec_scanlog, syslog, systemd_journal, trendmicro_url, trendmicro_vd, usnjrnl, utmp, utmpx, winevt, winevtx, winfirewall, winiis, winjob, winreg, xchatlog, xchatscrollback, zsh_extended_history
2018-07-03 06:05:48,141 [DEBUG] (MainProcess) PID:9 <hashing_analyzer> Got hasher names: sha256
2018-07-03 06:05:48,141 [DEBUG] (MainProcess) PID:9 <single_process> Processing started.
2018-07-03 06:05:48,147 [DEBUG] (MainProcess) PID:9 <worker> [ProcessFileEntry] processing file entry: /path/file.plaso
2018-07-03 06:05:48,147 [DEBUG] (MainProcess) PID:9 <worker> [ProcessFileEntryDataStream] processing data stream: "" of file entry: /path/file.plaso
2018-07-03 06:05:48,147 [DEBUG] (MainProcess) PID:9 <worker> [AnalyzeDataStream] analyzing file: /path/file.plaso
2018-07-03 06:05:48,155 [DEBUG] (MainProcess) PID:9 <hashing_analyzer> Processing results for hasher sha256
2018-07-03 06:05:48,155 [DEBUG] (MainProcess) PID:9 <worker> [AnalyzeFileObject] attribute sha256_hash:48294c3b12129f6acc73294730c851a5fb48f75c7d726a57491274c301a8a576 calculated for file: /path/file.plaso.
2018-07-03 06:05:48,156 [DEBUG] (MainProcess) PID:9 <worker> [AnalyzeDataStream] completed analyzing file: /path/file.plaso
2018-07-03 06:05:48,156 [DEBUG] (MainProcess) PID:9 <worker> [ExtractMetadataFromFileEntry] processing file entry: /path/file.plaso
2018-07-03 06:05:48,159 [DEBUG] (MainProcess) PID:9 <extractors> [ParseFileEntryWithParsers] parsing file: /path/file.plaso with parser: sqlite
2018-07-03 06:05:50,681 [DEBUG] (MainProcess) PID:9 <worker> [ProcessFileEntry] done processing file entry: /path/file.plaso
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 434, in ExtractEventsFromSources
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lzma.
[OK]


Source path     : /path/file.plaso
Source type     : single file
Processing time : 00:00:00

Processing started.
    status_update_callback=status_update_callback)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/single_process.py", line 283, in ProcessSources
    storage_writer.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 1308, in Close
    self._storage_file.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 665, in Close
    self._WriteSerializedAttributeContainerList(self._CONTAINER_TYPE_EVENT)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 445, in _WriteSerializedAttributeContainerList
    self._cursor.executemany(query, values_tuple_list)
OverflowError: Python int too large to convert to SQLite INTEGER
```

The stack trace is slightly different though.

**Comment by joachimmetz** [comment] 2018-07-03 06:30
Which pysqlite version are you running?

**Comment by Rolinh** [comment] 2018-07-03 06:44
> Which pysqlite version are you running?

The one packaged with Ubuntu 16.04. My setup has nothing special, docker image based on Ubuntu 16.04 with the gift ppa.

```
# apt show python-pysqlite2
Package: python-pysqlite2
Version: 2.7.0-1
Status: install ok installed
Priority: optional
Section: python
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Joel Rosdahl <joel@debian.org>
Installed-Size: 128 kB
Provides: python2.7-pysqlite2
Depends: libc6 (>= 2.14), libsqlite3-0 (>= 3.5.9), python (>= 2.7), python (<< 2.8)
Suggests: python-pysqlite2-doc, python-pysqlite2-dbg
Conflicts: python2.3-pysqlite2, python2.4-pysqlite2
Replaces: python2.3-pysqlite2, python2.4-pysqlite2
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
```

**Comment by joachimmetz** [comment] 2018-07-03 06:52
Any chance you could share the data or debug print the values tuple list to determine what the large integer is and where this value originates.

**Comment by joachimmetz** [comment] 2018-07-03 06:55
Latest version of pysqlite seems to be 2.8.3 I'll need to check which version we're using

**Comment by Rolinh** [comment] 2018-07-03 07:08
> Any chance you could share the data or debug print the values tuple list to determine what the large integer is and where this value originates.

Not really, this data is really sensitive I'm afraid.

> Latest version of pysqlite seems to be 2.8.3 I'll need to check which version we're using. We provide a 2.8.3 build in the gift ppa.

It looks like the version in the gift ppa is `python-pysqlite` but the version in the `python-plaso` dependencies is `python-pysqlite2`, which is the Ubuntu one.
```
# apt show python-plaso
Package: python-plaso
Version: 20180630-2ppa1~xenial
Priority: extra
Section: python
Source: plaso
Maintainer: Log2Timeline maintainers <log2timeline-maintainers@googlegroups.com>
Installed-Size: 3,150 kB
Depends: plaso-data, libbde-python (>= 20140531), libesedb-python (>= 20150409), libevt-python (>= 20120410), libevtx-python (>= 20141112), libewf-python (>= 20131210), libfsntfs-python (>= 20151130), libfvde-python (>= 20160719), libfwnt-python (>= 20180117), libfwsi-python (>= 20150606), liblnk-python (>= 20150830), libmsiecf-python (>= 20150314), libolecf-python (>= 20151223), libqcow-python (>= 20131204), libregf-python (>= 20150315), libscca-python (>= 20161031), libsigscan-python (>= 20150627), libsmdev-python (>= 20140529), libsmraw-python (>= 20140612), libvhdi-python (>= 20131210), libvmdk-python (>= 20140421), libvshadow-python (>= 20160109), libvslvm-python (>= 20160109), python-artifacts (>= 20170818), python-backports.lzma, python-bencode, python-biplist (>= 1.0.3), python-certifi (>= 2016.9.26), python-chardet (>= 2.0.1), python-construct (>= 2.5.2), python-crypto (>= 2.6), python-dateutil (>= 1.5), python-dfdatetime (>= 20180606), python-dfvfs (>= 20180326), python-dfwinreg (>= 20170521), python-dpkt (>= 1.8), python-dtfabric (>= 20180604), python-efilter (>= 1.5), python-elasticsearch (>= 5.4.0), python-future (>= 0.16.0), python-hachoir-core (>= 1.3.3), python-hachoir-metadata (>= 1.3.3), python-hachoir-parser (>= 1.3.4), python-idna (>= 2.5), python-pefile (>= 2017.5.26), python-psutil (>= 5.4.3), python-pyparsing (>= 2.0.3), python-pysqlite2, python-pytsk3 (>= 20160721), python-requests (>= 2.2.1), python-six (>= 1.1.0), python-tz, python-urllib3 (>= 1.7.1), python-xlsxwriter (>= 0.9.3), python-yaml (>= 3.10), python-yara (>= 3.4.0), python-zmq (>= 2.1.11), python (>= 2.7), python (<< 2.8)
Download-Size: 415 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 Packages
Description: Python 2 module of plaso (log2timeline)
```

**Comment by Rolinh** [comment] 2018-07-03 08:31
> Any chance you could share the data or debug print the values tuple list to determine what the large integer is and where this value originates.

The `values_tuple_list` contains 9887 elements which are tuples of the form `(number, read-only bufffer)`.  It looks to me like the first element of the tuple is a timestamp in microsecond (eg: `1522867542060000`).
At the end of the list though, these timestamps are just too big to be timestamps in microseconds. The biggest value I spotted at the end of this list is `1728001527604235993088L` and I suspect it's the value which is the root cause of the exception.
However, some timestamps are already suspicious besides this very large value (eg: `4683051143000000`, which would be in May 2118 or `2534023007990000` which would be in April 2050).

I suspect that the exception is a sign of a bug but that the bug lies elsewhere (assuming these are all supposed to be timestamps).

**Comment by joachimmetz** [comment] 2018-07-03 08:41
I agree that 1728001527604235993088L => 0xacd6aa02f6d80000 is likely the issue. This value would fit in the 64-bit but seeing the timestamp int is signed it likely overflows 63-bit. I'll add some tests to see if I can reproduce the exception. 

> I suspect that the exception is a sign of a bug but that the bug lies elsewhere (assuming these are all supposed to be timestamps).

I agree with this assessment, but the storage layer should handle these more gracefully as well. Any indication which parser is generating this? The cookie parser by any chance?

**Comment by Rolinh** [comment] 2018-07-03 09:23
@joachimmetz Good news: I was able to pinpoint the offending row within the `moz_cookies` table of the firefox's cookie sqlite database.

Here are steps that will allow you to reproduce this issue:

```
$ sqlite3 /data/test.sqlite
sqlite> CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, baseDomain TEXT, originAttributes TEXT NOT NULL DEFAULT '', name TEXT, value TEXT, host TEXT, path TEXT, expiry INTEGER, lastAccessed INTEGER, creationTime INTEGER, isSecure INTEGER, isHttpOnly INTEGER, appId INTEGER DEFAULT 0, inBrowserElement INTEGER DEFAULT 0, CONSTRAINT moz_uniqueid UNIQUE (name, host, path, originAttributes));
sqlite> CREATE INDEX moz_basedomain ON moz_cookies (baseDomain, originAttributes);
sqlite> INSERT INTO moz_cookies VALUES(1,'example.com','','zc','b9c980a0-a08c-4f9f-58a6-ac993af7ca85','.example.com','/',481529369421159609,1528906789972000,1526919609852000,0,0,0,0);
$ /usr/bin/log2timeline.py -d --status_view linear /data/test.plaso /data/test.sqlite
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lzma.
[OK]


Source path     : /data/test.sqlite
Source type     : single file
Processing time : 00:00:00

Processing started.
2018-07-03 09:21:30,909 [DEBUG] (MainProcess) PID:954 <log2timeline_tool> Starting extraction in single process mode.
2018-07-03 09:21:31,146 [DEBUG] (MainProcess) PID:954 <extractors> Active parsers: amcache, android_app_usage, asl_log, bash, bencode, binary_cookies, bsm_log, chrome_cache, chrome_preferences, cups_ipp, custom_destinations, dockerjson, dpkg, esedb, filestat, firefox_cache, firefox_cache2, fsevents, gdrive_synclog, hachoir, java_idx, lnk, mac_appfirewall_log, mac_keychain, mac_securityd, mactime, macwifi, mcafee_protection, mft, msiecf, olecf, openxml, opera_global, opera_typed_history, pe, plist, pls_recall, popularity_contest, prefetch, recycle_bin, recycle_bin_info2, rplog, sccm, selinux, skydrive_log, skydrive_log_old, sophos_av, sqlite, symantec_scanlog, syslog, systemd_journal, trendmicro_url, trendmicro_vd, usnjrnl, utmp, utmpx, winevt, winevtx, winfirewall, winiis, winjob, winreg, xchatlog, xchatscrollback, zsh_extended_history
2018-07-03 09:21:31,147 [DEBUG] (MainProcess) PID:954 <hashing_analyzer> Got hasher names: sha256
2018-07-03 09:21:31,147 [DEBUG] (MainProcess) PID:954 <single_process> Processing started.
2018-07-03 09:21:31,158 [DEBUG] (MainProcess) PID:954 <worker> [ProcessFileEntry] processing file entry: OS:/data/test.sqlite
2018-07-03 09:21:31,159 [DEBUG] (MainProcess) PID:954 <worker> [ProcessFileEntryDataStream] processing data stream: "" of file entry: OS:/data/test.sqlite
2018-07-03 09:21:31,159 [DEBUG] (MainProcess) PID:954 <worker> [AnalyzeDataStream] analyzing file: OS:/data/test.sqlite
2018-07-03 09:21:31,159 [DEBUG] (MainProcess) PID:954 <hashing_analyzer> Processing results for hasher sha256
2018-07-03 09:21:31,160 [DEBUG] (MainProcess) PID:954 <worker> [AnalyzeFileObject] attribute sha256_hash:874817cd98f393401446bf69c906d8d0c586b6f0ff54bdf79a2d4fcd30e00b38 calculated for file: OS:/data/test.sqlite.
2018-07-03 09:21:31,160 [DEBUG] (MainProcess) PID:954 <worker> [AnalyzeDataStream] completed analyzing file: OS:/data/test.sqlite
2018-07-03 09:21:31,160 [DEBUG] (MainProcess) PID:954 <worker> [ExtractMetadataFromFileEntry] processing file entry: OS:/data/test.sqlite
2018-07-03 09:21:31,167 [DEBUG] (MainProcess) PID:954 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/data/test.sqlite with parser: sqlite
2018-07-03 09:21:31,174 [DEBUG] (MainProcess) PID:954 <worker> [ProcessFileEntry] done processing file entry: OS:/data/test.sqlite
2018-07-03 09:21:31,176 [DEBUG] (MainProcess) PID:954 <sqlite_file> values_tuple_list len: 1
2018-07-03 09:21:31,177 [DEBUG] (MainProcess) PID:954 <sqlite_file> [(<read-only buffer for 0x7f261b54d710, size -1, offset 0 at 0x7f261b46eaf0>,)]
2018-07-03 09:21:31,177 [DEBUG] (MainProcess) PID:954 <sqlite_file> values_tuple_list len: 2
2018-07-03 09:21:31,177 [DEBUG] (MainProcess) PID:954 <sqlite_file> [(<read-only buffer for 0x7f261b523d98, size -1, offset 0 at 0x7f262583a470>,), (<read-only buffer for 0x7f261b460d88, size -1, offset 0 at 0x7f262d4597f0>,)]
2018-07-03 09:21:31,178 [DEBUG] (MainProcess) PID:954 <sqlite_file> values_tuple_list len: 6
2018-07-03 09:21:31,178 [DEBUG] (MainProcess) PID:954 <sqlite_file> [(1526919609852000, <read-only buffer for 0x7f261b516930, size -1, offset 0 at 0x7f262583a470>), (1528906789972000, <read-only buffer for 0x7f261b516e70, size -1, offset 0 at 0x7f2628c3ffb0>), (1530609372000000, <read-only buffer for 0x7f261b522a40, size -1, offset 0 at 0x7f261b46eaf0>), (1530609372000000, <read-only buffer for 0x7f261b522988, size -1, offset 0 at 0x7f261b46e770>), (1530609383000000, <read-only buffer for 0x7f261b54d710, size -1, offset 0 at 0x7f261b46ef30>), (481529369421159621197824L, <read-only buffer for 0x7f261b583e40, size -1, offset 0 at 0x7f261b46e3b0>)]
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 434, in ExtractEventsFromSources
    status_update_callback=status_update_callback)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/single_process.py", line 283, in ProcessSources
    storage_writer.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 1308, in Close
    self._storage_file.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 667, in Close
    self._WriteSerializedAttributeContainerList(self._CONTAINER_TYPE_EVENT)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 447, in _WriteSerializedAttributeContainerList
    self._cursor.executemany(query, values_tuple_list)
OverflowError: Python int too large to convert to SQLite INTEGER
```

**Comment by joachimmetz** [comment] 2018-07-03 09:47
thx, having a look at this in more detail later today

**Comment by Rolinh** [comment] 2018-07-05 12:07
Not sure if this is of any help but this exception is not raised with plaso `20171118`. It starts being raised with plaso `20171231`. If the bug is hard to spot, maybe bisecting between these two versions may help.

**Comment by joachimmetz** [comment] 2018-07-05 19:09
That is likely due to the ZIP storage ignoring the integer size limit.

**Comment by joachimmetz** [comment] 2018-07-08 13:17
> OverflowError: Python int too large to convert to SQLite INTEGER

I've been able to trigger this exception in some additional unit tests https://github.com/log2timeline/plaso/pull/2025

Added out of bounds check https://github.com/log2timeline/plaso/pull/2027

**Comment by joachimmetz** [comment] 2018-07-14 12:53
@Rolinh could you test with plaso HEAD to see if the issue persists

**Comment by Rolinh** [comment] 2018-07-16 08:15
@joachimmetz I've tested with the version from gift's dev PPA (it reports as being `plaso - log2timeline version 20180703`) and the exception was not raised.  I also exported data to CSV with psort and it looks like large date values are bound to `9999-12-31T23:59:59+00:00`.

**Comment by joachimmetz** [comment] 2018-07-21 04:31
@Rolinh I'm closing this issue but there is more to do here that is captures in other issues such as #2023

**Closed by joachimmetz** 2018-07-21 04:31 UTC
Labels: bug, storage
