### ISSUE TITLE
Cups_ipp parser verification check not working well

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#223] opened 2015-06-03 11:44 UTC
```
[WARNING] [cups_ipp] Unsupported name in file: TSK:/Windows/ServiceProfiles/LocalService/AppData/Roaming/Microsoft/Crypto/RSA/S-1-5-19/<filename>
```

**Comment by kiddinn** [comment] 2015-06-03 21:32
This warning comes after a "successful" verification, which means we have to take a look at why this is failing.

This warning, does this come from a disk image that is "known"? As in can you point me to where you see this so that I can try to replicate.

**Comment by Onager** [comment] 2015-06-07 14:28
5afe4de1b92fc382.customDestinations-ms from test_data seems to be parsed by cups_ipp, it triggers the unsupported operation code path.

**Comment by joachimmetz** [comment] 2015-06-08 12:57
```
2015-06-06 09:10:55,850 [WARNING] (Worker_01 ) PID:32170 <cups_ipp> [cups_ipp] Unsupported value in file: TSK:/Users/$USERNAME/AppData/Roaming/Microsoft/Protect/$SID/$GUID
2015-06-06 09:10:57,284 [WARNING] (Worker_00 ) PID:32169 <cups_ipp> [cups_ipp] Unsupported name in file: TSK:/Users/$USERNAME/AppData/Roaming/Microsoft/Windows/Recent/CustomDestinations/$ID.customDestinations-ms.
```

**Comment by kiddinn** [comment] 2015-07-01 03:14
Is this still an issue?

    $ log2timeline.py /tmp/foo.plaso test_data/5afe4de1b92fc382.customDestinations-ms 
    [INFO] Data files will be loaded from /Library/Python/2.7/site-packages/plaso-1.3.0_20150630-py2.7.egg/share/plaso by default.

    Source path				: /<PATH>/test_data/5afe4de1b92fc382.customDestinations-ms
    Is storage media image or device	: False

    Processing started.
    Processing completed.


Looking at pinfo:

    --------------------------------------------------------------------------------
    		Plaso Storage Information
    --------------------------------------------------------------------------------
    ...
    	parsers = android_app_usage,..., cups_ipp, custom_destinations, esedb, ...
    ...
    Parser counter information:
    	Counter: total = 111
    	Counter: custom_destinations/lnk/shell_items = 81
    	Counter: custom_destinations/lnk = 27
    	Counter: filestat = 3

At least it does not seem to trigger this FP for me anymore.

**Comment by kiddinn** [comment] 2015-09-24 20:49
I'm closing this one down, since I was unable to reproduce this issue anymore, if it's really not fixed, please re-open it.

**Closed by kiddinn** 2015-09-24 20:49 UTC
Labels: bug
