### ISSUE TITLE
"Waiting for worker Worker_1 to complete" indefinitely

### ISSUE THREAD

**Issue by apapadop** [log2timeline/plaso#71] opened 2014-12-17 01:14 UTC
I have this particular image which log2timeline_legacy whizzes through in less than 60 minutes and produces valid output. How lovely. What about plaso?

```
sudo log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
...takes approx. _12 hours_ to reach this state:

2014-12-16 23:29:03,543 [INFO] (Worker_7  ) PID:14088 <worker> Worker 7 (PID: 14088) stopped monitoring process queue.
2014-12-16 23:29:07,479 [INFO] (MainProcess) PID:14066 <foreman> Worker_1 [14076] has been removed from foreman monitoring.
2014-12-16 23:29:12,480 [INFO] (MainProcess) PID:14066 <foreman> Worker_2 [14078] has been removed from foreman monitoring.
2014-12-16 23:29:17,482 [INFO] (MainProcess) PID:14066 <foreman> Worker_3 [14080] has been removed from foreman monitoring.
2014-12-16 23:29:22,483 [INFO] (MainProcess) PID:14066 <foreman> Worker_4 [14082] has been removed from foreman monitoring.
2014-12-16 23:29:27,484 [INFO] (MainProcess) PID:14066 <foreman> Worker_5 [14084] has been removed from foreman monitoring.
2014-12-16 23:29:32,485 [INFO] (MainProcess) PID:14066 <foreman> Worker_6 [14085] has been removed from foreman monitoring.
2014-12-16 23:29:37,487 [INFO] (MainProcess) PID:14066 <foreman> Worker_7 [14088] has been removed from foreman monitoring.
2014-12-16 23:29:42,488 [INFO] (MainProcess) PID:14066 <foreman> Worker_0 [14074] has been removed from foreman monitoring.
2014-12-16 23:29:47,489 [INFO] (MainProcess) PID:14066 <frontend> Process Worker_1 [14076] is not monitored by the foreman. Most likely due to a worker having completed it's processing while waiting for another worker to complete.
2014-12-16 23:29:47,489 [INFO] (MainProcess) PID:14066 <frontend> Waiting for worker Worker_1 to complete.
```

It then just sits there snoring:
```
root     14065  0.0  0.0  75368   884 pts/14   S+   Dec16   0:00          |   |   \_ sudo log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14066  0.1  0.1 748280 45848 pts/14   S+   Dec16   1:01          |   |       \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14072 14.6  1.0 1028184 334632 pts/14 S+   Dec16 101:28          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14074  3.8  2.5 1731688 822924 pts/14 Sl+  Dec16  26:36          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14076  4.0  2.8 1841796 933144 pts/14 Sl+  Dec16  27:59          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14078  3.7  2.7 1796940 888388 pts/14 Sl+  Dec16  26:17          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14080  3.8  3.5 2091944 1183712 pts/14 Sl+ Dec16  26:59          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14082  3.7  2.8 1831596 923332 pts/14 Sl+  Dec16  25:56          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14084  3.6  2.5 1748088 839792 pts/14 Sl+  Dec16  25:28          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14085  3.8  2.9 1887264 978712 pts/14 Sl+  Dec16  26:26          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
root     14088  3.9  3.3 2011424 1102384 pts/14 Sl+ Dec16  27:28          |   |           \_ /usr/bin/python /usr/bin/log2timeline.py --debug --workers=8 --show-memory-usage --logfile l2t.log plaso3.dump /mnt/bde/bde1
```

Killing the main process with CTRL-C results in a corrupt plaso3.dump that cannot be processed with psort.py:

```
$ time psort.py -o Tln -w 01Dec_tln.csv plaso3.dump "date > '2014-11-30' and date < '2014-12-02'"
[ERROR] Unable to read entry index: 217733 from proto stream: 15
[INFO] Output processing is done.
[INFO] 
*********************************** Counter ************************************
[INFO]             Stored Events : 20935364
[INFO]            Filter By Date : 20935364

real	0m9.770s
user	0m8.718s
sys	0m0.307s
$ cat 01Dec_tln.csv 
Time|Source|Host|User|Description
$ wc -l l2t.log
83365213 l2t.log
$ ls -lh plaso3.dump l2t.log 
-rw-r--r-- 1 root root  12G Dec 17 01:02 l2t.log
-rw-r--r-- 1 root root 1.3G Dec 17 01:02 plaso3.dump
$ 
```

Trying to kill -HUP each worker individually has the same results.

This appears to be repeatable (have been through the whole process 3 times now).

What data may I provide from the debug log to help troubleshoot this?

Thanks!

**Comment by kiddinn** [comment] 2015-01-08 23:49
hi, sorry for the later reply.

But yes, email me directly... and @coderego can you test one thing for me? I have a small patch here: http://codereview.appspot.com/194970043 could you apply this to your code and see if this fixes this issue for you?

And I'm assuming this is easily reproducable?

**Comment by cvandeplas** [comment] 2015-02-20 09:43
Hello, same problem here. plaso-1.2.0-win-amd64-vs2010.
Reproducable every time. Killing the processes solves the hanging, but in the end the dump is corrupted.
I'm not sure about the OS version of the target machine. It is probably Win7.
Any news about the results of this patch? Unfortunately I am not on a system where I can run python natively or compile it to a windows binary.

**Comment by ddavidds** [comment] 2015-03-16 09:09
Hello, I have the same problem 
log2timeline - plaso back-end 1.2.1_20150312
debian 3.13.0-34-generic x64

PID:18472 <multi_process> Process Worker_1 [18481] is not monitored by the foreman. Most likely due to a worker having completed it's processing while waiting for another worker to complete.
2015-03-13 18:24:41,405
 [INFO] (MainProcess) PID:18472 <multi_process> Waiting for worker Worker_1 to complete

2 days waiting for the worker to complete :/

**Comment by joachimmetz** [comment] 2015-03-17 22:12
So the worker is stopped but not terminated I suspect the XML RPC server to be the culprit. CL with some changes to improved debugging this issue: http://codereview.appspot.com/214400043

**Comment by joachimmetz** [comment] 2015-03-25 08:47
I'm able to reproduce this issue, saw the worker status changes happen in a different order. Suspect that this [join](https://github.com/log2timeline/plaso/blob/master/plaso/multi_processing/multi_process.py#L344) is blocking the main process.

**Comment by joachimmetz** [comment] 2015-03-26 11:46
Even with the join now no longer a possible blocker the issue is still there, revisiting the XML RPC server.

**Comment by joachimmetz** [comment] 2015-03-27 15:47
Overhaul of foreman and RPC code: https://codereview.appspot.com/219420043/

**Comment by joachimmetz** [comment] 2015-04-01 11:41
For those of you that had issues with hanging workers, please try bleeding edge (HEAD) and see if the issue is gone now.

**Comment by joachimmetz** [comment] 2015-04-07 20:24
Issue seemed to be fixed for several cases where I could reproduce it. Closing issue reopen if still persist.

**Closed by joachimmetz** 2015-04-07 20:24 UTC
Labels: bug

**Comment by rodgermoore** [comment] 2015-05-05 11:12
Hi Joachim. 

I'm runnning into the same issue using Log2Timeline.exe 1.2 Final on Windows 7 64Bit , on a Windows 7 64 bit E01 image.

Do you know when a new pre-compiled version is going to be released for Windows with this issue solved? I tried to build the project myself but I'm having too much trouble doing this. 

Thanks
Rodger
