### ISSUE TITLE
Unable to created PyInstaller build from HEAD

### ISSUE THREAD

**Issue by ofir123** [log2timeline/plaso#2923] opened 2020-05-07 20:41 UTC
**Description of problem:**

I've built Plaso by following this guide:
https://plaso.readthedocs.io/en/latest/sources/developer/Packaging%20with%20pyinstaller.html?highlight=pyinstaller

The result EXE runs great on the builder machine, but raises an error on other machines.

On builder machine:
```
c:\Temp\plaso\dist\log2timeline>log2timeline.exe
ERROR: Unable to determine location of data files.

usage: log2timeline.exe [-h] [--troubles] [-V] [--artifact_definitions PATH]
                        [--custom_artifact_definitions PATH] [--data PATH]
                        [--artifact_filters ARTIFACT_FILTERS]
                        [--artifact_filters_file PATH] [--preferred_year YEAR]
                        [--process_archives] [--skip_compressed_streams]
                        [-f FILE_FILTER] [--hasher_file_size_limit SIZE]
                        [--hashers HASHER_LIST]
                        [--parsers PARSER_FILTER_EXPRESSION]
                        [--yara_rules PATH] [--partitions PARTITIONS]
                        [--volumes VOLUMES] [-z TIMEZONE] [--no_vss]
                        [--vss_only] [--vss_stores VSS_STORES]
                        [--credential TYPE:DATA] [-d] [-q] [--info]
                        [--use_markdown] [--no_dependencies_check]
                        [--logfile FILENAME] [--status_view TYPE] [-t TEXT]
                        [--buffer_size BUFFER_SIZE] [--queue_size QUEUE_SIZE]
                        [--single_process] [--temporary_directory DIRECTORY]
                        [--worker_memory_limit SIZE] [--workers WORKERS]
                        [--sigsegv_handler] [--profilers PROFILERS_LIST]
                        [--profiling_directory DIRECTORY]
                        [--profiling_sample_rate SAMPLE_RATE]
                        [--storage_format FORMAT]
                        [--task_storage_format FORMAT]
                        [STORAGE_FILE] [SOURCE]
```

On other clean Windows 10 machines:
```
C:\Users\Lenovo\Desktop\log2timeline\log2timeline>log2timeline.exe
Traceback (most recent call last):
  File "tools\log2timeline.py", line 14, in <module>
  File "c:\users\ofirb\anaconda3\envs\plaso\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "plaso\cli\log2timeline_tool.py", line 19, in <module>
  File "c:\users\ofirb\anaconda3\envs\plaso\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "plaso\cli\extraction_tool.py", line 18, in <module>
  File "c:\users\ofirb\anaconda3\envs\plaso\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "plaso\cli\storage_media_tool.py", line 21, in <module>
  File "c:\users\ofirb\anaconda3\envs\plaso\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\dfvfs\volume\tsk_volume_system.py", line 8, in <module>
  File "c:\users\ofirb\anaconda3\envs\plaso\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\dfvfs\lib\tsk_partition.py", line 6, in <module>
ImportError: DLL load failed: The specified module could not be found.
[15320] Failed to execute script log2timeline
```

This same error happens even when trying to wrap a simple script which is using `dfvfs`.

**Plaso version:**

Latest (from `master`).

**Operating system Plaso is running on:**

Windows 10 Pro.

**Installation method:**

built using [l2devtools][https://github.com/log2timeline/l2tdevtools]

Any help would be appreciated!
Thank you :)

**Comment by joachimmetz** [comment] 2020-05-08 03:53
1. First make sure you are able to run the unit tests (`run_tests.py`) before doing PyInstaller build. 
2. Seeing the error message see if pytsk.pyd was added by PyInstaller. If not try tweaking the Pyinstaller configuration to force it to add the pytsk project.
3. Double check if pytsk.pyd is a 64-bit DLL.

**Comment by ofir123** [comment] 2020-05-08 23:06
Thank you very much for the quick answer!
The tests are (almost) all good, and I see this file in the result directory (under `dist/log2timeline`):
`pytsk3.cp37-win_amd64.pyd` (I also checked the headers and made sure it's 64-Bit).

I'm building using Anaconda Python 3.7.7 64-bit - Is that an issue?
Are there any more checks are I can do to make sure everything ran properly and it's not something on my end?

About tests, I'm getting a few failures, but they all seem to be caused by minor versioning issues of some of the external packages, so I doubt that is part of the cause. Here's the results output after running the tests:
```
======================================================================
ERROR: testParseFile (parsers.mac_appfirewall.MacAppFirewallUnitTest)
Test parsing of a Mac Wifi log file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\parsers\mac_appfirewall.py", line 24, in testParseFile
    knowledge_base_values=knowledge_base_values)
  File ".\tests\parsers\test_lib.py", line 133, in _ParseFile
    knowledge_base_values=knowledge_base_values, timezone=timezone)
  File ".\tests\parsers\test_lib.py", line 164, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File ".\plaso\parsers\interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File ".\plaso\parsers\text_parser.py", line 404, in ParseFileObject
    raise errors.UnableToParseFile('Wrong file structure.')
plaso.lib.errors.UnableToParseFile: Wrong file structure.

======================================================================
ERROR: testParseFile (parsers.ntfs.NTFSMFTParserTest)
Tests the Parse function on a stand-alone $MFT file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\parsers\ntfs.py", line 32, in testParseFile
    storage_writer = self._ParseFileByPathSpec(os_path_spec, parser)
  File ".\tests\parsers\test_lib.py", line 164, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File ".\plaso\parsers\interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File ".\plaso\parsers\ntfs.py", line 331, in ParseFileObject
    self._ParseMFTEntry(parser_mediator, mft_entry)
  File ".\plaso\parsers\ntfs.py", line 288, in _ParseMFTEntry
    if mft_attribute.namespace != self._NAMESPACE_DOS:
AttributeError: 'pyfsntfs.file_name_attribute' object has no attribute 'namespace'

======================================================================
ERROR: testParseImage (parsers.ntfs.NTFSMFTParserTest)
Tests the Parse function on a storage media image.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\parsers\ntfs.py", line 102, in testParseImage
    storage_writer = self._ParseFileByPathSpec(tsk_path_spec, parser)
  File ".\tests\parsers\test_lib.py", line 164, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File ".\plaso\parsers\interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File ".\plaso\parsers\ntfs.py", line 331, in ParseFileObject
    self._ParseMFTEntry(parser_mediator, mft_entry)
  File ".\plaso\parsers\ntfs.py", line 288, in _ParseMFTEntry
    if mft_attribute.namespace != self._NAMESPACE_DOS:
AttributeError: 'pyfsntfs.file_name_attribute' object has no attribute 'namespace'

======================================================================
FAIL: testExtractEventsFromSourcesOnVSSImage (cli.log2timeline_tool.Log2TimelineToolTest)
Tests the ExtractEventsFromSources function on VSS image.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\cli\log2timeline_tool.py", line 427, in testExtractEventsFromSourcesOnVSSImage
    self._CheckOutput(output, expected_output)
  File "C:\temp\plaso\tests\cli\log2timeline_tool.py", line 102, in _CheckOutput
    self.assertEqual(output[4:], expected_output[4:])
AssertionError: Lists differ: ['', [102 chars]nts: 11.', '', 'Use pinfo to inspect warnings [20 chars], ''] != ['', [102 chars]nts: 3.', '', 'Use pinfo to inspect warnings i[19 chars], '']

First differing element 4:
'Number of warnings generated while extracting events: 11.'
'Number of warnings generated while extracting events: 3.'

  ['',
   'Processing started.',
   'Processing completed.',
   '',
-  'Number of warnings generated while extracting events: 11.',
?                                                         ^^

+  'Number of warnings generated while extracting events: 3.',
?                                                         ^

   '',
   'Use pinfo to inspect warnings in more detail.',
   '',
   '']

======================================================================
FAIL: testExtractEventsFromSourcesPartitionedImage (cli.log2timeline_tool.Log2TimelineToolTest)
Tests the ExtractEventsFromSources function on multi partition image.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\cli\log2timeline_tool.py", line 389, in testExtractEventsFromSourcesPartitionedImage
    self._CheckOutput(output, expected_output)
  File "C:\temp\plaso\tests\cli\log2timeline_tool.py", line 102, in _CheckOutput
    self.assertEqual(output[4:], expected_output[4:])
AssertionError: Lists differ: ['', [48 chars]'', 'Number of warnings generated while extrac[73 chars], ''] != ['', [48 chars]'', '']

First differing element 4:
'Number of warnings generated while extracting events: 8.'
''

First list contains 4 additional elements.
First extra element 5:
''

+ ['', 'Processing started.', 'Processing completed.', '', '']
- ['',
-  'Processing started.',
-  'Processing completed.',
-  '',
-  'Number of warnings generated while extracting events: 8.',
-  '',
-  'Use pinfo to inspect warnings in more detail.',
-  '',
-  '']

======================================================================
FAIL: testExtractEventsFromSourcePartitionedImage (cli.psteal_tool.PstealToolTest)
Tests the ExtractEventsFromSources function on a partitioned image.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\cli\psteal_tool.py", line 353, in testExtractEventsFromSourcePartitionedImage
    self._CheckOutput(output, expected_output)
  File "C:\temp\plaso\tests\cli\psteal_tool.py", line 48, in _CheckOutput
    self.assertEqual(output[4:], expected_output[4:])
AssertionError: Lists differ: ['', [48 chars]'', 'Number of warnings generated while extrac[73 chars], ''] != ['', [48 chars]'', '']

First differing element 4:
'Number of warnings generated while extracting events: 8.'
''

First list contains 4 additional elements.
First extra element 5:
''

+ ['', 'Processing started.', 'Processing completed.', '', '']
- ['',
-  'Processing started.',
-  'Processing completed.',
-  '',
-  'Number of warnings generated while extracting events: 8.',
-  '',
-  'Use pinfo to inspect warnings in more detail.',
-  '',
-  '']

======================================================================
FAIL: testExtractEventsFromSourceVSSImage (cli.psteal_tool.PstealToolTest)
Tests the ExtractEventsFromSources function on an image with VSS.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\cli\psteal_tool.py", line 399, in testExtractEventsFromSourceVSSImage
    self._CheckOutput(output, expected_output)
  File "C:\temp\plaso\tests\cli\psteal_tool.py", line 48, in _CheckOutput
    self.assertEqual(output[4:], expected_output[4:])
AssertionError: Lists differ: ['', [102 chars]nts: 11.', '', 'Use pinfo to inspect warnings [20 chars], ''] != ['', [102 chars]nts: 3.', '', 'Use pinfo to inspect warnings i[19 chars], '']

First differing element 4:
'Number of warnings generated while extracting events: 11.'
'Number of warnings generated while extracting events: 3.'

  ['',
   'Processing started.',
   'Processing completed.',
   '',
-  'Number of warnings generated while extracting events: 11.',
?                                                         ^^

+  'Number of warnings generated while extracting events: 3.',
?                                                         ^

   '',
   'Use pinfo to inspect warnings in more detail.',
   '',
   '']

======================================================================
FAIL: testScanSourceVSS (cli.storage_media_tool.StorageMediaToolTest)
Tests the ScanSource function on a VSS.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\cli\storage_media_tool.py", line 1303, in testScanSourceVSS
    self._TestScanSourceVSSImage(source_path)
  File "C:\temp\plaso\tests\cli\storage_media_tool.py", line 320, in _TestScanSourceVSSImage
    scan_node.type_indicator, dfvfs_definitions.TYPE_INDICATOR_TSK)
AssertionError: 'NTFS' != 'TSK'
- NTFS
+ TSK


======================================================================
FAIL: testIterator (lib.line_reader_file.BinaryDSVReaderTest)
Tests the iterator functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\lib\line_reader_file.py", line 198, in testIterator
    self.assertEqual(rows[0], [b'place', b'user', b'password'])
AssertionError: Lists differ: [b'place', b'user', b'password\r'] != [b'place', b'user', b'password']

First differing element 2:
b'password\r'
b'password'

- [b'place', b'user', b'password\r']
?                               --

+ [b'place', b'user', b'password']

======================================================================
FAIL: testIterator (lib.line_reader_file.BinaryLineReaderTest)
Test the iterator functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\lib\line_reader_file.py", line 162, in testIterator
    self.assertEqual(lines[0], b'place,user,password\n')
AssertionError: b'place,user,password\r\n' != b'place,user,password\n'

======================================================================
FAIL: testReadline (lib.line_reader_file.BinaryLineReaderTest)
Test the readline() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\lib\line_reader_file.py", line 37, in testReadline
    self.assertEqual(line, b'This is another file.\n')
AssertionError: b'This is another file.\r\n' != b'This is another file.\n'

======================================================================
FAIL: testReadlineMultipleLines (lib.line_reader_file.BinaryLineReaderTest)
Test the readline() function on multiple lines.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\lib\line_reader_file.py", line 64, in testReadlineMultipleLines
    self.assertEqual(line, b'place,user,password\n')
AssertionError: b'place,user,password\r\n' != b'place,user,password\n'

======================================================================
FAIL: testReadlines (lib.line_reader_file.BinaryLineReaderTest)
Test the readlines() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\lib\line_reader_file.py", line 103, in testReadlines
    self.assertEqual(lines[0], b'place,user,password\n')
AssertionError: b'place,user,password\r\n' != b'place,user,password\n'

======================================================================
FAIL: testReadlinesWithSizeHint (lib.line_reader_file.BinaryLineReaderTest)
Test the readlines() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\lib\line_reader_file.py", line 125, in testReadlinesWithSizeHint
    self.assertEqual(lines[0], b'place,user,password\n')
AssertionError: b'place,user,password\r\n' != b'place,user,password\n'

======================================================================
FAIL: testParse (parsers.apache_access.ApacheAccessUnitTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\parsers\apache_access.py", line 96, in testParse
    'unable to parse log line: "46.118.127.106 - - [20/May/2015:12:05:17 '
AssertionError: 'unab[58 chars]05:17 +0000] "GET /scripts/grok-py-test/co..." at offset: 1596' != 'unab[58 chars]05:17 +0000] "GET /scripts/grok-py-test/co..." at offset: 1589'
- unable to parse log line: "46.118.127.106 - - [20/May/2015:12:05:17 +0000] "GET /scripts/grok-py-test/co..." at offset: 1596
?                                                                                                                            -
+ unable to parse log line: "46.118.127.106 - - [20/May/2015:12:05:17 +0000] "GET /scripts/grok-py-test/co..." at offset: 1589
?                                                                                                                           +


======================================================================
FAIL: testParseFileObject (parsers.dsv_parser.DSVParserTest)
Tests the ParseFileObject function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\parsers\dsv_parser.py", line 101, in testParseFileObject
    self.assertEqual(row_offset, 20)
AssertionError: 21 != 20

======================================================================
FAIL: testParseFile (parsers.mac_securityd.MacOSSecurityUnitTest)
Test parsing of a MacOS securityd log file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\parsers\mac_securityd.py", line 46, in testParseFile
    self.assertEqual(event_data.message, expected_message)
AssertionError: 'secu[52 chars]DeviceInCircle Þetta ætti að virka líka, setja íslensku inn.\r' != 'secu[52 chars]DeviceInCircle Þetta ætti að virka líka, setja íslensku inn.'
?                                                                                                                     -
+ securityd_xpc_dictionary_handler EscrowSecurityAl[3273] DeviceInCircle Þetta ætti að virka líka, setja íslensku inn.

======================================================================
FAIL: testParse (parsers.santa.SantaUnitTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\plaso\tests\parsers\santa.py", line 27, in testParse
    self.assertEqual(storage_writer.number_of_warnings, 0)
AssertionError: 17 != 0

----------------------------------------------------------------------
Ran 1369 tests in 332.602s

FAILED (failures=15, errors=3, skipped=8)
```

**Comment by joachimmetz** [comment] 2020-05-09 04:30
I would recommend that you get the tests to to pass, this is also to ensure plaso and dependencies are working as intended. It looks like some of your dependencies are older and maybe that you have `\r` issues due to git autocrlf setting https://plaso.readthedocs.io/en/latest/sources/developer/Developing-Windows.html#git

But agree that that does not explain the DLL import error

> I'm building using Anaconda Python 3.7.7 64-bit - Is that an issue?

Not sure, PyInstaller uses a lot of magic.

> Are there any more checks are I can do to make sure everything ran properly and it's not something on my end?

Maybe https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html gives some additional tips

> The tests are (almost) all good, and I see this file in the result directory (under dist/log2timeline):
pytsk3.cp37-win_amd64.pyd (I also checked the headers and made sure it's 64-Bit).

And pytsk.pyd was build hermetic using its setup.py without relying on libtsk.dll? If not libtsk.dll also would need to be included. Also check if pytsk.pyd does depend on other DLLs e.g. Visual C runtime and that these are available to the PyInstaller build.

**Comment by joachimmetz** [comment] 2020-05-09 04:31
If you want an alternative to PyInstaller have a look at the plaso Docker build (https://plaso.readthedocs.io/en/latest/sources/user/Installing-with-docker.html) It is not equivalent but could do the trick.

**Comment by joachimmetz** [comment] 2020-05-16 06:17
@ofir123 were you able to resolve this?

**Comment by ofir123** [comment] 2020-05-18 23:22
Sorry for the late reponse @joachimmetz,
And big thanks again for all of your suggestions!

I went over the PyInstaller documentation, but didn't find anything too useful there.
The thing is I'm not sure where does `pytsk.pyd` actually searches for DLLS, let alone which ones are needed for it to work properly.
I'll dive deeper of course, but just wanted to check if you guys managed to get it working, to make sure it's not something stupid in my environment..

**Comment by joachimmetz** [comment] 2020-05-19 04:21
> The thing is I'm not sure where does pytsk.pyd actually searches for DLLS, let alone which ones are needed for it to work properly.

If it's build hermetic having only the PYD (which is a DLL) should be sufficient 

We had it working in the past. We are no longer proving a PyInstaller build but the script did work in the past. Unfortunately the process is fragile due to numerous factors like the build environment.

**Comment by ofir123** [comment] 2020-05-20 01:16
Got it!
It's ok, I'll keep poking it until it'll work hopefully :)
Thank you very much for the time and tips!

btw maybe it's worth mentioning that PyInstaller isn't supported anymore in your docs?

**Comment by joachimmetz** [comment] 2020-05-20 03:58
> btw maybe it's worth mentioning that PyInstaller isn't supported anymore in your docs?

We mentioned it on http://blog.kiddaland.net/2020/01/plaso-20200121-released.html that we stop providing builds. Not sure what information you are missing from the Plaso docs and what you mean with "support" in this context.

Technically PyInstaller is a stand-alone tool to build packaged releases from Python projects. There is not much there for Plaso to provide support for.

**Comment by ofir123** [comment] 2020-05-20 22:49
I just meant to add the information from these release notes (specifically "We are no longer providing PyInstaller packaged versions.") to this page:
https://plaso.readthedocs.io/en/latest/sources/developer/Packaging%20with%20pyinstaller.html

But I also wasn't aware of these release notes, so it's my bad as well! (could've searched a bit more before opening the issue here..)

**Comment by joachimmetz** [comment] 2020-05-22 18:26
So https://plaso.readthedocs.io/en/latest/sources/developer/Packaging%20with%20pyinstaller.html is page intended for developers that want to build their own PyInstaller packaged version. The release notes refer to the project (maintainers) no longer providing these builds as part of the release.

You can still try build these yourself and our build scripts have been moved to l2tdevtools, but as you've noticed this is typically not a process without struggle.

**Comment by joachimmetz** [comment] 2020-05-22 18:29
I'll close this issue, since the error you describe appears to lie in the build environment or build process.

**Closed by joachimmetz** 2020-05-22 18:29 UTC
Labels: dependency, question
