### ISSUE TITLE
Add nsrlsvr analysis plugin

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#421] opened 2015-11-30 15:22 UTC
Add an analysis plugin for tagging files in nsrlsvr.

**Comment by pettai** [comment] 2015-11-30 18:58
+1, that would be great!

**Comment by joachimmetz** [comment] 2015-12-03 08:27
Duplicate of: https://github.com/log2timeline/plaso/issues/300

**Closed by joachimmetz** 2015-12-03 08:27 UTC
Labels: analysis, enhancement
