### ISSUE TITLE
Psort analysis plugins use too much memory on Centos/Python 2.7.5

### ISSUE THREAD

**Issue by rodgermoore** [log2timeline/plaso#267] opened 2015-07-16 15:07 UTC
CentOS 7
Plaso 1.3.0 RC3 20150715 
Running *Psort --analysis windows_services -o json_line -w /mnt/hgfs/E/json_lines.json* on Win8 dump. All memory gets filled up and psort proces freezes up.

**Comment by Onager** [comment] 2015-07-16 15:11
Can you provide a little more information:
* Parser counter information from pinfo
* Does the problem occur without the --analysis option?
* Does the problem occur with a different output plugin? (try with -o null)

**Comment by Onager** [comment] 2015-07-16 15:24
I don't see anything obvious that would make the windows_services plugin in particular use up a lot of memory. It's possible that it's something in the analysis plugin subsystem in general. Could you try a different plugin, perhaps tagging?

**Comment by rodgermoore** [comment] 2015-07-17 06:36
* *Psort -o json_line -w /mnt/hgfs/E/json_lines.json* runs without problems on the same image. So without the --analysis windows_services --> no problems.

* Pinfo shows a total parser count of 9402230. 

* Trying the analysis plugin with -o null now

**Comment by Onager** [comment] 2015-07-20 09:46
Sounds like this is a problem with the entire analysis pipeline, not any one plugin in particular. What OS are you running this on?

**Comment by Onager** [comment] 2015-07-20 11:28
I can't replicate this on Ubuntu, or OS X. Memory usage stays consistent, and quite low. I suspect this is something to do with the underlying queues that are backing the analysis process, but I would have expected failures with log2timeline or psort without analysis plugins also. 

Assuming you're running this on a *nix system, what does  ```ipcs -ls``` say your "semaphore max value" is?

**Comment by rodgermoore** [comment] 2015-07-23 00:02
Sorry, abroad for a project till next week. Unable to test. To answer your question: running on CentOS. Its a Windows 8.1 (E01 image) dump I'm processing.

**Comment by rodgermoore** [comment] 2015-07-28 06:43
CentOS running in VMWare 9.04
semaphore max value = 32767

**Comment by Onager** [comment] 2015-07-28 11:46
OK, I'll try and reproduce on centos.

**Comment by rodgermoore** [comment] 2015-07-29 13:27
Its CentOS 7, not 6. Changed in original post.

**Comment by Onager** [comment] 2015-08-09 18:25
Can reproduce on Centos 7. I noticed that Centos is running python 2.7.5, which is older than what we've been testing with. 

Tried the experimental zeromq support I've been working on, and memory usage stayed low, as expected. I suspect some issue with the multiprocessing queue on 2.7.5.

**Comment by rodgermoore** [comment] 2015-08-27 12:42
So if I'm correct defining Python 2.7.10 as a prerequisite for Plaso will solve this Issue? On CentOS7 I can "make altinstall" to use Python 2.7.10 for Plaso, without messing up the OS, and solve this memory issue. Will test this.

**Comment by Onager** [comment] 2015-08-31 09:33
Yes, please give this a try - my current hypothesis is that this will fix the issue.

**Comment by rodgermoore** [comment] 2015-09-01 11:04
Ok will do.

**Comment by rodgermoore** [comment] 2015-09-18 15:23
Installing all the Plaso dependencies under the alt installed Python 2.7.10 version is a tedious task. I don't believe this will be a scenario recommended to users...it's hell ;) I wasn't able to install all the dependencies so I was unable to test if this would solve the issue. Close this issue?

**Comment by joachimmetz** [comment] 2015-09-19 05:18
>  I don't believe this will be a scenario recommended to users...it's hell ;)

The fact that it is tedious does not make it hell (joking or not). You can automate most of the process, see [l2tdevtools](https://github.com/log2timeline/l2tdevtools). We simply can not support every platform out there. That's why we recommend sticking with the recommended platforms.

> I was unable to install the dependencies so I could not test if this would solve the issue. 

That's quite selfish of you to consume significant time of people, to end up calling it hell (joking or not) and then giving up because you're unable to pull it off without going into specifics. IMO you have your self to blame since we explicit mention this in [Releases and roadmap](https://github.com/log2timeline/plaso/wiki/Releases-and-roadmap).

**Comment by rodgermoore** [comment] 2015-09-21 10:10
Wow, that is a powerful reaction Joachim. I didn't meant to disrespect you and / or the people putting all the effort into this project by saying having an alt installed Python 2.7.10 on CentOS7 will give users "hell ;)" to get all the dependencies and Plaso up and running. 

I am aware of l2tdevtools and I tried to use it. Probably because my lack of knowledge on how to configure these tools correctly and developing on Linux in general, I could not get all the dependencies installed correctly using the alt installed Python 2.7.10 version on CentOS7. I really like to test, explore and learn how to use new software being not afraid for some challenges up the road. But this task was so challenging for me I believed this road on CentOS7 was not recommended for other moderate skilled users like me. Saying this does NOT mean you should be supporting every platform out there, I never said that.

Secondly, I too invested a lot of time testing Plaso on CentOS7. As a result of this testing Onager figured out the Psort analysis memory issue might be caused by the native version (2.7.5) of Python being installed on CentOS7. So... did I "consume" significant time of people, ending up calling it hell (joking or not) without benefitting the Plaso project? I don't believe so but I'm sorry if people believe so otherwise.

With this my Plaso exploration on exotic systems comes to an end. From now on I will stay on safe roads only using Plaso on recommended platforms. I sure don't want to consume significant amounts of time of people working on this project when they believe it is not benefitting the project at all.

I wish you guys all the best developing Plaso in the future.

**Comment by joachimmetz** [comment] 2015-09-21 10:28
> Wow, that is a powerful reaction Joachim.

What do you find "powerful" about it? Me telling you straight up that we told you so?

> but this task was so challenging for me I believed this road on CentOS7 was not recommended for other moderate skilled users like me.

Agree, as indicated we know the process can be tedious. However let us know in detail what we can improve. With statements like it is "hell" or it "sucks" we cannot do anything actionable.

> Secondly, I too invested a lot of time testing Plaso on CentOS7. 

I understand but selecting a platform that has significant out of date Python version is not the best option for a project that is heavily under the development.

Compiling Python from source is not a action I can recommend anyone taking, but if you do you typically prepare for these and determine what you get your self into. We cannot look into your head and see what your level of expertise is.

If you really are that motivated to get it to work on CentOs that is commendable, but quitting in the middle and blaming it on the process is not; that is what I'm pointing out as selfish.

**Comment by kiddinn** [comment] 2015-09-22 23:37
I think we should rather discuss the actual issue at hand and not point fingers.

Unfortunately we (as in the plaso developers) do not have any spare cycles to keep debugging this issue. It is hard for us to reproduce this and would require significant resources that unfortunately we don't have ATM.

Since we have limited resources we try to focus our support on three platforms, Ubuntu, Mac OS X and Windows (typically the last released version of said platforms). We love all help we can get from others to get other platforms supported and I really appreciate all of your testing and I hope you don't get discouraged from helping us out in the future.

We can add a note into the documentation that Python 2.7.10 is the preferred or even required Python version to get plaso to run properly, or you can risk issues with too much memory consumption. And yes installing all the dependencies can be quite hard, especially if you are using some custom built binaries, such as a new Python version. And since we cannot really support all those different setups we rely on external contributors that really want to support it to provide that help.

I do appreciate all the help you've done with helping us testing plaso on CentOS but as you noted we may not be able to support the platform (at least not version 7) due to the older Python version that comes pre-installed.

I think in this case we may have to close this bug with the "cannot fix" explanation and try to focus on getting the tool to run better on the platforms we support.

**Comment by kiddinn** [comment] 2015-09-24 20:26
Closing this ticket down as we are unable to dedicate time to work on it.

**Closed by kiddinn** 2015-09-24 20:26 UTC
Labels: bug
