### ISSUE TITLE
SRUM parser causes worker to exceed memory limit

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#3444] opened 2021-01-19 13:02 UTC
**Description of problem:**

Processing a large (~100MB) SRUDB.dat file causes workers to exceed memory limit. Doubling the limit via --worker_memory_limit allowed processing to complete

**Command line and arguments:**

`log2timeline.py --artifact_filters WindowsSystemResourceUsageMonitorDatabaseFile --logfile srum.log srum.plaso /dev/source`

**Source data:**

Not available

**Plaso version:**

20201228

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**

Installed from [GiFT PPA][https://launchpad.net/~gift] stable track

**Debug output/tracebacks:**

<engine> Process: Worker_485 (PID: <PID>) killed because it exceeded the memory limit: 2147473648

**Comment by joachimmetz** [comment] 2021-02-11 12:53
Per chat unable to reproduce issue. Closing for now. Reopen if we can reproduce it

**Closed by joachimmetz** 2021-02-11 12:53 UTC
