### ISSUE TITLE
psort + Elastic output bug

### ISSUE THREAD

**Issue by TofBaasken** [log2timeline/plaso#172] opened 2015-04-21 09:25 UTC
Hello , 
I think there might be a bug when using the Elastic output format . When I try :

```
psort.py -o Elastic --elastic_server_ip 192.168.2.144 --elastic_port 9200 test.dump "date > '2014-01-01' and date < '2014-07-01'"
```

```
[WARNING] Unable to automatically determine data location.
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150420', u'psort.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150420-py2.7.egg/EGG-INFO/scripts/psort.py", line 253, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150420-py2.7.egg/EGG-INFO/scripts/psort.py", line 227, in Main
    counter = front_end.ProcessStorage(options)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150420-py2.7.egg/plaso/frontend/psort.py", line 312, in ProcessStorage
    self._output_format, output_mediator_object, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150420-py2.7.egg/plaso/output/manager.py", line 91, in NewOutputModule
    return output_class(output_mediator, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150420-py2.7.egg/plaso/output/elastic.py", line 64, in __init__
    super(ElasticSearchOutputModule, self).__init__(output_mediator, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150420-py2.7.egg/plaso/output/interface.py", line 44, in __init__
    u', '.join(kwargs.keys())))
ValueError: Unused keyword arguments: output_writer.
```

Thx in advance !

**Comment by TofBaasken** [comment] 2015-04-21 09:38
Took a quick view at the psort.py code and I think the error lies in the if structure on line 302 :)

**Comment by joachimmetz** [comment] 2015-04-21 10:12
Chatted with berggren he'll try to clean this up and add tests.

**Comment by berggren** [comment] 2015-05-20 08:46
I'm not able to reproduce this on my test system. It is possible that this has been resolved with the latest CLI refactoring work.

@TofBaasken can you "git pull" to get the latest code and try again?

**Comment by berggren** [comment] 2015-05-20 08:48
Note: I'm working on a bigger refactoring of the entire elastic output and this will improve the module significantly and be testable etc.

**Comment by kiddinn** [comment] 2015-09-24 20:43
what is the status of this?

**Comment by berggren** [comment] 2016-02-21 15:52
I can't reproduce this and I think this is probably fixed elsewhere in the codebase. Please re-open if there is a way to reproduce this and I'll take a look.

**Closed by berggren** 2016-02-21 15:52 UTC
Labels: bug
