### ISSUE TITLE
psort failed to output evtx logs into timesketch

### ISSUE THREAD

**Issue by 82d28a** [log2timeline/plaso#2450] opened 2019-04-04 16:18 UTC
**Description of problem:**
My apologies, I posted this to timesketch as well since I wasn't sure which was causing it. 

Using plaso: psort.py --output_format timesketch , I am able to import plaso files with "kitchen sink" parsers which includes winevtx type of events. However I am unable to ingest plaso files that only contain winevtx events. I tested one off non-winevtx specific plaso files and had no issues importing and viewing them in timesketch.

There are no errors in the psort output, but there appears to be errors in the standard out of the elastic search.

BTW I did confirm the winevtx plaso file held events by dumping them to csv.

I get this error per event attempted to be imported:

[2019-04-04T15:24:08,095][DEBUG][o.e.a.b.TransportShardBulkAction] [KhAeCt3] [6ba0c523bd2749588851f0f1a2516b7e][0] failed to execute bulk item (index) index {[6ba0c523bd2749588851f0f1a2516b7e][plaso_event][8q3z6GkBGgNwCVQGOP2o], source[n/a, actual length: [2kb], max length: 2kb]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
.....*[TRUNCATED]
Caused by: java.lang.IllegalStateException: No matching token for number_type [BIG_INTEGER]

Thanks

**Command line and arguments:**

log2timeline.py application_evtx.plaso application.evtx --parser winevtx
psort.py --output_format timesketch .....*[TRUNCATED]

**Source data:**
Windows 10 application.evtx
Generated application_evtx.plaso

Plaso version:
plaso-20190131-py3.6-amd64.zip

Operating system Plaso is running on:
Windows 2016 x64

Installation method:
plaso-20190131-py3.6-amd64.zip

**Comment by joachimmetz** [comment] 2019-04-04 16:47
Possible cause of: `Caused by: java.lang.IllegalStateException: No matching token for number_type [BIG_INTEGER]`

Is that the integer value is too large for ElasticSearch to handle: https://github.com/elastic/elasticsearch/issues/11508

Any indication from e.g. dynamic output what the offending value is?

**Comment by 82d28a** [comment] 2019-04-04 18:07
I spot checked a few but could not find it. I will check some more. Just looking at the json dumps the only thing i see that could be it is inode 20 digits long. 

Appreciate the looks.

**Comment by joachimmetz** [comment] 2019-04-04 18:13
Related: https://github.com/google/timesketch/issues/865

**Comment by 82d28a** [comment] 2019-04-09 19:03
Any updates on this? Or workarounds?

**Comment by joachimmetz** [comment] 2019-04-09 22:28
> Any updates on this? Or workarounds?

As indicated by your input it is unclear what the actual issue is. Based on the error there is an assumption, but that is all we have for now. So unless you're able to provide us with more information, the only thing we can do is to see if we can recreate the bigint issue and try to handle that exception condition.

**Comment by joachimmetz** [comment] 2019-05-04 10:42
https://github.com/log2timeline/plaso/pull/2488

**Comment by joachimmetz** [comment] 2019-06-29 10:10
@berggren @Onager any updates on testing this?

**Comment by joachimmetz** [comment] 2020-06-09 19:48
@berggren could this still be an issue with ES7 ?

**Comment by joachimmetz** [comment] 2020-11-16 04:53
Looks similar to https://github.com/log2timeline/plaso/issues/3170, closing

**Closed by joachimmetz** 2020-11-16 04:53 UTC
Labels: Elasticsearch, blocked, output, tools
