### ISSUE TITLE
Import error when loading plaso file into timesketch

### ISSUE THREAD

**Issue by Fryyyyy** [log2timeline/plaso#2686] opened 2019-07-03 02:35 UTC
**Description of problem:**
After generating a .plaso file from a supplied disk image, I am unable to import it into Timesketch.  Wasn't 100% sure whether to log this as a Plaso issue or Timesketch issue.

```2019-06-30 00:47:22,476 [INFO] (MainProcess) PID:29159 <data_location> Determined data location: /usr/share/plaso
2019-06-30 00:47:22,538 [INFO] (MainProcess) PID:29159 <timesketch_out> Timeline name: jenmack
2019-06-30 00:47:22,538 [INFO] (MainProcess) PID:29159 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/serializer.py", line 48, in dumps
    return json.dumps(data, default=self.default, ensure_ascii=False)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/serializer.py", line 34, in default
    raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))
TypeError: Unable to serialize b'BITUpdateDateOfLastCheck' (type: <class 'bytes'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 83, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 69, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 563, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 1032, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 549, in _ExportEvents
    deduplicate_events=deduplicate_events)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 451, in _ExportEvent
    deduplicate_events=deduplicate_events)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 598, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 125, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 78, in WriteEvent
    self.WriteEventBody(event, event_data, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 342, in WriteEventBody
    self._InsertEvent(event, event_data, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 227, in _InsertEvent
    self._FlushEvents()
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 114, in _FlushEvents
    index=self._index_name, request_timeout=self._DEFAULT_REQUEST_TIMEOUT)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 1165, in bulk
    doc_type, '_bulk'), params=params, body=self._bulk_body(body))
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 195, in _bulk_body
    body = '\n'.join(map(self.transport.serializer.dumps, body))
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/serializer.py", line 50, in dumps
    raise SerializationError(data, e)
elasticsearch.exceptions.SerializationError: ({'data_type': 'plist:key', 'sha256_hash': 'ab51393f55f597148bab43e467c02d368dacae166fc983d7da374f4d48013189', 'display_name': 'OS:/Volumes/jenmack_iphone/private/var/mobile/Containers/Data/Application/08E9740C-2852-4229-85F2-58EC115A9257/Library/Preferences/com.nytimes.NYTimes.plist', 'inode': 157030, 'parser': 'plist/plist_default', 'filename': '/Volumes/jenmack_iphone/private/var/mobile/Containers/Data/Application/08E9740C-2852-4229-85F2-58EC115A9257/Library/Preferences/com.nytimes.NYTimes.plist', 'key': b'BITUpdateDateOfLastCheck', 'pathspec': '{"__type__": "PathSpec", "location": "/Volumes/jenmack_iphone/private/var/mobile/Containers/Data/Application/08E9740C-2852-4229-85F2-58EC115A9257/Library/Preferences/com.nytimes.NYTimes.plist", "type_indicator": "OS"}', 'root': '', 'datetime': '0001-01-01T00:00:00+00:00', 'timestamp': -62135596800000000, 'timestamp_desc': 'Content Modification Time', 'message': "b'BITUpdateDateOfLastCheck'", 'tag': [], 'source_short': 'PLIST', 'source_long': 'Plist Entry'}, TypeError("Unable to serialize b'BITUpdateDateOfLastCheck' (type: <class 'bytes'>)",))
```

**Command line and arguments:**

log2timeline.sh --parsers macos jenmack-macos.plaso /Volumes/jenmack_iphone/

**Source data:**

Can share the .plaso file and raw image on request

**Plaso version:**

20190531

**Operating system Plaso is running on:**

OS X 10.14.5

**Installation method:**

 plaso-20190531-macos-10.13.dmg

**Comment by joachimmetz** [comment] 2019-07-03 04:33
Looks like a restriction in the elasticsearch module
```
TypeError("Unable to serialize b'BITUpdateDateOfLastCheck' (type: <class 'bytes'>)",))
```

Could you add the output of `log2timeline.py --troubles`?

**Comment by Fryyyyy** [comment] 2019-07-03 04:57
```$ log2timeline.py --troubles
2019-07-03 04:57:21,795 [INFO] (MainProcess) PID:2294 <data_location> Determined data location: /usr/local/share/plaso
Using Python version 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]

Path: /usr/local/bin/log2timeline.py

plaso - log2timeline version 20190531

Checking availability and versions of dependencies.
[OK]		Crypto version: 2.6.1
[OK]		artifacts version: 20190320
[OK]		bencode
[OK]		biplist
[OK]		certifi version: 2019.03.09
[OK]		chardet version: 3.0.4
[OK]		dateutil version: 2.8.0
[OK]		dfdatetime version: 20190116
[OK]		dfvfs version: 20190609
[OK]		dfwinreg version: 20190329
[OK]		dtfabric version: 20190120
[OK]		elasticsearch version: 6.3.1
[OK]		future version: 0.17.1
[OK]		idna
[OK]		lz4
[OK]		backports.lzma version: 0.0.13
[OK]		pefile version: 2018.8.8
[OK]		psutil version: 5.6.1
[OK]		pybde version: 20190317
[OK]		pyesedb version: 20181229
[OK]		pyevt version: 20181227
[OK]		pyevtx version: 20181227
[OK]		pyewf version: 20140802
[OK]		pyfsapfs version: 20190210
[OK]		pyfsntfs version: 20190104
[OK]		pyfvde version: 20170930
[OK]		pyfwnt version: 20181227
[OK]		pyfwsi version: 20181227
[OK]		pylnk version: 20181227
[OK]		pymsiecf version: 20181227
[OK]		pyolecf version: 20181231
[OK]		pyparsing version: 2.3.1
[OK]		pyqcow version: 20181227
[OK]		pyregf version: 20190303
[OK]		pyscca version: 20181227
[OK]		pysigscan version: 20190103
[OK]		pysmdev version: 20190315
[OK]		pysmraw version: 20181227
[OK]		pytsk3 version: 20190121
[OK]		pytz
[OK]		pyvhdi version: 20181227
[OK]		pyvmdk version: 20181227
[OK]		pyvshadow version: 20190323
[OK]		pyvslvm version: 20181227
[OK]		requests version: 2.21.0
[OK]		six version: 1.12.0
[OK]		pysqlite2.dbapi2 version: 3.24.0
[OK]		urllib3 version: 1.24.1
[OK]		xlsxwriter version: 1.1.5
[OK]		yaml version: 5.1
[OK]		yara version: 3.7.0
[OK]		zmq version: 18.0.1

```

**Comment by Fryyyyy** [comment] 2019-07-03 05:02
Actually, the traceback was copied from the Timesketch error page, so I guess it would use the VMs versions of things:

```2019-07-03 05:02:02,223 [INFO] (MainProcess) PID:30258 <data_location> Determined data location: /usr/share/plaso
Using Python version 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

Path: /usr/bin/log2timeline.py

plaso - log2timeline version 20190531

Checking availability and versions of dependencies.
[OK]		Crypto version: 2.6.1
[OK]		artifacts version: 20190320
[OK]		bencode
[OK]		biplist
[OK]		certifi version: 2017.07.27.1
[OK]		chardet version: 3.0.4
[OK]		dateutil version: 2.6.1
[OK]		dfdatetime version: 20190517
[OK]		dfvfs version: 20190511
[OK]		dfwinreg version: 20190517
[OK]		dtfabric version: 20190120
[OPTIONAL]	elasticsearch version: 5.4.0 is too old, 6.0 or later required.
[OK]		future version: 0.17.1
[OK]		idna
[OK]		lz4
[OK]		lzma
[OK]		pefile version: 2019.4.18
[OK]		psutil version: 5.6.2
[OK]		pybde version: 20190317
[OK]		pyesedb version: 20181229
[OK]		pyevt version: 20181227
[OK]		pyevtx version: 20181227
[OK]		pyewf version: 20140807
[OK]		pyfsapfs version: 20190510
[OK]		pyfsntfs version: 20190104
[OK]		pyfvde version: 20190104
[OK]		pyfwnt version: 20181227
[OK]		pyfwsi version: 20181227
[OK]		pylnk version: 20181227
[OK]		pymsiecf version: 20181227
[OK]		pyolecf version: 20181231
[OK]		pyparsing version: 2.4.0
[OK]		pyqcow version: 20181227
[OK]		pyregf version: 20190303
[OK]		pyscca version: 20181227
[OK]		pysigscan version: 20190103
[OK]		pysmdev version: 20190315
[OK]		pysmraw version: 20181227
[OK]		pytsk3 version: 20190506
[OK]		pytz
[OK]		pyvhdi version: 20181227
[OK]		pyvmdk version: 20181227
[OK]		pyvshadow version: 20190323
[OK]		pyvslvm version: 20181227
[OK]		requests version: 2.20.1
[OK]		six version: 1.12.0
[OK]		sqlite3 version: 3.22.0
[OK]		urllib3 version: 1.24.2
[OK]		xlsxwriter version: 1.1.7
[OK]		yaml version: 4.2
[OK]		yara version: 3.8.1
[OK]		zmq version: 18.0.1
```

**Comment by joachimmetz** [comment] 2019-07-03 05:09
> Actually, the traceback was copied from the Timesketch error page, so I guess it would use the VMs versions of things:

I need the versions of the plaso installation that fails to run.

`[OPTIONAL]	elasticsearch version: 5.4.0 is too old, 6.0 or later required.`

this might be related, could you try updating elasticsearch-py

**Comment by Fryyyyy** [comment] 2019-07-03 05:13
I'll try updating this to 6:

https://github.com/google/timesketch/blob/master/vagrant/bootstrap.sh#L30

**Comment by joachimmetz** [comment] 2019-07-03 05:14
please file an issue / PR against timesketch as well to update this configuration.

**Comment by Fryyyyy** [comment] 2019-07-03 05:19
I'm just testing now, I'll roll it into my current one

**Comment by Fryyyyy** [comment] 2019-07-03 06:28
I think it's also failing on up-to-date ES but the logs seem harder to get.

I see this:

```# cat /var/log/celery/*
[2019-07-03 06:18:53,194: INFO/ForkPoolWorker-2] Index timeline [jenmack] to index [ae1ee0f43d5b46ee82ece56a36efc7e3] (source: plaso)
[2019-07-03 06:19:25,703: INFO/ForkPoolWorker-2] Task timesketch.lib.tasks.run_plaso[ae1ee0f43d5b46ee82ece56a36efc7e3] succeeded in 32.51029919399991s: '2019-07-03 06:18:54,782 [INFO] (MainProcess) PID:29304 <data_location> Determined data location: /usr/share/plaso
2019-07-03 06:18:54,839 [INFO] (MainProcess) PID:29304 <timesketch_out> Timeline name: jenmack
2019-07-03 06:18:54,840 [INFO] (MainProcess) PID:29304 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/serializer.py", line 51, in dumps
    data, default=self.default, ensure_ascii=False, separators=(",", ":")
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/serializer.py", line 36, in default
    raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))
TypeError: Unable to serialize...'```

But no error in the front end, it just spins.

**Comment by joachimmetz** [comment] 2019-07-03 06:56
Ack we'll check with @berggren as well.

**Comment by joachimmetz** [comment] 2020-01-21 06:59
Looks like a duplicate of https://github.com/log2timeline/plaso/issues/2706

**Comment by joachimmetz** [comment] 2020-01-21 07:00
Closing this issue since #2706 was addressed and TimeSketch vagrant configuration was removed if I recall correctly.

**Closed by joachimmetz** 2020-01-21 07:00 UTC
Labels: output
