### ISSUE TITLE
Log2timeline not working in my Mac OS X

### ISSUE THREAD

**Issue by ricci3** [log2timeline/plaso#979] opened 2016-09-04 04:40 UTC
**Plaso version:**
1.4.0

**Operating system Plaso is running on:**
Mac OS X 10.11.6

**Installation method:**
Install of Log2timeline using plaso-1.4.0.dmg through install.sh

**Description of problem:**
After first installation, I cannot have the Log2timeline.py or log2timeline.sh work properly.

Error was found as
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 21, in <module>
    from plaso import dependencies
ImportError: cannot import name dependencies

Then with run_tests.py, then the following was observed:
Checking availability and versions of dependencies.
[OK]		artifacts version: 20160114
[OK]		bencode
[OK]		binplist version: 0.1.5
[OK]		construct version: 2.5.2
[OK]		dateutil version: 2.4.2
[FAILURE]	missing: dfdatetime.
[FAILURE]	dfvfs version: 20150303 is too old, 20160803 or later required.
[FAILURE]	dfwinreg version: 20160116 is too old, 20160320 or later required.
[OK]		dpkt version: 1.8.6.2
[FAILURE]	missing: efilter.
[OK]		hachoir_core version: 1.3.3
[OK]		hachoir_metadata version: 1.3.3
[OK]		hachoir_parser version: 1.3.4
Traceback (most recent call last):
  File "./run_tests.py", line 15, in <module>
    if not plaso.dependencies.CheckTestDependencies():
  File "./plaso/dependencies.py", line 504, in CheckTestDependencies
    if not CheckDependencies(latest_version_check=latest_version_check):
  File "./plaso/dependencies.py", line 441, in CheckDependencies
    verbose_output=verbose_output):
  File "./plaso/dependencies.py", line 196, in _CheckPythonModule
    module_object = _ImportPythonModule(module_name)
  File "./plaso/dependencies.py", line 412, in _ImportPythonModule
    module_object = list(map(__import__, [module_name]))[0]
  File "/Library/Python/2.7/site-packages/IPython/__init__.py", line 43, in <module>
    from .config.loader import Config
  File "/Library/Python/2.7/site-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/Library/Python/2.7/site-packages/IPython/config/application.py", line 31, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/Library/Python/2.7/site-packages/IPython/config/configurable.py", line 33, in <module>
    from IPython.utils.text import indent, wrap_paragraphs
  File "/Library/Python/2.7/site-packages/IPython/utils/text.py", line 28, in <module>
    from IPython.external.path import path
  File "/Library/Python/2.7/site-packages/IPython/external/path/__init__.py", line 2, in <module>
    from path import *
  File "/Library/Python/2.7/site-packages/path.py", line 126, in <module>
    except pkg_resources.DistributionNotFound:
NameError: name 'pkg_resources' is not defined

Then how to make it work in my mac machine?

**Comment by joachimmetz** [comment] 2016-09-04 05:20
```
[FAILURE] missing: efilter.
```

This looks a later version than 1.4.0 ?

**Comment by ricci3** [comment] 2016-09-04 06:16
But I installed that yesterday and using the download version from github.

$ cd /Volumes/plaso-1.4.0/
$ ls
Readme.txt	install.sh	licenses	packages
$ sudo ./install.sh

So what should I do next?

**Comment by joachimmetz** [comment] 2016-09-04 06:23
can you add the download link to be sure; could be something with the build.

**Comment by ricci3** [comment] 2016-09-04 07:10
I downloaded from https://github.com/log2timeline/plaso/releases/download/1.4.0/plaso-1.4.0-macosx-10.11.dmg

**Comment by joachimmetz** [comment] 2016-09-04 07:12
So the output you provided is from a more recent version, by any chance could there be more than 1 plaso installation on your machine?

**Comment by ricci3** [comment] 2016-09-04 07:20
I installed that and there is also another git clone in my machine. So is that I should remove the git clone one or I should remove the plaso-1.4.0?

**Comment by joachimmetz** [comment] 2016-09-04 07:24
They can conflict. Unless you're sufficiently knowledgeable of debugging these conflicts I opt to remove both versions and install the 1.5 RC2 instead: https://github.com/log2timeline/plaso/releases/tag/1.5.0-rc2

**Comment by ricci3** [comment] 2016-09-04 07:30
Please advise how to uninstall the install.sh installed plaso-1.4.0 version?

**Comment by joachimmetz** [comment] 2016-09-04 07:33
it uses the Mac OS X package manager, just as you uninstall any other Max OS X package. Which alas is not at user friendly as on other platforms: http://superuser.com/questions/36567/how-do-i-uninstall-any-apple-pkg-package-file

**Comment by ricci3** [comment] 2016-09-04 08:31
uninstalled the previous one and now installed 1.5RC, but with issues.

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 20, in <module>
    from plaso import dependencies
ImportError: cannot import name dependencies

**Comment by joachimmetz** [comment] 2016-09-04 08:37
What is the command line you are using?

**Comment by ricci3** [comment] 2016-09-04 09:01
both log2timeline.py and log2timeline.sh

$ log2timeline.py
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 20, in <module>
    from plaso import dependencies
ImportError: cannot import name dependencies
$ log2timeline.sh
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 20, in <module>
    from plaso import dependencies
ImportError: cannot import name dependencies

**Comment by joachimmetz** [comment] 2016-09-04 09:11
The log2timeline.sh should provide you with the right python path, log2timeline.py will not work without it:
```
PYTHONPATH=/Library/Python/2.7/site-packages/ /usr/local/bin/log2timeline.py
```

Can you check if there is a plaso sub directory in:
```
ls /Library/Python/2.7/site-packages/
```

**Comment by ricci3** [comment] 2016-09-04 09:31
plaso can be found in the /Library/Python/2.7/site-packages/

$ ls plaso*
plaso-1.2.1_20150327-py2.7.egg

plaso:
__init__.py		dependencies.pyc	output
__init__.pyc		engine			parsers
analysis		filters			preprocessors
analyzers		formatters		serializer
cli			frontend		storage
containers		lib			unix
dependencies.py		multi_processing	winnt

plaso-1.4.1_20160828-py2.7.egg-info:
PKG-INFO		dependency_links.txt
SOURCES.txt		top_level.txt

**Comment by joachimmetz** [comment] 2016-09-04 09:36
So there is your problem, you have another even older version of plaso installed. Remove that one.

**Comment by ricci3** [comment] 2016-09-04 11:47
Removed and reinstalled.

Now, the findings changed.

$ log2timeline.py
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 8, in <module>
    from plaso.cli import storage_media_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/storage_media_tool.py", line 10, in <module>
    from dfvfs.analyzer import fvde_analyzer_helper
ImportError: cannot import name fvde_analyzer_helper
brunhild:~ ricci$ log2timeline.sh
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 8, in <module>
    from plaso.cli import storage_media_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/storage_media_tool.py", line 10, in <module>
    from dfvfs.analyzer import fvde_analyzer_helper
ImportError: cannot import name fvde_analyzer_helper

**Comment by joachimmetz** [comment] 2016-09-04 11:51
* make sure libfvde is installed
* check for multiple dfvfs installations

**Comment by ricci3** [comment] 2016-09-04 12:24
Thx. after cleaning up all the duplicate pkg, Log2timeline error got different problem.

WARNING: unable to determine location of data files.
Checking availability and versions of dependencies.
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 767, in <module>
    if not Main():
  File "/usr/local/bin/log2timeline.py", line 749, in Main
    verbose_output=False):
  File "/Library/Python/2.7/site-packages/plaso/dependencies.py", line 429, in CheckDependencies
    verbose_output=verbose_output):
  File "/Library/Python/2.7/site-packages/plaso/dependencies.py", line 184, in _CheckPythonModule
    module_object = _ImportPythonModule(module_name)
  File "/Library/Python/2.7/site-packages/plaso/dependencies.py", line 400, in _ImportPythonModule
    module_object = list(map(__import__, [module_name]))[0]
  File "/Library/Python/2.7/site-packages/IPython/__init__.py", line 43, in <module>
    from .config.loader import Config
  File "/Library/Python/2.7/site-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/Library/Python/2.7/site-packages/IPython/config/application.py", line 31, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/Library/Python/2.7/site-packages/IPython/config/configurable.py", line 33, in <module>
    from IPython.utils.text import indent, wrap_paragraphs
  File "/Library/Python/2.7/site-packages/IPython/utils/text.py", line 28, in <module>
    from IPython.external.path import path
  File "/Library/Python/2.7/site-packages/IPython/external/path/__init__.py", line 2, in <module>
    from path import *
  File "/Library/Python/2.7/site-packages/path.py", line 126, in <module>
    except pkg_resources.DistributionNotFound:
NameError: name 'pkg_resources' is not defined

**Comment by joachimmetz** [comment] 2016-09-04 12:26
which version of IPython did you install?

**Comment by ricci3** [comment] 2016-09-04 13:03
Seems that ipython-1.2.1-py2.7.egg-info, but how can I check if there are multiple version of iPython installed?

**Comment by joachimmetz** [comment] 2016-09-04 13:10
check the python site-packages path as you did before for plaso

**Comment by ricci3** [comment] 2016-09-04 13:12
Actually, I checked and found the following:

$ ls -la|grep ipython
-rw-r--r--    1 root  wheel     3905 Dec 13  2015 ipython-1.2.1-py2.7.egg-info
drwxr-xr-x   22 root  wheel      748 Jan 24  2016 ipython_genutils
drwxr-xr-x   10 root  wheel      340 Jan 24  2016 ipython_genutils-0.1.0.dist-info

So it should be just one version installed

**Comment by joachimmetz** [comment] 2016-09-04 13:14
can you add a `-i` to your grep
`ls -la|grep ipython`

the presence of ipython_genutils indicates a more recent ipython was installed

**Comment by ricci3** [comment] 2016-09-04 13:32
Yeah. You are right. uninstalled and try install.sh but sill have the following issues:
WARNING: unable to determine location of data files.
Checking availability and versions of dependencies.
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 767, in <module>
    if not Main():
  File "/usr/local/bin/log2timeline.py", line 749, in Main
    verbose_output=False):
  File "/Library/Python/2.7/site-packages/plaso/dependencies.py", line 429, in CheckDependencies
    verbose_output=verbose_output):
  File "/Library/Python/2.7/site-packages/plaso/dependencies.py", line 184, in _CheckPythonModule
    module_object = _ImportPythonModule(module_name)
  File "/Library/Python/2.7/site-packages/plaso/dependencies.py", line 400, in _ImportPythonModule
    module_object = list(map(__import__, [module_name]))[0]
  File "/Library/Python/2.7/site-packages/IPython/__init__.py", line 43, in <module>
    from .config.loader import Config
  File "/Library/Python/2.7/site-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/Library/Python/2.7/site-packages/IPython/config/application.py", line 31, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/Library/Python/2.7/site-packages/IPython/config/configurable.py", line 33, in <module>
    from IPython.utils.text import indent, wrap_paragraphs
  File "/Library/Python/2.7/site-packages/IPython/utils/text.py", line 28, in <module>
    from IPython.external.path import path
  File "/Library/Python/2.7/site-packages/IPython/external/path/__init__.py", line 2, in <module>
    from path import *
  File "/Library/Python/2.7/site-packages/path.py", line 126, in <module>
    except pkg_resources.DistributionNotFound:
NameError: name 'pkg_resources' is not defined

Checked again for the site-packages:

$ ls -la|grep -i ipyt
drwxr-xr-x   28 root  wheel      952 Sep  4 21:28 IPython
-rw-r--r--    1 root  wheel     3905 Dec 13  2015 ipython-1.2.1-py2.7.egg-info

**Comment by joachimmetz** [comment] 2016-09-04 13:35
If I'm not mistaken `pkg_resources` is a dependency introduces in a later version of IPython. Maybe there is an IPython installation in a different location?

**Comment by joachimmetz** [comment] 2016-09-04 13:50
Or alternatively the existing IPython is not cleaned up correctly. Maybe uninstall and completely remove the /Library/Python/2.7/site-packages/IPython directory. If you have used pip to install/update your Python dependencies in the past your Python installation can be easily messed up.

**Comment by ricci3** [comment] 2016-09-04 14:03
using which ipython, I can find python there. But cannot uninstall using pip. Brew cannot find that too. Any other suggestions?

**Comment by joachimmetz** [comment] 2016-09-04 14:09
try a hard remove: `rm -rf /Library/Python/2.7/site-packages/IPython`/

note that using different package managers that are unaware of eachother like pip and brew will mess up your configuration very easily.

**Comment by joachimmetz** [comment] 2016-09-04 14:11
though the cause of the issue might actually be in:
```
/Library/Python/2.7/site-packages/path.py
```

**Comment by joachimmetz** [comment] 2016-09-04 14:15
So it looks IPython 1.2.1: https://github.com/ipython/ipython/tree/rel-1.2.1

imports "path"

https://github.com/ipython/ipython/blob/rel-1.2.1/IPython/external/path/__init__.py

but that imports another module named path on your system that tries to import pkg_resources which is not provided by the OSX version of Python.

**Comment by joachimmetz** [comment] 2016-09-04 14:17
Try removing the package that contains /Library/Python/2.7/site-packages/path.py or remove it manual. There could be more of these files on your system.

**Comment by ricci3** [comment] 2016-09-04 14:55
Sorry that I didn't state that more clearly, I found the ipython in /usr/local/bin/ipython

**Comment by joachimmetz** [comment] 2016-09-04 14:58
same advice: remove all duplicate, broken or other conflicting packages that were installed via pypi or brew.

**Comment by joachimmetz** [comment] 2016-09-04 16:00
I'm closing this issue seen the root cause in non-plaso related. Feel free to re-open if you do find a plaso root-cause.

**Closed by joachimmetz** 2016-09-04 16:00 UTC
Labels: deployment, question

**Comment by ricci3** [comment] 2016-09-05 01:52
Thx.

**Comment by joachimmetz** [comment] 2016-09-07 05:26
Added https://github.com/log2timeline/plaso/wiki/Troubleshooting-Mac-OS-X let me know if you want to add instructions from your recent experiences.
