### ISSUE TITLE
Plaso with ElasticSearch

### ISSUE THREAD

**Issue by beleka** [log2timeline/plaso#1868] opened 2018-05-02 14:14 UTC
Hello, i'm trying to use psort to output my plaso timeline on ELK Stack so i'm able to search and filter in a easier way. The command i use is:

psort.py -o elastic --server 127.0.0.1 --port 9200 --raw_fields --index_name timeline ~/Desktop/elk.plaso

I had an error with network i finally solved, but this one is just impossible, i checked source code, logs, etc. but can't fix it uu. Everyhelp would be appreciated. The error i get is this one:

2018-05-02 14:06:14,738 [INFO] (MainProcess) PID:37433 <elastic> Server address: 127.0.0.1
2018-05-02 14:06:14,738 [INFO] (MainProcess) PID:37433 <elastic> Server port: 9200
2018-05-02 14:06:14,738 [INFO] (MainProcess) PID:37433 <elastic> Index name: timeline
2018-05-02 14:06:14,738 [INFO] (MainProcess) PID:37433 <elastic> Document type: plaso_event
2018-05-02 14:06:14,739 [INFO] (MainProcess) PID:37433 <elastic> Flush interval: 1000
2018-05-02 14:06:14,739 [INFO] (MainProcess) PID:37433 <elastic> Add non analyzed string fields: True
2018-05-02 14:06:14,739 [INFO] (MainProcess) PID:37433 <elastic> Elastic user: None
2018-05-02 14:06:14,739 [INFO] (MainProcess) PID:37433 <elastic> Elastic password: ****
2018-05-02 14:06:14,739 [WARNING] (MainProcess) PID:37433 <psort_tool> Appending to an already existing storage file.
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 68, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 54, in Main
    tool.ProcessStorage()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/psort_tool.py", line 550, in ProcessStorage
    profiling_configuration=configuration.profiling)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 1017, in ExportEvents
    output_module.WriteHeader()
  File "/usr/lib/python2.7/dist-packages/plaso/output/elastic.py", line 318, in WriteHeader
    elastic_user=self._elastic_user)
  File "/usr/lib/python2.7/dist-packages/plaso/output/elastic.py", line 57, in __init__
    self._index = self._EnsureIndexExists(index_name, mapping)
  File "/usr/lib/python2.7/dist-packages/plaso/output/elastic.py", line 95, in _EnsureIndexExists
    index=index_name, body={'mappings': mapping})
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 103, in create
    params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(406, u'Content-Type header [] is not supported')

My psort version is 20180127 and my ELK version is the last one (6.2.0). Thank you everyone for your time ^^

______________________________________________________________________________

EDIT: I was able to make it work. But when i go to http://localhost:9200/_cat/indices?v to check my index from psort i can see this:

health status index      pri rep docs.count docs.deleted store.size pri.store.size
yellow open   timeline    5   1          0            0      1.1kb          1.1kb

I think the docs.count should be higher than 0. I'm studying the source of this problem. In the output it looks like a success, but there isn't any data in the elastic database, so i can't retrieve info from kibana i hope you can help me... u.u Thank you everyone.

**Comment by joachimmetz** [comment] 2018-05-03 04:25
This is a duplicate of https://github.com/log2timeline/plaso/issues/1827

Downgrade to Elasticsearch >= 5.4,< 6.0

6.0 and later are currently not supported by plaso, for when plaso might support 6.0 see: https://github.com/log2timeline/plaso/issues/1653

**Closed by joachimmetz** 2018-05-03 04:25 UTC
