### ISSUE TITLE
Log2timeline failing on parsing prefetch files in VSC.

### ISSUE THREAD

**Issue by timtaylor3** [log2timeline/plaso#2340] opened 2019-02-05 19:27 UTC
**Description of problem:**

Log2time core dumping on parsing prefetch files located in VSC's.  

When running in with -d, I noted the following on non-prefetch files.

 /usr/lib/python2.7/dist-packages/dfvfs/file_io/tsk_file_io.py(183)read()
data = self._tsk_file.read_random(self._current_offset, size)

Error was *** stack smashing detected ***: <unknown> terminated
aborted (core dumped)

Please describe the problem in as much detail as possible.

Parse the prefetch files in VSCs.

**Command line and arguments:**

log2timeline.py --single_process --status_view windows -z UTC --hashers all -hashers_file_size_limit 0 --partition all --vss_store all --log-file=log2timeline.log --parsers prefetch -f triage_filter.txt master_timeline.plaso image_file.e01

**Source data:**

I cannot supply the data.  

The source data was a Windows 10 VMDK, that was converted to an E01 using EnCase 7.12.  The image file verifies.  I have noted that at least one "Commercial" tool is having issues processing one of the VSCs.

According the log, prefetch did process some files.

**Plaso version:**

20190131 - All dependencies are ok or optional. 

**Operating system Plaso is running on:**

Ubuntu 18.04.1 LTS Bionic

Not the operating system of the image/files you're trying to analyze.

Windows 10

**Installation method:**

Installed via the instructions in read the docs.  apt-get install plaso-tools if I remember correctly.

If multiple methods were used please indicate.

**Debug output/tracebacks:**

**Comment by joachimmetz** [comment] 2019-02-05 20:44
instead of sharing the input data, could you share the core dump with me? best to email it to me. This might give me a lead.

Otherwise try peeling of layers of the onion:
* try ewfmount the image see if the issue persist
* try vshadowmount on top of ewfmount and run the log2timeline on the individual problematic snapshot
* try mounting the file system e.g. ntfs3g and run log2timeline on the mounted file system

Out of personal curiosity and to improve libvshadow I would be interested in learning why the VSS (VSC) is giving issues as well (https://github.com/libyal/libvshadow/wiki/Troubleshooting#format-or-behavioral-errors)

**Comment by joachimmetz** [comment] 2019-02-18 06:38
@timtaylor3 friendly ping, were you able to learn more?

**Comment by joachimmetz** [comment] 2019-03-21 09:08
unable to reproduce, due to lack of input, closing. reopen if the issue resurfaces.

**Closed by joachimmetz** 2019-03-21 09:08 UTC
Labels: needs closer look
