### ISSUE TITLE
Replacement Workers sometimes sleep forever

### ISSUE THREAD

**Issue by ktwombley** [log2timeline/plaso#1534] opened 2017-11-29 22:46 UTC
**Plaso version:**

20171118

**Operating system Plaso is running on:**

Ubuntu 14.04 / sift workstation

**Installation method:**

GIFT

**Description of problem:**

When log2timeline kills a Worker it spawns a new one. Some times these new workers do not start working. They show as state Sl+ in `ps`. They show as 'idle' when viewing progress via status window:
```
Worker_24       19134   idle            608.4 MiB       0 (0)           0 (0)
```

When using strace on one of these processes, it's just sitting in a call to futex:
```
root@siftworkstation:/cases/plaso# strace -p 19134
Process 19134 attached
futex(0x1cfef30, FUTEX_WAIT_PRIVATE, 0, NULL
```

Here's my commandline:
`sudo log2timeline.py -d --status_view window --workers 10 --vss_stores all --logfile /cases/plaso/ten_workers.log /cases/plaso/ten_workers.plaso /mnt/ewf_mount1/ewf1`

```
root@siftworkstation:/cases/plaso# grep Worker_24 ten_workers.log
2017-11-29 15:22:31,852 [DEBUG] (MainProcess) PID:18059 <task_engine> Starting worker process Worker_24
2017-11-29 15:22:31,872 [DEBUG] (Worker_24 ) PID:19134 <base_process> Process: Worker_24 (PID: 19134) started
2017-11-29 15:22:31,875 [DEBUG] (Worker_24 ) PID:19134 <base_process> Process: Worker_24 process status RPC server started
2017-11-29 15:22:31,898 [DEBUG] (Worker_24 ) PID:19134 <hashing_analyzer> Got hasher names: sha256
2017-11-29 15:22:31,899 [DEBUG] (Worker_24 ) PID:19134 <worker_process> Worker: Worker_24 (PID: 19134) started
2017-11-29 15:22:31,899 [DEBUG] (Worker_24 ) PID:19134 <worker_process> Worker_24 (PID: 19134) started monitoring task queue.
2017-11-29 15:22:31,899 [DEBUG] (Worker_24 ) PID:19134 <zeromq_queue> Creating socket for Worker_24 task queue
2017-11-29 15:22:31,900 [DEBUG] (Worker_24 ) PID:19134 <zeromq_queue> Worker_24 task queue connected to tcp://127.0.0.1:41306
2017-11-29 15:22:31,900 [DEBUG] (Worker_24 ) PID:19134 <zeromq_queue> Pop on Worker_24 task queue queue, port 41306
```

**Comment by joachimmetz** [comment] 2017-11-30 08:30
Thanks for the report.

To me it seems there are 2 issues that are hard for us to reproduce:
* a worker is being killed; could you try rerunning with `--debug` and see if the debug output log provides more detail
* new workers appear to be stalled; this might be a tricky one to solve, one option is to attach gdb with python support to the stalled process and get a back trace per thread

Let me know if this is something you're familiar with or we should write some instructions on how to do this.

**Comment by Onager** [comment] 2018-11-07 22:58
No reply from report in ~a year, and there have been substantial changes to task processing since Dec 2017. Closing.

**Closed by Onager** 2018-11-07 22:58 UTC
Labels: needs closer look
