### ISSUE TITLE
multiprocessing issue: AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by studiawan** [log2timeline/plaso#4164] opened 2022-07-19 01:28 UTC
**Description of problem:**

Multiprocessing issue when I build plaso from source after adding a plist parser plugin #4155.

**Command line and arguments:**
```
$ conda create --name plaso python=3.9
$ conda activate plaso
(plaso)$ pip install -r requirements.txt
(plaso)$ python setup.py build
(plaso)$ python setup.py install
(plaso)$ psteal.py --debug --source ~/Desktop/artifacts/uji-coba/ -o dynamic -w ~/Desktop/artifacts/uji-coba/timeline.csv
```
**Source data:**

https://github.com/studiawan/plaso/blob/main/test_data/com.apple.CarPlayApp.plist

**Plaso version:**

main branch (20220501)

**Operating system Plaso is running on:**

- macOS Monterey 12.4 Apple M1
- Anaconda virtual environment

**Installation method:**

- installed from plaso main branch
```
(plaso)$ pip install -r requirements.txt
(plaso)$ python setup.py build
(plaso)$ python setup.py install
```

**Debug output/tracebacks:**
```
2022-07-19 01:16:36,951 [INFO] (MainProcess) PID:16423 <data_location> Determined data location: /Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/plaso-20220501-py3.9.egg/share/plaso
2022-07-19 01:16:36,962 [INFO] (MainProcess) PID:16423 <artifact_definitions> Determined artifact definitions path: /Users/hudan/opt/anaconda3/envs/plaso-studiawan/share/artifacts
2022-07-19 01:16:37,661 [WARNING] (MainProcess) PID:16423 <tools> Unable to set memory limit to 4294967296 current limit is 9223372036854775807.
Checking availability and versions of dependencies.
[OK]


Source path             : /Users/hudan/Desktop/artifacts/uji-coba
Source type             : directory
Processing time         : 00:00:00

Processing started.
Traceback (most recent call last):
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/bin/psteal.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20220501', 'psteal.py')
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1459, in run_script
    exec(code, namespace, namespace)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/plaso-20220501-py3.9.egg/EGG-INFO/scripts/psteal.py", line 103, in <module>
    if not Main():
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/plaso-20220501-py3.9.egg/EGG-INFO/scripts/psteal.py", line 79, in Main
    tool.ExtractEventsFromSources()
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/plaso-20220501-py3.9.egg/plaso/cli/extraction_tool.py", line 730, in ExtractEventsFromSources
    processing_status = self._ProcessSources(session, storage_writer)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/plaso-20220501-py3.9.egg/plaso/cli/extraction_tool.py", line 583, in _ProcessSources
    processing_status = extraction_engine.ProcessSources(
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/plaso-20220501-py3.9.egg/plaso/multi_process/extraction_engine.py", line 992, in ProcessSources
    worker_process = self._StartWorkerProcess(process_name)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/site-packages/plaso-20220501-py3.9.egg/plaso/multi_process/extraction_engine.py", line 764, in _StartWorkerProcess
    process.start()
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'

[it is just hang in here, then I press ctrl+C]

^CException ignored in: <module 'threading' from '/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/Users/hudan/opt/anaconda3/envs/plaso-studiawan/lib/python3.9/threading.py", line 1470, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

**Comment by joachimmetz** [comment] 2022-07-19 03:12
Duplicate of: https://github.com/log2timeline/plaso/issues/3164, this is likely anaconda related not plaso related

**Comment by studiawan** [comment] 2022-07-19 04:15
Based on #3164, I will try to build using Docker. I will report this once it is resolved.

**Comment by joachimmetz** [comment] 2022-07-24 07:59
Ack, closing this issue for now, since it looks like a duplicate

**Closed by joachimmetz** 2022-07-24 07:59 UTC
Labels: duplicate, question, deployment, MacOS
