### ISSUE TITLE
Filestat info absent for PE files

### ISSUE THREAD

**Issue by jahrome** [log2timeline/plaso#265] opened 2015-07-16 11:36 UTC
Filestat parser does not appear to run for PE files (exe, dlls), this information is missing for these types of files.  
```
$ psort.py -o l2tcsv --data . plaso.dump -w plaso.csv
$ grep filestat plaso.csv > filestat.csv
```
filestat.csv does not contain any files processed by PE parser.

**Comment by joachimmetz** [comment] 2015-07-16 11:41
How did you invoke log2timeline ?

**Comment by jahrome** [comment] 2015-07-16 12:17
log2timeline.py --logfile plaso.log plaso.dump /dev/xxx

**Comment by joachimmetz** [comment] 2015-07-16 12:53
Having a look.

**Comment by kiddinn** [comment] 2015-07-16 20:54
reproducing on test.vhd (evil) image:

Run FLS on the partition:
```
$ grep mspaint.exe /tmp/evil.fls 
0|/WINDOWS/system32/dllcache/mspaint.exe ($FILE_NAME)|8710-48-5|r/rrwxrwxrwx|0|0|88|1092955526|998589600|1092954421|1092954273
0|/WINDOWS/system32/dllcache/mspaint.exe|8710-128-1|r/rrwxrwxrwx|0|0|339968|1092955526|998589600|1092955526|1092954273
0|/WINDOWS/system32/mspaint.exe ($FILE_NAME)|5107-48-5|r/rrwxrwxrwx|0|0|88|1092954273|998589600|1092954273|1092954273
0|/WINDOWS/system32/mspaint.exe|5107-128-4|r/rrwxrwxrwx|0|0|339968|1093532816|998589600|1093532816|1092954273
```

Run log2timeline and then psort without options:
```
$  grep mspaint.exe /tmp/evil_duplicate.csv | grep filestat
```

Then run psort again, this time with the ```-a``` flag to prevent duplicate events being merged:
```
$ grep mspaint.exe /tmp/evil_all.csv | grep filestat
```

Same, no events, so this is not an issue with the event duplication merging.

```
$ wc -l /tmp/evil.fls 
24909 /tmp/evil.fls
```

And then run mactime as well:
```
$ mactime -b /tmp/evil.fls -d > /tmp/evil.body
$ wc -l /tmp/evil.body 
50735 /tmp/evil.body
```

And compare that to pinfo output:
```
$ pinfo.py /tmp/evil.plaso 
--------------------------------------------------------------------------------
		Plaso Storage Information
--------------------------------------------------------------------------------
...
Parser counter information:
...
	Counter: filestat = 28894
...
```

And comparing that to older runs of the filestat parser this is a major difference in number of events parsed.

Comparing with the test spreadsheet we see:

Version 1.1.0 RC2 - filestat: 49.076 compared to 28.894 now.

**Comment by kiddinn** [comment] 2015-07-16 20:57
ATM running a test to see what files the filestat parser actually sees and then debugging from there.

**Comment by kiddinn** [comment] 2015-07-16 21:11
Ran the tool with the following options:
```
$ log2timeline.py --logfile /tmp/evil3.debug -d /tmp/evil3.plaso test.dd > /tmp/evil3.log
```

And included a print statement in the beginning of the filestat parser to print out all files it would see...just a simple (see added print statements):
```python
  def Parse(self, parser_mediator, **kwargs):
    """...docstring... """
    file_entry = parser_mediator.GetFileEntry()
    stat_object = file_entry.GetStat()
    if not stat_object:
      print u'ERROR NO STAT: {}'.format(parser_mediator.GetDisplayName())
      return

    print parser_mediator.GetDisplayName()
```

Running:
```
$ grep "ERROR NO STAT" /tmp/evil3.log 
$ grep "^TSK" /tmp/evil3.log  | wc -l
7206
$ cat /tmp/evil.body  | awk -F ',' '{print $NF}' | grep -v "FILE_NAME" | sort -u | wc -l
12355
```

Thus it seems the filestat parser saw 7.206 files while there seem to be 12.355 files parsed by FLS.

Let's specifically take a look at one example, the mspaint.exe file... the logs contains this:

```
$ grep mspaint.exe /tmp/evil3.debug 
2015-07-16 14:03:15,793 [DEBUG] (Worker_05 ) PID:11847 <worker> [ProcessFileEntry] parsing file: TSK:/WINDOWS/system32/mspaint.exe
2015-07-16 14:03:15,796 [DEBUG] (Worker_05 ) PID:11847 <worker> [ProcessFileEntry] parsing file: TSK:/WINDOWS/system32/mspaint.exe with parser: pe
2015-07-16 14:03:16,077 [DEBUG] (Worker_05 ) PID:11847 <worker> [ParseFileEntry] done processing: TSK:/WINDOWS/system32/mspaint.exe
2015-07-16 14:03:27,293 [DEBUG] (Worker_08 ) PID:11855 <worker> [ProcessFileEntry] parsing file: TSK:/WINDOWS/system32/dllcache/mspaint.exe
2015-07-16 14:03:27,295 [DEBUG] (Worker_08 ) PID:11855 <worker> [ProcessFileEntry] parsing file: TSK:/WINDOWS/system32/dllcache/mspaint.exe with parser: pe
2015-07-16 14:03:27,648 [DEBUG] (Worker_08 ) PID:11855 <worker> [ParseFileEntry] done processing: TSK:/WINDOWS/system32/dllcache/mspaint.exe

```

Which seems to suggest that the mspaint.exe was picked up by the collector and sent to parsing at one point.

The debug log for the file is:
```
2015-07-16 14:03:15,793 [DEBUG] (Worker_05 ) PID:11847 <worker> [ProcessFileEntry] parsing file: TSK:/WINDOWS/system32/mspaint.exe
2015-07-16 14:03:15,796 [DEBUG] (Worker_05 ) PID:11847 <worker> [ProcessFileEntry] parsing file: TSK:/WINDOWS/system32/mspaint.exe with parser: pe
2015-07-16 14:03:16,077 [DEBUG] (Worker_05 ) PID:11847 <worker> [ParseFileEntry] done processing: TSK:/WINDOWS/system32/mspaint.exe
```

So it seems to be processed by the PE parser and then nothing more, the next file then gets parsed.

Looking at the PE parser...the first thing it does is:

```python
  def ParseFileObject(self, parser_mediator, file_object, **unused_kwargs):
    """Parses a Portable Executable (PE) file-like object.

    Args:
      parser_mediator: A parser mediator object (instance of ParserMediator).
      file_object: A file-like object.

    Raises:
      UnableToParseFile: when the file cannot be parsed.
    """
    pe_data = file_object.read()
    try:
```

That is there is an unbound read operation on the file object... and this is before we ever confirm this is a PE file.... this needs to be fixed.

**Comment by kiddinn** [comment] 2015-07-16 21:11
There is also a blank 

try;
except:

This shuld be more explicit.... what type of exceptions are raised...

**Comment by kiddinn** [comment] 2015-07-16 21:28
The reason is the signature scanner. For PE files it triggers with a signature hit, and thus when scanning a PE file the only parser returned back is the PE parser.

This is most likely a problem in other places as well. Adding an explicit addition of filestat when there is a signature hit.

That resulted in:
```
	Counter: filestat = 49090
```

Comparing the two storage file (before and after change) with pinfo:
```
counter.filestat value mismatch 49090 != 28894.
counter.total value mismatch 170121 != 149925.
```

**Comment by kiddinn** [comment] 2015-07-16 21:31
This also results in values for the mspaint.exe file:
```
$ grep mspaint.exe /tmp/evil4.csv | grep filestat
2001-08-23T18:00:00+00:00,mtime,FILE,NTFS_DETECT mtime,TSK:/WINDOWS/system32/dllcache/mspaint.exe,filestat,TSK:/WINDOWS/system32/dllcache/mspaint.exe,-,1,12714
2001-08-23T18:00:00+00:00,mtime,FILE,NTFS_DETECT mtime,TSK:/WINDOWS/system32/mspaint.exe,filestat,TSK:/WINDOWS/system32/mspaint.exe,-,1,15826
2004-08-19T22:24:33.097260+00:00,crtime,FILE,NTFS_DETECT crtime,TSK:/WINDOWS/system32/mspaint.exe,filestat,TSK:/WINDOWS/system32/mspaint.exe,-,1,51248
2004-08-19T22:24:33.097260+00:00,crtime,FILE,NTFS_DETECT crtime,TSK:/WINDOWS/system32/dllcache/mspaint.exe,filestat,TSK:/WINDOWS/system32/dllcache/mspaint.exe,-,1,51247
2004-08-19T22:45:26.890126+00:00,atime,FILE,NTFS_DETECT atime,TSK:/WINDOWS/system32/dllcache/mspaint.exe,filestat,TSK:/WINDOWS/system32/dllcache/mspaint.exe,-,1,125466
2004-08-19T22:45:26.900140+00:00,ctime,FILE,NTFS_DETECT ctime,TSK:/WINDOWS/system32/dllcache/mspaint.exe,filestat,TSK:/WINDOWS/system32/dllcache/mspaint.exe,-,1,125467
2004-08-26T15:06:56.845078+00:00,atime,FILE,NTFS_DETECT atime,TSK:/WINDOWS/system32/mspaint.exe,filestat,TSK:/WINDOWS/system32/mspaint.exe,-,1,143175
2004-08-26T15:06:56.855092+00:00,ctime,FILE,NTFS_DETECT ctime,TSK:/WINDOWS/system32/mspaint.exe,filestat,TSK:/WINDOWS/system32/mspaint.exe,-,1,143176
```

**Comment by kiddinn** [comment] 2015-07-16 21:36
Created : http://codereview.appspot.com/252310043

**Comment by kiddinn** [comment] 2015-07-16 22:09
This same issue can be found for all other parsers that define a format specification.

As soon as a parser defines a format specification no other parsers are used to attempt to parse that file.

Example, all LNK files, OLECF files, Prefetech, ESEDB, etc are also missing from filestat parser due to this issue.

**Comment by joachimmetz** [comment] 2015-07-17 08:48
@kiddin before closing this issue please also add a test.

**Comment by kiddin** [comment] 2015-07-17 08:56
I think you are trying to mention @kiddinn :)

Angel Terziev
Sofia London Moskva Ltd.



mobile      +359 899 820 102
skype       angel.terziev
e-mail       design@sofialondonmoskva.com
web          http://sofialondonmoskva.com
facebook   http://www.facebook.com/sofialondonmoskva

**Comment by joachimmetz** [comment] 2015-07-17 08:57
> I think you are trying to mention @kiddinn :)

Yeah sorry about that,

**Comment by kiddinn** [comment] 2015-07-17 17:02
CL submitted, this is fixed, I'll keep this open until I've added tests, but removing the 1.3 blocker from the comment.

But if @kiddin wants to contribute the tests, I'm all for it, otherwise I'll do it.

**Comment by Onager** [comment] 2015-11-25 09:46
I think is obsolete, as we've change the way the filestat parser works (it's a file entry parser now).

@joachimmetz @kiddinn Unless you object, I'll close this out.

**Comment by joachimmetz** [comment] 2015-11-25 15:44
Did we add a test for this?

**Closed** 2015-12-12 12:08 UTC
Labels: bug
