### ISSUE TITLE
build_dependencies.py script and libvshadow (pyvshadow)

### ISSUE THREAD

**Issue by dnides** [log2timeline/plaso#97] opened 2015-01-26 04:24 UTC
Windows 8.1 x64, running build_dependicies.py script, appears everything completes as expected with the exception of libvshadow (pyvshadow). I do not see the source folder or the MSI in the output directory. I did a search in the msbuild.log for the string "shadow" and did not see any reference to  libvshadow (pyvshadow). Does this work for anyone else?

**Comment by joachimmetz** [comment] 2015-01-26 11:40
Building libvshadow has worked for me before.

> I did a search in the msbuild.log for the string "shadow" and did not see any reference to libvshadow (pyvshadow)

The msbuild.log is recreated per build of an individual dependency (at least those that use msbuild).

What output does the script return to you.

**Comment by joachimmetz** [comment] 2015-02-05 07:10
Ping @dnides any additional input?

**Comment by dnides** [comment] 2015-02-06 04:44
will try tomorrow.

**Comment by joachimmetz** [comment] 2015-02-06 19:49
Moving dependency script to https://github.com/log2timeline/devtools

**Comment by dnides** [comment] 2015-02-09 01:05
I pulled down latest build.py from devtools location. Below is console output of how far it got.

creating build\bdist.win32
creating build\bdist.win32\msi
creating build\bdist.win32\msi\Lib
creating build\bdist.win32\msi\Lib\site-packages
copying build\lib.win32-2.7\pyregf.pyd -> build\bdist.win32\msi\Lib\site-packages
running install_data
copying ..\msvscpp\Release\libregf.dll -> build\bdist.win32\msi\Lib\site-packages
copying LICENSE.libregf -> build\bdist.win32\msi\Lib\site-packages
running install_egg_info
Writing build\bdist.win32\msi\Lib\site-packages\pyregf-20150105.1-py2.7.egg-info
creating dist
removing 'build\bdist.win32\msi' (and everything under it)
[INFO] Moving: dist\pyregf-20150105.1.win32-py2.7.msi
Failed building: libsigscan

c:\plaso build\plaso\plaso\devtools>


---------below is a snippet from msbuild.log-----------

       "c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\msvscpp\libregf.sln" (default target) (1) ->
       (libfwps target) -> 
         ..\..\libfwps\libfwps_value.c(188): warning C4100: 'ascii_codepage' : unreferenced formal parameter


       "c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\msvscpp\libregf.sln" (default target) (1) ->
       (libfwnt target) -> 
         ..\..\libfwnt\libfwnt_access_control_list.c(278): warning C4102: 'on_error' : unreferenced label
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwnt\libfwnt_access_control_list.c(279): warning C4702: unreachable code


       "c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\msvscpp\libregf.sln" (default target) (1) ->
       (libfwsi target) -> 
         ..\..\libfwsi\libfwsi_users_property_view_values.c(145): warning C4100: 'ascii_codepage' : unreferenced formal parameter
         ..\..\libfwsi\libfwsi_uri_values.c(143): warning C4100: 'ascii_codepage' : unreferenced formal parameter
         ..\..\libfwsi\libfwsi_unknown_0x74_values.c(146): warning C4100: 'ascii_codepage' : unreferenced formal parameter
         ..\..\libfwsi\libfwsi_game_folder_values.c(310): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_file_entry_values.c(153): warning C4100: 'ascii_codepage' : unreferenced formal parameter
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_game_folder_values.c(319): warning C4702: unreachable code
         ..\..\libfwsi\libfwsi_extension_block_0xbeef0019_values.c(333): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_extension_block_0xbeef0014_values.c(438): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_extension_block_0xbeef0006_values.c(325): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_extension_block_0xbeef0003_values.c(293): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_extension_block_0xbeef0000_values.c(361): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_control_panel_values.c(299): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_control_panel_cpl_file_values.c(606): warning C4102: 'on_error' : unreferenced label
         ..\..\libfwsi\libfwsi_compressed_folder_values.c(864): warning C4102: 'on_error' : unreferenced label
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_compressed_folder_values.c(878): warning C4702: unreachable code
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_control_panel_cpl_file_values.c(614): warning C4702: unreachable code
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_control_panel_values.c(308): warning C4702: unreachable code
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_extension_block_0xbeef0000_values.c(370): warning C4702: unreachable code
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_extension_block_0xbeef0003_values.c(302): warning C4702: unreachable code
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_extension_block_0xbeef0006_values.c(333): warning C4702: unreachable code
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_extension_block_0xbeef0014_values.c(447): warning C4702: unreachable code
         c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\libfwsi\libfwsi_extension_block_0xbeef0019_values.c(342): warning C4702: unreachable code


       "c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\msvscpp\libregf.sln" (default target) (1) ->
       (libfdata target) -> 
         ..\..\libfdata\libfdata_btree.c(490): warning C4189: 'number_of_levels' : local variable is initialized but not referenced


       "c:\plaso build\plaso\plaso\devtools\dependencies\libregf-20150105\msvscpp\libregf.sln" (default target) (1) ->
       (regfexport target) -> 
         ..\..\regftools\regfexport.c(129): warning C4189: 'source_length' : local variable is initialized but not referenced

    164 Warning(s)
    0 Error(s)

Time Elapsed 00:01:17.94

**Comment by joachimmetz** [comment] 2015-02-09 07:23
>  pulled down latest build.py from devtools location and ran. Below is console output of how far it got.

Why? You had the original error with the current versions of the scripts. This way you are less likely to reproduce the error. Since I don't have much info to go on, regarding the original report I cannot do much there.

The issue the script reports is:
```
Failed building: libsigscan
```

And the msbuild.log file contains a successful libregf build.

**Comment by dnides** [comment] 2015-02-10 04:47
Because you said "Moving dependency script to https://github.com/log2timeline/devtools". Assumed this is what you wanted since that's all you said. Do you want me to try the build_dependencies.py script again?

The msbuild.log contains no reference to libsigscan. How can I help you debug why it is failing on libsigscan?

**Comment by joachimmetz** [comment] 2015-02-10 18:52
> Because you said "Moving dependency script to https://github.com/log2timeline/devtools"

No it was just an FYI that longer term I'll remove the code from plaso and maintain it there.

> The msbuild.log contains no reference to libsigscan. How can I help you debug why it is failing on libsigscan?

Not much atm, I was more interested in the lack of libvshadow but if the build script did not finish the first time that would explain it.

**Comment by joachimmetz** [comment] 2015-02-24 20:38
Closing issue.

**Closed** 2015-02-24 20:38 UTC
Labels: question
