### ISSUE TITLE
Unhandled exception in storage writer

### ISSUE THREAD

**Issue by kmbMA** [log2timeline/plaso#377] opened 2015-10-15 14:33 UTC
```
2015-10-14 12:58:53,921 [WARNING] (StorageWriter) PID:2384 <multi_process> Unhandled exception in storage writer (PID: 2384).
2015-10-14 12:58:53,926 [ERROR] (StorageWriter) PID:2384 <multi_process> 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/multi_process.py", line 1184, in _Main
    self._storage_writer.WriteEventObjects()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 1645, in WriteEventObjects
    self._Close()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 1675, in _Close
    self._storage_file.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 874, in Close
    self._FlushBuffer()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 431, in _FlushBuffer
    self._WriteStream(stream_name, b''.join(proto_str))
MemoryError
2015-10-14 12:59:17,026 [WARNING] (MainProcess) PID:2379 <multi_process> Killing process: Worker_00 (PID: 2385).
2015-10-14 12:59:17,026 [WARNING] (MainProcess) PID:2379 <multi_process> Killing process: Worker_04 (PID: 2392).
Processing completed with errors.
```

**Comment by joachimmetz** [comment] 2015-10-15 14:55
Which version of plaso is this? 1.3.0 stable or 1.3.1 development - <date> 

MemoryError indicates some memory constraint possibly in Python zipfile, judging by the location where the exception occurs.

**Comment by kmbMA** [comment] 2015-10-15 14:57
This is 1.3.0.

This is only happening when running against E01 files containing a MAC OSX from Yosemite and newer. Not just one, but any that we do.

Thank you,
Kevin Brisson | Corporate Investigative Services | Global Security Organization | Desk 508-898-7085 | Cell 508-331-3347 | Kevin.Brisson@emc.com<mailto:Kevin.Brisson@emc.com> | EMC ² Where Information Lives
Disclaimer: The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by joachimmetz** [comment] 2015-10-15 15:27
So storage is currently undergoing significant changes: https://github.com/log2timeline/plaso/issues/102

At first glance it looks like the serialized data stream might is getting to big. I'll see if I can reproduce this in an isolated test case.

**Comment by kmbMA** [comment] 2015-10-15 17:03
Joachim,

I just tried doing it again and watched the memory utilization. Right before it fails, the memory utilization on this system is at 100% used.

Thank you,
Kevin Brisson | Corporate Investigative Services | Global Security Organization | Desk 508-898-7085 | Cell 508-331-3347 | Kevin.Brisson@emc.com<mailto:Kevin.Brisson@emc.com> | EMC ² Where Information Lives
Disclaimer: The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by Onager** [comment] 2015-11-30 12:09
Assigning to Joachim as he seems to be looking into this.

**Comment by kmbMA** [comment] 2015-12-01 16:26
Daniel,
Thank you for the update.

Thank you,
Kevin Brisson | Corporate Investigative Services | Global Security Organization | Desk 508-898-7085 | Cell 508-331-3347 | Kevin.Brisson@emc.com<mailto:Kevin.Brisson@emc.com> | EMC ² Where Information Lives
Disclaimer: The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by joachimmetz** [comment] 2015-12-30 19:38
The Python zip file has no means to write data in an incremental way.
I've adopted an alternative approach in http://codereview.appspot.com/282020043.
Judging from the implementation of the zipfile write method the memory finger print of the reading the temporary file should be limited.

http://svn.python.org/view/python/trunk/Lib/zipfile.py?view=markup, line 1038

**Comment by joachimmetz** [comment] 2015-12-31 17:17
Some changes regarding memory consumption, I opt to try version 1.4 when released.

**Comment by kmbMA** [comment] 2015-12-31 18:29
Joachim,

Any idea when version 1.4 will be released?

Thank you,
Kevin Brisson | Corporate Investigative Services | Global Security Organization | Desk 508-898-7085 | Cell 508-331-3347 | Kevin.Brisson@emc.com<mailto:Kevin.Brisson@emc.com> | EMC ² Where Information Lives
Disclaimer: The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by joachimmetz** [comment] 2015-12-31 18:34
Soon

**Comment by joachimmetz** [comment] 2016-01-09 18:02
The new approach introduces issues when the storage file is stored in a directory different than the cwd.

**Closed** 2016-01-11 06:24 UTC
Labels: bug, storage
