### ISSUE TITLE
log2timeline running for a long time?

### ISSUE THREAD

**Issue by Rasmus-Riis** [log2timeline/plaso#1151] opened 2017-01-25 07:05 UTC
**Plaso version:**

1.5.1 

**Operating system Plaso is running on:**

Windows 7

**Installation method:**

packaged Release

**Description of problem:**

Log2timeline.exe has been working on a 123 GB image for 6 days and counting

I started it on a thursday expecting it to be done by monday. It's now wednesday and it is still going at it. No errors, but only a few files a second.

**Debug output/tracebacks:**

When I started the run first time I noticed that it was skipping a lot of the files (Timeout from zeromq). So I ran the tool again with the --disable__zeromq switch.

**Source data:**

It is being run against a Windows 7 e01 image. All partitions and all vss

**Comment by joachimmetz** [comment] 2017-01-25 07:13
what type of hardware are you running on? how many workers? How much memory?

**Comment by Rasmus-Riis** [comment] 2017-01-25 07:16
I am working on a Xeon(R) E5-1620 3.5 ghz with 64 GB RAM. The E01 image is
on a 7200 rpm harddisk and the plaso is being generated on SSD.

There are 8 workers in total


Rasmus

**Comment by Rasmus-Riis** [comment] 2017-01-25 07:32
Oh. Almost forgot. The machine started at 100% utilisation but the last
couple of days it has been 25%

**Comment by Rasmus-Riis** [comment] 2017-01-25 07:34
And disk io isn't maxed out at all

**Comment by joachimmetz** [comment] 2017-01-26 06:27
per conversation via mail, I'll try to get you some troubleshooting information later this week that might help pinpoint the root cause

**Comment by joachimmetz** [comment] 2017-01-28 11:42
A couple of things we could try:

profiling overall processing information
```
--profile --profiling-type=processing --profiling-directory=profile
```

profiling parser specific information
```
--profile --profiling-type=parsers --profiling-directory=profile
```

We are continuous working on improving profiling: https://github.com/log2timeline/plaso/issues/1043

**Comment by joachimmetz** [comment] 2017-01-28 11:47
Note to self, add performance troubleshooting info: https://github.com/log2timeline/plaso/wiki/Troubleshooting

**Comment by Rasmus-Riis** [comment] 2017-01-30 08:34
We have started another instance on another machine with the provided switches. How long are we supposed to let it run and should we include "> Output.txt"? It doesn't seem to produce anything in the outputdir

**Comment by treue** [comment] 2017-01-31 06:26
The profiling run  (ie. "--profile --profiling-type=processing --profiling-directory=profile") has now been running for 24+ hours, but unfortunately, nothing has been written into the profile directory: Are you sure that it writes to filesystem on the fly?

The profiling is not much good if we have to wait for log2timeline to finish: That will be weeks, at best...

**Comment by joachimmetz** [comment] 2017-01-31 06:42
it does not write on the fly but if you break plaso (Ctrl^C) once it should cleanly finish and write the profiling files

**Comment by treue** [comment] 2017-01-31 07:13
Ah ok, I have attached the profiling result from the first command:

log2timeline.exe --disable_zeromq --profile --profiling-type=processing --profiling-directory=profile

[processing-Main-processing.txt](https://github.com/log2timeline/plaso/files/741290/processing-Main-processing.txt)

I have started the other profiling test, but as mentioned, it takes about a day for the program to slow to a crawl, and I assume that we have to wait for that before shutting down...

**Comment by joachimmetz** [comment] 2017-01-31 07:24
Thanks for the profiling information

>  and I assume that we have to wait for that before shutting down...
Preferably yes, that is the most representative.

Also know my time at the moment is very limited, but I'll try to have a look as soon as time permits

**Comment by joachimmetz** [comment] 2017-01-31 07:32
```
profile name	number of samples	total CPU time	total system time
merge_check	124939	69530.4097326	69531.7269583
merge	108063	1269.58887307	1269.90303993
process_sources	1	80830.9579023	80832.0220001
get_event_source	186476	9992.39145771	9992.84799051
fill_event_source_heap	124940	9995.9219163	9996.05699348
schedule_task	116928	6.45424628189	6.30501508713
```

merge_check seems to be the largest culprit here roughly 86% of the total processing (process_sources)

**Comment by treue** [comment] 2017-01-31 08:05
Hm. Maybe we could run a fast run and check whether the merge_check part is as large a part of the processing time before the process slows down?

Can you briefly explain what merge_check is?

BTW, I am observing that two workers (out of 7) are far behind in number of events (~5000 events compared to ~5000000 events for the other workers). Is that normal?

**Comment by Onager** [comment] 2017-01-31 09:05
merge_check means the the main process is checking for workers to produce results to merge into the main store. 

It doesn't mean too much in this case, the main process will spend a lot of time here if it's waiting for workers to finish with different files.

What sort of files/directories are the two slow workers working on? What status are the workers reporting? Idle? Collecting?

**Comment by Onager** [comment] 2017-01-31 09:20
By the way, what exactly were the zeromq timeouts mentioned initially? There are two timeouts that could be being hit, one if a worker isn't able to get a new task to process within two seconds (usually because it's waiting for another worker to finish producing some path specs, it just waits a bit longer) and another if the main path spec queue doesn't receive a request within 10 minutes.

Both would point to slow workers, or a delay in the merge-queue-request loop.

**Comment by treue** [comment] 2017-02-01 11:45
Onager, the specific warning is "main_task_queue timeout waiting for a request". I assume that means that it is the latter case...

**Comment by Onager** [comment] 2017-02-01 12:36
OK, that's a slightly different timeout, where no workers have asked for a new piece of work within 4 seconds. This doesn't indicate a major problem.

The 10 minute timeout is actually if the main process has had a full buffer, and no requests for workers. You'd know if you hit this one, there'd be a QueueFull exception, and the main process would die.

**Comment by treue** [comment] 2017-02-01 15:34
hm, alright. The second profiling crashed earlier today, so I'll try to run it once more, but there was an odd observation: The workload used to fall to 25% of the CPU (after being at 100% for many hours), but this didn't happen with profiling. I'm guessing that profiling might take up the remaining CPU power...

**Comment by treue** [comment] 2017-02-02 07:54
The parser profiling doesn't produce any profiling, ie. the profiling directory is empty, even after a clean shutdown. Is that a bug, or should we do something else?

**Comment by Onager** [comment] 2017-07-19 08:53
We've refactored profiling in #1209 and the processing subsystem in #1301. I suspect the various fail cases in the task manager and engine were the cause of the issues originally reported. I'm closing this out as obsolete, but please open a new issue if you have similar issues.

**Closed by Onager** 2017-07-19 08:53 UTC
Labels: question
