### ISSUE TITLE
"Unable to retrieve stat object with error: [Errno 2] No such file or directory" when parsing Linux volume

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#84] opened 2015-01-15 06:27 UTC
Attempting to parse a Linux volume (specifically, Ubuntu 14, which is a Volume Snapshot from AWS) using log2timeline.py and I get a constant stream of the titled errors until "completion" (though sometimes it never completes as I also have an issue with Workers as stated in Issue #49 as well). Even when I do get a resulting zip file as the dump, psort just yields garbage output, no matter the output plugin selected. This occurs with both plaso back-end 1.2.1_20141220 and 1.2.0. 

Full errors are like the following:

```
2015-01-14 06:16:34,220 [WARNING] (CollectionProcess) PID:23200 <collector> Unable to process file: type: OS, location: /mnt/point/etc/alternatives/rview; with error: Unable to retrieve stat object with error: [Errno 2] No such file or directory: '/mnt/point/etc/alternatives/rview'
```

Though I get the above errors, the referenced files are actually accessible at the path listed and I'm able to do a successful 'stat <path_to_file>'.

**Comment by joachimmetz** [comment] 2015-01-15 07:19
You mention parsing a "Linux volume" I assume you mean a storage media image containing a volume with an ext file system? If so which version of ext? Based on you error output though it looks like a mounted file system? Can you maybe add the command and arguments you are running.

**Comment by jpoling-dswrx** [comment] 2015-01-15 15:54
First off, thanks for the incredibly quick response. 

Yes, it is an ext4 file system. The AWS volume I'm analyzing has been attached to the AWS analysis instance as a block device, of which I'm mounting as a filesystem. 

sudo mount -r ro,loop,noexec /dev/<device> /mnt/<fs>
sudo log2timeline.py temp.dump /mnt/<fs>

**Comment by joachimmetz** [comment] 2015-01-16 07:33
At first glance I see no reason why the errors are happening. To narrow things down a bit:

* Is a os.stat from Python (on what appears a directory) possible at all?
* anything in dmegs or /var/log/messages (or equiv) that might indicate an underlying root cause

What can you tell be about the AWS volume itself.

* Can its content change (online) or is it offline?
* Is it mounted over network storage or is it stored locally on the system?

**Comment by jpoling-dswrx** [comment] 2015-01-20 05:34
I believe the error may be in Python's attempt to do the os.stat() on the files. I can do a successful "stat /mnt/x_fs/bin/netcat/". However, launching python interface, importing "os", and performing "os.stat('/mnt/x_fs/bin/netcat/')" yields the same error I am getting from this tool. So, that could be whatever the issue is. Nothing is apparently wrong in dmesg related to this. 

The currently mounted filesystem's contents cannot change (it was a volume snapshot that was then attached to the machine as block device, which was then mounted read-only... you can see my specific commands in my previous post). How exactly it is currently mounted, I would presume, is that the volume snapshot was attached to the current AWS instance I'm utilizing via the "Attach Volume" option with the AWS interface. But, how exactly that is implemented by AWS, I'm uncertain.

Is there anything else I can do to help you troubleshoot?

**Comment by joachimmetz** [comment] 2015-01-20 06:24
```
performing "os.stat('/mnt/x_fs/bin/netcat/')" yields the same error I am getting from this tool
```
This would require a deep dive in Python and AWS to figure out why how directory stats should behave. Can you check if other Python functions like `os.path.isdir('/mnt/x_fs/bin/netcat/')` is working. Maybe check with Amazon tech support (or equiv) why this behavior is showing as well.

```
which was then mounted read-only... you can see my specific commands in my previous post).
```
For context I was more seeing if the same file system is mounted in multiple places, e.g. one on a running VM another read only on your analysis VM. I'm also not familiar with AWS snapshot internals, but e.g. VSS on Windows can change snapshots while "mounted".

**Comment by jpoling-dswrx** [comment] 2015-01-20 16:03
Running an "os.path.isdir('/mnt/x_fs/bin/netcat')" returns "False", and the same goes for "os.path.isdir('/mnt/x_fs/root/')", which should certainly return true if all is working well. Running "os.path.isfile('/mnt/x_fs/bin/netcat')" returns "False" which again is incorrect.

So, obviously something is going awry there. What, I'm not exactly sure. I thought perhaps it could be that it was mounted as a loop device, so I unmounted it and remounted simply "ro". Upon doing this, the "os.path.isdir" function works (whereas before it did not), but os.stat still produces the same error.

**Comment by joachimmetz** [comment] 2015-01-20 16:50
Judging from the failing Python call I think the underlying AWS drivers have a non-typical behavior. As mentioned before this will require a deep dive in Python and AWS for finding an answer. If you have AWS support I would ask them the reason for this behavior first.

**Comment by jpoling-dswrx** [comment] 2015-01-20 16:52
Understood and it's appearing that way. Don't want to trouble you with AWS-side issues, but wanted to ensure it wasn't something on the Plaso side before I went down that route.

Thanks for all of the assistance.

**Comment by joachimmetz** [comment] 2015-01-20 16:53
Please let us know what the outcome of that is. Could be helpful to other people running into similar issues.

**Comment by jpoling-dswrx** [comment] 2015-01-20 16:55
If I can get an answer on it, I absolutely will. 

If you have any specific questions to relay to them, I will do so as well and see how they respond.

**Comment by joachimmetz** [comment] 2015-01-20 21:44
Marking as wontfix for now; since there is not much to fix on the plaso side at the moment.

**Comment by jpoling-dswrx** [comment] 2015-01-20 22:03
Understood and agreed. Thanks for all the help thus far. Will continue investigation on my own.

**Closed** 2015-01-22 07:27 UTC
Labels: wontfix
