### ISSUE TITLE
sccm parser very slow to process unsupported sccm log files (/Windows/CCM/Logs/*.log)

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#2040] opened 2018-07-13 12:25 UTC
**Description of problem:**

Multiple workers hang with 100% CPU when using SCCM parser on log files in /windows/CCM/Logs/ directory.

**Command line and arguments:**

/usr/bin/python /usr/bin/log2timeline.py --single-process --debug /data/out.dump /mnt/Windows/CCM/Logs

**Source data:**

File has been sent to joachim via email

**Plaso version:**

20180630

**Operating system Plaso is running on:**

Arch Linux docker container

**Installation method:**

docker latest

**Debug output/tracebacks:**

```
2018-07-13 12:20:00,898 [DEBUG] (MainProcess) PID:8 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/mnt/Windows/CCM/Logs/AssetAdvisor-20180115-090826.log with parser: pls_recall
2018-07-13 12:20:00,898 [DEBUG] (MainProcess) PID:8 <extractors> pls_recall unable to parse file: OS:/mnt/Windows/CCM/Logs/AssetAdvisor-20180115-090826.log with error: Verification of first record failed.
2018-07-13 12:20:00,898 [DEBUG] (MainProcess) PID:8 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/mnt/Windows/CCM/Logs/AssetAdvisor-20180115-090826.log with parser: sccm
^C^C^C
```

**Comment by bf** [comment] 2018-07-13 12:33
I can confirm that parsing the files with the --parsers="-sccm" option completes successfully.

**Comment by bf** [comment] 2018-07-13 12:40
File has been sent via email to joachim's gmail address.

**Comment by Onager** [comment] 2018-07-13 14:36
Assigning to @joachimmetz since he has the files causing the issue.

**Comment by joachimmetz** [comment] 2018-07-14 11:58
Not a confirmed bug yet, removing bug label and adding the label need closer look

**Comment by joachimmetz** [comment] 2018-07-14 12:02
Log file is encoded as UTF-8 + BOM
```
00000000  ef bb bf 3c 21 5b 4c 4f  47 5b 63 63 70 5f 6d 69  |...<![LOG[ccp_mi|
00000010  63 72 6f 73 6f 66 74 5f  73 69 6c 76 65 72 6c 69  |crosoft_silverli|
```

**Comment by bf** [comment] 2018-07-16 10:48
So @joachimmetz is this a wontfix? Then I will fork and try to fix myself.

**Comment by bf** [comment] 2018-07-16 10:52
I see we are using `pyparsing` library. There is some SO discussion that pyparsing performance can be improved 100x by enabling pypackrat via `ParserElement.enablePackrat()` (see https://stackoverflow.com/questions/21370697/pyparsing-performance-and-memory-usage )

Is that maybe an option?

**Comment by joachimmetz** [comment] 2018-07-16 11:09
> So @joachimmetz is this a wontfix?

Nope. Though this is not a bug (seeing that the code is working as expected) this is something that needs to be addressed (it is not working optimally). However this needs some careful consideration first.

> Then I will fork and try to fix myself.

You're always free to fork and propose a fix.

> Is that maybe an option?

That could be an option. Unsure how much that will help in this case.

**Comment by bf** [comment] 2018-07-16 11:19
Thanks for your assessment. Please consider that in my case 8 threads got stuck at 100% for more than half an hour, with no progress. I'll try to fix it so I can use plaso with the disk at hand.

**Comment by joachimmetz** [comment] 2018-07-16 11:31
> I'll try to fix it so I can use plaso with the disk at hand.

I opt to disable the sccm parser for now as a work around

**Comment by Onager** [comment] 2018-07-31 21:17
@bf could you send me the files causing this issue as well, so I can take a look at this?

**Comment by bf** [comment] 2018-07-31 21:38
What is your email?

**Comment by joachimmetz** [comment] 2018-08-01 03:41
@bf I've forwarded them to @Onager

**Comment by Onager** [comment] 2018-08-01 15:08
Found the problem, the SCCM parser wasn't correctly for timezone offsets <100 minutes.

PR in a moment.

**Comment by joachimmetz** [comment] 2018-08-01 15:14
@Onager please leave this issue open, there is an underlying issue with the selection of the pyparsing grammar and the mutli line parser being very slow.

**Comment by Onager** [comment] 2018-08-01 15:40
@joachimmetz I've opened #2064 for pyparsing improvements (and I have some more PRs incoming). Let's focus this issue on the SCCM problem that triggered slowness in this case.

**Comment by bf** [comment] 2018-08-01 15:53
Thanks for your hard work guys, I really appreciate the plaso project. Unfortunately I cannot really contribute in terms of code, but maybe in future issues. Thank you.

**Closed as completed** 2018-10-11 15:26 UTC
Labels: bug, parsers
