### ISSUE TITLE
issue with psort and 4n6time output

### ISSUE THREAD

**Issue by smclinden** [log2timeline/plaso#409] opened 2015-11-10 15:53 UTC
Applies to version 1.3.1-20151103

I'm seeing an issue with the psort output for 4n6time, namely psort finishes without an error but the resulting output includes only dates from the epoch until 2010. If I output .xlsx, instead, I get all the events from the epoch until the system was imaged in mid-2015. No filters were used. The source is a Windows 2003 Server. This is on Ubuntu LTS 14.04.

I see the same behavior if I used the Windows binaries from the latest release version (1.3).

**Comment by Onager** [comment] 2015-11-11 19:50
The 4n6time output module hasn't been reviewed for a while. I'll take a look when I get a chance.

**Comment by joachimmetz** [comment] 2015-12-03 08:10
> I'm seeing an issue with the psort output for 4n6time

@smclinden In which tool are you seeing this? and with which 4n6time format?

Adding @dnides for input on 4n6time, seeing there is no reference documentation.

**Comment by joachimmetz** [comment] 2015-12-03 08:11
removing milestone not a show stopper for 1.4 release.

**Comment by smclinden** [comment] 2015-12-03 15:06
Not sure that I understand the question "Which tool?" I am seeing it with the 4n6time_SQLite output format for psort and, as I said, I see it with both the Windows and Linux ports.

**Comment by joachimmetz** [comment] 2015-12-03 15:33
> Not sure that I understand the question "Which tool?"

Are you looking at the resulting sqlite database in an sqlite viewer or in 4n6time? If the latter which version?

**Comment by joachimmetz** [comment] 2015-12-29 08:29
@smclinden any updates?

**Comment by joachimmetz** [comment] 2015-12-30 12:33
Just ran:
```
psort.py -o 4n6time_sqlite storage.plaso -w 4n6time.db
```
Ran into a couple of issues on the way.

But got to the point where I could run:
```
sqlite3 4n6time.db
SELECT datetime FROM log2timeline;
```

And the date and time values look all the same.

**Comment by joachimmetz** [comment] 2015-12-30 12:55
I've created http://codereview.appspot.com/276630043 for some issues with creating the indexes.

Closing this issue since I cannot reproduce it. Reopen when you have more details.

**Closed by joachimmetz** 2015-12-30 12:55 UTC
Labels: bug, output
