### ISSUE TITLE
Error: Missing required artifact definition: LinuxDistributionRelease

### ISSUE THREAD

**Issue by Lyro1** [log2timeline/plaso#2168] opened 2018-10-04 14:08 UTC
**Description of problem:**

When I run `log2timeline.py`, I get the following error:
```
Error: Missing required artifact definition: LinuxDistributionRelease
```
I verified my dependencies, and it seems that the version of artifacts is OK.

**Command line and arguments:**

I am calling `log2timeline.py`  with the file `syslog_image.dd` in the test_data folder
```
$ log2timeline.py outputs/result.plaso test_data/syslog_image.dd
ERROR: Missing required artifact definition: LinuxDistributionRelease

usage: log2timeline.py [-h] [-V] [--artifact_definitions PATH]
                       [--custom_artifact_definitions PATH] [--data PATH]
                       [--artifact_filters ARTIFACT_FILTERS]
                       [--artifact_filters_file PATH] [--preferred_year YEAR]
                       [--process_archives] [--skip_compressed_streams]
                       [-f FILE_FILTER] [--hasher_file_size_limit SIZE]
                       [--hashers HASHER_LIST] [--parsers PARSER_LIST]
                       [--yara_rules PATH] [--partitions PARTITIONS]
                       [--offset IMAGE_OFFSET] [--ob IMAGE_OFFSET_BYTES]
                       [--sector_size BYTES_PER_SECTOR] [-z TIMEZONE]
                       [--no_vss] [--vss_only] [--vss_stores VSS_STORES]
                       [--credential TYPE:DATA] [-d] [-q] [--info]
                       [--use_markdown] [--no_dependencies_check]
                       [--logfile FILENAME] [--status_view TYPE] [-t TEXT]
                       [--buffer_size BUFFER_SIZE] [--queue_size QUEUE_SIZE]
                       [--single_process] [--process_memory_limit SIZE]
                       [--temporary_directory DIRECTORY]
                       [--worker_memory_limit SIZE] [--workers WORKERS]
                       [--disable_zeromq] [--sigsegv_handler]
                       [--profilers PROFILERS_LIST]
                       [--profiling_directory DIRECTORY]
                       [--profiling_sample_rate SAMPLE_RATE]
                       [--storage_format FORMAT]
                       [STORAGE_FILE] [SOURCE]
```
And here is my call to check the dependencies
```
$ python utils/check_dependencies.py 
Checking availability and versions of dependencies.
[OK]		Crypto version: 2.6.1
[OK]		artifacts version: 20180827
[OK]		bencode
[OK]		biplist
[OK]		certifi version: 2018.08.24
[OK]		chardet version: 3.0.4
[OK]		dateutil version: 2.7.3
[OK]		dfdatetime version: 20180704
[OK]		dfvfs version: 20180831
[OK]		dfwinreg version: 20180712
[OK]		dtfabric version: 20180808
[OK]		efilter
[OPTIONAL]	elasticsearch version: 6.3.1
[OK]		elasticsearch5 version: 5.5.5
[OK]		future version: 0.16.0
[OPTIONAL]	hachoir_core version: 1.3.3
[OPTIONAL]	hachoir_metadata version: 1.3.3
[OPTIONAL]	hachoir_parser version: 1.3.4
[OK]		idna
[OPTIONAL]	lz4
[OPTIONAL]	lzma version: 0.5.3
[OK]		pefile version: 2018.8.8
[OK]		psutil version: 5.4.7
[OK]		pybde version: 20180806
[OK]		pyesedb version: 20170121
[OK]		pyevt version: 20180317
[OK]		pyevtx version: 20170122
[OK]		pyewf version: 20171104
[OK]		pyfsntfs version: 20170315
[OK]		pyfvde version: 20180108
[OK]		pyfwnt version: 20180117
[OK]		pyfwsi version: 20180630
[OK]		pylnk version: 20180626
[OK]		pymsiecf version: 20170116
[OK]		pyolecf version: 20170825
[OK]		pyparsing version: 2.2.2
[OK]		pyqcow version: 20180831
[OK]		pyregf version: 20170130
[OK]		pyscca version: 20170205
[OK]		pysigscan version: 20170124
[OK]		pysmdev version: 20171112
[OK]		pysmraw version: 20171105
[OK]		pytsk3 version: 20180225
[OK]		pytz version: 2018.5
[OK]		pyvhdi version: 20170223
[OK]		pyvmdk version: 20170226
[OK]		pyvshadow version: 20170902
[OK]		pyvslvm version: 20160110
[OK]		requests version: 2.19.1
[OK]		six version: 1.11.0
[OK]		sqlite3 version: 3.16.2
[OK]		urllib3 version: 1.23
[OK]		xlsxwriter version: 1.1.1
[OK]		yaml version: 3.13
[OK]		yara version: 3.8.1
[OK]		zmq version: 17.1.2
```

**Plaso version:**

20180930

**Operating system Plaso is running on:**

Debian 9

**Installation method:**

Installed with the package `plaso-20180930.tar.gz`

**Comment by joachimmetz** [comment] 2018-10-04 15:14
1. Can you check your Forensic Artifacts yaml files do contain a `LinuxDistributionRelease` definition.
2. Point log2timeline explicitly to the definition files with `--artifact_definitions`

**Comment by Lyro1** [comment] 2018-10-05 07:43
After checking if there was a `LinuxDistributionRelease` definition in the linux.yaml file, I found out that there was none. I will try to clone the github one to test with it.

**Comment by kero99** [comment] 2018-10-08 16:02
Maybe conflict with old version of artifact python package, try to remove old version of artifact and reinstall:
- locate artifacts
- rm -rf /usr/lib/python2.7/dist-packages/artifacts (in my environment)
- Reinstall from https://github.com/ForensicArtifacts/artifacts/releases (sudo python setup.py install)

Best regards!

**Comment by Lyro1** [comment] 2018-10-09 13:51
> Maybe conflict with old version of artifact python package, try to remove old version of artifact and reinstall:
> 
> * locate artifacts
> * rm -rf /usr/lib/python2.7/dist-packages/artifacts (in my environment)
> * Reinstall from https://github.com/ForensicArtifacts/artifacts/releases (sudo python setup.py install)
> 
> Best regards!

I tried to do so, and it does not fix my issue. When I try to reinstall from the latest artifacts release (20180827), I come back to the previous error:

```
ERROR: Missing required artifact definition: LinuxDistributionRelease
```

But when I search in the `data/linux.yaml` file, I find this definition

```
---
name: LinuxDistributionRelease
doc: Linux distribution release information of non-LSB compliant systems.
sources:
- type: FILE 
   attributes:
      paths:
         - '/etc/enterprise-release'
         - '/etc/oracle-release'
         - '/etc/redhat-release'
         - '/etc/system-release'
provides: [os_release, os_major_version, os_minor_version]
labels: [Software]
supported_os: [Linux]
```

I call the command like so:
```
log2timeline.py test.plaso plaso-20180930/test_data/syslog_image.dd --artifact_definitions artifacts-20180827
```
since my folder looks like the following:
```
.
- plaso-20180930/
- artifacts-2080827/
```

**Comment by LawrenceRRogers** [comment] 2019-01-11 16:37
Please note that the new artifacts 20190111 appears to have the same problem. Please see https://forensics.cert.org/repository/ByPackage/plaso.html for how I fixed this for pals 20181219 for Fedora 24 and 25 and CentOS/RHEL 7.

**Comment by joachimmetz** [comment] 2019-01-12 06:17
@LawrenceRRogers could you be more specific what issue you encountered and what steps lead up to that issue.

**Comment by joachimmetz** [comment] 2019-01-13 09:30
I've been able to reproduce this for 20190111, the artifacts has a data subdirectory to many in the setup.py installation path. I'll make the necessary changes. Closing this issue.

**Closed by joachimmetz** 2019-01-13 09:30 UTC
Labels: deployment, pending input reporter, question

**Comment by roddines** [comment] 2019-04-17 05:20
Still getting this in latest

**Comment by joachimmetz** [comment] 2019-04-17 06:05
`AssertionError: "Missing source path." does not match "Unable to read artifact definitions from: /usr/share/artifacts with error: After: WindowsPendingFileRenames Invalid artifact definition: WindowsPersistenceMechanisms returned_types no longer supported."`

It looks like your installation contains an older version of the artifact definitions

**Comment by roddines** [comment] 2019-04-17 07:13
No, I don't think so, I explicitly did as Kero99 suggested and removed any remnants then reinstalled artifacts-20190320

**Comment by roddines** [comment] 2019-04-17 07:16
Please be more specific how to do this?? 

> note that the tool checks for the latest artifacts module, not for the definitions. You need to point log2timeline.py or psteal.py to the path containing up to date artifact definitions.<

**Comment by joachimmetz** [comment] 2019-04-17 07:19
returned_types was removed in 
https://github.com/ForensicArtifacts/artifacts/commit/ec1c547515216bedf629f26aef6f66900ea4e4ab on March 1 

The 20190320 release is from March 20, https://github.com/ForensicArtifacts/artifacts/releases

Can you check /usr/share/artifacts/windows.yaml if `WindowsPersistenceMechanisms` matches that of https://github.com/ForensicArtifacts/artifacts/blob/master/data/windows.yaml#L1215

**Comment by joachimmetz** [comment] 2019-04-17 07:23
> Please be more specific how to do this??

if you run `log2timeline.py --help` it says:

```
...
data location arguments:
  --artifact_definitions PATH, --artifact-definitions PATH
                        Path to a directory containing artifact definitions,
                        which are .yaml files. Artifact definitions can be
                        used to describe and quickly collect data of interest,
                        such as specific files or Windows Registry keys.
...
```

**Comment by joachimmetz** [comment] 2019-04-18 03:59
I was able to reproduce the WindowsPersistenceMechanisms errir with an older version of the artifacts definitions. Pointing log2timeline.py to the right directory with `--artifact_definitions` solved it for me.
