### ISSUE TITLE
Psort AttributeError

### ISSUE THREAD

**Issue by yuval96** [log2timeline/plaso#214] opened 2015-06-01 08:01 UTC
Hello,
I'm using plaso v. 1.2.0. While trying to create a csv output file, I encounter the following error:

```
C:\Windows\system32>C:\Users\Cyber\Downloads\plaso-1.2.0-win-amd64-vs2010\plaso\
psort.exe -o L2tcsv  -w C:\output4.csv C:\output.dump
Traceback (most recent call last):
  File "<string>", line 761, in <module>
  File "<string>", line 735, in Main
  File "<string>", line 361, in ParseStorage
  File "c:\Projects\plaso\build\psort\out00-PYZ.pyz\plaso.lib.output", line 295,
 in __exit__
  File "c:\Projects\plaso\build\psort\out00-PYZ.pyz\plaso.lib.output", line 288,
 in End
  File "c:\Projects\plaso\build\psort\out00-PYZ.pyz\plaso.lib.output", line 255,
 in Flush
  File "c:\Projects\plaso\build\psort\out00-PYZ.pyz\plaso.output.l2t_csv", line
59, in WriteEvent
  File "c:\Projects\plaso\build\psort\out00-PYZ.pyz\plaso.output.l2t_csv", line
127, in EventBody
  File "c:\Projects\plaso\build\psort\out00-PYZ.pyz\plaso.output.helper", line 4
4, in GetLegacy
AttributeError: 'EventObject' object has no attribute 'timestamp_desc'
```

I would like to mention that I've searched a solution online before posting this question, including in GitHub, and haven't found a solution.
Thank you.

**Comment by joachimmetz** [comment] 2015-06-01 08:17
Duplicate of: https://github.com/log2timeline/plaso/issues/141

**Comment by joachimmetz** [comment] 2015-06-01 08:18
I opt to try the development version of plaso or wait for the next release which is hopefully we get out a release candidate soon.

**Closed by joachimmetz** 2015-06-01 08:18 UTC
Labels: duplicate

**Comment by yuval96** [comment] 2015-06-01 08:19
I have read #141 and did not find it helpfull

**Comment by joachimmetz** [comment] 2015-06-01 08:20
What were you expecting that might have helped you?

**Comment by yuval96** [comment] 2015-06-01 08:28
Can you refer me to a guide that explains how to install the use the development version properly?
I don't have experiment in using this kind of software, and found it a bit too complicated for me after trying for several hours to install the development & dependencies and so on...
Thank you.

**Comment by joachimmetz** [comment] 2015-06-01 08:31
You can find all the information on how to install the development version and dependencies here: https://github.com/log2timeline/plaso/wiki

> I don't have experiment in using this kind of software, and found it a bit too complicated for me after trying for several hours to install the development & dependencies and so on...

Then I opt waiting for the next release.

**Comment by yuval96** [comment] 2015-06-01 08:43
thank you
