### ISSUE TITLE
SIFT: no such parser presets file: /usr/share/plaso/presets.yaml

### ISSUE THREAD

**Issue by dougkoster** [log2timeline/plaso#2350] opened 2019-02-15 18:12 UTC
I have a fresh SIFT VM running on 16.04. I installed Plaso using the following commands: 

sudo apt-get update
sudo apt-get install python-plaso plaso-tools

My install appeared to be successful. 
# log2timeline.py -V
plaso - log2timeline version 20190131

When I try and do a test run I get an error message about a missing yaml file:
root@siftworkstation -> /u/s/pytan 
# log2timeline.py /tmp/plaso_test.dump /mnt/hgfs/D_DRIVE/Test\ Images/xp\ dblake.dd 
2019-02-15 17:45:39,851 [INFO] (MainProcess) PID:23109 <data_location> Determined data location: /usr/share/plaso
ERROR: No such parser presets file: /usr/share/plaso/presets.yaml.

I looked at the files on GitHub and didn't see the file presets.yaml.

**Comment by s4parke** [comment] 2019-02-16 05:42
**+1 --  Steps to reproduce:**
1. Install latest apt package (Ubuntu 16.04 / SIFT Workstation)
`$ sudo apt-get update && sudo apt-get install plaso-tools`
 
2. Run command with no args
`$ log2timeline.py `
`  2019-02-15 23:45:39,851 [INFO] (MainProcess) PID: ... location: /usr/share/plaso`
`   ERROR: No such parser presets file: /usr/share/plaso/presets.yaml`

**Workaround:** Copy the file `/master/test_data/presets.yaml` to `/usr/share/plaso/`.

**Comment by joachimmetz** [comment] 2019-02-16 07:30
I'm unable to reproduce this when I install plaso from the GIFT PPA on a 16.04 amd64 live CD (without SIFT).

Can you check if the plaso-data package is installed.

**Comment by joachimmetz** [comment] 2019-02-16 07:32
> I looked at the files on GitHub and didn't see the file presets.yaml.

presets.yaml can be found under data https://github.com/log2timeline/plaso/tree/master/data

**Comment by dougkoster** [comment] 2019-02-16 19:54
Thanks...that fixed the issue.

**Comment by s4parke** [comment] 2019-02-17 00:16
@joachimmetz :
> I'm unable to reproduce this when I install plaso from the GIFT PPA (stable track) on a 16.04 amd64 live CD (without SIFT)

I can only produce this error on the _SIFT Workstation virtual machine_ downloaded from the SANS website [(download link)](https://digital-forensics.sans.org/community/downloads).  I do not see the error if I install [SIFT-CLI](https://github.com/sans-dfir/sift-cli#installation) on a clean Ubuntu 16.04 Amazon EC2 machine.   

> Can you check if the plaso-data package is installed.

Yes, at least one version of plaso-data is installed on the SIFT-workstation Virtualbox VM:
<img width="618" alt="screen shot 2019-02-16 at 6 55 13 pm" src="https://user-images.githubusercontent.com/656510/52906560-754d8b00-321c-11e9-88c0-ddab3c7da283.png">

I decided to use SIFT-CLI on Ubuntu instead of the SIFT-workstation VM. :)

**Comment by joachimmetz** [comment] 2019-02-17 07:42
A reason I could think of is that the old version of plaso-data is (gets) installed on SIFT and is not updated.

**Comment by joachimmetz** [comment] 2019-02-17 08:06
> I can only produce this error on the _SIFT Workstation virtual machine_ downloaded from the SANS website [(download link)](https://digital-forensics.sans.org/community/downloads).

Unfortunately the ova is **not** accessible without log-in so I **cannot** confirm how this VM is configured.

**Comment by dougkoster** [comment] 2019-02-17 13:36
I was working from the .ova image.

________________________________

**Comment by joachimmetz** [comment] 2019-03-20 05:12
Made changes https://github.com/log2timeline/plaso/pull/2396 and https://github.com/log2timeline/plaso/pull/2399 to enforce version dependencies of the data files. Closing this issue.

**Closed by joachimmetz** 2019-03-20 05:12 UTC
Labels: dependency, deployment
