### ISSUE TITLE
IOError 13 in Windows packaged release

### ISSUE THREAD

**Issue by KDPryor** [log2timeline/plaso#1009] opened 2016-09-21 15:54 UTC
**Plaso version:**
1.5.0 Win32

**Operating system Plaso is running on:**
Windows 7 32 bit

**Installation method:**
Win 32 packaged release

**Description of problem:**
L2T errors out with permission denied error on every use

**Source data:**

When running log2timeline.exe it errors out each time with this:

C:\Users\Ken\Desktop\plaso>log2timeline --parsers "linux,webhist" \users\ken\desktop\plaso\l2t.dump \users\ken\desktop\plaso\rpi-micro-sd.001

Checking availability and versions of dependencies.
[OK]

The following partitions were found:
Identifier      Offset (in bytes)       Size (in bytes)
p1              4194304 (0x00400000)    1.0GiB / 1.1GB (1081805824 B)
p2              1090519040 (0x41000000) 60.0MiB / 62.9MB (62914560 B)
p3              1157627904 (0x45000000) 6.2GiB / 6.7GB (6668943360 B)
p4              7826571264 (0x1d2800000)        32.0MiB / 33.6MB (33554432 B)

Please specify the identifier of the partition that should be processed.
All partitions can be defined as: "all". Note that you can abort with Ctrl^C.
p3

Source path     : C:\users\ken\desktop\plaso\rpi-micro-sd.001
Source type     : storage media image

Processing started.
2016-09-21 00:11:27,573 [WARNING](MainProcess) PID:3820 <extraction_frontend> A
ppending to an already existing storage file.
2016-09-21 00:11:27,605 [INFO](MainProcess) PID:3820 <engine> Preprocessing det
ected platform: Linux
2016-09-21 00:11:27,776 [INFO](MainProcess) PID:3820 <interface> [PreProcess] S
et attribute: time_zone_str to America/Chicago
2016-09-21 00:11:27,776 [INFO](MainProcess) PID:3820 <extraction_frontend> Sett
ing timezone to: America/Chicago
Worker_00 (PID: 3368) - events produced: 0 - file: TSK:/ - running: True
Worker_01 (PID: 3124) - events produced: 0 - file:  - running: True
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 791, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 288, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 417, in _ScheduleTasks
  File "plaso\multi_processing\task_engine.py", line 221, in _MergeTaskStorage
  File "plaso\storage\zip_file.py", line 3291, in StartMergeTaskStorage
  File "plaso\storage\gzip_file.py", line 305, in __init__
  File "gzip.py", line 34, in open
  File "gzip.py", line 94, in **init**
IOError: [Errno 13] Permission denied: u'\users\ken\desktop\plaso\tmpgwnmvz
\merge\3aa385e09b044ce5b8aebdb8b76640c2.plaso'

Failed to execute script log2timeline

Please describe the source that is causing the issue.

**Comment by Onager** [comment] 2016-09-21 16:20
Is there any software running that might be locking the task result files? Antivirus and backup software would be prime suspects.

One thing that would help is using procmon (from sysinternals) to see what's opening these files.

**Comment by KDPryor** [comment] 2016-09-21 17:18
Starting to wonder if it's a problem with the image itself. I'm getting the same problem on another computer with this image. Will test and report back.

**Comment by cshanahan** [comment] 2016-09-21 18:06
I am experiencing the same behavior.

**Plaso version:**
1.5.0 Win32

**Operating system Plaso is running on:**
Windows 7 64-bit

**Installation method:**
Win 64-bit packaged release

**Source data:**
Three separate tests. Each test was run on different evidence. Each was a single evidence file in EWF format (E01) comprised of a single NTFS volume.

**Description of problem:**
I am testing the 64-bit Windows Plaso v1.5.0 release. I tested Plaso with 3 different images so far and none of my tests have completed without error. For now, I am just doing the "kitchen sink" approach [ log2timeline.exe  evidence.dump  evidence.e01 ]. Most error and lock up soon after I issue the L2T command. On 2 occasions, L2T ran for an hour or so before issuing the same error, seen below. I tried with and without VSS for each evidence image. I even moved the evidence images to the same file system where Plaso is running from, and my file system has plenty of space. No backup software is running on my system. For my next test, I'll disable A/V and try again. I'll report back ASAP.
```
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 791, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 288, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 417, in _ScheduleTasks
  File "plaso\multi_processing\task_engine.py", line 221, in _MergeTaskStorage
  File "plaso\storage\zip_file.py", line 3291, in StartMergeTaskStorage
  File "plaso\storage\gzip_file.py", line 305, in __init__
  File "gzip.py", line 34, in open
  File "gzip.py", line 94, in __init__
IOError: [Errno 13] Permission denied: u'tmpj6xssc\\merge\\21163a9f297f426fbf47406b0fb6e1a4.plaso'
Failed to execute script log2timeline
```

--
Chris

**Comment by cshanahan** [comment] 2016-09-22 01:55
Performed another test this evening using another test evidence file. Same error.

**Plaso version:**
1.5.0 Win64

**Operating system Plaso is running on:**
Windows 8.1 64-bit

**Installation method:**
Win 64-bit packaged release

**Source data:**
A single evidence file in EWF format (E01) comprised of a single NTFS volume.

**Description of problem:**
I performed another test, this time using a different evidence file and a different workstation (Windows 8.1). Same error. No backup software is running on my system and no third-party A/V. Windows Defender Real-Time Protection is disabled.

```
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 791, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 288, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 417, in _ScheduleTasks
  File "plaso\multi_processing\task_engine.py", line 221, in _MergeTaskStorage
  File "plaso\storage\zip_file.py", line 3291, in StartMergeTaskStorage
  File "plaso\storage\gzip_file.py", line 305, in __init__
  File "gzip.py", line 34, in open
  File "gzip.py", line 94, in __init__
IOError: [Errno 13] Permission denied: u'tmpsa2ijb\\merge\\421df48ad6cd40118dd2b682f83d5fe5.plaso'
Failed to execute script log2timeline
```

--
Chris

**Comment by Onager** [comment] 2016-09-22 08:31
I haven't been able to reproduce this, which is frustrating. Some thoughts:

- This doesn't look to be related to the data being processed
- Current assumption is that something is locking the file, whether that's some Plaso component or something else on the system

**Comment by KDPryor** [comment] 2016-09-23 00:48
I've tried several things since my original post. I exported the partition I'm interested from the full disk image but still getting the same result.

**Comment by KDPryor** [comment] 2016-09-23 02:24
I just downloaded version 1.4.0 and it performed perfectly against this image.

Ken

**Comment by joachimmetz** [comment] 2016-09-23 04:58
> I just downloaded version 1.4.0 and it performed perfectly against this image.

this is as expected the issue you describe is something specific to 1.5.0 in combination with Windows.
be warned 1.4.0 has other issues.

**Comment by the-IMOL** [comment] 2016-09-29 20:03
Just to let everyone know, I've experienced the same error. The associated data includes:

**Plaso version:**
1.5.0 Win64

**Operating system Plaso is running on:**
Windows Server 2008 R2 Enterprise 

**Installation method:**
Win 64-bit packaged release

**Source data:**
A 500GB raw DD image file containing a single NTFS volume (Windows 7 Enterprise)

Description of problem:
Like the others above, I'm testing the 64-bit Windows Plaso v1.5.0 release on some case image files. The program ended with the same **[errno 13]** and the message "Failed to execute script log2timeline".

The program ran for about 1.5 - 2 hrs and created a 21MB dump file before stopping at the error message. I'm currently running another test on a Windows 7 Enterprise machine using the Plaso 1.5.0 x64 packaged install release. I'll report back with the results once it finishes.

The error messages produced from THIS particular test included:

[ ...snip... ]
Worker_08 (PID: 1628) - events produced: 25489 - file: TSK:/Program Files (x86)/
Microsoft Office/CLIPART/PUB60COR/SO00197_.WMF - running: True
Worker_09 (PID: 5048) - events produced: 28094 - file: TSK:/Program Files (x86)/
Microsoft Office/CLIPART/PUB60COR/SO00159_.WMF - running: True
Worker_10 (PID: 4548) - events produced: 71529 - file: TSK:/Program Files (x86)/
Microsoft Office/CLIPART/PUB60COR/SO00208_.WMF - running: True
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 791, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 288, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 417, in _ScheduleTasks
  File "plaso\multi_processing\task_engine.py", line 221, in _MergeTaskStorage
  File "plaso\storage\zip_file.py", line 3291, in StartMergeTaskStorage
  File "plaso\storage\gzip_file.py", line 305, in __init__
  File "gzip.py", line 34, in open
  File "gzip.py", line 94, in __init__
IOError: [Errno 13] Permission denied: u'f:\\tmptn_9hn\\merge\\79666b74971f4cf9a
8647165a18204b6.plaso'
Failed to execute script log2timeline

**Comment by the-IMOL** [comment] 2016-09-30 13:19
Note - this is a follow-up from my previous comment. Plaso 1.5.0 errored out again but this time it was a completely different error (although it was generated after only running the command:
_log2timeline.exe --parsers "winevtx"_. The error produced was:

_2016-09-29 22:25:58,315 [WARNING] (MainProcess) PID:15764 <zeromq_queue> main_ta
sk_queue timeout waiting for a request._

I'll open another report under that subject/heading since it's different than the IOerror 13 in this thread.

**Comment by Onager** [comment] 2016-10-03 13:15
A trace from procmon filtering for for FileCreate()s on .plaso files during a log2timeline run would be very helpful in tracking this issue down. I don't have time right at the moment to demonstrate how to do this step by step, but I'll do so later this week if its not clear.

**Comment by KDPryor** [comment] 2016-10-03 16:43
I will try to make time this evening to do that this evening and post the results.

**Comment by the-IMOL** [comment] 2016-10-03 19:04
Are you talking about a full procmon capture file? I can provide data from the the procmon filter but I'll have to set up a separate box to do it which will take some time. The system I'm currently using is full of 'unsanitized' output with host name/domain, case names, etc, I obviously can't provide.

But in general terms, is the attached screenshot what you meant by the procmon filter? If so, I'm curious about the disk.002 targeting. This is only a single 500gb image file (dd format) with the extension ".001", no split files with ".002" and so on. Is this relevant or should be ignored?

![plaso150procmon](https://cloud.githubusercontent.com/assets/16653803/19049933/0f448f2a-8972-11e6-8ebd-04063ddc827f.png)

**Comment by joachimmetz** [comment] 2016-10-03 19:30
> Is this relevant or should be ignored?

This can be safely ignore. Due to your naming convention (extension) dfvfs will look for additional split RAW segment files.

**Comment by Onager** [comment] 2016-10-04 16:06
@the-IMOL not the whole procmon log, just entries relating to files ending with ".plaso".

**Comment by the-IMOL** [comment] 2016-10-04 21:14
There are several hundred thousand log entries related to files ending with ".plaso" so I've pasted the last 100 or so attached at the bottom. But first, here's the window view related to those entries down below:

Worker_01 (PID: 6832) - events produced: 32078 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-s..-jscript9.resources_31bf3856ad364e35_11.2.9600.1
8376_en-us_c42243838d11ebef.manifest - running: True
Worker_02 (PID: 3944) - events produced: 33663 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-rasmontr.resources_31bf3856ad364e35_6.1.7600.16385_
en-us_7bd6d21865c61ce8.manifest - running: True
Worker_03 (PID: 4516) - events produced: 35546 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-r..ry-editor.resources_31bf3856ad364e35_6.1.7600.16
385_en-us_56c62ea31c70474f.manifest - running: True
Worker_04 (PID: 4332) - events produced: 38216 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-remoteassistance-diag_31bf3856ad364e35_6.1.7600.163
85_none_0f7601a1f6f55d23.manifest - running: True
Worker_05 (PID: 3932) - events produced: 34517 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-s..cardgames.resources_31bf3856ad364e35_6.1.7600.16
385_en-us_cece0ab660493710.manifest - running: True
Worker_06 (PID: 3588) - events produced: 35063 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-s..enter-adm.resources_31bf3856ad364e35_6.1.7600.16
385_en-us_dae5b4c8881a63c6.manifest - running: True
Worker_07 (PID: 3484) - events produced: 35036 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-s..chrecognizereng.ale_31bf3856ad364e35_6.1.7600.16
385_en-gb_e3a447542ad2c5da.manifest - running: True
Worker_08 (PID: 5372) - events produced: 38380 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-s..ckgammon-deployment_31bf3856ad364e35_6.1.7600.16
385_none_75a0383d814f991e.manifest - running: True
Worker_09 (PID: 3580) - events produced: 38622 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-s..audiodepthconverter_31bf3856ad364e35_6.1.7601.17
514_none_db147a3bd314ad01.manifest - running: True
Worker_10 (PID: 5332) - events produced: 68001 - file: TSK:/Windows/winsxs/Manifests/amd64_microsoft-windows-s..boxgames-backgammon_31bf3856ad364e35_6.1.7600.16
385_none_668d031845881638.manifest - running: True
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 791, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 288, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 417, in _ScheduleTasks
  File "plaso\multi_processing\task_engine.py", line 221, in _MergeTaskStorage
  File "plaso\storage\zip_file.py", line 3291, in StartMergeTaskStorage
  File "plaso\storage\gzip_file.py", line 305, in __init__
  File "gzip.py", line 34, in open
  File "gzip.py", line 94, in __init__
IOError: [Errno 13] Permission denied: u'f:\\tmpc1hb41\\merge\\b046256a2e9a4fec9
57c40a147f66a41.plaso'
Failed to execute script log2timeline

**Comment by Onager** [comment] 2016-10-10 15:02
Looks like os.rename() isn't atomic, and python still has a lock on the file for a short time after the rename is complete.

We need to not fail if we can't open the task storage, and retry.

**Comment by dc3-plaso** [comment] 2016-10-11 12:46
I'm getting a similar error during the merging of the *.plaso files:

```
File "C:\plaso\plaso\storage\gzip_file.py", line 396, in MergeAttributeContainers
   os.remove(self._path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'X:\\test_image\\tmpqxrprx\\merge\\44f92a1a59c49dc4abc17ec7feec50.plaso'
```

It was running on Windows 7 64bit VM created just to run plaso. 

Perhaps we need synchronization locks for these methods.

**Comment by Onager** [comment] 2017-01-31 15:33
This should be fixed in the current dev version. I haven't been able to test this though, due to other blocking bugs.

**Comment by joachimmetz** [comment] 2017-08-14 07:01
Please try the latest pre-release this should be addressed. Closing this issue.

**Closed by joachimmetz** 2017-08-14 07:01 UTC
Labels: bug, core
