### ISSUE TITLE
Issue processing bodyfile

### ISSUE THREAD

**Issue by jamdunnDFW** [log2timeline/plaso#1760] opened 2018-03-15 22:59 UTC
Log2timeline appears to be unable to process a bodyfile in the latest release version (plaso-20180127). This has been tested on both the Windows and Linux versions of Log2timeline. 

Bodyfiles were generated using analyze-mft.py and mftdump.exe -> parse_mft.py. Have tried the following commands. 

`$log2timeline.py file.plaso mft.body -z [timezone] `
-and-
`$log2timeline.py file.plaso mft.body -z [timezone] --parsers mactime`

**Operating system Plaso is running on:**
Ubuntu 16.04
Windows 10

**Comment by joachimmetz** [comment] 2018-03-16 02:39
What happend if you run log2timeline with the [test bodyfile](https://github.com/log2timeline/plaso/blob/master/test_data/mactime.body) ?

What specific analyzeMFT and mftdump command options are you using?
Also see: https://github.com/log2timeline/plaso/wiki/Tips-and-Tricks#analyzemft-and-plaso

**Comment by joachimmetz** [comment] 2018-03-23 06:44
@jamdunnDFW friendly ping

**Comment by jamdunnDFW** [comment] 2018-03-29 01:52
Apologies for the late response. I finally had a chance to look at this today with the latest Windows build.

1) The test bodyfile exported normally when it was run through log2timeline and psort. All events in the exported timeline were classified as "mactime"; However, when the plaso db was run through pinfo all events were categorized as "N/A". 

Commands used:
`$ log2timeline.exe test.plaso test.body`
`$ psort.exe test.plaso -o l2tcsv -w test.csv` (no issues)
`$ pinfo.exe test.plaso` (all events classified as N/A)

2) When I attempted to merge a bodyfile into an existing plaso db, none of the "mactime" events were included in the output when processed with psort. 

Commands used:
`$ log2timeline.exe test2.plaso test.body` (test2.plaso contained existing data)
`$ psort.exe test2.plaso -o l2tcsv -w test2.csv` (no "mactime" events in output)

**Comment by joachimmetz** [comment] 2018-03-29 05:02
> However, when the plaso db was run through pinfo all events were categorized as "N/A".

This is likely related to: https://github.com/log2timeline/plaso/issues/1687

> When I attempted to merge a bodyfile into an existing plaso db, none of the "mactime" events were included in the output when processed with psort.

I'll have look to see if I can reproduce this

**Comment by joachimmetz** [comment] 2018-05-01 12:59
```
plaso - log2timeline version 20180501

Source path	: mactime.body
Source type	: single file
Processing time	: 00:00:00

Identifier      PID     Status          Memory          Sources         Events          File
Main            9227    completed       104.8 MiB       1 (0)           44 (44)         

Processing completed.
```

```
sh run_pinfo.sh test.plaso

************************** Plaso Storage Information ***************************
            Filename : test.plaso
      Format version : 20180101
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
dda4b077-d19e-4756-ae36-4ad54ab1ec96 : 2018-05-01T12:58:07.565065+00:00
--------------------------------------------------------------------------------

**************** Session: dda4b077-d19e-4756-ae36-4ad54ab1ec96 *****************
                Start time : 2018-05-01T12:58:07.565065+00:00
           Completion time : 2018-05-01T12:58:07.632902+00:00
              Product name : plaso
           Product version : 20180501
    Command line arguments : 
                             plaso/tools/log2timeline.py
                             --artifact_definitions /usr/share/artifacts/
                             --log-file=test.log.gz
                             --profilers=memory,parsers,processing,storage,task_queue
                             --profiling-directory=profile --debug test.plaso
                             plaso/test_data/mactime.body
  Parser filter expression : N/A
Enabled parser and plugins : amcache, android_app_usage, asl_log, bash,
                             bencode, bencode/bencode_transmission,
                             bencode/bencode_utorrent, binary_cookies, bsm_log,
                             chrome_cache, chrome_preferences, cups_ipp,
                             custom_destinations, dockerjson, dpkg, esedb,
                             esedb/file_history, esedb/msie_webcache,
                             esedb/srum, filestat, firefox_cache,
                             firefox_cache2, fsevents, gdrive_synclog, hachoir,
                             java_idx, lnk, mac_appfirewall_log, mac_keychain,
                             mac_securityd, mactime, macwifi,
                             mcafee_protection, mft, msiecf, olecf,
                             olecf/olecf_automatic_destinations,
                             olecf/olecf_default, olecf/olecf_document_summary,
                             olecf/olecf_summary, openxml, opera_global,
                             opera_typed_history, pe, plist, plist/airport,
                             plist/apple_id, plist/ipod_device,
                             plist/macosx_bluetooth,
                             plist/macosx_install_history, plist/macuser,
                             plist/maxos_software_update, plist/plist_default,
                             plist/safari_history, plist/spotlight,
                             plist/spotlight_volume, plist/time_machine,
                             pls_recall, popularity_contest, prefetch,
                             recycle_bin, recycle_bin_info2, rplog, sccm,
                             selinux, skydrive_log, skydrive_log_old,
                             sophos_av, sqlite, sqlite/android_calls,
                             sqlite/android_sms, sqlite/android_webview,
                             sqlite/android_webviewcache, sqlite/appusage,
                             sqlite/chrome_27_history, sqlite/chrome_8_history,
                             sqlite/chrome_cookies,
                             sqlite/chrome_extension_activity,
                             sqlite/firefox_cookies, sqlite/firefox_downloads,
                             sqlite/firefox_history, sqlite/google_drive,
                             sqlite/imessage, sqlite/kik_messenger,
                             sqlite/ls_quarantine,
                             sqlite/mac_document_versions,
                             sqlite/mackeeper_cache, sqlite/safari_history,
                             sqlite/skype, sqlite/twitter_ios,
                             sqlite/zeitgeist, symantec_scanlog, syslog,
                             syslog/cron, syslog/ssh, systemd_journal,
                             trendmicro_vd, usnjrnl, utmp, utmpx, winevt,
                             winevtx, winfirewall, winiis, winjob, winreg,
                             winreg/appcompatcache, winreg/bagmru,
                             winreg/ccleaner, winreg/explorer_mountpoints2,
                             winreg/explorer_programscache,
                             winreg/microsoft_office_mru,
                             winreg/microsoft_outlook_mru,
                             winreg/mrulist_shell_item_list,
                             winreg/mrulist_string,
                             winreg/mrulistex_shell_item_list,
                             winreg/mrulistex_string,
                             winreg/mrulistex_string_and_shell_item,
                             winreg/mrulistex_string_and_shell_item_list,
                             winreg/msie_zone, winreg/mstsc_rdp,
                             winreg/mstsc_rdp_mru, winreg/network_drives,
                             winreg/networks, winreg/userassist,
                             winreg/windows_boot_execute,
                             winreg/windows_boot_verify, winreg/windows_run,
                             winreg/windows_sam_users, winreg/windows_services,
                             winreg/windows_shutdown,
                             winreg/windows_task_cache,
                             winreg/windows_timezone,
                             winreg/windows_typed_urls,
                             winreg/windows_usb_devices,
                             winreg/windows_usbstor_devices,
                             winreg/windows_version, winreg/winlogon,
                             winreg/winrar_mru, winreg/winreg_default,
                             xchatlog, xchatscrollback, zsh_extended_history
        Preferred encoding : UTF-8
                Debug mode : True
               Filter file : N/A
--------------------------------------------------------------------------------

************************* Events generated per parser **************************
Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
            filestat : 3
             mactime : 41
               Total : 44
--------------------------------------------------------------------------------
No errors stored.

No analysis reports stored.
```

**Comment by joachimmetz** [comment] 2018-05-01 13:03
I'm unable to reproduce with current HEAD (version 20180501)

**Comment by joachimmetz** [comment] 2018-05-01 13:09
> When I attempted to merge a bodyfile into an existing plaso db, none of the "mactime" events were included in the output when processed with psort.

```
************************* Events generated per parser **************************
Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
            filestat : 6
             mactime : 41
             winevtx : 1601
               Total : 1648
--------------------------------------------------------------------------------
```

```
grep 'Mactime Bodyfile' output.log 

No hits
```

Able to reproduce, marking as bug.

**Comment by joachimmetz** [comment] 2018-05-01 13:44
added end-to-end test https://codereview.appspot.com/347750043 but requires https://github.com/log2timeline/plaso/issues/1861 to be fully effective

**Comment by joachimmetz** [comment] 2018-05-01 14:12
Looks like this to do is the culprit:
https://github.com/log2timeline/plaso/blob/master/plaso/storage/sqlite/sqlite_file.py#L124

**Comment by joachimmetz** [comment] 2018-05-01 16:04
Fixes committed

**Closed** 2018-05-01 16:04 UTC
Labels: bug, output

**Comment by jamdunnDFW** [comment] 2018-08-05 18:15
Out of curiosity what tool generated the test bodyfile? 

I have tried to use the bodyfile output from mftdump, analyzeMFT, and MFTECmd using the latest version and haven't been able to get Log2timeline to process the data. I am happy to share samples of my output if that helps. 

Being able to identify deleted files and see full file paths really helps when reviewing a timeline.

**Comment by joachimmetz** [comment] 2018-09-17 09:52
@BannersSecret if you can provide me with a redacted line (change paths) of an entry that does not parse that would be useful.

**Comment by BannersSecret** [comment] 2018-09-17 11:53
@joachimmetz Here you go:

From analyzeMFT output:

0|/Program Files (x86)/Common Files/microsoft shared/ink/pt-PT|0|0|0|0|0|1305252850|1305252850|1305252850|1305252850
0|/Program Files (x86)/Common Files/microsoft shared/ink/ro-RO|0|0|0|0|0|1305252850|1305252850|1305252850|1305252850
0|/Program Files (x86)/Common Files/microsoft shared/ink/ru-RU|0|0|0|0|0|1305252850|1305252850|1305252850|1305252850

From TZWorks (same three entries):

0|[root]\Program Files\Common Files\Microsoft Shared\ink\pt-PT:$I30 (dir)|110||0|0|272|1305252850|1305252850|1305252850|1305252850
0|[root]\Program Files\Common Files\Microsoft Shared\ink\ro-RO:$I30 (dir)|111||0|0|272|1200737480|1200737480|1382635687|1200737480
0|[root]\Program Files\Common Files\Microsoft Shared\ink\ro-RO:$I30 (dir)|111||0|0|272|1305252850|1305252850|1305252850|1305252850
0|[root]\Program Files\Common Files\Microsoft Shared\ink\ru-RU:$I30 (dir)|112||0|0|272|1200737480|1200737480|1382635687|1200737480
0|[root]\Program Files\Common Files\Microsoft Shared\ink\ru-RU:$I30 (dir)|112||0|0|272|1305252850|1305252850|1305252850|1305252850

Thanks for your help.

**Comment by jamdunnDFW** [comment] 2018-09-17 15:18
Based on my testing and other issues I have seen escalated I think this may be related to the size of the bodyfile trying to be ingested.

A test I just performed on version 20180630 failed when my bodyfile had 271296 lines, but successfully processed a trimmed down version of the same bodyfile (first 20 lines) after running through the head command. 

Related: https://github.com/log2timeline/plaso/issues/2056

**Comment by jamdunnDFW** [comment] 2018-09-17 15:23
Upon further review my 51MB body file seems to exceed the file size limit in dsv_parser.py

https://codereview.appspot.com/348730043/diff/1/plaso/parsers/dsv_parser.py

**Comment by joachimmetz** [comment] 2018-09-18 04:10
@jamdunnDFW thx for confirming, I was thinking this as well. I'll have a look when time permits. The limit is there to prevent the python csv module consuming vasts amount of memory.

**Comment by jamdunnDFW** [comment] 2018-09-18 07:47
Thanks @joachimmetz.

@BannersSecret I was able to create a workaround by modifying line 49 in dsv_parser.py in the Ubuntu packaged release to a larger size in order to accommodate ingesting a bodyfile.

**Comment by BannersSecret** [comment] 2018-09-18 08:17
@jamdunnDFW That worked perfectly! Thank you!
