### ISSUE TITLE
Unable to output events to json

### ISSUE THREAD

**Issue by rosymac2019** [log2timeline/plaso#2654] opened 2019-06-17 10:48 UTC
I am trying to convert a plaso file of size 35,348 kb into Json file but the output is always a empty file does size of file create an issue in conversion

**Command line and arguments:**

psort.exe -z US/Pacific -o json -w "C:\FINAL_TIMELINE_OUTPUT1.json" "C:\OUTPUT_1.plaso"

**Plaso version:**

 20190531

**Operating system Plaso is running on:**

it is running of windows operating system

**Installation method:**

 installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch

**Comment by joachimmetz** [comment] 2019-06-17 11:51
what does pinfo tell you regarding the number of events in the plaso file?

have you tried other output formats? do they provide more output?

any information in the log files? have you tried debug output to see if there is more information?

**Comment by rosymac2019** [comment] 2019-06-17 13:04
The output of pinfo is

C:\Users\bhuvani\Downloads\plaso-20190531-py3.7-amd64>pinfo.exe "C:\OUTPUT_1.plaso"

************************** Plaso Storage Information ***************************
            Filename : OUTPUT_1.plaso
      Format version : 20190309
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
f62da2b6-7533-41ca-8c3f-fd1a2e25a769 : 2019-06-17T16:07:13.788548+00:00
--------------------------------------------------------------------------------

**************** Session: f62da2b6-7533-41ca-8c3f-fd1a2e25a769 *****************
                Start time : 2019-06-17T16:07:13.788548+00:00
           Completion time : 2019-06-17T17:32:01.547783+00:00
              Product name : plaso
           Product version : 20190531
    Command line arguments : log2timeline.exe C:\OUTPUT_1.plaso
                             C:\Users\bhuvani\Desktop\20170518A10.E01
  Parser filter expression : win7
Enabled parser and plugins : amcache, bencode, bencode/bencode_transmission,
                             bencode/bencode_utorrent, binary_cookies,
                             chrome_cache, chrome_preferences,
                             custom_destinations, czip, czip/oxml, esedb,
                             esedb/file_history, esedb/msie_webcache,
                             esedb/srum, filestat, firefox_cache,
                             gdrive_synclog, java_idx, lnk, mcafee_protection,
                             msiecf, olecf, olecf/olecf_automatic_destinations,
                             olecf/olecf_default, olecf/olecf_document_summary,
                             olecf/olecf_summary, opera_global,
                             opera_typed_history, pe, plist, plist/airport,
                             plist/apple_id, plist/ipod_device,
                             plist/macosx_bluetooth,
                             plist/macosx_install_history, plist/macuser,
                             plist/maxos_software_update, plist/plist_default,
                             plist/safari_history, plist/spotlight,
                             plist/spotlight_volume, plist/time_machine,
                             prefetch, recycle_bin, sccm, skydrive_log,
                             skydrive_log_old, sqlite, sqlite/android_calls,
                             sqlite/android_sms, sqlite/android_webview,
                             sqlite/android_webviewcache, sqlite/appusage,
                             sqlite/chrome_27_history, sqlite/chrome_8_history,
                             sqlite/chrome_autofill, sqlite/chrome_cookies,
                             sqlite/chrome_extension_activity,
                             sqlite/firefox_cookies, sqlite/firefox_downloads,
                             sqlite/firefox_history, sqlite/google_drive,
                             sqlite/hangouts_messages, sqlite/imessage,
                             sqlite/kik_messenger, sqlite/kodi,
                             sqlite/ls_quarantine,
                             sqlite/mac_document_versions,
                             sqlite/mac_knowledgec, sqlite/mac_notes,
                             sqlite/mac_notificationcenter,
                             sqlite/mackeeper_cache, sqlite/safari_history,
                             sqlite/skype, sqlite/tango_android_profile,
                             sqlite/tango_android_tc, sqlite/twitter_android,
                             sqlite/twitter_ios, sqlite/windows_timeline,
                             sqlite/zeitgeist, symantec_scanlog, usnjrnl,
                             winevtx, winfirewall, winjob, winreg,
                             winreg/appcompatcache, winreg/bagmru,
                             winreg/ccleaner, winreg/explorer_mountpoints2,
                             winreg/explorer_programscache,
                             winreg/microsoft_office_mru,
                             winreg/microsoft_outlook_mru,
                             winreg/mrulist_shell_item_list,
                             winreg/mrulist_string,
                             winreg/mrulistex_shell_item_list,
                             winreg/mrulistex_string,
                             winreg/mrulistex_string_and_shell_item,
                             winreg/mrulistex_string_and_shell_item_list,
                             winreg/msie_zone, winreg/mstsc_rdp,
                             winreg/mstsc_rdp_mru, winreg/network_drives,
                             winreg/networks, winreg/userassist,
                             winreg/windows_boot_execute,
                             winreg/windows_boot_verify, winreg/windows_run,
                             winreg/windows_sam_users, winreg/windows_services,
                             winreg/windows_shutdown,
                             winreg/windows_task_cache,
                             winreg/windows_timezone,
                             winreg/windows_typed_urls,
                             winreg/windows_usb_devices,
                             winreg/windows_usbstor_devices,
                             winreg/windows_version, winreg/winlogon,
                             winreg/winrar_mru, winreg/winreg_default
        Preferred encoding : cp1252
                Debug mode : False
          Artifact filters : N/A
               Filter file : N/A
--------------------------------------------------------------------------------
No warnings stored.

No analysis reports stored.

**Comment by rosymac2019** [comment] 2019-06-17 13:09
i tried CSV format, but it gives the empty file even in that case

**Comment by joachimmetz** [comment] 2019-06-17 13:11
Looks like your plaso file might be empty (This might be related to the PyInstaller build). Any indication in the log files generated by log2timeline.exe ?

Possible similar issue: https://github.com/log2timeline/plaso/issues/2555

**Comment by rosymac2019** [comment] 2019-06-17 13:24
the size of plaso file is 35,348
log file data:
2019-06-17 09:07:17,593 [INFO] (MainProcess) PID:7940 <engine> Preprocessing detected operating systems: Windows NT
2019-06-17 09:07:17,595 [INFO] (MainProcess) PID:7940 <extraction_tool> Parser filter expression set to: win7
2019-06-17 10:32:20,464 [INFO] (MainProcess) PID:7940 <zeromq_queue> Queue main_task_queue responder exiting.

**Comment by merciless73** [comment] 2019-06-18 22:42
Just had what appears to be the exact same issue. Fix was to remove the win7 parser. My target E01 was Windows 2012. I assumed the parser wasn't doing an OS check and just tied to the which artifacts would be processed. Still unsure of the underlying mechanism, but removing the win 7 parser results in a plaso file with events for me. Since processing takes a bit this is easier to test on a small folder with a few loose files.

**Comment by joachimmetz** [comment] 2019-06-19 03:52
@merciless73 could you provide debug logs so we can try to determine what is going on

**Comment by merciless73** [comment] 2019-06-19 12:52
To make testing a bit quicker, I switched from running against a full image and began running Plaso against a folder of "loose files" on my Desktop. There are only a couple of LNK files in the folder. Here are my observations:

If I include "--parsers win7" in the command line, the test fails. No events are parsed out. Pinfo lists the enabled parsers, but the logs do not show any parsers being used. 

If I exclude "--parsers win7" from the command line, the test succeeds. Events are parsed out. Pinfo lists the enabled parsers, and the logs show the parsers as well.

Thinking this was the issue, I again ran Plaso against an E01 of a Win2012 server without the "--parsers win7" in the command line. However, again no events were output. Pinfo surprisingly still shows "win7" as the "parser filter expression" although I did not specify this. You explained to me that this is by design as Plaso attempts to identify the target OS and apply the parsers that make sense. 

These tests were originally run on a Win2016 host. I attempted the same test on a Win10 host. I used the same, compiled version of Plaso and ran against LNK files in a folder on my Desktop. The results were the same. Including the "--parsers win7" in the command line results in no event output. Removing it produces events. 

I am attaching the relevant logs from one of the failed test runs (win 2016 host, targeting loose LNK files in a desktop folder".

Thank you.

[test_fail.zip](https://github.com/log2timeline/plaso/files/3306143/test_fail.zip)

**Comment by joachimmetz** [comment] 2019-06-20 18:14
@merciless73 thanks for testing and the necessary details. I've been able to reproduce this on Win10 with a directory as input, tracking this in https://github.com/log2timeline/plaso/issues/2665

**Comment by joachimmetz** [comment] 2019-06-20 18:15
@rosymac2019 could you confirm / deny if you ran log2timeline.py with `--parsers` ?

**Comment by merciless73** [comment] 2019-06-20 22:46
> @rosymac2019 could you confirm / deny if you ran log2timeline.py with `--parsers` ? (based on your pinfo output it does not look like it)

From what I can tell, the issue occurs whenever a "parser preset" is applied. For my case, It didn't matter if I specified '--parsers win 7' or if I left it out and log2timeline applied it due to some form of operating system autodetect. The issue occurred in any situation where the pinfo output contained: "Parser filter expression : win7".

**Comment by joachimmetz** [comment] 2019-06-21 04:15
@merciless73 I need @rosymac2019 input to determine if he might be experiencing a different issue

**Comment by joachimmetz** [comment] 2019-07-13 08:41
No input from original reporter, new version with fix for https://github.com/log2timeline/plaso/issues/2665 has been released. Closing this issue, reopen if new information is available.

**Closed by joachimmetz** 2019-07-13 08:41 UTC
Labels: pyinstaller, question, windows
