### ISSUE TITLE
Plaso Log2timeline 1.4.0 stuck on big files

### ISSUE THREAD

**Issue by sarcarx** [log2timeline/plaso#752] opened 2016-06-28 16:06 UTC
**Plaso version:**

1.4.0 Release

**Operating system Plaso is running on:**

Debian testing

**Installation method:**

installed from OS packages

**Description of problem:**

I am not sure wether or not this is possible, but parsing an entire windows partition takes a lot of time. I noticed the workers that slow the process are the one stuck on files that are big and cannot be processed (pagefile.sys) for example.
If this is the case it might also stop the processing and displays the error that workers were idle for too long. Which would be fine if it just dropped the file and moved on.
Is there a way to impose a maximum file size?
I also saw that sometimes, log2timeline tries to parse a file that it cannot (happened to me for SCCM logs) and just prints an error for each line, is there a way to tell the program to drop the file if it meets too many errors?

**Comment by Onager** [comment] 2016-06-28 19:41
We're aware of these issues, and are planning to address most of them in the upcoming 1.5 release.
One thing that might help is disabling file hashing using --hashers none. This reduce CPU and I/O usage, which can cause Plaso to run slowly and abort on resource constrained systems.

**Comment by sarcarx** [comment] 2016-06-29 08:37
is there also a way to disable parsers? For example I want the windows one but without the winevt parser.

**Comment by joachimmetz** [comment] 2016-06-29 09:48
```
log2timeline.py --help
```

Should provide you the syntax to disable hashers and/or parsers

**Comment by joachimmetz** [comment] 2016-07-02 15:40
> I am not sure wether or not this is possible, but parsing an entire windows partition takes a lot of time.

Have a look at: http://blog.kiddaland.net/2013/02/targeted-timelines-part-i.html

> I noticed the workers that slow the process are the one stuck on files that are big and cannot be processed (pagefile.sys) for example.

Working as intended, large "big" files are hashed by default

> If this is the case it might also stop the processing and displays the error that workers were idle for too long.

Will be fixed by: https://github.com/log2timeline/plaso/issues/338

> Is there a way to impose a maximum file size?

Not at the moment, see suggestion to turn of hashing.

> I also saw that sometimes, log2timeline tries to parse a file that it cannot (happened to me for SCCM logs) and just prints an error for each line, is there a way to tell the program to drop the file if it meets too many errors?

Extraction errors should not be a show stopper, work is in progress to make is less spammy to the output.

Closing this issue.

**Closed by joachimmetz** 2016-07-02 15:40 UTC
Labels: question
