### ISSUE TITLE
multiprocessing EOFError raised by PyInstaller packaged version

### ISSUE THREAD

**Issue by amarvind** [log2timeline/plaso#2555] opened 2019-05-27 05:58 UTC
I'm getting an error in log2timeline as

[5532] Failed to execute script log2timeline
Traceback (most recent call last):
File "tools\log2timeline.py" , line 68, in <module>
File "tools\log2timeline.py" , line 18, in main
File "PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py" , line 43, in_freeze_support
File "multiprocessing\spwan.py",line 105, in spwan_main
File "multiprocessing\spwan.py",line 115, in _main
EOFError: Ran out of input
[5948] Failed to execute script log2timeline

Version used : plaso-20190131-py3.6-amd64.zip

Please share any solution to resolve the issue

**Comment by joachimmetz** [comment] 2019-05-27 06:01
@amarvind you'll have to provide more detail, it looks like you did not even fill in the issue template.

**Comment by amarvind** [comment] 2019-05-27 08:58
> @amarvind you'll have to provide more detail, it looks like you did not even fill in the issue template.

I'm getting an error in log2timeline as

[5532] Failed to execute script log2timeline
Traceback (most recent call last):
File "tools\log2timeline.py" , line 68, in 
File "tools\log2timeline.py" , line 18, in main
File "PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py" , line 43, in_freeze_support
File "multiprocessing\spwan.py",line 105, in spwan_main
File "multiprocessing\spwan.py",line 115, in _main
EOFError: Ran out of input
[5948] Failed to execute script log2timeline

Version used : plaso-20190131-py3.6-amd64.zip

Please share any solution to resolve the issue

**Comment by joachimmetz** [comment] 2019-05-27 10:47
Unfortunately this trace back is not very informative and hints to an issue within Python mulitprocessing.

**Comment by joachimmetz** [comment] 2019-06-04 08:20
A similar issue surfaced on https://ci.appveyor.com/project/log2timeline/plaso/build/job/35xhk45e162oiukm

**Comment by joachimmetz** [comment] 2019-06-05 04:36
This seems to be a pyinstaller build specific issue. 

@amarvind which version of Windows did you run log2timeline.exe on?

**Comment by amarvind** [comment] 2019-06-05 09:55
> This seems to be a pyinstaller build specific issue. Some additional changes in #2610 but issue still surfaces on AppVeyor.
> 
> @amarvind which version of Windows did you run log2timeline.exe on?

I ran on Windows 10

**Comment by joachimmetz** [comment] 2019-06-06 04:23
@amarvind so far I've only been able to reproduce this on the AppVeyor VMs. And the recommendations mentioned in https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing do not address the issue.

So a work-around for now is to install plaso without pyinstaller. https://plaso.readthedocs.io/en/latest/sources/developer/Dependencies.html#windows from l2tbinaries

**Comment by joachimmetz** [comment] 2020-06-09 19:34
PyInstaller build is no longer provided, closing issue.

**Closed by joachimmetz** 2020-06-09 19:34 UTC
Labels: deployment, needs closer look, pyinstaller, windows
