### ISSUE TITLE
Out of memory when processing HFS+ disk image

### ISSUE THREAD

**Issue by ge0rg** [log2timeline/plaso#585] opened 2016-02-12 13:53 UTC
When processing a full disk image from an OSX 10.10 system, log2timeline.py slowly fills up the RAM until the machine comes to a halt (16GB RAM + 20GB swap).

Plaso is started as `log2timeline.py mac-hdd.plaso ./case-01/macbook500.dd`, the image is 466GiB and contains three partitions (EFI boot, main HFS+, recovery HFS+). Partition 2 (main HFS+) was selected at the prompt. It was not possible to mount the partition using the kernel hfsplus module, which seems to be a general problem in recent Linux kernels, 

This was tested on Debian SID (x64, kernel 3.18), first with the shiny new Debian-own plaso_1.4.0 package, then with the python-plaso_1.4.0-1ppa1~trusty package from the Ubuntu GIFT repository, both installed with their respective dependencies from the same repository, and removed before installing the other variant. Both variants slowly filled up the RAM.

There is a flood of compression errors in the log, so this might be related to #526 (libtsk version is 4.2.0):

```
2016-02-12 14:40:41,376 [WARNING] (Worker_04 ) PID:8547 <worker> Analyzer failed to determine compressed stream type indicators for file: TSK:/Applications/Apple Configurator.app/Contents/Resources/AppleConfigurator.help/Contents/Resources/zh_CN.lproj/InfoPlist.strings with error: pysigscan_scanner_scan_file_object: unable to scan file. pysigscan_file_object_read_buffer: unable to read from file object with error: 'File_read_random: (tsk3.c:494) Read error: Invalid file offset (tsk_fs_attr_read - 0)'. pysigscan_file_object_io_handle_read: unable to read from file object. libbfio_handle_read_buffer: unable to read from handle. libsigscan_scanner_scan_file_io_handle: unable to read buffer.
```

**Comment by Onager** [comment] 2016-02-12 14:06
Try running with --use_zeromq. This won't help if this indeed related to #526 but I should be more memory efficient.

**Comment by ge0rg** [comment] 2016-02-12 14:34
Tried again with --use_zeromq, and it still filled up all my RAM. Didn't measure if it took longer, though. Anything else I can try to pinpoint the problem?

**Comment by joachimmetz** [comment] 2016-02-15 07:06
Have a look at [Troubleshooting - High memory usage](https://github.com/log2timeline/plaso/wiki/Troubleshooting#high-memory-usage)

**Comment by ge0rg** [comment] 2016-02-19 11:23
Thanks very much for the hint. I've disabled swap (to have plaso finish in a reasonable time), re-ran the command as described in [Profiling memory usage](https://github.com/log2timeline/plaso/wiki/Profiling#profiling-memory-usage) over night and obtained a set of nine hpy files (the workers had all been OOM-killed, though), with a total of <8MB:

```
>>> from guppy import hpy
>>> heapy = hpy()
>>> for i in range(9): d=heapy.load("%d.hpy"%i); size += d.size; print d.__repr__().splitlines()[0]
... 
Partition of a set of 3547 objects. Total size = 617232 bytes.
Partition of a set of 3596 objects. Total size = 627208 bytes.
Partition of a set of 3588 objects. Total size = 623576 bytes.
Partition of a set of 3596 objects. Total size = 625432 bytes.
Partition of a set of 3587 objects. Total size = 623352 bytes.
Partition of a set of 6516 objects. Total size = 892112 bytes.
Partition of a set of 3574 objects. Total size = 616344 bytes.
Partition of a set of 3838 objects. Total size = 686936 bytes.
Partition of a set of 11878 objects. Total size = 2959264 bytes.
>>> print size/1024./1024
7.88827514648
```

In a second experiment, I ran plaso again, waited until it reached approximately 8GB of total memory usage (around 20 minutes) and pressed ^C. This time, it only created 6 hpy files totalling under 4MB:

```
>>> size = 0
>>> for i in range(6): d=heapy.load("%d.hpy"%i); size += d.size; print d.__repr__().splitlines()[0]
... 
Partition of a set of 3593 objects. Total size = 620504 bytes.
Partition of a set of 3587 objects. Total size = 622952 bytes.
Partition of a set of 6520 objects. Total size = 892696 bytes.
Partition of a set of 3533 objects. Total size = 613960 bytes.
Partition of a set of 3589 objects. Total size = 625920 bytes.
Partition of a set of 3596 objects. Total size = 626112 bytes.
>>> print size/1024./1024
3.81674194336
```

Shortly before the interruption, plaso showed the following stats screen:
```
Identifier	PID	Status		Events		File
Collector	28953	running			
Worker_00	28956	parsing		158910 (172)	TSK:/Applications/iPhoto.app/Contents/Resources/Themes/Assets/ClassicTrim/ridged-inner-frame/ridged-i-frame-border-top-left.png
Worker_01	28958	hashing		162498 (289)	TSK:/Applications/iPhoto.app/Contents/Resources/Themes/Assets/ClassicTrim/ridged-notecard-segments/ribbed-notecard-bttm-segment.png
Worker_02	28960	parsing		157430 (196)	TSK:/Applications/iPhoto.app/Contents/Resources/Themes/Assets/ClassicTrim/ridged-inner-frame/ridged-i-frame-border-left-segment.png
Worker_03	28962	hashing		164965 (406)	TSK:/Applications/iPhoto.app/Contents/Resources/Themes/Assets/ClassicTrim/ridged-inner-frame/ridged-i-frame-border-top-right.png
Worker_04	28964	hashing		159605 (212)	TSK:/Applications/iPhoto.app/Contents/Resources/Themes/Assets/ClassicTrim/ridged-inner-frame/ridged-i-frame-border-top-spacer.png
Worker_05	28966	parsing		135437 (416)	TSK:/Applications/iPhoto.app/Contents/Resources/Themes/Assets/ClassicTrim/ridged-inner-frame/ridged-i-frame-border-right-spacer.png
StorageWriter	28951	running		938847 (1697)	
```
With Collector and StorageWriter, there are eight processes, but only six hpy files, so it's possible the leaking happens in another PID. Is the events column listing the queue size or the total number processed so far?

Do you have any ideas how to further debug this issue?

**Comment by joachimmetz** [comment] 2016-02-19 15:17
So a couple of preliminary (assumed) conclusions:

* the excessive usage is in the workers because they get OOM killed
* it is likely to be a low-level leak otherwise it would show up in heapy like a hot loop with a cyclic reference

Based on those assumptions I would run valgrind on single user mode (which is likely to be very slow) or try to pin point the leak by turning parsers on and off. Maybe start with `filestat` only and see what the memory consumption is.

**Comment by ge0rg** [comment] 2016-02-19 15:38
I'm not sure I agree with your first conclusion, as the OOM killer has been pretty wild (it also killed most of my Chrome tabs and extensions).

However, I've done a short test with `log2timeline.py --parsers=filestat --single_process --profile --profiling-sample-rate=5000 --profiling-type=memory mac-hdd.plaso ./case-01/macbook500.dd` and had to abort it after ~10 minutes and 6GBytes of RAM in use. I will run a valgrind test next and report afterwards.

**Comment by Onager** [comment] 2016-02-19 15:44
Suggestion - try with --hashers=none

**Comment by joachimmetz** [comment] 2016-02-19 15:49
> I'm not sure if I agree with your first conclusion

No worries, I put the **assumed** there for a reason ;)

**Comment by ge0rg** [comment] 2016-02-19 15:59
Tried `log2timeline.py --hashers=none --parsers=filestat --single_process --profile --profiling-sample-rate=5000 --profiling-type=memory mac-hdd.plaso ./case-01/macbook500.dd` - still eats up my memory (5.5GB after ~10mins).

**Comment by ge0rg** [comment] 2016-02-26 12:55
Alright, so I've run valgrind overnight (it took some time indeed), just to find out that it was missing libtsk debug symbols. Another re-run (aborted when it reached 4GiB of RES memory, as displayed by top), provided the [attached memcheck log (l2t-valgrind.zip)](https://github.com/log2timeline/plaso/files/148184/l2t-valgrind.zip).

Unfortunately, valgrind didn't report the total memory in use, but at least it tells (via the valkyrie UI frontend) that it leaked ~140MBytes, which is ~3.5% of the total memory shown by top. Most of the leaked memory seems to originate from HFS access in libtsk in pytsk. However, it does not explain what the other 3.9GiB were used for.

I'll try another valgrind run with `--show-leak-kinds=all`, but I'm not sure if it will be of much help.

**Comment by ge0rg** [comment] 2016-02-26 16:53
Alright, another profiling run, now with `/usr/bin/time`, valgrind and heapy, now aborted after ~4.7GiB. Verbose time stats:

	Command being timed: "valgrind --leak-check=full --show-leak-kinds=all --xml=yes --xml-file=l2t-valgrind-allleaks.xml log2timeline.py --parsers=filestat --single_process --profile --profiling-sample-rate=5000 --profiling-type=memory mac-hdd.plaso ./case-01/macbook500.dd"
	User time (seconds): 10081.36
	System time (seconds): 99.32
	Percent of CPU this job got: 98%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:52:08
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 4720096
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 117
	Minor (reclaiming a frame) page faults: 2665916
	Voluntary context switches: 5639
	Involuntary context switches: 352426
	Swaps: 0
	File system inputs: 4538592
	File system outputs: 325792
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

Valgrind and heapy logs: [l2t-valgrind-alleaks.zip](https://github.com/log2timeline/plaso/files/148576/l2t-valgrind-alleaks.zip)

According to heapy, 17MBytes are used:

    Partition of a set of 57101 objects. Total size = 17399088 bytes.

Valkyrie overflows its counters and reports -1.7GiB (leaked+allocated), which corresponds to ~4.5GiB. The biggest perpetrator is libsigscan with 2GiB of allocated and still accessible memory:

![valkyrie stacktrace screenshot](https://cloud.githubusercontent.com/assets/165635/13358786/49f26a52-dcb1-11e5-8c05-d2e1e5811168.png)

As this one place makes up almost half of the used memory, and all other individual places are several orders of magnitude below, I would blame it for the issue I'm experiencing. I can provide another stack trace with libsigscan-dbg loaded as well.

**Comment by joachimmetz** [comment] 2016-02-26 20:11
> According to heapy, 17MBytes are used:

So heapy only knows about Python allocated objects. We use is to catch cyclic object references in a hot loop. From your description it sounds that you are experiencing a leak in libtsk/pytsk. I'll have a look at the valgrind files tomorrow (local time) and see if I can determine a pattern. The issue for us is that libtsk is a third party library and (based on past experience) will be harder to get certain issues fixed.

**Comment by ge0rg** [comment] 2016-02-27 13:43
While the leak is indeed in libtsk, it is not very dramatic (~50MB of the 4GiB). It seems that libsigscan is the bigger culprit, accumulating ~2GiB of RAM in the above scenario. While the memory is technically still reachable, I'm not sure it is actually needed. From the valgrind runs I am pretty sure libsigscan is what is causing the OOM situation. Here a valkyrie screenshot with libsigscan source code lines added:

![valkyrie-stack-2](https://cloud.githubusercontent.com/assets/165635/13373173/50f29408-dd60-11e5-93a5-07ff060b44e0.png)

**Comment by joachimmetz** [comment] 2016-02-27 14:48
> It seems that libsigscan is the bigger culprit, accumulating ~2GiB of RAM in the above scenario.

I'll need to take a closer look at this libsigscan by itself should not use that much memory. I'm wondering if this behavior is caused by a hot loop where more memory is consumed before the garbage collector kicks in.

**Comment by ge0rg** [comment] 2016-03-07 11:02
Please let me know if you found anything. I'm eager to build&test components from git, if needed :)

**Comment by joachimmetz** [comment] 2016-03-07 20:13
A bit swamped at the moment, I'll let you know as soon as time permits.

**Comment by wjohnsonsled** [comment] 2016-09-20 17:28
Is there a work around for any of this?  I believe I am seeing similar issues.  Getting a lot of "unable to read" & "buffer" related errors on several different HFS+ images..

**Comment by joachimmetz** [comment] 2017-12-06 07:10
So far I've not been able to reproduce this issue.

**Comment by joachimmetz** [comment] 2018-05-23 06:14
We fixed a binplist memory consumption issue recently and have moved to biplist https://github.com/log2timeline/plaso/issues/1776

**Comment by joachimmetz** [comment] 2018-05-23 06:14
Closing issue since plaso and dependencies have changed in the mean time

**Closed by joachimmetz** 2018-05-23 06:14 UTC
Labels: core, question
