### ISSUE TITLE
Psort.py cannot generate l2tcsv output

### ISSUE THREAD

**Issue by ricci3** [log2timeline/plaso#188] opened 2015-05-10 04:59 UTC
For an incomplete output from log2timeline.py, when psort.py was used, it was found that the psort.py <output.dump> can operate, but psort.py -t l2tcsv would resulted in following error:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 761, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 735, in Main
    counter = front_end.ParseStorage(options)
  File "/usr/bin/psort.py", line 361, in ParseStorage
    self._filter_buffer, event_queue_producers)
  File "/usr/lib/python2.7/dist-packages/plaso/lib/output.py", line 295, in __exit__
    self.End()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/output.py", line 288, in End
    self.Flush()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/output.py", line 255, in Flush
    self.formatter.WriteEvent(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/l2t_csv.py", line 59, in WriteEvent
    self.EventBody(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/l2t_csv.py", line 127, in EventBody
    helper.GetLegacy(event_object),
  File "/usr/lib/python2.7/dist-packages/plaso/output/helper.py", line 44, in GetLegacy
    if evt.timestamp_desc in [
AttributeError: 'EventObject' object has no attribute 'timestamp_desc'

**Comment by joachimmetz** [comment] 2015-05-10 06:32
This looks like a duplicate of: https://github.com/log2timeline/plaso/issues/141. Which version of plaso are you using?

**Comment by joachimmetz** [comment] 2015-05-10 06:40
This file: plaso/output/helper.py no longer exists please update your version of plaso to fix this issue.

**Closed by joachimmetz** 2015-05-10 06:40 UTC
Labels: duplicate
