### ISSUE TITLE
Psort ValueError: Unsupported timezone: Arabic Standard Time

### ISSUE THREAD

**Issue by Sid-Vishez** [log2timeline/plaso#967] opened 2016-08-29 11:41 UTC
**Plaso version:**

1.5RC2

**Operating system Plaso is running on:**

Windows 7 for create plaso file and Ubuntu 14.04 for output to Timesketch.

**Installation method:**

GiFT [https://launchpad.net/~gift]

**Description of problem:**

Please describe the problem in as much detail as possible, including relevant command line arguments, flags etc.
What does the tool not do that it should? What would you like it to do?

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Debug output/tracebacks:**

user@host:/path$ psort.py -o timesketch -z Europe/Moscow plasodump.plaso
2016-08-29 17:23:55,754 [INFO] (MainProcess) PID:27119 <timesketch_out> Document type: plaso_event
2016-08-29 17:23:55,754 [INFO] (MainProcess) PID:27119 <timesketch_out> Flush interval: 1000
2016-08-29 17:23:55,755 [INFO] (MainProcess) PID:27119 <timesketch_out> Index name: cad67303a8b44d05b057d610695dbdea
2016-08-29 17:23:55,755 [INFO] (MainProcess) PID:27119 <timesketch_out> Timeline name:
2016-08-29 17:23:55,755 [INFO] (MainProcess) PID:27119 <timesketch_out> Owner of the timeline: None
Missing parameter timeline_name for output module: plasodump
2016-08-29 17:23:59,000 [INFO] (MainProcess) PID:27119 <timesketch_out> Document type: plaso_event
2016-08-29 17:23:59,000 [INFO] (MainProcess) PID:27119 <timesketch_out> Flush interval: 1000
2016-08-29 17:23:59,000 [INFO] (MainProcess) PID:27119 <timesketch_out> Index name: cad67303a8b44d05b057d610695dbdea
2016-08-29 17:23:59,000 [INFO] (MainProcess) PID:27119 <timesketch_out> Timeline name: plasodump

2016-08-29 17:23:59,001 [INFO] (MainProcess) PID:27119 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 867, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 853, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 797, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 283, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 601, in ExportEvents
    storage_reader.ReadPreprocessingInformation(knowledge_base_object)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 422, in ReadPreprocessingInformation
    return self._storage_file.ReadPreprocessingInformation(knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 2783, in ReadPreprocessingInformation
    stream_number, system_configuration)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/knowledge_base.py", line 245, in ReadSystemConfigurationArtifact
    self.SetTimezone(system_configuration.time_zone)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/knowledge_base.py", line 268, in SetTimezone
    raise ValueError(u'Unsupported timezone: {0:s}'.format(timezone))
ValueError: Unsupported timezone: Arabic Standard Time

user@host:/path$ psort.py -V
plaso - psort version 1.4.1_20160828

**Source data:**

WinXP ATM E01 image

**Comment by Onager** [comment] 2016-08-29 12:17
Thanks for the report. Ultimately we'll solve this with #726 but in the interim, I'll add the appropriate mapping for this zone.

**Comment by Onager** [comment] 2016-08-31 15:38
Actually, I was mistaken about the root cause here - preprocessing seems to be misbehaving. @joachimmetz any theories about how this string could come to be in the SystemConfigurationArtifact?

**Comment by joachimmetz** [comment] 2016-08-31 15:46
Note to self, prevent plaso to store and read an invalid timezone.

**Comment by Onager** [comment] 2016-09-11 12:15
This is now fixed.

**Closed by Onager** 2016-09-11 12:15 UTC
Labels: enhancement, preprocessing
