### ISSUE TITLE
Infinite Loop: Terminating Worker - Worker is still Alive 

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#108] opened 2015-02-11 18:11 UTC
According to the log messages, I experience an infinite loop in which crashed workers cannot be killed and restarted by plaso. After pressing CTRL+C I receive "Stopping Collector" and "Aborted by User", but the program is still not terminated.

I am running `log2timeline - plaso back-end 1.2.1_20150206` on an arch linux system with the same dependencies as outlined in issue #107.

Is this pebkac or a genuine problem with plaso? I am willing to actively assist you in debugging it. 

Please let me know if you need further information.

```
[...]
2015-02-11 19:05:57,564 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_4 at http://localhost:29338
2015-02-11 19:05:57,564 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_4 [29338] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:05:57,565 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_4 [29338] is still alive.
2015-02-11 19:05:57,566 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_5 at http://localhost:29341
2015-02-11 19:05:57,566 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_5 [29341] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:05:57,566 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_5 [29341] is still alive.
2015-02-11 19:05:57,567 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_6 at http://localhost:29344
2015-02-11 19:05:57,568 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_6 [29344] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:05:57,568 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_6 [29344] is still alive.
2015-02-11 19:06:07,570 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_0 at http://localhost:29329
2015-02-11 19:06:07,570 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_0 [29329] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:07,571 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_0 [29329] is still alive.
2015-02-11 19:06:07,572 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_1 at http://localhost:29331
2015-02-11 19:06:07,572 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_1 [29331] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:07,573 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_1 [29331] is still alive.
2015-02-11 19:06:07,574 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_2 at http://localhost:29333
2015-02-11 19:06:07,574 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_2 [29333] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:07,574 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_2 [29333] is still alive.
2015-02-11 19:06:07,575 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_3 at http://localhost:29336
2015-02-11 19:06:07,575 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_3 [29336] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:07,576 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_3 [29336] is still alive.
2015-02-11 19:06:07,577 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_4 at http://localhost:29338
2015-02-11 19:06:07,577 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_4 [29338] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:07,578 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_4 [29338] is still alive.
2015-02-11 19:06:07,579 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_5 at http://localhost:29341
2015-02-11 19:06:07,579 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_5 [29341] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:07,579 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_5 [29341] is still alive.
2015-02-11 19:06:07,580 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_6 at http://localhost:29344
2015-02-11 19:06:07,580 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_6 [29344] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:07,581 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_6 [29344] is still alive.
2015-02-11 19:06:17,583 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_0 at http://localhost:29329
2015-02-11 19:06:17,583 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_0 [29329] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:17,584 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_0 [29329] is still alive.
2015-02-11 19:06:17,585 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_1 at http://localhost:29331
2015-02-11 19:06:17,585 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_1 [29331] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:17,586 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_1 [29331] is still alive.
2015-02-11 19:06:17,586 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_2 at http://localhost:29333
2015-02-11 19:06:17,587 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_2 [29333] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:17,587 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_2 [29333] is still alive.
2015-02-11 19:06:17,588 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_3 at http://localhost:29336
2015-02-11 19:06:17,588 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_3 [29336] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:17,589 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_3 [29336] is still alive.
2015-02-11 19:06:17,589 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_4 at http://localhost:29338
2015-02-11 19:06:17,590 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_4 [29338] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:17,590 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_4 [29338] is still alive.
2015-02-11 19:06:17,591 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_5 at http://localhost:29341
2015-02-11 19:06:17,591 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_5 [29341] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:17,592 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_5 [29341] is still alive.
2015-02-11 19:06:17,592 [WARNING] (MainProcess) PID:29290 <foreman> Unable to connect to RPC socket to: Worker_6 at http://localhost:29344
2015-02-11 19:06:17,593 [ERROR] (MainProcess) PID:29290 <foreman> Process Worker_6 [29344] is not functioning when it should be. Terminating it and removing from list.
2015-02-11 19:06:17,593 [WARNING] (MainProcess) PID:29290 <foreman> Process Worker_6 [29344] is still alive.
```

**Comment by kiddinn** [comment] 2015-02-11 22:16
This is a genuine problem in plaso, and likely due to the new and experimental compressed file support. This is still WIP ATM.

Is this consistent though, as in if you kill the tool and re-start it, do you get the same results?

**Comment by kiddinn** [comment] 2015-02-11 22:16
assigning this to @joachimmetz since he's got other bugs with similar nature assigned to him

**Comment by bf** [comment] 2015-02-11 23:01
Unfortunately I cannot reproduce this issue at the moment. It would've helped if I printed the actual command in my bug report..

**Comment by joachimmetz** [comment] 2015-02-12 06:16
No this is not a similar issue as the others. I'm speculation but  this is likely caused by the XML RPC in the foreman having unwanted side effects on process management.

**Comment by joachimmetz** [comment] 2015-02-12 06:26
Likely related to https://github.com/log2timeline/plaso/issues/71

**Comment by joachimmetz** [comment] 2015-03-30 06:09
Marking as duplicate of #71.

**Closed by joachimmetz** 2015-03-30 06:09 UTC
Labels: bug, duplicate
