### ISSUE TITLE
KeyError : in collection.py

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1132] opened 2017-01-17 15:57 UTC
**Plaso version:**

1.5.2_20170117

**Operating system Plaso is running on:**

Lubuntu

**Installation method:**
Git clone for development and us PPA:GIFT/DEV

**Description of problem:**

Another error while log2timeline is running against enCase image.
Following error appears:

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.5.2.post20170116', 'log2timeline.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 657, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 643, in Main
    tool.ProcessSources()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 554, in ProcessSources
    status_update_callback=status_update_callback, timezone=self._timezone)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/frontend/extraction_frontend.py", line 423, in ProcessSources
    show_memory_usage=self._show_worker_memory_information)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/task_engine.py", line 772, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/task_engine.py", line 276, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/task_engine.py", line 408, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/task_engine.py", line 165, in _MergeTaskStorage
    for task in self._task_manager.GetProcessingTasks():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/task_manager.py", line 186, in GetProcessingTasks
    return list(self._tasks_processing.values())
  File "/usr/lib/python2.7/collections.py", line 123, in values
    return [self[key] for key in self]
KeyError: u'dcb93abf24c348609aacc7656d5d3899'
2017-01-17 23:16:14,921 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:16:19,629 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:16:37,645 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:16:42,578 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:16:48,262 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:16:54,154 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:17:12,389 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:17:16,971 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:17:28,834 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:17:49,885 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:17:59,604 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:18:09,595 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 23:18:16,017 [WARNING] (MainProcess) PID:16028 <zeromq_queue> main_task_queue timeout waiting for a request.

Regard.

**Comment by joachimmetz** [comment] 2017-01-17 20:37
Looks like a duplicate of https://github.com/log2timeline/plaso/issues/1010

**Comment by Onager** [comment] 2017-01-18 07:19
Yep, this is a duplicate.

**Closed by Onager** 2017-01-18 07:19 UTC
Labels: duplicate
