### ISSUE TITLE
In-memory Windows Registry structures from a memory capture are not processed

### ISSUE THREAD

**Issue by MikeHofmann** [log2timeline/plaso#3564] opened 2021-04-23 13:28 UTC
**Description of problem:**

We are analyzing a few memory dumps using `volatility3`. So far we were able to extract several Windows-Eventlogs, Registryhives and several other IOCs from the memory dump. `log2timeline` is extracting everything from the extracted Eventlogs, but never extracts anything from the hives.

For example the registry is dumped by using:

```
vol.py \
   -f memory_layer.raw \
  -o registry \
  windows.registry.hivelist.HiveList --dump
```

```
Volatility 3 Framework 1.0.1
Progress:  100.00               PDB scanning finished
Offset  FileFullPath    File output

0xc000ad61e000          registry.NONAME.0xc000ad61e000.hive
0xc000ad627000  \REGISTRY\MACHINE\SYSTEM        registry.SYSTEM.0xc000ad627000.hive
0xc000ad638000  \REGISTRY\MACHINE\HARDWARE      registry.HARDWARE.0xc000ad638000.hive
0xc000ae712000  \SystemRoot\System32\Config\SAM registry.SAM.0xc000ae712000.hive
0xc000ae716000  \SystemRoot\System32\Config\SECURITY    registry.SECURITY.0xc000ae716000.hive
0xc000ae70e000  \SystemRoot\System32\Config\DEFAULT     registry.DEFAULT.0xc000ae70e000.hive
0xc000ae6c7000  \SystemRoot\System32\Config\SOFTWARE    registry.SOFTWARE.0xc000ae6c7000.hive
0xc000b229b000  \Device\HarddiskVolume1\Boot\BCD        registry.BCD.0xc000b229b000.hive
0xc000ae8df000  \??\C:\Windows\ServiceProfiles\NetworkService\NTUSER.DAT        registry.NTUSERDAT.0xc000ae8df000.hive
0xc000ae96e000  \SystemRoot\System32\Config\BBI registry.BBI.0xc000ae96e000.hive
0xc000ae9cb000  \??\C:\Windows\ServiceProfiles\LocalService\NTUSER.DAT  registry.NTUSERDAT.0xc000ae9cb000.hive
0xc000af428000  \??\C:\Users\Administrator\ntuser.dat   registry.ntuserdat.0xc000af428000.hive
0xc000af938000  \??\C:\Users\Administrator\AppData\Local\Microsoft\Windows\UsrClass.dat registry.UsrClassdat.0xc000af938000.hive
```

With another volatility3-plugin we were able to extract some Eventlogs. So currently we have the following file structure:

```
dump
├── evtx
│   └── file.0xe00061dfb7c0.0xe000619e8f00.DataSectionObject.Microsoft-Windows-TerminalServices-RDPClient%4Operational.evtx.dat
├── registry
│   ├── registry.BBI.0xc000ae96e000.hive
│   ├── registry.BCD.0xc000b229b000.hive
│   ├── registry.DEFAULT.0xc000ae70e000.hive
│   ├── registry.HARDWARE.0xc000ad638000.hive
│   ├── registry.NONAME.0xc000ad61e000.hive
│   ├── registry.NTUSERDAT.0xc000ae8df000.hive
│   ├── registry.NTUSERDAT.0xc000ae9cb000.hive
│   ├── registry.SAM.0xc000ae712000.hive
│   ├── registry.SECURITY.0xc000ae716000.hive
│   ├── registry.SOFTWARE.0xc000ae6c7000.hive
│   ├── registry.SYSTEM.0xc000ad627000.hive
│   ├── registry.UsrClassdat.0xc000af938000.hive
│   └── registry.ntuserdat.0xc000af428000.hive
```

**Command line and arguments:**

```
log2timeline.py \
   --debug \
   --workers 1 \
   timeline.plaso \
   dump
```

`log2timeline.py` is able to identify all the files and is using the correct (IMHO) parsers on the files.

i.e. on the Eventlogs from the worker.log:

```
2021-04-23 13:06:51,150 [DEBUG] (Worker_00 ) PID:511 <worker> [ExtractMetadataFromFileEntry] processing file entry: OS:/redacted/dump/evtx/file.0xe00061dfb7c0.0xe000619e8f00.DataSectionObject.Microsoft-Windows-TerminalServices-RDPClient%4Operational.evtx.dat
2021-04-23 13:06:51,151 [DEBUG] (Worker_00 ) PID:511 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/redacted/evtx/file.0xe00061dfb7c0.0xe000619e8f00.DataSectionObject.Microsoft-Windows-TerminalServices-RDPClient%4Operational.evtx.dat with parser: winevtx
2021-04-23 13:06:51,404 [DEBUG] (Worker_00 ) PID:511 <worker> [ProcessFileEntry] done processing file entry: OS:/redacted/dump/evtx/file.0xe00061dfb7c0.0xe000619e8f00.DataSectionObject.Microsoft-Windows-TerminalServices-RDPClient%4Operational.evtx.dat
```

and on a hive:

```
2021-04-23 13:06:51,925 [DEBUG] (Worker_00 ) PID:511 <worker> [ExtractMetadataFromFileEntry] processing file entry: OS:/redacted/dump/registry/registry.ntuserdat.0xc000af428000.hive
2021-04-23 13:06:51,927 [DEBUG] (Worker_00 ) PID:511 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/redacted/dump/registry/registry.ntuserdat.0xc000af428000.hive with parser: winreg
2021-04-23 13:06:51,928 [DEBUG] (Worker_00 ) PID:511 <worker> [ProcessFileEntry] done processing file entry: OS:/redacted/issue_mho/dump/registry/registry.ntuserdat.0xc000af428000.hive
```

The `.hive` do have proper magic bytes:

```
file registry/*.hive

registry/registry.BBI.0xc000ae96e000.hive:         MS Windows registry file, NT/2000 or above
registry/registry.BCD.0xc000b229b000.hive:         MS Windows registry file, NT/2000 or above
registry/registry.DEFAULT.0xc000ae70e000.hive:     MS Windows registry file, NT/2000 or above
registry/registry.HARDWARE.0xc000ad638000.hive:    MS Windows registry file, NT/2000 or above
registry/registry.NONAME.0xc000ad61e000.hive:      MS Windows registry file, NT/2000 or above
registry/registry.NTUSERDAT.0xc000ae8df000.hive:   MS Windows registry file, NT/2000 or above
registry/registry.NTUSERDAT.0xc000ae9cb000.hive:   MS Windows registry file, NT/2000 or above
registry/registry.SAM.0xc000ae712000.hive:         MS Windows registry file, NT/2000 or above
registry/registry.SECURITY.0xc000ae716000.hive:    MS Windows registry file, NT/2000 or above
registry/registry.SOFTWARE.0xc000ae6c7000.hive:    MS Windows registry file, NT/2000 or above
registry/registry.SYSTEM.0xc000ad627000.hive:      MS Windows registry file, NT/2000 or above
registry/registry.UsrClassdat.0xc000af938000.hive: MS Windows registry file, NT/2000 or above
registry/registry.ntuserdat.0xc000af428000.hive:   MS Windows registry file, NT/2000 or above
```

and can also be processed with other forensic tools.

**Source data:**

i can provide a similar `.hive` file via pm.

**Plaso version:**

```
log2timeline.py --version
plaso - log2timeline version 20210412
```

**Operating system Plaso is running on:**

Running on docker

**Installation method:**

using the latest docker image

**Comment by joachimmetz** [comment] 2021-04-23 14:05
That's because in-memory Windows Registry structures are not fully the same as on-disk ones.

**Comment by joachimmetz** [comment] 2021-04-25 08:33
Duplicate of https://github.com/log2timeline/plaso/issues/3266 closing

**Closed by joachimmetz** 2021-04-25 08:33 UTC
Labels: duplicate, question
