### ISSUE TITLE
Log2timeline. What's happened?

### ISSUE THREAD

**Issue by b0cq** [log2timeline/plaso#1065] opened 2016-10-23 21:11 UTC
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 791, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 288, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 417, in _ScheduleTasks
  File "plaso\multi_processing\task_engine.py", line 221, in _MergeTaskStorage
  File "plaso\storage\zip_file.py", line 3291, in StartMergeTaskStorage
  File "plaso\storage\gzip_file.py", line 305, in __init__
  File "gzip.py", line 34, in open
  File "gzip.py", line 94, in __init__
IOError: [Errno 13] Permission denied: u'tmppt6clj\\merge\\65d55ace919643958ef14cabf2b8f34a.plaso'
Failed to execute script log2timeline

**Comment by joachimmetz** [comment] 2016-10-24 06:00
Please provide the information requested in the issue template. Based on the current information I would guess this is a duplicate of https://github.com/log2timeline/plaso/issues/1009

**Comment by Onager** [comment] 2016-10-26 15:13
No response from @b0cq closing out, for #1009

**Closed by Onager** 2016-10-26 15:13 UTC
Labels: question
