### ISSUE TITLE
unable to get event filter to generate output with psort on kali linux 

### ISSUE THREAD

**Issue by evilcode1** [log2timeline/plaso#2678] opened 2019-06-25 23:09 UTC
hello all ... im trying to make .plaso file for my .img i run this command 

> log2timeline.py --no_dependencies_check --parsers "win7" -z "Asia/Jerusalem" ~/Desktop/last11.plaso /media/root/Elements/zib.img
```
Tasks:          Queued  Processing      Merging         Abandoned       Total
                0       0               0               0               0

Identifier      PID     Status          Memory          Sources         Events          File
Main            6849    collecting      777.0 MiB       3 (0)           0 (0)           
Worker_00       7212    idle            678.0 MiB       0 (0)           0 (0)           
Worker_01       7217    idle            677.4 MiB       0 (0)           0 (0)           
Worker_02       7220    idle            677.3 MiB       0 (0)           0 (0)   

```

what is the problem !!! ?? 

> Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

**Comment by joachimmetz** [comment] 2019-06-26 03:59
Can you provided the other details requested in the issue template?

**Comment by evilcode1** [comment] 2019-06-26 08:46
solved by ignore VSS files but i have another issue with psort :( 3 days solving plaso issues :( 
i used this command :+1: 

> psort.py -z "Asia/Jerusalem" -o l2tcsv -q /root/Desktop/5.plaso "date < '2019-05-18 12:00:00' and date > '2019-06-11 12:00:00'" -w /root/Desktop/6.csv

event = 0 !!

**Comment by evilcode1** [comment] 2019-06-26 08:56
i dont know if i should wait !! because when i remove tha date filter it's start counting event's ,, the hdd have logs since 2009 year , so should i wait when i used data filter in 2019 until he arrived that point and it will start count event's ????

**Comment by joachimmetz** [comment] 2019-06-26 09:23
@evilcode1 we cannot help you if you don't provide the information we ask you for. 

> 3 days solving plaso issues :(

You appear to want to do things your own way, hence you might be running into issue that the documentation already advices against doing.

**Comment by evilcode1** [comment] 2019-06-26 09:24
okay what the info u need and where i can found them ?

**Comment by joachimmetz** [comment] 2019-06-26 09:26
the initial issue templates asks for information, please provide us with that. I've added this below

Also see https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html it describes to systemically gather information that can help to troubleshooting (instead of applying random experimentation with different variables until it works).

**Description of problem:**

Please describe the problem in as much detail as possible.
What does the tool not do that it should? What would you like it to do?

**Command line and arguments:**

Please provide the command with arguments you ran when you experienced
the problem.

**Source data:**

Please provide the source data you used when you experienced the problem.
For publicly available data please provide an URL or path of the source data.

**Plaso version:**

For example 20171231

**Operating system Plaso is running on:**

Not the operating system of the image/files you're trying to analyze.

**Installation method:**

For example:
* installed from [GiFT PPA][https://launchpad.net/~gift] stable track
* installed from [GiFT COPR][https://copr.fedorainfracloud.org/coprs/g/gift/] stable track
* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch
* built using [l2devtools][https://github.com/log2timeline/l2tdevtools]
* other, namely ...

If multiple methods were used please indicate.

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.
Also see: [Producing debug logs][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html#producing-debug-logs]

For more information see the [troubleshooting
guide][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html].

**Comment by evilcode1** [comment] 2019-06-26 09:39
the problem is : 
i got 0 event when i used psort on my .plaso dump which generated by log2timeline 
the pinfo.py for my .plaso : 

> ************************** Plaso Storage Information ***************************
>             Filename : 5.plaso
>       Format version : 20190309
> Serialization format : json
> --------------------------------------------------------------------------------
> 
> *********************************** Sessions ***********************************
> 7902d541-40a4-458f-a89f-41abed70c053 : 2019-06-25T23:25:50.375718Z
> --------------------------------------------------------------------------------
> 
> **************** Session: 7902d541-40a4-458f-a89f-41abed70c053 *****************
>                 Start time : 2019-06-25T23:25:50.375718Z
>            Completion time : 2019-06-26T06:44:06.019713Z
>               Product name : plaso
>            Product version : 20190531
>     Command line arguments : /usr/local/bin/log2timeline.py
>                              --no_dependencies_check --parsers win7 -z
>                              Asia/Jerusalem /root/Desktop/5.plaso
>                              /media/root/Elements/zib.img
>   Parser filter expression : win7
> Enabled parser and plugins : amcache, bencode, bencode/bencode_transmission,
>                              bencode/bencode_utorrent, binary_cookies,
>                              chrome_cache, chrome_preferences,
>                              custom_destinations, czip, czip/oxml, esedb,
>                              esedb/file_history, esedb/msie_webcache,
>                              esedb/srum, filestat, firefox_cache,
>                              gdrive_synclog, java_idx, lnk, mcafee_protection,
>                              msiecf, olecf, olecf/olecf_automatic_destinations,
>                              olecf/olecf_default, olecf/olecf_document_summary,
>                              olecf/olecf_summary, opera_global,
>                              opera_typed_history, pe, plist, plist/airport,
>                              plist/apple_id, plist/ipod_device,
>                              plist/macosx_bluetooth,
>                              plist/macosx_install_history, plist/macuser,
>                              plist/maxos_software_update, plist/plist_default,
>                              plist/safari_history, plist/spotlight,
>                              plist/spotlight_volume, plist/time_machine,
>                              prefetch, recycle_bin, sccm, skydrive_log,
>                              skydrive_log_old, sqlite, sqlite/android_calls,
>                              sqlite/android_sms, sqlite/android_webview,
>                              sqlite/android_webviewcache, sqlite/appusage,
>                              sqlite/chrome_27_history, sqlite/chrome_8_history,
>                              sqlite/chrome_autofill, sqlite/chrome_cookies,
>                              sqlite/chrome_extension_activity,
>                              sqlite/firefox_cookies, sqlite/firefox_downloads,
>                              sqlite/firefox_history, sqlite/google_drive,
>                              sqlite/hangouts_messages, sqlite/imessage,
>                              sqlite/kik_messenger, sqlite/kodi,
>                              sqlite/ls_quarantine,
>                              sqlite/mac_document_versions,
>                              sqlite/mac_knowledgec, sqlite/mac_notes,
>                              sqlite/mac_notificationcenter,
>                              sqlite/mackeeper_cache, sqlite/safari_history,
>                              sqlite/skype, sqlite/tango_android_profile,
>                              sqlite/tango_android_tc, sqlite/twitter_android,
>                              sqlite/twitter_ios, sqlite/windows_timeline,
>                              sqlite/zeitgeist, symantec_scanlog, usnjrnl,
>                              winevtx, winfirewall, winjob, winreg,
>                              winreg/appcompatcache, winreg/bagmru,
>                              winreg/ccleaner, winreg/explorer_mountpoints2,
>                              winreg/explorer_programscache,
>                              winreg/microsoft_office_mru,
>                              winreg/microsoft_outlook_mru,
>                              winreg/mrulist_shell_item_list,
>                              winreg/mrulist_string,
>                              winreg/mrulistex_shell_item_list,
>                              winreg/mrulistex_string,
>                              winreg/mrulistex_string_and_shell_item,
>                              winreg/mrulistex_string_and_shell_item_list,
>                              winreg/msie_zone, winreg/mstsc_rdp,
>                              winreg/mstsc_rdp_mru, winreg/network_drives,
>                              winreg/networks, winreg/userassist,
>                              winreg/windows_boot_execute,
>                              winreg/windows_boot_verify, winreg/windows_run,
>                              winreg/windows_sam_users, winreg/windows_services,
>                              winreg/windows_shutdown,
>                              winreg/windows_task_cache,
>                              winreg/windows_timezone,
>                              winreg/windows_typed_urls,
>                              winreg/windows_usb_devices,
>                              winreg/windows_usbstor_devices,
>                              winreg/windows_version, winreg/winlogon,
>                              winreg/winrar_mru, winreg/winreg_default
>         Preferred encoding : UTF-8
>                 Debug mode : False
>           Artifact filters : N/A
>                Filter file : N/A
>    Number of event sources : 339066
> 
plaso version : plaso - log2timeline version 20190531
os : Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
Installation method: 
apt-get install plaso 
Debug output/tracebacks:

> 2019-06-26 12:33:27,903 [WARNING] (MainProcess) PID:4109 <psort_tool> Appending to an already existing storage file.
> 2019-06-26 12:33:27,907 [WARNING] (MainProcess) PID:4109 <knowledge_base> Unsupported time zone: IST, defaulting to UTC

by the way i changed the time zone to UTC

**Comment by joachimmetz** [comment] 2019-06-26 09:45
* Anything in the debug log of the workers?
* how large is your plaso file?
* what does pinfo tell you about the number of events per parser are in the plaso file?
* does https://github.com/log2timeline/plaso/issues/2665 describe the behaviour you are experiencing?

**Comment by evilcode1** [comment] 2019-06-26 09:50
1- debug log for workers !! is there a workers log for psort.py !! 
2- plaso file size is : 2GB
3 -

> ************************* Events generated per parser **************************
>                 Parser (plugin) name : Number of events
> --------------------------------------------------------------------------------
>                       appcompatcache : 4087
>                               bagmru : 1434
>                    chrome_27_history : 946
>                      chrome_autofill : 243
>                         chrome_cache : 7906
>                       chrome_cookies : 7589
>                   chrome_preferences : 70
>                explorer_mountpoints2 : 22
>               explorer_programscache : 16
>                             filestat : 1355681
>                google_analytics_utma : 56
>                google_analytics_utmb : 34
>                google_analytics_utmt : 31
>                google_analytics_utmz : 48
>                             java_idx : 1664
>                                  lnk : 38297
>                microsoft_outlook_mru : 1
>                       mrulist_string : 33
>            mrulistex_shell_item_list : 42
>                     mrulistex_string : 33
>      mrulistex_string_and_shell_item : 30
> mrulistex_string_and_shell_item_list : 2
>                        msie_webcache : 15746
>                            msie_zone : 144
>                               msiecf : 1600
>                            mstsc_rdp : 7
>                        mstsc_rdp_mru : 2
>                             networks : 22
>         olecf_automatic_destinations : 8909
>                        olecf_default : 8829
>                                 oxml : 10482
>                                   pe : 161518
>                             prefetch : 277
>                          recycle_bin : 189
>                          shell_items : 33111
>                           userassist : 205
>                              usnjrnl : 310111
>                 windows_boot_execute : 12
>                          windows_run : 28
>                    windows_sam_users : 8
>                     windows_services : 2560
>                     windows_shutdown : 6
>                   windows_task_cache : 468
>                     windows_timezone : 6
>                   windows_typed_urls : 6
>                  windows_usb_devices : 100
>              windows_usbstor_devices : 103
>                      windows_version : 8
>                              winevtx : 752265
>                             winlogon : 12
>                           winrar_mru : 3
>                       winreg_default : 887919
>                                Total : 3612921
> 

> plaso - psort version 20190531
> 
> Storage file		: 5.plaso
> Processing time		: 00:09:20
> 
> Events:         Filtered        In time slice   Duplicates      MACB grouped    Total
>                 3612921         0               0               0               3612921
> 
> Identifier              PID     Status          Memory          Events          Tags            Reports
> Main                    4837    exporting       122.1 MiB       0 (0)           0 (0)           0 (0)
> 
> Processing completed.
>

**Comment by joachimmetz** [comment] 2019-06-26 10:07
>  debug log for workers !! is there a workers log for psort.py !!

Side note: dd `--debug` for log2timeline.py (as described in the troubleshooting documentation I referenced earlier). So it looks like your plaso file does contain events. Good that means that we can focus our attention on psort.

* did you run psort with out the date filter?
* did you try changing the logic of your filter? "date < '2019-05-18 12:00:00' and date > '2019-06-11 12:00:00'" tells psort you want events that both predate 2019-05-18 12:00:00 and post date 2019-06-11 12:00:00 at the same time? if you are looking for events that are between 2019-05-18 12:00:00 and 2019-06-11 12:00:00, you'll need to change the filter or change AND to OR if you want to ignore that time range

**Comment by joachimmetz** [comment] 2019-06-26 14:25
@evilcode1 seeing the lack of additional responses I assume changing the logic of the filter solved your issue?

**Comment by evilcode1** [comment] 2019-06-26 14:28
not yet my brother i did not try ... i left my office i will try tonight and let u know keep the issue open :) thank u for helping the comunity <3

**Comment by evilcode1** [comment] 2019-06-26 14:35
okay i connect the pc by teamviwer ... when i try it with OR to ignore the date it work but it's count million of log's so i cant open the CSV file i used quick CSV viwer it keep telling me out of memory and crash ..
that's why i need a time range ... some one made a crime on that PC between 2019-05-18 12:00:00 and post date 2019-06-11 12:00:00 ... so how i can solve this issue :( i need the logs at that time

**Comment by joachimmetz** [comment] 2019-06-26 14:57
>  some one made a crime on that PC between 2019-05-18 12:00:00 and post date 2019-06-11 12:00:00

is this 12 AM or 12 PM? note that plaso uses a 24h clock

then your filter is likely:
`date >= '2019-05-18 12:00:00' AND date <= '2019-06-11 12:00:00'`

> so i cant open the CSV file i used quick CSV viwer it keep telling me out of memory and crash

on Linux you can use a command lien tool like `less` or `more`

**Comment by evilcode1** [comment] 2019-06-26 15:11
i think there is an issue with dates ... take a look at this :

>  **09/17/30828**,02:48:05,Asia/Jerusalem,....,WEBHIST,MSIE WebCache container record,Expiration Time,-,HMADMOOJ,URL: http://www.youtube.com/
> embed/PV3mnnwhQSI,URL: http://www.youtube.com/embed/PV3mnnwhQSI Access count: 85 Sync count: 0 Filename: PV3mnnwhQSI[1] Cached file siz
> e: 0 Response headers: HTTP/1.1 301 Moved PermanentlyContent-Length: 0Location: https://www.youtube.com/embed/PV3mnnwhQSI Entry identif
> ier: 2000 Container identifier: 1 Cache identifier: 0,2,TSK:/Users/hmadmooj/AppData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat,74
> 48,-,esedb/msie_webcache,sha256_hash: 7f481ccfdb55d94fe1c0b3692c5fbbe9dfca684ab44acb86ed80264359106994
when i cat my .plaso dump i found this strange date : 09/17/30828 what is that mean !! i think that's why my filter does not count any event ?

**Comment by joachimmetz** [comment] 2019-06-26 15:18
> i think there is an issue with dates ... take a look at this :

there can be many different reasons for strange date and time values, dirty ESE database, expiration dates far in the future, data format changes.

> when i cat my .plaso dump i found this strange date : 09/17/30828 what is that mean !! i think that's why my filter does not count any event ?

no your filter `date < '2019-05-18 12:00:00' and date > '2019-06-11 12:00:00'` is wrong because you are want a date and time that is both before 2019-05-18 and 2019-06-11. Your filter logic is incorrect, if you don't understand this or the reason why date and time values can be off. Plaso is likely not the tool you want to use in the first place.

**Comment by evilcode1** [comment] 2019-06-26 15:22
my brother is not my first time i used this super tool i solve a lot of cases with it but this is my first time i faced all of this issues ...
an i used this argument : date >= '2019-05-18 12:00:00' AND date <= '2019-06-11 12:00:00' 
still event's 0 :(

**Comment by evilcode1** [comment] 2019-06-26 17:52
if u want i can upload the .plaso file and send it 2 u on a inbox

**Comment by joachimmetz** [comment] 2019-06-26 21:36
I was not able to reproduce the behavior you describe, a date filter as I described works for me.

Having the plaso file could be useful, feel free to mail or upload to a file sharing platform.

**Comment by evilcode1** [comment] 2019-06-28 08:48
i send it to ur gmail .. thank u for helping us check it brother <3

**Comment by joachimmetz** [comment] 2019-06-29 09:13
`psort.py -w filter.log 5.plaso "date >= '2019-05-18 12:00:00' AND date <= '2019-06-11 12:00:00'"`

works fine for me

**Comment by joachimmetz** [comment] 2019-07-07 06:56
@evilcode1 any updates from your side? Otherwise I'll close this out, since it looks like an issue caused by and incorrect event filter.

**Comment by joachimmetz** [comment] 2019-07-11 07:44
No input from original reporter in 2 weeks, closing issue. Marking as invalid since unable to reproduce with the correct filter expression.

**Closed by joachimmetz** 2019-07-11 07:44 UTC
Labels: pending reporter input, question
