### ISSUE TITLE
plaso-20190708 - log2timeline.exe (py3.7 x64 binaries) not reading --parser input correctly

### ISSUE THREAD

**Issue by mattnotmax** [log2timeline/plaso#2763] opened 2019-10-31 10:51 UTC
**Description of problem:**

When I run Windows command line for log2timeline.exe for the `plaso-20190708-py3.7-amd64.zip` binaries, the `--parser` argument is not correctly parsed. The logs note incorrectly it is passed `win7` although it appears to attempt to run all the parsers. 

**Command line and arguments:**

Using the SANS 508 .vhdx collection `base-rd01-triage.vhdx`, this is mounted as E:. The log2timeline command:
```
log2timeline.exe --parsers "recycle_bin" D:\plaso_test\20190708_plaso.dump E:\C --log-file=log2timeline_problem.log.gz --debug
```
Result of pinfo shows that the `--parsers recycle_bin` was not respected and the full range of parsers was run.
```
c:\Users\Matt\Desktop\plaso-20190708>pinfo D:\plaso_test\20190708_plaso.dump

************************** Plaso Storage Information ***************************
            Filename : 20190708_plaso.dump
      Format version : 20190309
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
2af86024-c2a8-4878-9bbe-3dc1c2623fef : 2019-10-31T09:55:30.125434Z
--------------------------------------------------------------------------------

**************** Session: 2af86024-c2a8-4878-9bbe-3dc1c2623fef *****************
                Start time : 2019-10-31T09:55:30.125434Z
           Completion time : 2019-10-31T10:00:58.775001Z
              Product name : plaso
           Product version : 20190708
    Command line arguments : log2timeline.exe --parsers recycle_bin
                             D:\plaso_test\20190708_plaso.dump E:\C
                             --log-file=log2timeline_problem.log.gz --debug
  Parser filter expression :
                             amcache,bencode,binary_cookies,chrome_cache,chrome_preferences,custom_destinations,czip/oxml,esedb,esedb/file_history,esedb/msie_webcache,filestat,firefox_cache,gdrive_synclog,java_idx,lnk,mcafee_protection,msiecf,olecf,olecf/olecf_automatic_destinations,opera_global,opera_typed_history,pe,plist/safari_history,prefetch,recycle_bin,sccm,skydrive_log,skydrive_log_old,sqlite/chrome_27_history,sqlite/chrome_8_history,sqlite/chrome_autofill,sqlite/chrome_cookies,sqlite/chrome_extension_activity,sqlite/firefox_cookies,sqlite/firefox_downloads,sqlite/firefox_history,sqlite/google_drive,sqlite/skype,symantec_scanlog,usnjrnl,winevtx,winfirewall,winjob,winreg
Enabled parser and plugins : amcache, bencode, bencode/bencode_transmission,
                             bencode/bencode_utorrent, binary_cookies,
                             chrome_cache, chrome_preferences,
                             custom_destinations, czip, czip/oxml, esedb,
                             esedb/file_history, esedb/msie_webcache,
                             esedb/srum, filestat, firefox_cache,
                             gdrive_synclog, java_idx, lnk, mcafee_protection,
                             msiecf, olecf, olecf/olecf_automatic_destinations,
                             olecf/olecf_default, olecf/olecf_document_summary,
                             olecf/olecf_summary, opera_global,
                             opera_typed_history, pe, plist, plist/airport,
                             plist/apple_id, plist/ipod_device,
                             plist/macosx_bluetooth,
                             plist/macosx_install_history, plist/macuser,
                             plist/maxos_software_update, plist/plist_default,
                             plist/safari_history, plist/spotlight,
                             plist/spotlight_volume, plist/time_machine,
                             prefetch, recycle_bin, sccm, skydrive_log,
                             skydrive_log_old, sqlite, sqlite/android_calls,
                             sqlite/android_sms, sqlite/android_webview,
                             sqlite/android_webviewcache, sqlite/appusage,
                             sqlite/chrome_27_history, sqlite/chrome_8_history,
                             sqlite/chrome_autofill, sqlite/chrome_cookies,
                             sqlite/chrome_extension_activity,
                             sqlite/firefox_cookies, sqlite/firefox_downloads,
                             sqlite/firefox_history, sqlite/google_drive,
                             sqlite/hangouts_messages, sqlite/imessage,
                             sqlite/kik_messenger, sqlite/kodi,
                             sqlite/ls_quarantine,
                             sqlite/mac_document_versions,
                             sqlite/mac_knowledgec, sqlite/mac_notes,
                             sqlite/mac_notificationcenter,
                             sqlite/mackeeper_cache, sqlite/safari_history,
                             sqlite/skype, sqlite/tango_android_profile,
                             sqlite/tango_android_tc, sqlite/twitter_android,
                             sqlite/twitter_ios, sqlite/windows_timeline,
                             sqlite/zeitgeist, symantec_scanlog, usnjrnl,
                             winevtx, winfirewall, winjob, winreg,
                             winreg/appcompatcache, winreg/bagmru,
                             winreg/ccleaner, winreg/explorer_mountpoints2,
                             winreg/explorer_programscache,
                             winreg/microsoft_office_mru,
                             winreg/microsoft_outlook_mru,
                             winreg/mrulist_shell_item_list,
                             winreg/mrulist_string,
                             winreg/mrulistex_shell_item_list,
                             winreg/mrulistex_string,
                             winreg/mrulistex_string_and_shell_item,
                             winreg/mrulistex_string_and_shell_item_list,
                             winreg/msie_zone, winreg/mstsc_rdp,
                             winreg/mstsc_rdp_mru, winreg/network_drives,
                             winreg/networks, winreg/userassist,
                             winreg/windows_boot_execute,
                             winreg/windows_boot_verify, winreg/windows_run,
                             winreg/windows_sam_users, winreg/windows_services,
                             winreg/windows_shutdown,
                             winreg/windows_task_cache,
                             winreg/windows_timezone,
                             winreg/windows_typed_urls,
                             winreg/windows_usb_devices,
                             winreg/windows_usbstor_devices,
                             winreg/windows_version, winreg/winlogon,
                             winreg/winrar_mru, winreg/winreg_default
        Preferred encoding : cp1252
                Debug mode : True
          Artifact filters : N/A
               Filter file : N/A
   Number of event sources : 17867
--------------------------------------------------------------------------------

************************* Events generated per parser **************************
                Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
                      appcompatcache : 796
                              bagmru : 250
                   chrome_27_history : 720
                     chrome_autofill : 185
                        chrome_cache : 5829
                      chrome_cookies : 4622
                  chrome_preferences : 40
               explorer_mountpoints2 : 12
              explorer_programscache : 3
                            filestat : 53597
                     firefox_cookies : 1434
                     firefox_history : 88
               google_analytics_utma : 11
               google_analytics_utmb : 5
               google_analytics_utmt : 4
               google_analytics_utmz : 9
                                 lnk : 1435
                      mrulist_string : 25
           mrulistex_shell_item_list : 10
                    mrulistex_string : 27
     mrulistex_string_and_shell_item : 25
mrulistex_string_and_shell_item_list : 1
                           msie_zone : 72
                           mstsc_rdp : 6
                       mstsc_rdp_mru : 1
                      network_drives : 3
                            networks : 4
        olecf_automatic_destinations : 484
                       olecf_default : 44
                                oxml : 94
                                  pe : 4293
                            prefetch : 1286
                         recycle_bin : 1
                         shell_items : 2304
                          userassist : 121
                windows_boot_execute : 2
                         windows_run : 16
                   windows_sam_users : 12
                    windows_services : 625
                    windows_shutdown : 1
                  windows_task_cache : 587
                    windows_timezone : 1
                  windows_typed_urls : 9
                     windows_version : 4
                             winevtx : 353378
                            winlogon : 4
                      winreg_default : 405293
                               Total : 837773
--------------------------------------------------------------------------------

************************ Warnings generated per parser *************************
 Parser (plugin) name : Number of warnings
--------------------------------------------------------------------------------
          <No parser> : 37
                olecf : 5
sqlite/chrome_cookies : 3
   chrome_preferences : 2
              winevtx : 2973
--------------------------------------------------------------------------------

************************* Pathspecs with most warnings *************************
Number of warnings : Pathspec
--------------------------------------------------------------------------------
               153 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-Audio%4PlaybackManager.evtx
               134 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-Wcmsvc%4Operational.evtx
               124 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-Security-SPP-UX-GenuineCenter-Logging%4Operational.evtx
               122 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-CloudStorageWizard%4Operational.evtx
               122 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\System.evtx
               122 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-AppXDeploymentServer%4Operational.evtx
               116 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-SmbClient%4Connectivity.evtx
               111 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-Diagnosis-Scripted%4Admin.evtx
               106 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-TZSync%4Operational.evtx
               101 : type: OS, location:
                     E:\C\Windows\system32\winevt\logs\Microsoft-Windows-NetworkProfile%4Operational.evtx
--------------------------------------------------------------------------------
No analysis reports stored.
```

This is also evident in the debug logs `log2timeline_problem.log.gz` which identifies it as `win7`
```
2019-10-31 20:55:30,927 [INFO] (MainProcess) PID:15000 <engine> Preprocessing detected operating systems: Windows NT
2019-10-31 20:55:30,927 [DEBUG] (MainProcess) PID:15000 <extraction_tool> Preprocessing done.
2019-10-31 20:55:30,927 [INFO] (MainProcess) PID:15000 <extraction_tool> Parser filter expression set to: win7
2019-10-31 20:55:30,927 [DEBUG] (MainProcess) PID:15000 <log2timeline_tool> Starting extraction in multi process mode.
```

Located on the SANS 508 Windows SIFT workstation are compiled binaries for plaso 20190331. Copying these off and running on the same system as before: 

```
log2timeline.exe --parsers "recycle_bin" D:\plaso_test\20190331_plaso.dump E:\C --log-file=log2timeline_problem.log.gz --debug
```
result of pinfo shows that `--parsers` was correctly identified. 

```
c:\Users\Matt\Desktop\plaso-20190331>pinfo D:\plaso_test\20190331_plaso.dump

************************** Plaso Storage Information ***************************
            Filename : 20190331_plaso.dump
      Format version : 20180101
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
7c38c161-a9c2-442b-8838-92abb6482f51 : 2019-10-31T10:08:49.543000+00:00
--------------------------------------------------------------------------------

**************** Session: 7c38c161-a9c2-442b-8838-92abb6482f51 *****************
                Start time : 2019-10-31T10:08:49.543000+00:00
           Completion time : 2019-10-31T10:13:15.594000+00:00
              Product name : plaso
           Product version : 20190331
    Command line arguments : log2timeline.exe --parsers recycle_bin
                             D:\plaso_test\20190331_plaso.dump E:\C
                             --log-file=log2timeline_problem.log.gz --debug
  Parser filter expression : recycle_bin
Enabled parser and plugins : recycle_bin
        Preferred encoding : cp1252
                Debug mode : True
          Artifact filters : N/A
               Filter file : N/A
--------------------------------------------------------------------------------

************************* Events generated per parser **************************
Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
         recycle_bin : 1
               Total : 1
--------------------------------------------------------------------------------

*********************************** Error: 0 ***********************************
           Message : analyzer failed to determine archive type indicators with
                     error: pysigscan_scanner_scan_file_object: unable to scan
                     file. libsigscan_scanner_scan_file_io_handle: unable to
                     read buffer.
      Parser chain :
Path specification : type: OS, location:
                     E:\C\log2timeline-20191031T082632.log.gz
                   : type: GZIP
--------------------------------------------------------------------------------
No analysis reports stored.
```
**Operating system Plaso is running on:**

Dell XPS15 Windows 10 Pro 1903 x64

**Installation method:**

C++ dependencies have been installed.
Windows binaries for 20190708 unzipped and run direct from Desktop
Windows binaries for 20190331 copied from SANS 508 Windows SIFT workstation and run from Desktop

**Debug output/tracebacks:**
Attached for both versions.
[plaso_test_logs.zip](https://github.com/log2timeline/plaso/files/3793261/plaso_test_logs.zip)

The output of `--troubles` seems to indicate that Python is based on version issue: v2.7.13 for 20190331 and v3.7.3 for 20190708. Apologies I don't have any other compiled Windows versions to test. 

If it makes any difference, I'm only running 3.7 on this system:
```c:\Users\Matt\Desktop\plaso-20190708>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
```

Output of `log2timeline.exe --troubles` for 20190331
```
c:\Users\Matt\Desktop\plaso-20190331>log2timeline.exe --troubles
2019-10-31 21:22:20,568 [INFO] (MainProcess) PID:16012 <data_location> Determined data location: c:\Users\Matt\Desktop\PLASO-~2\data
Using Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]

Path: c:\Users\Matt\Desktop\plaso-20190331\log2timeline.py

plaso - log2timeline version 20190331

Checking availability and versions of dependencies.
[OK]            Crypto version: 2.6.1
[OK]            artifacts version: 20190305
[OK]            bencode
[OK]            biplist
[OK]            certifi version: 2019.03.09
[OK]            chardet version: 3.0.4
[OK]            dateutil version: 2.8.0
[OK]            dfdatetime version: 20190116
[OK]            dfvfs version: 20190128
[OK]            dfwinreg version: 20190311
[OK]            dtfabric version: 20190120
[OPTIONAL]      elasticsearch version: 5.5.1 is too old, 6.0 or later required.
[OK]            future version: 0.17.1
[OK]            idna
[OPTIONAL]      missing: lz4.
[OPTIONAL]      missing: lzma.
[OK]            pefile version: 2018.8.8
[OK]            psutil version: 5.6.1
[OK]            pybde version: 20190317
[OK]            pyesedb version: 20181229
[OK]            pyevt version: 20181227
[OK]            pyevtx version: 20181227
[OK]            pyewf version: 20170703
[OK]            pyfsapfs version: 20190210
[OK]            pyfsntfs version: 20190104
[OK]            pyfvde version: 20190104
[OK]            pyfwnt version: 20181227
[OK]            pyfwsi version: 20181227
[OK]            pylnk version: 20181227
[OK]            pymsiecf version: 20181227
[OK]            pyolecf version: 20181231
[OK]            pyparsing version: 2.3.1
[OK]            pyqcow version: 20181227
[OK]            pyregf version: 20190303
[OK]            pyscca version: 20181227
[OK]            pysigscan version: 20190103
[OK]            pysmdev version: 20190315
[OK]            pysmraw version: 20181227
[OK]            pytsk3 version: 20190121
[OK]            pytz
[OK]            pyvhdi version: 20181227
[OK]            pyvmdk version: 20181227
[OK]            pyvshadow version: 20190127
[OK]            pyvslvm version: 20181227
[OK]            requests version: 2.21.0
[OK]            six version: 1.12.0
[OK]            sqlite3
[OK]            urllib3 version: 1.24.1
[OK]            xlsxwriter version: 1.1.5
[OK]            yaml version: 5.1
[OK]            yara version: 3.8.1
[OK]            zmq version: 18.0.1
[OK]            pysqlite2.dbapi2 version: 3.19.2

Also see: https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html
```

and for version 20190708
```
c:\Users\Matt\Desktop\plaso-20190708>log2timeline.exe --troubles
2019-10-31 21:23:22,033 [INFO] (MainProcess) PID:3744 <data_location> Determined data location: c:\Users\Matt\Desktop\plaso-20190708\data
Using Python version 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

Path: c:\Users\Matt\Desktop\plaso-20190708\log2timeline.py

plaso - log2timeline version 20190708

Checking availability and versions of dependencies.
[OK]            Crypto version: 2.6.1
[OK]            artifacts version: 20190320
[OK]            bencode
[OK]            biplist
[OK]            certifi version: 2019.06.16
[OK]            chardet version: 3.0.4
[OK]            dateutil version: 2.8.0
[OK]            defusedxml version: 0.6.0
[OK]            dfdatetime version: 20190517
[OK]            dfvfs version: 20190609
[OK]            dfwinreg version: 20190517
[OK]            dtfabric version: 20190120
[OK]            elasticsearch version: 6.3.1
[OK]            future version: 0.17.1
[OK]            idna
[OPTIONAL]      missing: lz4.
[OK]            lzma
[OK]            pefile version: 2019.4.18
[OK]            psutil version: 5.6.3
[OK]            pybde version: 20190701
[OK]            pyesedb version: 20181229
[OK]            pyevt version: 20181227
[OK]            pyevtx version: 20190619
[OK]            pyewf version: 20140807
[OK]            pyfsapfs version: 20190510
[OK]            pyfsntfs version: 20190104
[OK]            pyfvde version: 20190104
[OK]            pyfwnt version: 20181227
[OK]            pyfwsi version: 20181227
[OK]            pylnk version: 20181227
[OK]            pymsiecf version: 20181227
[OK]            pyolecf version: 20181231
[OK]            pyparsing version: 2.4.0
[OK]            pyqcow version: 20181227
[OK]            pyregf version: 20190303
[OK]            pyscca version: 20190605
[OK]            pysigscan version: 20190629
[OK]            pysmdev version: 20190315
[OK]            pysmraw version: 20181227
[OK]            pytsk3 version: 20190506
[OK]            pytz
[OK]            pyvhdi version: 20181227
[OK]            pyvmdk version: 20181227
[OK]            pyvshadow version: 20190323
[OK]            pyvslvm version: 20181227
[OK]            requests version: 2.22.0
[OK]            six version: 1.12.0
[OK]            sqlite3 version: 3.21.0
[OK]            urllib3 version: 1.25.3
[OK]            xlsxwriter version: 1.1.8
[OK]            yaml version: 5.1.1
[OK]            yara version: 3.10.0
[OK]            zmq version: 18.0.2
```

Looking at old issues not sure if it relates to:
https://github.com/log2timeline/plaso/issues/2665

Apologies in advance if this is a user-issue. I've been racking my brains and can't get it to work for the new version. Thanks for a great tool.

**Comment by joachimmetz** [comment] 2019-10-31 10:55
Looks like this is a duplicate of https://github.com/log2timeline/plaso/issues/2732

**Comment by mattnotmax** [comment] 2019-10-31 10:57
Grr.. apologies. How did I not see this! Thanks

**Comment by joachimmetz** [comment] 2019-10-31 10:57
20190916 release is still WIP (see: https://github.com/log2timeline/plaso/issues/2755)

However note that we might discontinue the PyInstaller builds due to previous issues with PyInstaller and the need for funding by the PyInstaller project (http://www.pyinstaller.org/funding.html).

**Comment by joachimmetz** [comment] 2019-10-31 10:59
We'll see if we can finalize the 20190916 release, when time permits. However both @Onager and my time has been limited the last months.

**Comment by joachimmetz** [comment] 2019-10-31 10:59
Closing issue.

**Comment by mattnotmax** [comment] 2019-10-31 10:59
Ok, noted with thanks. Happy to close if you see fit.

**Closed by joachimmetz** 2019-10-31 10:59 UTC
Labels: duplicate
