### ISSUE TITLE
Unexplained Input/output error

### ISSUE THREAD

**Issue by ricci3** [log2timeline/plaso#978] opened 2016-09-04 04:29 UTC
**Plaso version:**
Plaso Engine: 1.4.0, Python 2.7.6
**Operating system Plaso is running on:**
Ubuntu 14.04.5 LTS
**Installation method:**
Installed using SIFT
**Description of problem:**
When I execute Log2timeline.py, it terminated after executing for a short while with the following error message.

Please advise how to fix that?
**Debug output/tracebacks:**
2016-09-04 12:04:51,074 [WARNING] (MainProcess) PID:4265 <xmlrpc> Error while making RPC call: [Errno 111] Connection refused
2016-09-04 12:04:51,173 [ERROR] (MainProcess) PID:4265 <multi_process> Process Collector (PID: 6586) is not functioning correctly. Status code killed.
2016-09-04 12:04:51,181 [WARNING] (MainProcess) PID:4265 <multi_process> Processing aborted with engine error: Collector unexpectedly terminated.
2016-09-04 12:04:51,199 [WARNING] (MainProcess) PID:4265 <multi_process> Terminating process: StorageWriter (PID: 6584).
2016-09-04 12:04:51,202 [WARNING] (MainProcess) PID:4265 <multi_process> Terminating process: Worker_00 (PID: 6588).
2016-09-04 12:04:51,206 [WARNING] (MainProcess) PID:4265 <multi_process> Terminating process: Worker_01 (PID: 6590).
2016-09-04 12:04:51,552 [WARNING] (StorageWriter) PID:6584 <multi_process> Unhandled exception in storage writer (PID: 6584).
2016-09-04 12:04:51,570 [ERROR] (StorageWriter) PID:6584 <multi_process> [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/multi_process.py", line 1428, in _Main
    self._storage_writer.WriteEventObjects()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/writer.py", line 62, in WriteEventObjects
    self._Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/writer.py", line 92, in _Close
    self._storage_file.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 1585, in Close
    self._WritePreprocessObject(self._pre_obj)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 1501, in _WritePreprocessObject
    self._WriteStream(u'information.dump', stream_data)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 919, in _WriteStream
    self._zipfile.writestr(stream_name, stream_data)
  File "/usr/lib/python2.7/zipfile.py", line 1243, in writestr
    self.fp.flush()
IOError: [Errno 5] Input/output error
2016-09-04 12:05:04,073 [WARNING] (MainProcess) PID:4265 <multi_process> Killing process: Worker_00 (PID: 6588).
2016-09-04 12:05:04,079 [WARNING] (MainProcess) PID:4265 <multi_process> Killing process: Worker_01 (PID: 6590).
Processing completed with errors.

**Comment by joachimmetz** [comment] 2016-09-04 08:30
Any indication what the cause of the IOError is? available space on the file system?

**Comment by ricci3** [comment] 2016-09-04 09:00
The output was put to an SSD located on FAT32 environment. There should be sufficient disk space on the disk. Any suggestions?

**Comment by joachimmetz** [comment] 2016-09-04 09:02
Maybe the ZIP file is exceeding the maximum FAT-32 file size?

**Comment by ricci3** [comment] 2016-09-04 09:08
But when will zip file be created? I saw that the issue happen at the beginning when generating the dump file.

**Comment by joachimmetz** [comment] 2016-09-04 09:13
The error indicates `Input/output error`, which refers to some low-level error likely outside of plaso. Have a look at your system logs to see what the root cause is. Also FAT-32 has a small maximum file size I recommend using another file system.

**Comment by joachimmetz** [comment] 2016-09-11 12:28
@ricci3 any update on additional information e.g. from your system logs? I'm closing this issue now, will reopen if there is more information.

**Closed by joachimmetz** 2016-09-11 12:28 UTC
Labels: question
