### ISSUE TITLE
Feature request : Add Srum database 

### ISSUE THREAD

**Issue by nwf9** [log2timeline/plaso#1127] opened 2017-01-15 04:59 UTC
Add the new parser Srum database parser into the timeline https://github.com/williballenthin/srum-dump

**Comment by joachimmetz** [comment] 2017-01-15 07:51
Duplicate of: https://github.com/log2timeline/plaso/issues/427

**Closed by joachimmetz** 2017-01-15 07:51 UTC
Labels: duplicate

**Comment by joachimmetz** [comment] 2018-01-18 07:23
For context https://github.com/williballenthin/srum-dump is an out of date fork (copy) of https://github.com/MarkBaggett/srum-dump with some alterations.
