### ISSUE TITLE
libtsk/pytsk failing to detect NTFS file system in VHD

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#2226] opened 2018-11-30 02:58 UTC
**Description of problem:**
log2timeline is not processing the files inside a vhd when the vhd is provided as the source.  It does produce a database file. When running pinfo on the database file you can see that there no events generated. The files in the vhd should produce events. Mounting the vhd as a drive and using it as a source, log2timeline processes the files and generates events as expected.  The attached log file has an error that a file can't be opened.

I grabbed the image.vhd from GitHub and processed with the same command.  Same results,  no events generated. Additionally,  the image.vhd file can't be mounted in Windows.  At least not in the normal fashion. 

I have attached the database, pinfo and log files.  I can provide the vhd if needed.  22gb.

-Mark

**Command with arguments**

`log2timeline --debug --logfile logs\tarpon.log --no_dependencies_check tarpon.plaso tarpon.vhd
`

**Plaso version:** Windows binaries - 20180930

**Comment by joachimmetz** [comment] 2018-11-30 07:17
I'm not able to reproduce this with image.vhd with HEAD on Linux. 

Can you share the tarpon.log.

> Additionally, the image.vhd file can't be mounted in Windows. At least not in the normal fashion.

Can you elaborate. What is the "normal fashion" in your perspective?

> I can provide the vhd if needed. 22gb.

Yes this could be useful, please drop me a mail and I can have look.

**Comment by mark-hallman** [comment] 2018-11-30 13:44
Joachim,

I have attached log, pinfo and database, everthing but the actual vhd.  I will provide a download link separately for the that.   

How do I get the list of dependencies for the Windows versions?  I don't see anything like "check_dependencies.py" that is provided in the Linux version.  

What I meant my "normal fashion" was either mounting the vhd with the Windows Disk Management Utility or just double clicking the vhd. What should i expect to see in th image.vhd test file?

I will rerun these tests in Lunix and provide the results.

Thanks for looking into this. 

-Mark

[plaso_vhd_tests.zip](https://github.com/log2timeline/plaso/files/2633376/plaso_vhd_tests.zip)

**Comment by joachimmetz** [comment] 2018-12-02 16:35
```
vhdiinfo base-rd01-triage.vhd
vhdiinfo 20181125

Virtual Hard Disk (VHD) image information:
	Format:			1.0
	Disk type:		Dynamic
	Media size:		10 GiB (10835984384 bytes)
	Identifier:		de26377d-e2bd-4d1d-b9ac-2063900427f1
```

```
mmls fuse/vhdi1 
DOS Partition Table
Offset Sector: 0
Units are in 512-byte sectors

      Slot      Start        End          Length       Description
000:  Meta      0000000000   0000000000   0000000001   Primary Table (#0)
001:  -------   0000000000   0000000062   0000000063   Unallocated
002:  000:000   0000000063   0021157604   0021157542   NTFS / exFAT (0x07)
003:  -------   0021157605   0021164031   0000006427   Unallocated
```

```
fls -o 63 fuse/vhdi1 
Cannot determine file system type
```

**For some reason libtsk 4.6.0 is not able to detect the NTFS file system**

```
fls -v -o 63 fuse/vhdi1 

...
ntfs_open: Incorrect NTFS magic
...
```

**libtsk thinks the volume signature is wrong?**

```
fsntfsinfo -o $(( 63 * 512 )) fuse/vhdi1
fsntfsinfo 20180910

Windows NT File System information:

Volume information:
	Name				: base-rd01-triage
	Version				: 3.1
	Serial number			: fecac6e0452e96eb
	Cluster block size		: 4096
	MFT entry size			: 1024
	Index entry size		: 4096
```

**libfsntfs thinks the signature is fine.**

https://github.com/sleuthkit/sleuthkit/blob/9e4bc4b5c0d34dcb266191558337be1e199af3da/tsk/fs/ntfs.c#L4989
```
    /* Check the magic value */
    if (tsk_fs_guessu16(fs, ntfs->fs->magic, NTFS_FS_MAGIC)) {
        tsk_error_reset();
        tsk_error_set_errno(TSK_ERR_FS_MAGIC);
        tsk_error_set_errstr("Not a NTFS file system (magic)");
        if (tsk_verbose)
            fprintf(stderr, "ntfs_open: Incorrect NTFS magic\n");
        goto on_error;
    }
```

https://github.com/sleuthkit/sleuthkit/blob/9e4bc4b5c0d34dcb266191558337be1e199af3da/tsk/fs/tsk_ntfs.h#L31
```
//#define NTFS_FS_MAGIC 0x5346544E      /* "NTFS" in little endian */
#define NTFS_FS_MAGIC	0xAA55
```

```
hexdump -Cv -s $(( 63 * 512 )) fuse/vhdi1

00007e00  00 00 00 4e 54 46 53 20  20 20 20 00 02 08 00 00  |...NTFS    .....|
00007e10  00 00 00 00 00 f8 00 00  3f 00 ff 00 3f 00 00 00  |........?...?...|
00007e20  00 00 00 00 80 00 80 00  a5 d6 42 01 00 00 00 00  |..........B.....|
00007e30  19 09 04 00 00 00 00 00  6a 2d 14 00 00 00 00 00  |........j-......|
00007e40  f6 00 00 00 01 00 00 00  eb 96 2e 45 e0 c6 ca fe  |...........E....|
00007e50  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
...
00007ff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

**Comment by joachimmetz** [comment] 2018-12-02 16:37
@mark-hallman looks like libtsk (used by pytsk, used by dfVFS, used by plaso) is failing to detect the NTFS file system. Unclear why it is checking for 0xAA55 instead of 0x5346544E.

**Comment by joachimmetz** [comment] 2018-12-03 09:12
I've created an issue upstream: https://github.com/sleuthkit/sleuthkit/issues/1382

**Comment by mark-hallman** [comment] 2018-12-03 13:12
Thanks Joachimn,  I will continue to track in Plaso & TSK.

**Comment by joachimmetz** [comment] 2018-12-15 12:08
Looks like upstream is not responding.

Unfortunately there is no short term (structural) fix. Couple of workarounds:
* patch libtsk/pytsk
* mount the file system with ntfs3g (or equiv)

For the structural fix https://github.com/log2timeline/dfvfs/issues/352

Closing this issue seeing this lies outside our control.

**Closed by joachimmetz** 2018-12-15 12:08 UTC
Labels: dependency

**Comment by joachimmetz** [comment] 2020-05-03 09:51
@mark-hallman log2timeline/dfvfs#352 has been resolved. Have a look with the plaso 20200430 testing pre-release (or wait for the release) and see if that addresses the issue.
