### ISSUE TITLE
psort & multiprocessing

### ISSUE THREAD

**Issue by garanews** [log2timeline/plaso#2529] opened 2019-05-15 15:24 UTC
Is it possible to set in some way the possibility to use all CPU cores when doing psort? (output timesketch)
Thanks

**Comment by joachimmetz** [comment] 2019-05-15 16:07
What do you want to have these CPU cores do?

I assume you mean something like: https://github.com/log2timeline/plaso/issues/2501

**Comment by garanews** [comment] 2019-05-17 07:52
when using log2timeline I see all cpu used 100%:
![image](https://user-images.githubusercontent.com/16938405/57911570-6791bb00-7888-11e9-8e9a-f0f07b6e2803.png)

When running psort I see only one cpu used:
![image](https://user-images.githubusercontent.com/16938405/57911740-da029b00-7888-11e9-9e01-396d5eb19264.png)


I presume psort is ordering data contained in plaso file and is using a single process, but why ordering data if I send to timesketch (elasticsearch)? this action (order things by datatime) is already done by database so why spend time running psort (and single cpu) to order the things?

**Comment by joachimmetz** [comment] 2019-05-17 08:36
> I presume psort is ordering data contained in plaso file and is using a single process, but why ordering data if I send to timesketch (elasticsearch)?

this is because at the time it was added plaso was focussing on text file based output.

In relation to #2501 we could add something that ignores ordering and de-duplication of output types that could do this more efficiently themselves.

**Comment by joachimmetz** [comment] 2019-05-17 09:42
@garanews thx for the additional output I've marked this as a duplicate of #2501, where the tl;dr is optimize ES and TS output modules for performance

**Closed** 2019-05-17 09:42 UTC
Labels: duplicate, output, question
