### ISSUE TITLE
Failed AppVeyor test SRUM

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1922] opened 2018-06-04 10:38 UTC
See: https://ci.appveyor.com/project/joachimmetz/plaso/build/4618/job/sxuhl116hw5m2vqc

**Comment by joachimmetz** [comment] 2018-06-13 03:47
This is a duplicate of: https://github.com/log2timeline/plaso/issues/1791

**Closed by joachimmetz** 2018-06-13 03:47 UTC
Labels: testing
