### ISSUE TITLE
ImportError: cannot import name analysis, environment issue?

### ISSUE THREAD

**Issue by jasonblanks** [log2timeline/plaso#133] opened 2015-03-10 18:48 UTC
at some point between updating git source, psort has broke.  Unsure if this is an environment/user error on my side or not. Hoping maybe you might have suggestions.  setup.py build/install kick off without errors.

jason@Danzig:~/Dev/test/plaso$ psort.py
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150310', u'psort.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150310-py2.7.egg/EGG-INFO/scripts/psort.py", line 21, in <module>
    from plaso import analysis
ImportError: cannot import name analysis

jason@Danzig:~/Dev/test/plaso$ ./utils/check_dependencies.py 
Checking availability and versions of plaso dependencies.
[OK]		bencode
[OK]		binplist version: 0.1.4
[OK]		construct version: 2.5.2
[OK]		dateutil.parser
[OK]		dfvfs version: 20150224
[OK]		dpkt version: 1.8
[OK]		google.protobuf
[OK]		hachoir_core version: 1.3.3
[OK]		hachoir_parser version: 1.3.4
[OK]		hachoir_metadata version: 1.3.3
[OK]		IPython version: 1.2.1
[OK]		yaml version: 3.11
[OK]		psutil version: 2.2.1
[OK]		pyparsing version: 2.0.3
[OK]		pytz
[OK]		six version: 1.9.0
[OK]		sqlite3 version: 3.8.2
[OK]		SleuthKit version: 4.1.3
[OK]		pytsk3 version: 20140506
[OK]		libbde (pybde) version: 20150204
[OK]		libesedb (pyesedb) version: 20141110
[OK]		libevt (pyevt) version: 20150105
[OK]		libevtx (pyevtx) version: 20150105
[OK]		libewf (pyewf) version: 20150126
[OK]		libfwsi (pyfwsi) version: 20150124
[OK]		liblnk (pylnk) version: 20150105
[OK]		libmsiecf (pymsiecf) version: 20150106
[OK]		libolecf (pyolecf) version: 20150106
[OK]		libqcow (pyqcow) version: 20150105
[OK]		libregf (pyregf) version: 20150105
[OK]		libsigscan (pysigscan) version: 20150125
[OK]		libsmdev (pysmdev) version: 20150105
[OK]		libsmraw (pysmraw) version: 20150105
[OK]		libvhdi (pyvhdi) version: 20150110
[OK]		libvmdk (pyvmdk) version: 20150105
[OK]		libvshadow (pyvshadow) version: 20150106

further:
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150310-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

jason@Danzig:~/Dev/test/plaso$ ls /usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150310-py2.7.egg/ 
>EGG-INFO  plaso  share

Dev/test/plaso$ ls /usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150310-py2.7.egg/plaso

>analysis   engine  filters     frontend  __init__.py   lib               output   preprocessors  serializer  unix   winreg
artifacts  events  formatters  hashers   __init__.pyc  multi_processing  parsers  proto          storage     winnt

**Comment by jasonblanks** [comment] 2015-03-10 19:34
further:
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150310-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

jason@Danzig:~/Dev/plaso/plaso$ ls /usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150310-py2.7.egg/
EGG-INFO  plaso  share
---------------------
jason@Danzig:~/Dev/plaso/plaso$ ls /usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150310-py2.7.egg/plaso
analysis   engine  filters     frontend  __init__.py   lib               output   preprocessors  serializer  unix   winreg
artifacts  events  formatters  hashers   __init__.pyc  multi_processing  parsers  proto          storage     winnt

**Comment by joachimmetz** [comment] 2015-03-13 19:08
Often the cause of these type of issue is caused by having multiple versions of plaso installed side-by-side. Try setting PYTHONPATH manually.

**Comment by joachimmetz** [comment] 2015-03-15 03:02
Can you also try running ./run_tests.py.

**Comment by jasonblanks** [comment] 2015-03-17 16:24
Regarding the initial question, adding the below to to .bashrc fixed this for me.
PYTHONPATH="${PYTHONPATH}:/usr/lib/python2.7/dist-packages"
export PYTHONPATH

running a ./run_tests.py on a fresh git clone with no changes, and check_dependencies all ok:

======================================================================
ERROR: testScanSource (plaso.frontend.frontend_test.ExtractionFrontendTests)
Tests the ScanSource function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/test/plaso/plaso/frontend/frontend_test.py", line 194, in testScanSource
    self._TestScanSourcePartitionedImage(test_file)
  File "/home/jason/Dev/test/plaso/plaso/frontend/frontend_test.py", line 78, in _TestScanSourcePartitionedImage
    test_front_end.ScanSource(options)
  File "/home/jason/Dev/test/plaso/plaso/frontend/frontend.py", line 736, in ScanSource
    self._scan_context, scan_path_spec=scan_path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 406, in Scan
    return self._ScanNode(scan_context, scan_node)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 265, in _ScanNode
    source_path_spec = self.ScanForVolumeSystem(scan_node.path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 513, in ScanForVolumeSystem
    source_path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 342, in GetVolumeSystemTypeIndicators
    resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 182, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_io.py", line 75, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_object_io.py", line 63, in _Open
    self._file_object = self._OpenFileObject(path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/ewf_file_io.py", line 86, in _OpenFileObject
    ewf_handle.open_file_objects(self._file_objects)
IOError: pyewf_handle_open_file_objects: unable to open file. libewf_segment_table_append_segment_by_segment_file: invalid segment table. libewf_handle_open_file_io_pool: unable to append segment: 1 to segment table.

----------------------------------------------------------------------
Ran 405 tests in 63.894s

**Comment by jasonblanks** [comment] 2015-03-18 22:15
As a test I created a new ubuntu vm from scratch and rebuilt everything. Same issue.

**Comment by joachimmetz** [comment] 2015-03-20 12:09
>  As a test I created a new ubuntu vm from scratch and rebuilt everything. Same issue.

Which issue "ImportError: cannot import name analysis" or "IOError: pyewf_handle_open_file_objects: unable to open file" ?

**Comment by joachimmetz** [comment] 2015-03-31 05:44
No reply from OP, closing issue, reopen if still persists.

**Closed by joachimmetz** 2015-03-31 05:44 UTC
Labels: question
