### ISSUE TITLE
Pre-Compiled windows binaries like plaso-20191203

### ISSUE THREAD

**Issue by angry-bender** [log2timeline/plaso#3991] opened 2021-12-14 06:04 UTC
**Description of problem:**

There hasn't been a pre-compiled version of plaso since 2019. Is it possible to re-include this as part of the release packages.

The binaries at https://github.com/log2timeline/l2tbinaries are not very user friendly to use, as they require the installation of around 20-30 msi's and the user documentation doesn't document this process at all, if I have interpreted the instructions correctly. 

Having a precompiled executable for windows is by far the easiest way to run in a windows environment.

**Comment by joachimmetz** [comment] 2021-12-14 06:06
@angry-bender you can create these yourself https://plaso.readthedocs.io/en/latest/sources/developer/Packaging-with-pyinstaller.html

If you are volunteering to help maintain the packed executables let me know

**Comment by joachimmetz** [comment] 2021-12-14 06:07
Duplicate of https://github.com/log2timeline/plaso/issues/3003

**Closed by joachimmetz** 2021-12-14 06:06 UTC
