### ISSUE TITLE
Only VSS recognized. 

### ISSUE THREAD

**Issue by unicornhippo** [log2timeline/plaso#700] opened 2016-05-11 00:04 UTC
Version 1.4.0 running on Ubuntu 14.04

Installed via the SIFT Workstation bootstrap as of 5/9/2016. Using:

```
wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash 

-s -- -i

Two separate attempts:

1.  log2timeline.py plaso.dump /mnt/bde/bde1 (mounted via bdemount to decrypt)


This listed VSS1-VSS10 (no other partitions indicated).


2. log2timeline.py plaso.dump image.raw  

Two partitions entered with one being the encrypted one.

Entered necessary information to decrypt.

This listed the same VSS1-VSS10 (no other partitions indicated)


For both options, log2timeline only lists VSS partitions.  

In both cases I went ahead and selected the most recent VSS to see what happened:

plaso -log2timeline Version 1.4.0

Source path /mnt/bde/bde1
Source type storage media image

Identifier    PID   Status   Events    File
Collector     75983     running
Worker_00     75986     running 40 (0) VSS10:TSK /pagefile.sys
Worker_01          running       8 (0) VSS10: TSK /hiberfil.sys
StorageWriter      sleeping     48 (0)

Processing completed without errors.

* This is the same regardless of whether I use option one or option two (running against raw image or /bde1 image).

Do I need to convert the raw image file to EWF for this to work properly?  I saw that raw images 

are supported with log2timeline.py.


Debug output:

plaso - log2timeline version 1.4.0

Source path	:directory/rawimage.001
Source type	: storage media image

Identifier	PID	Status		Events		File
Collector	75983	running			
Worker_00	75986	running		12257 (0)	VSS10:TSK:/pagefile.sys
Worker_01	75989	running		409 (0)		VSS10:TSK:/hiberfil.sys
StorageWriter	75981	sleeping	12666 (0)	

2016-05-10 16:56:11,536 [DEBUG] (MainProcess) PID:75975 <processing_status> Processing incomplete - extraction still in progress.
2016-05-10 16:56:11,536 [ERROR] (MainProcess) PID:75975 <multi_process> Workers idle for too long
2016-05-10 16:56:11,536 [WARNING] (MainProcess) PID:75975 <multi_process> Processing aborted with engine error: Workers idle for too long.
2016-05-10 16:56:11,537 [DEBUG] (MainProcess) PID:75975 <multi_process> Stopping extraction processes.
2016-05-10 16:56:11,537 [DEBUG] (MainProcess) PID:75975 <multi_process> Process: Worker_00 (PID: 75986) has been removed from the monitoring list.
2016-05-10 16:56:11,537 [DEBUG] (MainProcess) PID:75975 <multi_process> Process: Worker_01 (PID: 75989) has been removed from the monitoring list.
2016-05-10 16:56:11,537 [DEBUG] (MainProcess) PID:75975 <multi_process> Process: StorageWriter (PID: 75981) has been removed from the monitoring list.
2016-05-10 16:56:11,537 [DEBUG] (MainProcess) PID:75975 <multi_process> Process: Collector (PID: 75983) has been removed from the monitoring list.
2016-05-10 16:56:11,539 [WARNING] (MainProcess) PID:75975 <multi_process> Terminating process: Worker_00 (PID: 75986).
2016-05-10 16:56:11,539 [WARNING] (MainProcess) PID:75975 <multi_process> Terminating process: Worker_01 (PID: 75989).
2016-05-10 16:56:11,540 [WARNING] (MainProcess) PID:75975 <multi_process> Terminating process: StorageWriter (PID: 75981).
2016-05-10 16:56:11,540 [WARNING] (MainProcess) PID:75975 <multi_process> Terminating process: Collector (PID: 75983).
2016-05-10 16:56:11,540 [DEBUG] (MainProcess) PID:75975 <multi_process> Emptying queues.
2016-05-10 16:56:11,563 [DEBUG] (MainProcess) PID:75975 <multi_process> Waiting for process: Worker_00 (PID: 75986).
2016-05-10 16:56:11,564 [DEBUG] (StorageWriter) PID:75981 <queue> ConsumeItems exiting, dequeued QueueAbort object.
2016-05-10 16:56:12,820 [DEBUG] (StorageWriter) PID:75981 <zip_file> [Storage] Closing the storage, number of events added: 12666
2016-05-10 16:56:12,821 [DEBUG] (StorageWriter) PID:75981 <multi_process> Storage writer (PID: 75981) stopped.
2016-05-10 16:56:15,042 [DEBUG] (StorageWriter) PID:75981 <multi_process> Process: StorageWriter process status RPC server stopped
2016-05-10 16:56:15,042 [DEBUG] (StorageWriter) PID:75981 <multi_process> Process: StorageWriter (PID: 75981) stopped
2016-05-10 16:56:16,564 [DEBUG] (MainProcess) PID:75975 <multi_process> Waiting for process: Worker_01 (PID: 75989).
2016-05-10 16:56:21,565 [DEBUG] (MainProcess) PID:75975 <multi_process> Waiting for process: StorageWriter (PID: 75981).
2016-05-10 16:56:21,566 [DEBUG] (MainProcess) PID:75975 <multi_process> Process StorageWriter (PID: 75981) stopped.
2016-05-10 16:56:21,566 [DEBUG] (MainProcess) PID:75975 <multi_process> Waiting for process: Collector (PID: 75983).
2016-05-10 16:56:26,567 [WARNING] (MainProcess) PID:75975 <multi_process> Killing process: Worker_00 (PID: 75986).
2016-05-10 16:56:26,567 [WARNING] (MainProcess) PID:75975 <multi_process> Killing process: Worker_01 (PID: 75989).
2016-05-10 16:56:26,567 [WARNING] (MainProcess) PID:75975 <multi_process> Killing process: Collector (PID: 75983).
```

**Comment by joachimmetz** [comment] 2016-05-11 04:23
> log2timeline.py plaso.dump /mnt/bde/bde1 (mounted via bdemount to decrypt)
> This listed VSS1-VSS10 (no other partitions indicated).

So:
1. /mnt/bde/bde1 is the decrypted BitLocker volume which can contain VSS. Why would you expect partions here? (Also see: http://unix.stackexchange.com/questions/87300/differences-between-volume-partition-and-drive)
2. plaso will only ask about how to process VSS it finds and assumes the current volume (in this case the decrypted BDE volume) by default - there is a pending feature request to change this

> log2timeline.py plaso.dump image.raw
> Two partitions entered with one being the encrypted one.
> This is the same regardless of whether I use option one or option two (running against raw image or /bde1 image).

So to me this sounds like working as intended

> Do I need to convert the raw image file to EWF for this to work properly?

What are you expecting that log2timeline.py is not giving you? Why do you think converting to an EWF is going to change anything?

**Comment by unicornhippo** [comment] 2016-05-11 15:40
I think partition was the incorrect word to use.  Besides that it does not seem to be pulling information from all directories/files, just from what appears to be the partition that was never encrypted.  I am going to run it again.  Let me grab more information.  When it completes the process, it has stated "Process completed with errors."  I think some of that can be seen in the information at the bottom of my initial request.  Thank you for responding so fast.

**Comment by unicornhippo** [comment] 2016-05-11 15:57
Here it is:

I think this is actually an issue with Python running on this Ubuntu installation.  Errors are the end.  

root@ubuntu:/media/xxx/xxx/xxxx20160427-1# log2timeline.py test.plaso xxxx20160427-1-1.001
Checking availability and versions of plaso dependencies.
[OK]

The following partitions were found:
Identifier	Offset (in bytes)	Size (in bytes)
p1		1048576 (0x00100000)	1.0GiB / 1.1GB (1073741824 B)
p2		1074790400 (0x40100000)	475.9GiB / 511.0GB (511033999360 B)

Please specify the identifier of the partition that should be processed.
All partitions can be defined as: "all". Note that you can abort with Ctrl^C.

all

Found a BitLocker encrypted volume.
Supported credentials:

  0. startup_key
  1. recovery_password
  2. password
  3. skip

Note that you can abort with Ctrl^C.

Select a credential to unlock the volume: 1


The following Volume Shadow Snapshots (VSS) were found:
Identifier		Creation Time
vss1			2016-01-16T14:54:15.182938+00:00
vss10			2016-04-21T21:22:53.787001+00:00
vss2			2016-01-18T23:53:03.735320+00:00
vss3			2016-01-20T04:03:37.140475+00:00
vss4			2016-01-24T21:33:12.147050+00:00
vss5			2016-01-29T17:48:26.990079+00:00
vss6			2016-02-02T20:20:01.325151+00:00
vss7			2016-02-25T15:03:46.772887+00:00
vss8			2016-03-08T22:45:42.938516+00:00
vss9			2016-03-29T21:36:53.990114+00:00

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores can
be defined as: 1,3,5 (a list of comma separated values). Ranges and lists can
also be combined as: 1,3..5. The first store is 1. All stores can be defined
as "all". If no stores are specified none will be processed. You
can abort with Ctrl^C.
vss9


plaso - log2timeline version 1.4.0

Source path	: /media/xxx/xxx/xxx20160427-1/xxx20160427-1-1.001
Source type	: storage media image

Identifier	PID	Status		Events		File
Collector	3942	running			
Worker_00	3945	sleeping	12225 (0)	TSK:/$Extend/$UsnJrnl:$J
Worker_01	3948	sleeping	393 (0)		TSK:/System Volume Information/EfaSIDat/SYMEFA.DB
StorageWriter	3940	sleeping	12618 (0)	

2016-05-11 08:53:34,604 [ERROR] (MainProcess) PID:3930 <multi_process> Process Collector (PID: 3942) is not functioning correctly. Status code killed.
2016-05-11 08:53:34,605 [WARNING] (MainProcess) PID:3930 <multi_process> Processing aborted with engine error: Collector unexpectedly terminated.
2016-05-11 08:53:34,605 [WARNING] (MainProcess) PID:3930 <multi_process> Terminating process: Worker_00 (PID: 3945).
2016-05-11 08:53:34,606 [WARNING] (MainProcess) PID:3930 <multi_process> Terminating process: StorageWriter (PID: 3940).
2016-05-11 08:53:34,606 [WARNING] (MainProcess) PID:3930 <multi_process> Terminating process: Worker_01 (PID: 3948).
Processing completed with errors.

--

Some of the error messages I was able to grab while it was running:


2016-05-11 08:53:31,515 [WARNING] (Collector ) PID:3942 <multi_process> Unhandled exception in collector (PID: 3942).
2016-05-11 08:53:31,515 [ERROR] (Collector ) PID:3942 <multi_process> Directory_Con: (tsk3.c:361) Unable to open directory: Error in metadata structure (Extension record 184 (file ref = 0) is not for attribute list of 37830)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/multi_process.py", line 286, in _Main
    self._collector.Collect(self._source_path_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 124, in Collect
    source_path_spec, find_specs=self._filter_find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 105, in _ProcessPathSpec
    self._ProcessFileSystem(path_spec, find_specs=find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 61, in _ProcessFileSystem
    self._fs_collector.Collect(file_system, path_spec, find_specs=find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 327, in Collect
    self._ProcessDirectory(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 255, in _ProcessDirectory
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_entry.py", line 439, in sub_file_entries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 67, in entries
    for entry in self._EntriesGenerator():
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_entry.py", line 77, in _EntriesGenerator
    tsk_directory = fs_info.open_dir(path=location)
IOError: Directory_Con: (tsk3.c:361) Unable to open directory: Error in metadata structure (Extension record 184 (file ref = 0) is not for attribute list of 37830)

**Comment by joachimmetz** [comment] 2016-05-11 18:40
> "Process completed with errors."

FYI this is a generic notification that errors occurred during processing.
We are working on capturing these

> tsk_directory = fs_info.open_dir(path=location)
IOError: Directory_Con: (tsk3.c:361) Unable to open directory: Error in metadata structure (Extension record 184 (file ref = 0) is not for attribute list of 37830)

Looks like an issue with TSK/pytsk not being able to parse this directory

> 2016-05-11 08:53:34,604 ERROR PID:3930 Process Collector (PID: 3942) is not functioning correctly. Status code killed.

Can you check the output of `dmesg` if there might be an OOM killer (out of memory) message.

**Comment by unicornhippo** [comment] 2016-05-11 22:48
I found nothing in the dmesg output indicating that Ubuntu was out of memory.  As far as TSK/pytsk, I think I probably just need to make some updates and that will help with this issue.

**Comment by Onager** [comment] 2016-05-18 04:54
@unicornhippo it sounds like we can close this issue out for now - yes?

**Comment by Onager** [comment] 2016-06-01 10:29
No response - closing issue.

**Closed by Onager** 2016-06-01 10:29 UTC
Labels: question
