### ISSUE TITLE
Improve parsing for remote access logs

### ISSUE THREAD

**Issue by vlejd** [log2timeline/plaso#995] opened 2016-09-13 11:40 UTC
**Plaso version:**

1.4.1_20160912

**Description of problem:**

Plaso could parse more information from remote access (and similar) logs. Namely 
- windows:evtx:record : For event 4624 (An account was successfully logged on) it is possible to parse source user id, source user name, target user id, target user name, target machine name, target machine ip form message (strings) field. For event event 4648 (login with certificate) it is possible to parse source user id, source user name, target user name, target machine name, target machine ip. This can be parsed by accessing right elements of event.strings
- bsm:event: For events that have message like "BSM_TOKEN_RETURN32: Success" it is possible to parse source user name, target user name, source machine ip and target user id. Further more those logs contain  aid, euid, egid, uid, gid, pid, session_id, terminal_port, terminal_ip, which are probably not that important. This can be parsed with a few regexp.
- syslog:line : Can give target user name, source machine ip for events with message like "Accepted password for". Can be parsed with a regexp.

Question is how should those additional data be represented. Option one is creating new properties for corresponding Event classes. However those would be empty a lot of a times. Second option is adding a one new property that would hold parsed information in a dict without strict format (only parsed information would be there).

**Comment by Onager** [comment] 2016-09-13 12:11
Do you mean "remote access" rather than "ssh"? Evtx records for example
don't usually contain SSH information....

**Comment by joachimmetz** [comment] 2016-09-13 19:05
Isn't this a duplicate of https://github.com/log2timeline/plaso/issues/158 ?

**Comment by joachimmetz** [comment] 2016-09-19 18:25
So this is a subset of 158, per discussion keep working on this regarding what you need and we can always make it more generic in the future.

**Comment by pettai** [comment] 2016-12-26 09:03
Regarding Improved winevtx parser #995, the "username" field is still just "-".
I would find it even more useful if the data from "strings_parsed" field "target_user_name":"XXXXX" would be fed into the generic "username" field too (like the parsing of GroupPolicy + TaskScheduler parsed events do)

**Comment by joachimmetz** [comment] 2019-05-19 18:29
@Onager any action items on this issue or close?

**Comment by joachimmetz** [comment] 2021-05-16 11:19
Unclear what the request is here, closing.

**Closed by joachimmetz** 2021-05-16 11:19 UTC
Labels: enhancement, parsers
